-- Restores missing accents in pt-BR question text (133 questions).
-- Only prompt/options/explanation of the pt-BR original change, and only
-- accents/crase (checked when generating: stripping accents, old == new).
-- options keep their order and count, so correct_index is untouched; the
-- en/es translations are not affected. Idempotent: running again rewrites
-- the same text.

update questions q
set prompt = v.prompt, options = v.options, explanation = v.explanation
from (values
  ('0031206c-5833-4628-8ac5-05e12101ae76', 'As divisões regionais de um estado servem principalmente para:',
   array['Organizar o planejamento e a administração do território', 'Definir fronteiras entre países', 'Substituir os municípios', 'Marcar fusos horários diferentes'],
   'As divisões regionais ajudam no planejamento, na gestão e na comparação de dados dentro do estado.'),
  ('015362fd-3bca-4eca-a810-8d5f3ed6dc6f', 'Qual bioma brasileiro é considerado o mais devastado, restando pequena parte de sua cobertura original?',
   array['A Mata Atlântica', 'A Amazônia', 'O Cerrado', 'O Pantanal'],
   'A Mata Atlântica, no litoral mais povoado, é o bioma mais devastado, com pequena parte da vegetação original preservada.'),
  ('0177e767-32d4-468d-9687-2b2b8c91fd2c', 'A chamada "guerra fiscal" entre estados e municípios consiste em:',
   array['A oferta de incentivos e redução de impostos para atrair indústrias', 'Um conflito militar entre estados', 'A criação de um imposto único nacional', 'A proibição de qualquer incentivo fiscal'],
   'Na guerra fiscal, entes federativos concedem benefícios tributários para atrair fábricas para seu território.'),
  ('02ef7f38-a4b8-44de-855e-5d0bda24ca97', 'A região do Sudoeste Goiano destaca-se, sobretudo, por:',
   array['Forte produção agrícola de grãos', 'Extração de sal marinho', 'Indústria de alta tecnologia aeroespacial', 'Turismo de esqui'],
   'O Sudoeste Goiano (Rio Verde, Jataí, Mineiros) é uma das principais regiões produtoras de grãos do estado.'),
  ('03c5ef46-9631-41d1-9d66-b8bf7be5f8e2', 'O Rio Meia Ponte é afluente de qual rio maior?',
   array['Rio Araguaia', 'Rio Tocantins', 'Rio Paranaíba', 'Rio São Francisco'],
   'O Meia Ponte deságua no Paranaíba, integrando a bacia do Paraná.'),
  ('0425b201-00d3-4ca6-8c0a-7daf70269590', 'Um objeto é lançado horizontalmente a 15 m/s do alto de uma plataforma de 20 m de altura (g = 10 m/s2). Qual é o alcance horizontal até atingir o solo?',
   array['15 m', '20 m', '30 m', '45 m'],
   'Tempo de queda: t = raiz(2h/g) = raiz(4) = 2 s. Alcance = v.t = 15 x 2 = 30 m.'),
  ('072275a0-25ca-439f-9527-df3506adc8f1', 'Um objeto é colocado a 30 cm de um espelho côncavo de distância focal 10 cm. A que distância do espelho se forma a imagem? (1/f = 1/p + 1/p'')',
   array['7,5 cm', '10 cm', '15 cm', '30 cm'],
   '1/10 = 1/30 + 1/p''. Logo 1/p'' = 1/10 - 1/30 = 2/30, e p'' = 15 cm.'),
  ('074881be-6bc3-4d78-85d3-9207d8fa2790', 'Um espelho côncavo tem raio de curvatura de 40 cm. Um objeto colocado a 40 cm do espelho (sobre o centro de curvatura) forma uma imagem que é:',
   array['real, invertida e de mesmo tamanho', 'virtual e maior', 'real e menor', 'imprópria, no infinito'],
   'A distância focal é R/2 = 20 cm. Com o objeto no centro de curvatura (2f), a imagem se forma sobre C: real, invertida e do mesmo tamanho.'),
  ('0783f7f9-844a-4544-bb5f-703c88394e90', 'Rio Verde, no sudoeste goiano, é um importante polo de:',
   array['Agronegócio, com grãos e frigoríficos', 'Extração de petróleo offshore', 'Turismo de praias', 'Indústria naval'],
   'Rio Verde é um dos maiores polos do agronegócio goiano, com produção de grãos e frigoríficos.'),
  ('08646ded-ae73-49ee-a05e-53ae2109ec91', 'Ao se encontrar com o Rio Grande, o Rio Paranaíba dá origem a qual rio?',
   array['Rio Paraná', 'Rio Tocantins', 'Rio Araguaia', 'Rio Paraguai'],
   'A junção do Paranaíba com o Rio Grande forma o Rio Paraná.'),
  ('089e6be8-0cf5-4a42-93b0-87c7971435ba', 'Uma máquina térmica recebe 800 J da fonte quente e rejeita 600 J para a fonte fria em cada ciclo. Qual é o seu rendimento?',
   array['20%', '25%', '33%', '75%'],
   'Rendimento = 1 - Qfria/Qquente = 1 - 600/800 = 0,25, ou seja, 25%.'),
  ('0af6798b-eedd-483b-a6f6-fe4e3bf3d9be', 'A separação das diferentes classes sociais no espaço das cidades, com áreas ricas e pobres bem distintas, é chamada de:',
   array['Conurbação', 'Integração urbana', 'Segregação socioespacial', 'Reforma agrária'],
   'A segregação socioespacial reflete a desigualdade no espaço urbano, separando centro/periferia e condomínios/favelas.'),
  ('0f424d67-028e-4d50-9cf5-cc58ab4b1bf6', 'As únicas usinas nucleares em operação no Brasil (Angra 1 e 2) ficam em qual estado?',
   array['Rio de Janeiro', 'Bahia', 'Paraná', 'Amazonas'],
   'As usinas de Angra dos Reis (Angra 1 e 2) ficam no litoral do Rio de Janeiro.'),
  ('10c2166e-66cb-437e-abd9-1b85e998a380', 'O modelo de "substituição de importações" adotado no Brasil consistia em:',
   array['Produzir internamente bens que antes eram importados', 'Aumentar a importação de todos os produtos', 'Proibir qualquer produção nacional', 'Exportar apenas matéria-prima'],
   'A substituição de importações buscava produzir no país os bens antes comprados do exterior.'),
  ('10c33054-4ee9-46bc-a76d-6454063f1dbb', 'No Rio Corumbá localiza-se um importante aproveitamento energético. Qual?',
   array['A Usina Hidrelétrica de Corumbá', 'A Usina Nuclear de Corumbá', 'O Porto de Corumbá', 'A Represa do Castanhão'],
   'O Corumbá abriga usinas hidrelétricas, com destaque para a UHE Corumbá.'),
  ('10dd0a2c-ae4c-4973-991f-7e65c9d788fa', 'Um bloco de 2 kg sobre uma mesa horizontal sem atrito é ligado por um fio, que passa por uma polia, a um bloco de 3 kg pendurado (g = 10 m/s2). Qual é a aceleração do sistema?',
   array['5 m/s2', '6 m/s2', '10 m/s2', '15 m/s2'],
   'A força motriz é o peso do bloco pendurado: a = (m2.g)/(m1+m2) = 30/5 = 6 m/s2.'),
  ('112707b4-0364-44be-afee-27741f80a636', 'Um chuveiro de 4400 W é usado em média 0,5 hora por dia durante 30 dias. Qual é o consumo aproximado de energia no período?',
   array['6,6 kWh', '66 kWh', '132 kWh', '220 kWh'],
   'Consumo = potência x tempo = 4,4 kW x 0,5 h x 30 = 66 kWh.'),
  ('118fae67-4aa2-414b-a9a0-d1aba77af6be', 'Um carrinho parte do repouso e desce uma rampa lisa a partir de uma altura de 3,2 m (g = 10 m/s2). Qual é sua velocidade ao chegar na base?',
   array['4 m/s', '6,4 m/s', '8 m/s', '16 m/s'],
   'Conservação de energia: v = raiz(2gh) = raiz(2 x 10 x 3,2) = raiz(64) = 8 m/s.'),
  ('139ea3c2-7d2e-4c0c-90b6-3b38ae915d78', 'Qual é a segunda maior cidade da Região Metropolitana de Goiânia?',
   array['Aparecida de Goiânia', 'Senador Canedo', 'Goianira', 'Nerópolis'],
   'Aparecida de Goiânia é a segunda mais populosa da região metropolitana.'),
  ('148d6230-1ae9-4662-ac3c-d586fdc95daf', 'Em 2001, o Rio Vermelho ficou marcado por qual evento na Cidade de Goiás?',
   array['Uma seca que secou totalmente o leito', 'Uma grande enchente que atingiu o centro histórico', 'A construção de uma usina nuclear', 'A descoberta de petróleo'],
   'A enchente de 2001 invadiu o centro histórico da Cidade de Goiás, causando grandes danos ao patrimônio.'),
  ('17dab805-4862-53c4-8fc0-3673be576a4f', 'Uma pessoa hipermétrope tem o ponto próximo a 50 cm. Para ler a 25 cm, ela precisa de lentes com vergência de:',
   array['−2 di', '+4 di', '+2 di', '+0,5 di'],
   'A lente deve formar, de um objeto a 25 cm, uma imagem virtual a 50 cm: V = 1/p + 1/p'' = 1/0,25 − 1/0,5 = 4 − 2 = +2 di. É convergente, como toda correção de hipermetropia.'),
  ('18f1dcda-2e31-4722-a7d2-bb4ab7597b11', 'As árvores do Cerrado costumam ter troncos tortuosos e cascas grossas como adaptação principalmente a:',
   array['Ao frio intenso e à neve', 'Ao fogo e à estiagem prolongada', 'À alta salinidade do solo', 'Ao excesso permanente de água'],
   'Cascas grossas e raízes profundas são adaptações ao fogo natural e à longa estação seca.'),
  ('19b0ed3e-3afb-4fa4-803a-41d4ed63cb36', 'A taxa de fecundidade brasileira, nas últimas décadas:',
   array['Caiu para abaixo do nível de reposição (cerca de 2,1 filhos por mulher)', 'Aumentou para mais de 6 filhos por mulher', 'Permaneceu exatamente igual desde 1950', 'Nunca foi medida no país'],
   'A fecundidade caiu bastante e hoje está abaixo do nível de reposição, contribuindo para o envelhecimento.'),
  ('1bce2288-c9b2-4c7c-961c-a45aceb9c0bc', 'A junção das manchas urbanas de cidades vizinhas, que crescem até se encostarem, é chamada de:',
   array['Metropolização', 'Litoralização', 'Conurbação', 'Ruralização'],
   'Conurbação é a fusão física de áreas urbanas de municípios vizinhos, como Goiânia e Aparecida de Goiânia.'),
  ('1bf4fca5-0f60-4ed0-b342-013616a9c7b7', 'Qual a diferença entre "matriz energética" e "matriz elétrica"?',
   array['Matriz energética reúne todas as fontes de energia; matriz elétrica trata só da geração de eletricidade', 'São exatamente a mesma coisa', 'Matriz elétrica inclui os combustíveis dos carros; a energética não', 'Nenhuma das duas existe no Brasil'],
   'A matriz energética abrange todo o consumo de energia (transporte, indústria etc.); a matriz elétrica é só a eletricidade.'),
  ('1c2713b8-eb77-42bd-9b8e-e0020fd8f1b3', 'A energia eólica no Brasil concentra-se principalmente em qual região?',
   array['Nordeste', 'Norte', 'Centro-Oeste', 'Sudeste'],
   'O Nordeste, com ventos constantes no litoral e no sertão, lidera a geração eólica do país.'),
  ('1d53e2fd-9c9e-40e5-8908-9cc4e6667469', 'O crescimento vegetativo (ou natural) de uma população é calculado por:',
   array['Natalidade menos mortalidade', 'Natalidade mais mortalidade', 'Número de imigrantes apenas', 'Densidade demográfica vezes área'],
   'O crescimento vegetativo é a diferença entre a taxa de natalidade e a de mortalidade.'),
  ('1ea4ec77-6875-4aba-9444-db936ecb53c3', 'O período de estiagem (seca) em Goiás ocorre aproximadamente entre:',
   array['Maio e setembro', 'Novembro e fevereiro', 'Dezembro e março', 'O ano inteiro, sem variação'],
   'A estação seca goiana vai, em média, de maio a setembro.'),
  ('20977c50-2ee1-4213-a3a4-d10f8d1f27a4', 'O chamado "arco do desmatamento" corresponde a:',
   array['A faixa de avanço da fronteira agropecuária no sul e leste da Amazônia', 'Uma cadeia de montanhas no Nordeste', 'Uma corrente marítima do litoral', 'Uma área urbana de São Paulo'],
   'O arco do desmatamento é a região de expansão da fronteira agropecuária que avança sobre a Amazônia (PA, MT, RO).'),
  ('20ba9085-7ada-4427-a0f7-864df8f11c31', 'A transição demográfica pela qual o Brasil passa caracteriza-se por:',
   array['Aumento simultâneo de natalidade e mortalidade', 'Queda da natalidade e da mortalidade, com envelhecimento da população', 'População cada vez mais jovem', 'Ausência de qualquer mudança populacional'],
   'Na transição demográfica, natalidade e mortalidade caem, o crescimento desacelera e a população envelhece.'),
  ('2357465a-9185-4163-87a6-b2cd1bfb7039', 'Entre as principais migrações internas do Brasil no século XX destaca-se:',
   array['A migração do Nordeste para o Sudeste', 'A migração do Sudeste para a Antártida', 'A migração para fora do país em massa', 'A ausência de qualquer migração interna'],
   'O fluxo de nordestinos para o Sudeste industrializado foi uma das maiores migrações internas do país.'),
  ('236dcfe2-cb2d-4d81-a3c6-efedaab46198', 'Entre os fatores locacionais que influenciam onde uma indústria se instala estão:',
   array['Apenas a cor do prédio da fábrica', 'Somente o nome do proprietário', 'Exclusivamente o clima do local', 'Proximidade de matéria-prima, mercado, mão de obra, energia e transporte'],
   'A localização industrial considera matéria-prima, mercado consumidor, mão de obra, energia e infraestrutura de transporte.'),
  ('2448a223-51b8-4bc4-8a48-8d1b6cf9a61a', 'Além de Goiânia e Aparecida, integram a Região Metropolitana municípios como:',
   array['Senador Canedo, Trindade e Goianira', 'Rio Verde, Jataí e Mineiros', 'Catalão, Ipameri e Pires do Rio', 'Porangatu, Uruaçu e Niquelândia'],
   'Senador Canedo, Trindade, Goianira, Nerópolis e Hidrolândia estão entre os municípios da região metropolitana.'),
  ('258db94d-aa36-4897-8cf9-9b50e553dbca', 'Acordos como o de Paris e conferências como as COPs têm como objetivo:',
   array['Estabelecer metas para reduzir emissões e conter as mudanças climáticas', 'Aumentar a produção de petróleo', 'Incentivar o desmatamento', 'Proibir a energia solar'],
   'O Acordo de Paris e as COPs buscam limitar o aquecimento global por meio de metas de redução de emissões.'),
  ('28fa409b-f634-454f-896a-6284821a0902', 'Um problema típico do inverno seco em Goiás é:',
   array['Enchentes constantes', 'Baixa umidade do ar e aumento das queimadas', 'Nevascas frequentes', 'Formação de furacões'],
   'No auge da seca, a umidade relativa cai muito, favorecendo queimadas e problemas respiratórios.'),
  ('29350276-a392-470b-a0c9-8de790875115', 'Em relação à população, o Brasil é:',
   array['O país mais populoso da América do Sul', 'O país menos populoso da América', 'Um país sem população urbana', 'O menor país em área do mundo'],
   'Com mais de 200 milhões de habitantes, o Brasil é o país mais populoso da América do Sul.'),
  ('2aa3abed-0b68-43c2-81b5-fa6d8536f18d', 'Um bloco de 10 kg sobre superfície horizontal recebe uma força horizontal de 40 N. O coeficiente de atrito cinético é 0,3 (g = 10 m/s2). Qual é a aceleração do bloco?',
   array['1 m/s2', '2 m/s2', '3 m/s2', '4 m/s2'],
   'Normal = 100 N; atrito = 0,3 x 100 = 30 N; resultante = 40 - 30 = 10 N; a = 10/10 = 1 m/s2.'),
  ('2fdb8be7-df48-483c-a420-d167d0e9e6b6', 'Goiás é um dos maiores produtores nacionais de qual produto derivado da cana?',
   array['Etanol e açúcar', 'Vinho', 'Cerveja', 'Azeite'],
   'A cana-de-açúcar sustenta forte produção goiana de etanol e açúcar.'),
  ('317887e0-cea3-4066-89f2-ebbcda2bafba', 'Os municípios goianos vizinhos de Brasília formam a área conhecida como:',
   array['Entorno do Distrito Federal', 'Zona da Mata goiana', 'Baixada Cuiabana', 'Triângulo Mineiro'],
   'A região próxima a Brasília é chamada de Entorno do Distrito Federal.'),
  ('31e2c745-3f8f-447f-ae05-9abec4033fd8', 'A industrialização brasileira se intensificou, sobretudo, a partir de:',
   array['A partir de 1930, no governo Getúlio Vargas', 'No período colonial, no século XVI', 'Apenas após o ano 2000', 'No Império, com Dom Pedro I'],
   'A industrialização ganhou força a partir de 1930, no governo Vargas, com apoio estatal e substituição de importações.'),
  ('3334e1a7-b37b-4faa-bf7e-8479937b94c3', 'A urbanização é um processo caracterizado por:',
   array['O crescimento da população urbana em relação à rural', 'A migração das cidades para o campo', 'A redução do número de cidades', 'O aumento da produção agrícola'],
   'Urbanização é o aumento da proporção de pessoas vivendo em áreas urbanas em relação às rurais.'),
  ('34d2af89-0a36-4762-86d4-fe8072fa1cc3', 'O Pantanal, um dos biomas brasileiros, destaca-se por ser:',
   array['A maior planície alagável do mundo, sensível a grandes incêndios como os de 2020', 'Um deserto de areia', 'Uma região coberta de gelo', 'Uma área totalmente urbanizada'],
   'O Pantanal é a maior planície alagável do planeta; em 2020 sofreu incêndios de grande proporção.'),
  ('37e70f1d-1a51-478f-bb97-6b7a08d06bff', 'As usinas termelétricas no Brasil costumam ser mais acionadas quando:',
   array['Os reservatórios das hidrelétricas estão baixos (períodos de seca)', 'Chove muito e os reservatórios estão cheios', 'A demanda por energia é nula', 'O vento está muito forte'],
   'Em períodos de seca, as termelétricas (mais caras e poluentes) são acionadas para complementar a geração.'),
  ('3b55d6ce-7ab1-4351-a892-2e596e6ec617', 'Uma pessoa hipermétrope tem mais dificuldade para:',
   array['Ler um livro segurado próximo aos olhos', 'Ler uma placa de trânsito distante', 'Distinguir cores em qualquer distância', 'Enxergar em ambientes muito escuros'],
   'A hipermetropia prejudica principalmente a visão de perto, dificultando atividades como a leitura de um livro próximo.'),
  ('3d3d4750-6431-4299-a8d4-5d3ba45391e9', 'Após o fim da Guerra Fria, a ordem mundial passou de bipolar para:',
   array['Unipolar sob hegemonia dos EUA e, cada vez mais, multipolar', 'Totalmente sem potências', 'Bipolar entre Brasil e Índia', 'Um império único e permanente'],
   'Com o fim da URSS, os EUA tornaram-se a potência hegemônica; hoje o mundo caminha para a multipolaridade (ascensão da China).'),
  ('418a53f1-031f-41d0-9afa-a029f0f29490', 'A tendência de redução da participação da indústria no PIB, com avanço do setor de serviços, é chamada de:',
   array['Desindustrialização', 'Industrialização tardia', 'Substituição de importações', 'Conurbação'],
   'A desindustrialização é a perda de peso relativo da indústria na economia, acompanhada do crescimento dos serviços.'),
  ('42cfe8e9-4b39-4f6f-8e6a-1d8d3e9d200e', 'São organizações econômicas de alcance global:',
   array['FMI, Banco Mundial e OMC', 'Apenas o Mercosul', 'Somente a OTAN', 'Apenas a ONU Ambiental'],
   'FMI, Banco Mundial e Organização Mundial do Comércio (OMC) são instituições centrais da economia globalizada.'),
  ('491334fe-646f-402f-b045-c5278b127570', 'A Região Metropolitana de Goiânia corresponde a:',
   array['A maior aglomeração urbana de Goiás', 'A menor cidade do estado', 'Uma área exclusivamente rural', 'Um parque nacional'],
   'A RM de Goiânia é a maior concentração populacional e urbana do estado.'),
  ('4a48395c-ce96-4295-8fce-eca8a606a7eb', 'O conceito de desenvolvimento sustentável propõe:',
   array['Usar os recursos naturais atendendo o presente sem comprometer as futuras gerações', 'Explorar todos os recursos o mais rápido possível', 'Proibir qualquer atividade econômica', 'Ignorar os impactos ambientais'],
   'Desenvolvimento sustentável concilia crescimento econômico, justiça social e conservação ambiental para o futuro.'),
  ('4a558e00-c458-48ae-aec8-412b0563aa99', 'Diferentemente do Meia Ponte (bacia do Paraná), o Rio das Almas corre para qual bacia?',
   array['Bacia do São Francisco', 'Bacia Tocantins-Araguaia', 'Bacia do Paraná', 'Bacia do Uruguai'],
   'O Rio das Almas pertence à bacia Tocantins-Araguaia; junto ao Rio Maranhão ajuda a formar o Rio Tocantins.'),
  ('52c6d456-906c-4f15-ae4f-76d610566afa', 'O Rio Vermelho pertence à mesma bacia de qual grande rio goiano, do qual é afluente?',
   array['Rio Paranaíba', 'Rio Araguaia', 'Rio São Francisco', 'Rio Paraná'],
   'O Rio Vermelho é afluente do Araguaia, integrando a bacia Tocantins-Araguaia.'),
  ('54aa40bd-bf10-447e-9078-a5d4e8031024', 'O Brasil é referência mundial em biocombustível produzido a partir da:',
   array['Cana-de-açúcar (etanol)', 'Extração de carvão', 'Fissão do urânio', 'Queima de plástico'],
   'Desde o Proálcool (1975), o Brasil é pioneiro na produção de etanol a partir da cana-de-açúcar.'),
  ('54ea09cc-6eb3-489b-b523-ba92ef0659c0', 'Um bloco de 2 kg lançado a 10 m/s sobre uma superfície horizontal para completamente após deslizar 10 m (g = 10 m/s2). Qual é o coeficiente de atrito cinético?',
   array['0,1', '0,25', '0,5', '1,0'],
   'A energia cinética é dissipada pelo atrito: (m.v^2)/2 = mu.m.g.d. Logo 100 = mu x 200, e mu = 0,5.'),
  ('55f70bd0-7105-420f-8b6b-854f3337fcdb', 'Qual é o bioma predominante no estado de Goiás?',
   array['Amazônia', 'Caatinga', 'Cerrado', 'Mata Atlântica'],
   'O Cerrado cobre a maior parte do território goiano.'),
  ('58895b64-dbfc-49e9-a5a6-e84b954cc959', 'O Rio Vermelho, que passa pela Cidade de Goiás, deságua em qual rio?',
   array['No Rio Araguaia', 'No Rio São Francisco', 'No Rio Meia Ponte', 'No Rio Paraná'],
   'O Rio Vermelho é afluente do Araguaia, dentro da bacia Tocantins-Araguaia.'),
  ('5917a652-c56d-46a5-82c5-43f984e8e6e8', 'A posição de Goiás em área elevada do Planalto Central dá ao estado importância por:',
   array['Funcionar como dispersor de águas de várias bacias hidrográficas', 'Ter saída direta para o oceano', 'Concentrar as maiores jazidas de carvão do país', 'Abrigar geleiras permanentes'],
   'Por estar em terras altas centrais, Goiás abriga nascentes que alimentam bacias como Araguaia-Tocantins, Paraná e São Francisco.'),
  ('5ab92107-e473-46ae-a30a-d788bc478cc5', 'Uma desvantagem ambiental importante das grandes hidrelétricas é:',
   array['O alagamento de áreas e o deslocamento de populações', 'A emissão direta de radiação nuclear', 'O consumo de carvão mineral', 'A ausência total de produção de energia'],
   'A formação de reservatórios alaga áreas, afeta ecossistemas e desloca comunidades.'),
  ('5bd344d4-21bb-4a1a-80d3-db969cf28348', 'A Usina de Itaipu, uma das maiores do mundo, está localizada no:',
   array['Rio São Francisco', 'Rio Paraná (fronteira Brasil-Paraguai)', 'Rio Amazonas', 'Rio Tietê'],
   'Itaipu fica no Rio Paraná, na fronteira entre Brasil e Paraguai.'),
  ('5f4bee5a-4979-4edc-8b65-f163b41e3f8e', 'Qual é o maior bioma do Brasil em extensão territorial?',
   array['A Amazônia', 'A Caatinga', 'O Pampa', 'O Pantanal'],
   'A Amazônia, floresta tropical, é o maior bioma brasileiro em área.'),
  ('6434d6d5-b43a-4b2e-abb0-482a849d22ca', 'A globalização, apesar de integrar economias, também é criticada por:',
   array['Aprofundar as desigualdades entre países e dentro deles', 'Eliminar completamente a pobreza no mundo', 'Impedir o comércio internacional', 'Acabar com as empresas multinacionais'],
   'Os fluxos globais concentram riqueza e podem ampliar desigualdades entre centro e periferia e dentro dos países.'),
  ('67710b60-06d3-48d9-8858-b7467b76fd5c', 'Se o raio da órbita de um satélite ao redor da Terra for multiplicado por 4, seu período de revolução passa a ser (Terceira Lei de Kepler):',
   array['2 vezes maior', '4 vezes maior', '8 vezes maior', '16 vezes maior'],
   'Por Kepler, T^2 é proporcional a R^3. Com R x 4, T^2 x 64, então T x 8.'),
  ('6852e71a-b152-4670-9f3a-fbf6c0e0ff08', 'Um cubo maciço de 10 cm de aresta é totalmente imerso em água (densidade 1000 kg/m3; g = 10 m/s2). Qual é o empuxo sobre o cubo?',
   array['0,1 N', '1 N', '10 N', '100 N'],
   'Volume = (0,1)^3 = 0,001 m3. Empuxo = densidade x V x g = 1000 x 0,001 x 10 = 10 N.'),
  ('694f3756-7c2b-4948-8fda-061eea2ea71c', 'No período de seca, o Araguaia é famoso por um fenômeno que atrai turismo, sobretudo na cidade goiana de Aruanã. Que fenômeno é esse?',
   array['O congelamento das margens', 'A formação de extensas praias fluviais de areia branca', 'O desaparecimento total do leito', 'A inversão do sentido da correnteza'],
   'Na estiagem, o nível baixa e surgem grandes praias de areia, como as de Aruanã.'),
  ('6abca4fc-3f41-4d28-b12c-f0dac73ac56d', 'O curso do Rio Paranaíba se destaca economicamente, sobretudo, pela presença de:',
   array['Grandes usinas hidrelétricas, como Itumbiara e São Simão', 'Geleiras usadas para turismo', 'Portos de navios oceânicos', 'Minas de carvão mineral no leito'],
   'O Paranaíba é muito aproveitado para geração de energia, com usinas como Itumbiara, Cachoeira Dourada e São Simão.'),
  ('6d58a5e2-8c64-4af2-886f-3f97a0b85edf', 'A distribuição da população brasileira pelo território é marcada por:',
   array['Distribuição perfeitamente uniforme', 'Concentração no litoral e no Sudeste', 'Concentração apenas na Amazônia', 'Vazio total no litoral'],
   'A ocupação histórica concentrou a população no litoral e, sobretudo, na região Sudeste.'),
  ('6f101a4f-ea75-406d-b5b2-d8f1f40c1912', 'O Cerrado é chamado de "berço das águas" do Brasil porque:',
   array['Abriga nascentes que alimentam várias grandes bacias hidrográficas', 'Recebe as maiores chuvas do planeta', 'Fica totalmente inundado o ano inteiro', 'Não possui nenhum rio em seu território'],
   'No Cerrado nascem rios de bacias importantes (Araguaia-Tocantins, Paraná e São Francisco), daí o apelido.'),
  ('731276be-20a8-4237-8f7b-bb43bfb1a5a0', 'A economia de Goiás está fortemente ligada a qual setor?',
   array['Agronegócio', 'Pesca oceânica', 'Indústria naval', 'Extração de petróleo no mar'],
   'O agronegócio (agricultura e pecuária) é a base da economia goiana.'),
  ('73ceeccb-9488-4f0f-a063-ac1837d14b66', 'As chuvas no estado de Goiás concentram-se principalmente:',
   array['No inverno', 'No verão (aproximadamente de outubro a março)', 'Distribuídas igualmente o ano todo', 'Apenas em setembro'],
   'As precipitações concentram-se no verão, entre outubro e março.'),
  ('78048776-a257-43c5-a91c-a5038e9fff6a', 'Tecnopolos como São José dos Campos e Campinas destacam-se por concentrar:',
   array['Produção de commodities agrícolas', 'Indústria de alta tecnologia (aeronáutica e eletrônica)', 'Mineração de carvão', 'Pesca industrial'],
   'Esses tecnopolos reúnem indústrias de alta tecnologia, como a aeronáutica (Embraer) e a eletrônica.'),
  ('788b1e24-e62f-48cc-8598-bd4a31d924b0', 'Aparecida de Goiânia forma uma mancha urbana contínua (conurbação) com qual cidade?',
   array['Goiânia', 'Anápolis', 'Catalão', 'Formosa'],
   'Aparecida de Goiânia é conurbada com Goiânia, formando o núcleo da região metropolitana.'),
  ('7b63c9ab-b4be-4e6d-8dcb-0fb0fb95c867', 'Um projétil é lançado a 20 m/s formando 30 graus com a horizontal (g = 10 m/s2, sen30 = 0,5). Qual é a altura máxima atingida?',
   array['2,5 m', '5 m', '10 m', '20 m'],
   'Componente vertical: vy = 20 x 0,5 = 10 m/s. Altura máxima = vy^2 / (2g) = 100 / 20 = 5 m.'),
  ('7df9a7b9-4224-4397-aca0-5dd7e338583a', 'O Rio Paranaíba pertence a qual bacia hidrográfica?',
   array['Bacia Tocantins-Araguaia', 'Bacia Amazônica', 'Bacia do Paraná', 'Bacia do São Francisco'],
   'O Paranaíba integra a bacia do Paraná (bacia do Prata).'),
  ('805077bc-9330-4d0a-9741-ca75625a2563', 'O IDH (Índice de Desenvolvimento Humano) combina indicadores de:',
   array['Apenas o tamanho do território', 'Renda, educação e saúde (expectativa de vida)', 'Somente a quantidade de indústrias', 'Apenas o número de eleitores'],
   'O IDH reúne renda, educação e longevidade (saúde) para medir o desenvolvimento humano.'),
  ('8193cb40-e6ed-45f6-a2d2-d1fe5286f187', 'O pré-sal brasileiro refere-se a:',
   array['Reservas de petróleo em águas profundas, abaixo de uma camada de sal', 'Uma nova fonte de energia solar', 'Depósitos de carvão no Sul', 'Usinas nucleares submarinas'],
   'O pré-sal são grandes reservas de petróleo situadas em águas profundas, sob uma espessa camada de sal.'),
  ('8289c185-a540-4624-b80b-99707bac89f4', 'O Rio das Almas banha o norte goiano, passando por regiões de municípios como:',
   array['Goianésia, Barro Alto e Niquelândia', 'Rio Verde e Jataí', 'Catalão e Ipameri', 'Aparecida de Goiânia e Trindade'],
   'O das Almas percorre o norte do estado, próximo a Goianésia, Barro Alto e Niquelândia.'),
  ('8395b9ee-1b57-41b8-b88c-76233b822cc3', 'O Rio Araguaia forma trechos da divisa natural de Goiás com quais estados?',
   array['Mato Grosso e Tocantins', 'Bahia e Minas Gerais', 'Mato Grosso do Sul e São Paulo', 'Pará e Maranhão'],
   'O Araguaia separa Goiás de Mato Grosso (a oeste) e do Tocantins (ao norte).'),
  ('83dce9da-3c6f-47ef-8565-8e2f7bc59d42', 'A capital Goiânia destaca-se por ter sido, na sua origem:',
   array['Uma cidade planejada, construída na década de 1930', 'Uma antiga colônia portuguesa do século XVI', 'Uma vila de mineração do litoral', 'Uma cidade fundada após o ano 2000'],
   'Goiânia foi planejada e construída nos anos 1930 para ser a nova capital.'),
  ('89d6e89d-8c00-4642-a5a1-ef3092c2b7c3', 'O grupo BRICS reúne, originalmente, quais países?',
   array['Brasil, Rússia, Índia, China e África do Sul', 'Estados Unidos, Reino Unido e França', 'Alemanha, Japão e Canadá', 'Argentina, Chile e Uruguai'],
   'BRICS é a sigla de Brasil, Rússia, Índia, China e África do Sul, economias emergentes (o grupo foi ampliado em 2024).'),
  ('8c54d2da-5b1c-4f0f-ab26-ed74108ab189', 'Entre os blocos econômicos, aquele com maior grau de integração, incluindo moeda única (euro), é:',
   array['A União Europeia', 'O Mercosul', 'A ASEAN', 'O USMCA'],
   'A União Europeia é o bloco mais integrado, com livre circulação e moeda comum (euro) entre vários membros.'),
  ('8e3dbf00-7784-4991-91a2-390fe5483b93', 'Qual é a capital do estado de Goiás?',
   array['Anápolis', 'Goiânia', 'Cidade de Goiás', 'Rio Verde'],
   'Goiânia é a capital de Goiás desde 1937, substituindo a antiga Cidade de Goiás.'),
  ('8e7e21b9-05aa-4d53-ad5c-e2c4ef3ccd65', 'A hierarquia urbana (rede urbana) organiza as cidades conforme:',
   array['Apenas o tamanho físico do território', 'Sua influência e oferta de serviços, das metrópoles às pequenas cidades', 'A ordem alfabética dos nomes', 'A altitude em relação ao mar'],
   'A rede urbana hierarquiza as cidades pela área de influência e pelos serviços que oferecem, das metrópoles às cidades locais.'),
  ('919673fe-d034-41d3-a1a0-d6432c8cefc7', 'Um bloco desce um plano inclinado de 37 graus (sen37 = 0,6; cos37 = 0,8) com coeficiente de atrito cinético 0,25 (g = 10 m/s2). Qual é a aceleração do bloco?',
   array['2 m/s2', '3 m/s2', '4 m/s2', '6 m/s2'],
   'a = g(sen - mu.cos) = 10(0,6 - 0,25 x 0,8) = 10(0,6 - 0,2) = 4 m/s2.'),
  ('9307205e-6b7f-4d01-a8e5-0f75d9a0c3de', 'No Brasil, uma das principais fontes de emissão de gases de efeito estufa é:',
   array['O desmatamento e as queimadas', 'A energia hidrelétrica', 'O plantio de árvores nativas', 'A criação de parques nacionais'],
   'Diferentemente de países industrializados, no Brasil o desmatamento e as queimadas respondem por grande parte das emissões.'),
  ('9a69983a-db16-47e6-9f8a-342c31e06e40', 'Em uma corda, dois pontos consecutivos que oscilam em concordância de fase estão separados por 0,4 m, e o período da onda é 0,1 s. Qual é a velocidade de propagação?',
   array['0,04 m/s', '2 m/s', '4 m/s', '40 m/s'],
   'A distância entre pontos consecutivos em concordância de fase é um comprimento de onda (0,4 m). v = lambda/T = 0,4/0,1 = 4 m/s.'),
  ('9dbdd106-bddc-4544-837f-a06f361d1338', 'Além da importância ambiental, o Rio Meia Ponte é estratégico para a Região Metropolitana de Goiânia porque:',
   array['Participa do abastecimento de água da região', 'É uma rota de navios de carga', 'Serve de fronteira internacional', 'Abriga a maior geleira do Brasil'],
   'O Meia Ponte é uma das fontes de água para o abastecimento da região metropolitana.'),
  ('9fb52534-fd5c-4d85-bdd4-db8df6c66fa6', 'A crise hídrica que afetou o Sudeste em 2014-2015 evidenciou a importância:',
   array['Da preservação de nascentes e mananciais para o abastecimento de água', 'Do aumento do consumo de água sem controle', 'Da eliminação das represas', 'Da poluição dos rios'],
   'A escassez de água mostrou como a preservação de nascentes e mananciais é essencial para o abastecimento.'),
  ('a1b3d144-f1fc-4a64-8664-a8654da1b0b0', 'São consideradas fontes de energia RENOVÁVEIS:',
   array['Petróleo, carvão e gás natural', 'Sol, vento, água e biomassa', 'Apenas o urânio', 'Somente o carvão mineral'],
   'Sol, vento, água e biomassa se renovam na natureza; petróleo, carvão e gás são não renováveis.'),
  ('a46ac0f5-3619-470d-aa11-320bdc7e7d5b', 'Na mineração, Goiás se destaca na produção de minerais como:',
   array['Níquel e nióbio', 'Carvão mineral e turfa', 'Diamante e petróleo', 'Sal-gema e enxofre'],
   'Goiás é importante produtor de níquel (Niquelândia, Barro Alto) e de nióbio e fosfato (região de Catalão).'),
  ('a6000292-2d52-4b88-98a8-2b5d1bc5bdb6', 'O Mercosul é um bloco econômico formado, entre outros, por:',
   array['Brasil, Argentina, Uruguai e Paraguai', 'Estados Unidos, Canadá e México', 'China, Japão e Coreia', 'França, Alemanha e Itália'],
   'O Mercosul reúne países da América do Sul, tendo Brasil, Argentina, Uruguai e Paraguai como membros fundadores.'),
  ('a63322c8-f9ce-463c-9cf5-08106f7a9df2', 'Anápolis, uma das maiores cidades de Goiás, é conhecida principalmente como:',
   array['Polo industrial e logístico (DAIA e Porto Seco)', 'Estância de águas termais', 'Cidade histórica colonial', 'Maior porto marítimo do Centro-Oeste'],
   'Anápolis abriga o Distrito Agroindustrial (DAIA) e um importante Porto Seco, sendo polo industrial e logístico.'),
  ('a6deb288-88cd-4496-8c11-aa404d642e31', 'Um objeto é colocado a 40 cm de uma lente convergente de distância focal 20 cm. A imagem formada é:',
   array['virtual e maior', 'real, de mesmo tamanho e invertida', 'real e 2 vezes maior', 'virtual e menor'],
   '1/20 = 1/40 + 1/p'' leva a p'' = 40 cm. O aumento é -p''/p = -1: imagem real, invertida e do mesmo tamanho.'),
  ('a8690503-1ead-4c4b-9dcc-f257a6352e1d', 'A chamada "desconcentração industrial" recente refere-se a:',
   array['A dispersão de indústrias do Sudeste para o interior e outras regiões, atraídas por incentivos', 'A concentração total das indústrias em uma única cidade', 'O fechamento de todas as indústrias do país', 'A proibição de novas fábricas'],
   'A partir das últimas décadas do século XX, indústrias se dispersaram para o interior de SP, o Sul e outras regiões, atraídas por incentivos.'),
  ('aa044257-c31c-4232-905d-260744d2d836', 'O crescimento urbano acelerado, sem oferta suficiente de emprego, moradia e infraestrutura, gerando periferias precárias e subemprego, é conhecido como:',
   array['Macrocefalia urbana (cidade inchada)', 'Conurbação planejada', 'Desenvolvimento sustentável', 'Ruralização'],
   'A macrocefalia urbana descreve a "cidade inchada": cresce mais rápido do que sua capacidade de absorver a população.'),
  ('aefbebb0-8903-4fb6-9dc0-3011e7358c57', 'O clima predominante em Goiás é classificado como:',
   array['Tropical com estação seca (tipo Aw)', 'Equatorial úmido o ano todo', 'Semiárido', 'Subtropical com neve no inverno'],
   'Goiás tem clima tropical de savana (Aw), com forte sazonalidade de chuvas.'),
  ('af18dbc3-a046-4bfa-8d08-c06609901f67', 'As duas maiores metrópoles do Brasil, no topo da hierarquia urbana, são:',
   array['Brasília e Salvador', 'São Paulo e Rio de Janeiro', 'Manaus e Belém', 'Curitiba e Porto Alegre'],
   'São Paulo e Rio de Janeiro são as maiores metrópoles brasileiras; São Paulo lidera a rede urbana nacional.'),
  ('afb17d76-264d-49d9-bfa8-88c016fc48f5', 'A densidade demográfica de uma região é definida como:',
   array['O número de habitantes por quilômetro quadrado', 'O total de habitantes do país', 'A quantidade de cidades', 'A renda média da população'],
   'Densidade demográfica é a razão entre a população e a área (hab/km2).'),
  ('afc7f520-aea0-4c8a-abd4-692d0011f971', 'O Distrito Agroindustrial de Anápolis (DAIA) é um importante polo de qual tipo de indústria?',
   array['Farmacêutica e automotiva', 'Têxtil e calçadista', 'Siderúrgica pesada', 'Petroquímica de refino'],
   'O DAIA concentra indústrias farmacêuticas e também montadoras do setor automotivo.'),
  ('b094edd7-a574-4919-b711-0b53ea777664', 'Que quantidade de calor é necessária para aquecer 200 g de água de 20 C até 70 C? (calor específico da água = 1 cal/g.C)',
   array['2000 cal', '5000 cal', '10000 cal', '14000 cal'],
   'Q = m.c.deltaT = 200 x 1 x 50 = 10000 cal.'),
  ('b0d6e3c7-7492-4b09-a1c3-710d6a4b1bd3', 'Atualmente, a principal ameaça ao Cerrado goiano é:',
   array['O avanço do gelo continental', 'A expansão da agropecuária e o desmatamento', 'A elevação do nível do mar', 'A ausência total de atividade humana'],
   'A expansão de lavouras (como a soja) e pastagens é a maior pressão sobre o Cerrado.'),
  ('b4ba4280-9db4-4584-aa1b-dc64187eadad', 'Em que ano foi criada oficialmente a Região Metropolitana de Goiânia?',
   array['Em 1999', 'Em 1937', 'Em 1960', 'Em 2015'],
   'A Região Metropolitana de Goiânia foi instituída por lei em 1999.'),
  ('b641c8ee-2056-4a80-bc94-8ed0a865d1b6', 'São Paulo é considerada uma "cidade global" porque:',
   array['Concentra sedes de empresas, serviços e conexões com a economia mundial', 'É a capital política do país', 'Tem a maior produção agrícola do Brasil', 'Não possui relação com outras cidades'],
   'Cidades globais, como São Paulo, são nós de comando da economia mundial, concentrando serviços e sedes de multinacionais.'),
  ('c089707f-50c5-4198-a5e6-bf196807ddde', 'Um carro a 20 m/s freia com desaceleração constante e para após percorrer 40 m. Qual é o módulo da desaceleração?',
   array['2 m/s2', '5 m/s2', '8 m/s2', '10 m/s2'],
   'Por Torricelli: 0 = 20^2 - 2a(40), então 400 = 80a e a = 5 m/s2.'),
  ('c0ebc299-74fc-4721-9287-5bf14b0454b9', 'O envelhecimento da população brasileira tende a pressionar, sobretudo:',
   array['O sistema previdenciário (aposentadorias)', 'A produção de brinquedos infantis apenas', 'O número de escolas de educação infantil', 'A oferta de creches, exclusivamente'],
   'Mais idosos e menos jovens aumentam a razão de dependência e pressionam a Previdência.'),
  ('c43fc6a9-a675-40bd-ace6-03be9784baa7', 'O Cerrado é considerado o segundo maior bioma do Brasil, ficando atrás apenas da:',
   array['Caatinga', 'Amazônia', 'Mata Atlântica', 'Pampa'],
   'O Cerrado é o segundo maior bioma brasileiro em extensão, atrás da Amazônia.'),
  ('c49a5281-8819-4061-8b11-45e5526a5a27', 'A pirâmide etária brasileira, nas últimas décadas, vem apresentando:',
   array['Base cada vez mais larga', 'Base estreitando e topo alargando (envelhecimento)', 'Formato perfeitamente retangular desde sempre', 'Ausência de idosos'],
   'A base (jovens) estreita e o topo (idosos) se alarga, refletindo o envelhecimento da população.'),
  ('c59ea127-e540-4648-9114-03f20c219d5d', 'Comparada à média mundial, a matriz energética brasileira é:',
   array['Mais limpa e renovável, com grande peso das hidrelétricas', 'Baseada quase toda em carvão mineral', 'Totalmente dependente de energia nuclear', 'Sem qualquer fonte renovável'],
   'O Brasil tem participação de renováveis bem acima da média mundial, sobretudo pela energia hidrelétrica.'),
  ('c7975b15-f3ce-462c-acc9-085a37548590', 'A OTAN é caracterizada como:',
   array['Uma aliança militar liderada por EUA e países europeus', 'Um bloco econômico da América do Sul', 'Uma organização ambiental da ONU', 'Um acordo comercial asiático'],
   'A OTAN é uma aliança militar do bloco ocidental, formada por EUA, Canadá e países europeus.'),
  ('c8b9e3fe-57f3-4a5b-a651-4d38bc1385d4', 'A Região Metropolitana de Goiânia tem como cidade-núcleo:',
   array['Goiânia', 'Anápolis', 'Aparecida de Goiânia', 'Trindade'],
   'Goiânia é o município-polo da região metropolitana.'),
  ('c9a66d44-8a75-45b8-b773-21a62f9bef23', 'Uma marca do clima goiano é a existência de duas estações bem definidas:',
   array['Verão chuvoso e inverno seco', 'Um verão e um outono chuvosos apenas', 'Quatro estações com neve', 'Uma única estação úmida o ano todo'],
   'O clima de Goiás alterna um verão chuvoso e um inverno seco bem marcados.'),
  ('c9ad6ada-c554-4892-8843-8083c355c0d9', 'A sigla RIDE, que envolve municípios de Goiás, refere-se a:',
   array['Região Integrada de Desenvolvimento do Distrito Federal e Entorno', 'Rede Interestadual de Energia', 'Reserva Indígena de Desenvolvimento Econômico', 'Rodovia Interestadual do Entorno'],
   'A RIDE reúne o Distrito Federal e municípios goianos e mineiros do seu entorno para planejamento conjunto.'),
  ('cba9ad6a-ef46-4713-b492-f6360c100ca9', 'Entre os principais produtos agrícolas de Goiás estão:',
   array['Soja, milho e cana-de-açúcar', 'Cacau, borracha e guaraná', 'Uva, maçã e trigo de inverno', 'Café, banana e coco da Bahia'],
   'Goiás é grande produtor de soja, milho e cana-de-açúcar.'),
  ('ceb61090-afd5-4cbc-a102-4f9e1974d1ce', 'O nome do Rio das Almas aparece ligado à história de povoamento do:',
   array['Litoral goiano', 'Norte/centro de Goiás, região de mineração antiga', 'Pantanal goiano', 'Sertão nordestino'],
   'O das Almas corta o centro-norte goiano, área ligada à antiga mineração e ao povoamento colonial.'),
  ('d4a86dc9-a104-453c-a121-1af6147616cc', 'O êxodo rural, central na urbanização brasileira, corresponde a:',
   array['Migração da população do campo para as cidades', 'Migração das cidades para o campo', 'Crescimento da população rural', 'Migração entre países'],
   'Êxodo rural é o deslocamento de população das áreas rurais para as urbanas.'),
  ('d5091608-6728-4326-84ae-fcf081a0468e', 'Apesar da matriz elétrica limpa, um grande desafio energético do Brasil ainda é:',
   array['A forte dependência de combustíveis fósseis no setor de transportes', 'A ausência total de hidrelétricas', 'A proibição de energia solar', 'A falta de qualquer reserva de petróleo'],
   'Mesmo com eletricidade renovável, os transportes ainda dependem muito de combustíveis fósseis, um desafio da transição energética.'),
  ('daf9e6a3-0d4e-44ad-a9cc-81dc48bd3d66', 'Dois resistores de 10 ohms e 20 ohms são ligados em série a uma fonte de 30 V. Qual é a corrente que percorre o circuito?',
   array['0,5 A', '1 A', '1,5 A', '2 A'],
   'Em série, Req = 10 + 20 = 30 ohms. i = U/Req = 30/30 = 1 A.'),
  ('dcad29ea-13ce-4658-b27b-d169bc8b5810', 'Depois de Goiânia, qual é o município mais populoso de Goiás?',
   array['Aparecida de Goiânia', 'Luziânia', 'Jataí', 'Formosa'],
   'Aparecida de Goiânia, conurbada com a capital, é o segundo município mais populoso do estado.'),
  ('e0c39f2e-ce23-4372-86a9-3ee5fdd809f6', 'A Guerra Fria (1947-1991) foi marcada pela bipolaridade entre:',
   array['Estados Unidos (capitalismo) e União Soviética (socialismo)', 'Brasil e Argentina', 'França e Alemanha', 'China e Índia'],
   'A Guerra Fria opôs os EUA (capitalistas) e a URSS (socialista), dividindo o mundo em dois blocos.'),
  ('e287fdf0-86a4-4d07-a26b-ced803f0b613', 'Três resistores idênticos de 6 ohms são associados em paralelo. Qual é a resistência equivalente da associação?',
   array['2 ohms', '6 ohms', '9 ohms', '18 ohms'],
   'Para resistores iguais em paralelo, Req = R/n = 6/3 = 2 ohms.'),
  ('e39961e6-f05e-44e3-bcad-2f0fa8ce6305', 'Entre as principais causas do desmatamento na Amazônia estão:',
   array['Pecuária, agricultura, extração ilegal de madeira e grilagem de terras', 'O turismo ecológico controlado', 'A criação de unidades de conservação', 'O reflorestamento'],
   'A abertura de pastagens e lavouras, a madeira ilegal e a grilagem estão entre as principais causas do desmatamento.'),
  ('e3c7407c-9c94-4aa9-8ed2-7a7ac9ce11c7', 'A porção nordeste de Goiás abriga as maiores altitudes do estado, na região da:',
   array['Chapada dos Veadeiros', 'Serra do Mar', 'Planície do Pantanal', 'Depressão Sertaneja'],
   'A Chapada dos Veadeiros, no nordeste goiano, concentra as maiores altitudes do estado.'),
  ('e43982b1-ec6b-471c-8365-704f015b4048', 'A qual grande bacia hidrográfica pertence o Rio Araguaia?',
   array['Bacia do São Francisco', 'Bacia do Paraná', 'Bacia Tocantins-Araguaia', 'Bacia Amazônica'],
   'O Araguaia é um dos principais rios da bacia Tocantins-Araguaia.'),
  ('e441bb2c-1622-47e4-a0e2-14616632dbb9', 'Qual é um dos principais problemas ambientais associados ao Rio Meia Ponte?',
   array['Excesso de gelo nas margens', 'Elevado grau de poluição por esgoto e ocupação urbana', 'Salinização por água do mar', 'Ausência completa de vida aquática desde a nascente'],
   'Por atravessar a área metropolitana de Goiânia, o Meia Ponte sofre com lançamento de esgoto e degradação.'),
  ('e5b08bdf-d264-47a6-af9a-4a89341e2820', 'No Conselho de Segurança da ONU, têm poder de veto os cinco membros permanentes:',
   array['EUA, Rússia, China, França e Reino Unido', 'Brasil, Índia, Alemanha, Japão e Itália', 'Todos os países do mundo', 'Apenas os EUA'],
   'Os cinco membros permanentes (EUA, Rússia, China, França e Reino Unido) têm poder de veto no Conselho de Segurança.'),
  ('e7aeea1a-8190-44be-af65-d6f90ee83223', 'A globalização pode ser definida como:',
   array['A crescente integração econômica, cultural e informacional entre os países', 'O isolamento total das economias nacionais', 'O fim do comércio entre países', 'A eliminação das empresas multinacionais'],
   'A globalização é a intensificação das conexões econômicas, culturais e tecnológicas em escala mundial.'),
  ('e8bf08d3-ae1c-4628-bed2-995ffdcd64d1', 'O Rio Corumbá é afluente de qual rio, integrando a bacia do Paraná?',
   array['Rio Araguaia', 'Rio Paranaíba', 'Rio Tocantins', 'Rio São Francisco'],
   'O Corumbá deságua no Paranaíba, dentro da bacia do Paraná.'),
  ('e9a762b8-8fab-4065-ba6c-11738a4296d3', 'A oeste do estado, junto ao Rio Araguaia, predomina uma área mais rebaixada conhecida como:',
   array['Planalto da Borborema', 'Depressão do Araguaia', 'Serra da Mantiqueira', 'Chapada Diamantina'],
   'A porção oeste, no vale do Araguaia, corresponde a uma área de depressão (Depressão do Araguaia).'),
  ('e9ce9aa6-8453-43ef-b69c-8f4d161530cd', 'A Divisão Internacional do Trabalho (DIT) refere-se a:',
   array['A especialização dos países: centrais produzem tecnologia; periféricos, matérias-primas', 'A divisão de tarefas dentro de uma única fábrica', 'A jornada de trabalho em horas', 'Um acordo sobre feriados mundiais'],
   'A DIT descreve os papéis dos países na economia mundial: centrais (indústria/tecnologia) e periféricos (matérias-primas).'),
  ('ea1d60d0-e01c-4141-9fab-68f6947d9591', 'O chamado "bônus demográfico" ocorre quando:',
   array['A população em idade ativa é maior que a população dependente (jovens e idosos)', 'Toda a população é composta por idosos', 'Não há pessoas em idade de trabalhar', 'A população para de crescer completamente'],
   'No bônus demográfico, há proporcionalmente mais gente em idade produtiva do que dependentes, favorecendo a economia.'),
  ('eb6e27c7-fd6b-4eee-8ee6-9cc1c6df8146', 'Qual é a principal fonte de energia elétrica do Brasil?',
   array['Hidrelétrica', 'Carvão mineral', 'Nuclear', 'Petróleo'],
   'A maior parte da eletricidade brasileira vem de usinas hidrelétricas.'),
  ('eb91348e-86fc-49e3-9be7-c8296e9f4561', 'Conflitos recentes, como a guerra entre Rússia e Ucrânia, evidenciam que a geopolítica atual envolve:',
   array['Disputas por poder, território, recursos e áreas de influência', 'Apenas questões esportivas', 'O fim de qualquer rivalidade entre potências', 'A ausência de interesses econômicos'],
   'Conflitos geopolíticos atuais refletem disputas por poder, recursos, território e zonas de influência entre potências.'),
  ('f3352d40-5b27-4608-95bc-8e46255df2c7', 'Aproximadamente, quantos municípios possui o estado de Goiás?',
   array['Cerca de 46', 'Cerca de 246', 'Mais de 800', 'Cerca de 30'],
   'Goiás é formado por 246 municípios.'),
  ('f99b0f88-04bb-4c9c-8733-7ad933bda331', 'A indústria de base (ou de bens de produção) caracteriza-se por:',
   array['Produzir bens de consumo final, como alimentos', 'Não utilizar matéria-prima', 'Produzir máquinas e insumos para outras indústrias (ex.: siderurgia)', 'Referir-se apenas ao artesanato'],
   'A indústria de base fornece máquinas, equipamentos e insumos (como aço) usados por outras indústrias.'),
  ('ffa314b7-d9c0-4e06-a425-66ca870bc828', 'O relevo de Goiás é predominantemente formado por:',
   array['Planaltos e chapadas do Planalto Central', 'Planícies litorâneas', 'Grandes cadeias de montanhas jovens', 'Depressões abaixo do nível do mar'],
   'Goiás situa-se no Planalto Central brasileiro, com predomínio de planaltos e chapadas.')
) as v(id, prompt, options, explanation)
where q.id = v.id::uuid
  and cardinality(q.options) = cardinality(v.options);
