-- Questões de prática para o primeiro lote de dossiês (dossiers_seed_2026_08.sql).
-- Rode dossier_questions_schema.sql e dossiers_seed_2026_08.sql antes deste arquivo.
-- Os ids dos dossiês são resolvidos por título via subquery, então a ordem exata
-- de execução dos outros dois arquivos entre si não importa, desde que rodem antes deste.

insert into dossier_questions (dossier_id, prompt, options, correct_index, explanation, order_index) values
-- Brasil — Eleições 2026
((select id from dossiers where title = 'Eleições 2026: a disputa pela Presidência começa oficialmente'),
  'Em que data as campanhas eleitorais de 2026 foram oficialmente liberadas nas ruas e na internet, segundo o TSE?',
  array['16 de agosto de 2026', '1º de outubro de 2026', '5 de agosto de 2026', '15 de novembro de 2026'], 0,
  'A propaganda eleitoral foi liberada a partir de 16 de agosto de 2026, quando Lula e Flávio Bolsonaro realizaram seus primeiros grandes atos de campanha.', 1),
((select id from dossiers where title = 'Eleições 2026: a disputa pela Presidência começa oficialmente'),
  'Em 2026, além do presidente da República, quais outros cargos são disputados nas eleições gerais brasileiras?',
  array['Governadores, senadores e deputados federais e estaduais', 'Apenas prefeitos e vereadores', 'Apenas senadores', 'Nenhum outro cargo é disputado no mesmo ano'], 0,
  '2026 é ano de eleições gerais, quando são escolhidos simultaneamente presidente, governadores, senadores e deputados.', 2),
((select id from dossiers where title = 'Eleições 2026: a disputa pela Presidência começa oficialmente'),
  'Qual órgão é responsável por fiscalizar o processo eleitoral brasileiro, incluindo o uso de tecnologia e desinformação nas campanhas?',
  array['O TSE (Tribunal Superior Eleitoral)', 'O STF (Supremo Tribunal Federal)', 'O Banco Central', 'O Ministério da Educação'], 0,
  'O TSE é o órgão responsável por organizar e fiscalizar as eleições no Brasil.', 3),
((select id from dossiers where title = 'Eleições 2026: a disputa pela Presidência começa oficialmente'),
  'Quem lançou sua pré-candidatura à Presidência em um evento no Rio de Janeiro em 16 de agosto de 2026?',
  array['Flávio Bolsonaro', 'Luiz Inácio Lula da Silva', 'O presidente do TSE', 'Nenhum candidato lançou campanha nessa data'], 0,
  'Flávio Bolsonaro lançou sua pré-candidatura à Presidência no Rio de Janeiro, no mesmo dia do ato de Lula em São Bernardo do Campo.', 4),
((select id from dossiers where title = 'Eleições 2026: a disputa pela Presidência começa oficialmente'),
  'Segundo o calendário eleitoral, quando deve ocorrer o primeiro turno da eleição presidencial de 2026?',
  array['Em outubro de 2026', 'Em agosto de 2026', 'Em dezembro de 2026', 'Em fevereiro de 2027'], 0,
  'O primeiro turno da eleição presidencial deve ocorrer em outubro, conforme o calendário eleitoral fixado pela Constituição.', 5),

-- Mundo e Geopolítica — Conflitos armados de 2026
((select id from dossiers where title = 'Os principais conflitos armados do mundo em 2026'),
  'Segundo analistas internacionais, qual conflito se consolidou em 2026 como um "conflito de atrito", marcado por uso massivo de drones e ataques a infraestrutura?',
  array['A guerra na Ucrânia', 'A guerra civil no Sudão', 'O conflito em Mianmar', 'A guerra no Iêmen'], 0,
  'O texto descreve a guerra na Ucrânia como um conflito de atrito, com avanços lentos e uso intenso de drones.', 1),
((select id from dossiers where title = 'Os principais conflitos armados do mundo em 2026'),
  'Em qual região específica do Sudão a guerra civil se intensificou em 2026, segundo o texto?',
  array['Darfur', 'Ituri', 'Antália', 'Gaza'], 0,
  'O texto cita Darfur como uma das regiões onde os confrontos da guerra civil sudanesa se intensificaram.', 2),
((select id from dossiers where title = 'Os principais conflitos armados do mundo em 2026'),
  'Além da Ucrânia e do Sudão, quais outros conflitos são citados entre os principais de 2026?',
  array['Gaza, República Democrática do Congo, Mianmar e Iêmen', 'Apenas conflitos na América do Sul', 'Nenhum outro conflito relevante é mencionado', 'Apenas disputas comerciais entre União Europeia e Estados Unidos'], 0,
  'O texto cita Gaza, RDC, Mianmar e Iêmen como outros dos principais conflitos monitorados em 2026.', 3),
((select id from dossiers where title = 'Os principais conflitos armados do mundo em 2026'),
  'Qual tensão geopolítica envolvendo a China é apontada como um dos pontos mais observados pela comunidade internacional em 2026?',
  array['A tensão entre China e Taiwan', 'Um conflito entre China e Brasil', 'Uma disputa entre China e Austrália pela Antártida', 'Nenhuma tensão envolvendo a China é mencionada'], 0,
  'O texto aponta a tensão entre China e Taiwan como um dos principais pontos de observação internacional.', 4),
((select id from dossiers where title = 'Os principais conflitos armados do mundo em 2026'),
  'Segundo o texto, o que os diferentes conflitos de 2026 têm em comum, além de causas específicas?',
  array['Refletem uma ordem internacional cada vez mais fragmentada, com menor capacidade de mediação de organismos como a ONU', 'Foram todos resolvidos rapidamente por acordos de paz', 'Não têm qualquer relação entre si', 'Ocorrem exclusivamente em um único continente'], 0,
  'O texto destaca que, apesar de causas específicas, os conflitos compartilham o pano de fundo de uma ordem internacional fragmentada.', 5),

-- Economia — Selic e inflação
((select id from dossiers where title = 'Selic recua para 14% em meio à queda da expectativa de inflação'),
  'Para qual patamar o Copom reduziu a taxa Selic na reunião encerrada em 5 de agosto de 2026?',
  array['14% ao ano', '14,25% ao ano', '13,75% ao ano', '5,02% ao ano'], 0,
  'O Copom reduziu a Selic em 0,25 ponto percentual, de 14,25% para 14% ao ano.', 1),
((select id from dossiers where title = 'Selic recua para 14% em meio à queda da expectativa de inflação'),
  'Qual foi a expectativa de inflação (IPCA) para o fechamento de 2026, segundo o Boletim Focus citado no texto?',
  array['5,02%', '14%', '1,98%', '0,25%'], 0,
  'O Boletim Focus projetou a inflação de 2026 em 5,02%.', 2),
((select id from dossiers where title = 'Selic recua para 14% em meio à queda da expectativa de inflação'),
  'Qual é a projeção de crescimento do PIB brasileiro para 2026 mencionada no texto?',
  array['Cerca de 1,98%', 'Cerca de 14%', 'Cerca de 5,02%', 'Cerca de 0,25%'], 0,
  'O texto cita uma projeção de crescimento do PIB de aproximadamente 1,98% para 2026.', 3),
((select id from dossiers where title = 'Selic recua para 14% em meio à queda da expectativa de inflação'),
  'Qual é o efeito geral esperado quando o Banco Central reduz a taxa Selic?',
  array['O crédito tende a ficar mais barato, estimulando consumo e investimentos', 'O crédito tende a ficar mais caro, reduzindo o consumo', 'Não há qualquer efeito sobre o crédito', 'A inflação sobe automaticamente e de forma descontrolada'], 0,
  'Juros mais baixos tornam o crédito mais barato, estimulando consumo e investimento, efeito oposto ao de uma alta de juros.', 4),
((select id from dossiers where title = 'Selic recua para 14% em meio à queda da expectativa de inflação'),
  'O que é o Boletim Focus, citado no texto como fonte das projeções de inflação e PIB?',
  array['Um relatório semanal do Banco Central com a mediana das projeções do mercado financeiro', 'Uma lei aprovada pelo Congresso Nacional', 'Um índice de preços calculado pelo IBGE', 'Um programa de investimentos em inteligência artificial'], 0,
  'O Boletim Focus é publicado semanalmente pelo Banco Central, reunindo as projeções médias do mercado financeiro.', 5),

-- Meio Ambiente — COP31
((select id from dossiers where title = 'Depois da COP30, o mundo se prepara para a COP31 na Turquia'),
  'Onde será realizada a COP31, marcada para novembro de 2026?',
  array['Em Antália, na Turquia', 'Em Belém, no Brasil', 'Em Glasgow, no Reino Unido', 'Em Sydney, na Austrália'], 0,
  'A COP31 será realizada em Antália, na Turquia, entre 9 e 20 de novembro de 2026.', 1),
((select id from dossiers where title = 'Depois da COP30, o mundo se prepara para a COP31 na Turquia'),
  'O que há de inédito no formato de presidência da COP31?',
  array['Ela terá presidência compartilhada entre dois países, Turquia e Austrália', 'Ela não terá nenhum país anfitrião', 'Será presidida exclusivamente pela ONU, sem participação de países', 'Será presidida por uma empresa privada'], 0,
  'Pela primeira vez, a COP terá presidência compartilhada: a Turquia como anfitriã e a Austrália liderando as negociações.', 2),
((select id from dossiers where title = 'Depois da COP30, o mundo se prepara para a COP31 na Turquia'),
  'Qual foi o tema do Dia Mundial do Meio Ambiente de 2026, celebrado em 5 de junho?',
  array['Mudanças climáticas', 'Poluição plástica', 'Perda de biodiversidade marinha', 'Desmatamento na Amazônia'], 0,
  'O tema de 2026 foram as mudanças climáticas, com a campanha "Agora Pelo Clima" promovida pelo PNUMA.', 3),
((select id from dossiers where title = 'Depois da COP30, o mundo se prepara para a COP31 na Turquia'),
  'O que caracteriza os últimos onze anos, segundo dados climáticos citados no texto?',
  array['Foram os mais quentes já registrados globalmente', 'Foram os mais frios das últimas décadas', 'Não apresentaram qualquer variação de temperatura', 'Tiveram redução constante da temperatura média'], 0,
  'O texto afirma que os últimos onze anos foram os mais quentes já registrados no planeta.', 4),
((select id from dossiers where title = 'Depois da COP30, o mundo se prepara para a COP31 na Turquia'),
  'Qual limite de aquecimento, estabelecido pelo Acordo de Paris, o mundo está próximo de ultrapassar temporariamente, segundo o texto?',
  array['1,5°C', '3°C', '0,5°C', '5°C'], 0,
  'O texto menciona que o mundo caminha para ultrapassar temporariamente o limite de 1,5°C estabelecido pelo Acordo de Paris.', 5),

-- Ciência e Tecnologia — IA em 2026
((select id from dossiers where title = 'Inteligência artificial em 2026: da novidade à maturidade'),
  'Segundo o texto, qual é a principal mudança na forma como a inteligência artificial é vista em 2026?',
  array['Ela passa de uma fase de novidade para uma fase de maturidade, com foco em resultados práticos', 'Ela deixa de ser usada por empresas e governos', 'Ela é substituída por outras tecnologias mais simples', 'Não houve qualquer mudança relevante em relação a anos anteriores'], 0,
  'O texto descreve 2026 como o ano em que a IA amadurece, priorizando aplicações práticas em vez de apenas demonstrações.', 1),
((select id from dossiers where title = 'Inteligência artificial em 2026: da novidade à maturidade'),
  'O que caracteriza os chamados "agentes autônomos", uma das principais tendências de IA em 2026?',
  array['São assistentes digitais capazes de executar tarefas completas com menor intervenção humana', 'São robôs físicos exclusivos para uso industrial', 'São programas que substituem totalmente os smartphones', 'São modelos de IA que funcionam apenas offline'], 0,
  'Os agentes autônomos evoluem dos assistentes digitais tradicionais, executando tarefas completas com menos intervenção humana.', 2),
((select id from dossiers where title = 'Inteligência artificial em 2026: da novidade à maturidade'),
  'O que são os "modelos multimodais", outra tendência de IA destacada em 2026?',
  array['Modelos que combinam texto, imagem, áudio e dados estruturados', 'Modelos que funcionam exclusivamente com texto', 'Modelos usados apenas em jogos eletrônicos', 'Modelos que não processam nenhum tipo de dado'], 0,
  'Modelos multimodais combinam diferentes tipos de dados para interpretar cenários mais complexos.', 3),
((select id from dossiers where title = 'Inteligência artificial em 2026: da novidade à maturidade'),
  'Qual valor o setor global de inteligência artificial deve superar em 2026, segundo o texto?',
  array['US$ 900 bilhões', 'R$ 23 bilhões', 'US$ 40 bilhões', 'R$ 900 milhões'], 0,
  'O texto cita que o setor global de IA deve superar US$ 900 bilhões em valor em 2026.', 4),
((select id from dossiers where title = 'Inteligência artificial em 2026: da novidade à maturidade'),
  'Quanto o Brasil prevê investir em inteligência artificial até 2028, segundo o Plano Brasileiro de Inteligência Artificial citado no texto?',
  array['R$ 23 bilhões', 'US$ 900 bilhões', 'R$ 900 bilhões', 'R$ 23 milhões'], 0,
  'O Plano Brasileiro de Inteligência Artificial prevê R$ 23 bilhões em investimentos até 2028.', 5),

-- Sociedade — Educação política
((select id from dossiers where title = 'Educação política passa a integrar o currículo das escolas brasileiras'),
  'Qual lei brasileira define os conteúdos obrigatórios ensinados nas escolas do país, mencionada no texto?',
  array['A LDB (Lei de Diretrizes e Bases da Educação Nacional)', 'A Constituição Federal, exclusivamente', 'O Código Civil', 'A Lei Orgânica dos Municípios'], 0,
  'A LDB é a legislação que define os conteúdos obrigatórios do currículo escolar brasileiro.', 1),
((select id from dossiers where title = 'Educação política passa a integrar o currículo das escolas brasileiras'),
  'O que passou a ser obrigatório na educação básica brasileira, segundo a mudança na LDB citada no texto?',
  array['A educação política e os direitos de cidadania', 'Apenas o ensino de línguas estrangeiras', 'Apenas disciplinas técnicas e profissionalizantes', 'Nenhum novo conteúdo foi incluído'], 0,
  'A mudança tornou obrigatória a abordagem de educação política e direitos de cidadania na educação básica.', 2),
((select id from dossiers where title = 'Educação política passa a integrar o currículo das escolas brasileiras'),
  'Qual é o objetivo declarado da inclusão da educação política no currículo escolar, segundo o texto?',
  array['Garantir que os estudantes conheçam a organização do Estado e os canais de participação democrática', 'Substituir totalmente o ensino de matemática', 'Eliminar a necessidade de eleições no país', 'Reduzir o número de anos de escolarização obrigatória'], 0,
  'O objetivo é que os estudantes tenham acesso a ensinamentos práticos sobre o funcionamento do Estado e a participação democrática.', 3),
((select id from dossiers where title = 'Educação política passa a integrar o currículo das escolas brasileiras'),
  'Segundo o texto, em que contexto a medida de tornar a educação política obrigatória é apresentada como resposta?',
  array['À baixa participação política de jovens e à preocupação com a desinformação', 'A um excesso de participação política da juventude', 'A uma redução do número de partidos políticos', 'A uma crise no sistema de saúde'], 0,
  'A medida busca fortalecer a formação cidadã dos estudantes diante da baixa participação política jovem e da desinformação.', 4),
((select id from dossiers where title = 'Educação política passa a integrar o currículo das escolas brasileiras'),
  'Quais outros temas já são citados como obrigatórios no currículo escolar brasileiro, segundo o texto?',
  array['A história e cultura afro-brasileira e indígena', 'Apenas conteúdos de educação física', 'Nenhum outro tema é obrigatório além da educação política', 'Apenas conteúdos de tecnologia da informação'], 0,
  'O texto cita que a educação política se soma a outras pautas já obrigatórias, como a história e cultura afro-brasileira e indígena.', 5),

-- Saúde — Ebola e Cbesp
((select id from dossiers where title = 'Brasil monitora surto de Ebola na África e avança na criação de um centro de emergências em saúde'),
  'Em que país e província foi identificado o surto de Ebola citado no texto, em maio de 2026?',
  array['Na província de Ituri, na República Democrática do Congo', 'No estado do Amazonas, no Brasil', 'Em Antália, na Turquia', 'Em Darfur, no Sudão'], 0,
  'O surto de Ebola foi identificado em maio de 2026 na província de Ituri, na República Democrática do Congo.', 1),
((select id from dossiers where title = 'Brasil monitora surto de Ebola na África e avança na criação de um centro de emergências em saúde'),
  'Qual é o nível de risco de disseminação do Ebola no Brasil, segundo as autoridades de saúde citadas no texto?',
  array['Considerado baixo', 'Considerado extremamente alto', 'Considerado inexistente, sem qualquer monitoramento', 'Não avaliado pelas autoridades'], 0,
  'Apesar de casos suspeitos notificados, o risco de introdução e disseminação da doença no Brasil é considerado baixo.', 2),
((select id from dossiers where title = 'Brasil monitora surto de Ebola na África e avança na criação de um centro de emergências em saúde'),
  'O que é o Cbesp, mencionado no texto como uma estrutura que o Brasil planeja criar até o fim de 2026?',
  array['O Centro Brasileiro de Emergências em Saúde Pública', 'Um novo hospital público em Brasília', 'Uma vacina contra o Ebola', 'Um acordo internacional de comércio'], 0,
  'O Cbesp é a estrutura nacional planejada para o enfrentamento de epidemias, surtos e outras emergências de saúde.', 3),
((select id from dossiers where title = 'Brasil monitora surto de Ebola na África e avança na criação de um centro de emergências em saúde'),
  'Qual experiência anterior motiva a criação do Cbesp, segundo o texto?',
  array['As falhas de coordenação observadas durante a pandemia de covid-19', 'O sucesso total da resposta à pandemia de covid-19, sem qualquer falha', 'Um surto de dengue ocorrido em 2020', 'Nenhuma experiência anterior é mencionada'], 0,
  'O texto explica que o Cbesp busca evitar repetir falhas de coordenação vistas durante a pandemia de covid-19.', 4),
((select id from dossiers where title = 'Brasil monitora surto de Ebola na África e avança na criação de um centro de emergências em saúde'),
  'Além de epidemias e surtos, que outro tipo de evento o Cbesp deve enfrentar, segundo o texto?',
  array['Eventos climáticos com impacto direto na saúde da população', 'Apenas eventos esportivos internacionais', 'Apenas crises econômicas', 'Nenhum outro tipo de evento além de epidemias'], 0,
  'O texto cita que o Cbesp também deve atuar em eventos climáticos com impacto direto na saúde da população.', 5);
