-- Química — Funções orgânicas (10 leaves, 5 questões cada)
insert into questions (catalog_node_id, prompt, options, correct_index, explanation, order_index) values
-- Hidrocarbonetos (0b38a8c8-d003-4a83-a64c-e9d13a55d2f2)
('0b38a8c8-d003-4a83-a64c-e9d13a55d2f2', 'Hidrocarbonetos são compostos orgânicos formados exclusivamente por átomos de:',
  array['Carbono e hidrogênio', 'Carbono e oxigênio', 'Carbono e nitrogênio', 'Hidrogênio e oxigênio'], 0,
  'Por definição, os hidrocarbonetos contêm apenas carbono e hidrogênio em sua composição.', 1),
('0b38a8c8-d003-4a83-a64c-e9d13a55d2f2', 'Os hidrocarbonetos saturados, com apenas ligações simples entre carbonos, são chamados de:',
  array['Alcanos', 'Alcenos', 'Alcinos', 'Aromáticos'], 0,
  'Os alcanos são hidrocarbonetos saturados, com fórmula geral CₙH₂ₙ₊₂.', 2),
('0b38a8c8-d003-4a83-a64c-e9d13a55d2f2', 'O metano (CH₄), principal componente do gás natural, é classificado como:',
  array['Um alcano', 'Um alceno', 'Um álcool', 'Um ácido carboxílico'], 0,
  'O metano é o alcano mais simples, formado por um único átomo de carbono ligado a quatro hidrogênios.', 3),
('0b38a8c8-d003-4a83-a64c-e9d13a55d2f2', 'O benzeno (C₆H₆), estrutura fundamental dos compostos aromáticos, é caracterizado por possuir:',
  array['Um anel de seis carbonos com ligações alternadas (ressonância)', 'Uma cadeia aberta e saturada', 'Apenas ligações triplas entre os carbonos', 'Nenhum átomo de carbono em sua estrutura'], 0,
  'O benzeno possui um anel hexagonal característico, com ligações que apresentam propriedades de ressonância.', 4),
('0b38a8c8-d003-4a83-a64c-e9d13a55d2f2', 'Os hidrocarbonetos são amplamente utilizados como fonte de energia, sendo a base de combustíveis como:',
  array['Gasolina, diesel e gás natural', 'Água e sal de cozinha', 'Vinagre e álcool de cozinha', 'Apenas materiais radioativos'], 0,
  'A maior parte dos combustíveis fósseis utilizados atualmente é composta essencialmente por hidrocarbonetos.', 5),

-- Álcool (bfab5e46-9539-4913-9b74-9caa035c2ee2)
('bfab5e46-9539-4913-9b74-9caa035c2ee2', 'A função orgânica álcool é caracterizada pela presença do grupo funcional:',
  array['Hidroxila (-OH) ligada a um carbono saturado', 'Carbonila (C=O)', 'Carboxila (-COOH)', 'Amina (-NH₂)'], 0,
  'O grupo hidroxila (-OH), ligado a um carbono saturado (não aromático), caracteriza os álcoois.', 1),
('bfab5e46-9539-4913-9b74-9caa035c2ee2', 'O etanol (álcool etílico), amplamente utilizado como combustível e em bebidas alcoólicas, é obtido industrialmente, entre outras formas, a partir da fermentação de:',
  array['Açúcares, como os presentes na cana-de-açúcar', 'Petróleo bruto exclusivamente', 'Minérios metálicos', 'Gases nobres'], 0,
  'A fermentação de açúcares (como a sacarose da cana) por leveduras é o principal processo de obtenção do etanol no Brasil.', 2),
('bfab5e46-9539-4913-9b74-9caa035c2ee2', 'Os álcoois são classificados em primários, secundários ou terciários de acordo com:',
  array['O tipo de carbono ao qual a hidroxila está ligada', 'O número total de átomos de carbono na molécula', 'O estado físico do composto', 'A presença ou ausência de anéis na estrutura'], 0,
  'A classificação depende se a hidroxila está ligada a um carbono primário, secundário ou terciário.', 3),
('bfab5e46-9539-4913-9b74-9caa035c2ee2', 'O metanol, diferentemente do etanol, é uma substância:',
  array['Altamente tóxica para o ser humano, podendo causar cegueira e morte', 'Segura para consumo humano em qualquer quantidade', 'Idêntica quimicamente ao etanol', 'Utilizada exclusivamente como adoçante'], 0,
  'O metanol é tóxico mesmo em pequenas quantidades, podendo causar graves danos à visão e ao sistema nervoso.', 4),
('bfab5e46-9539-4913-9b74-9caa035c2ee2', 'O glicerol (glicerina), um álcool com três hidroxilas (triálcool), é amplamente utilizado em:',
  array['Cosméticos e produtos de higiene, por suas propriedades hidratantes', 'Combustíveis automotivos exclusivamente', 'Fabricação de vidros', 'Produção de gases nobres'], 0,
  'O glicerol é valorizado por sua capacidade de reter umidade, sendo amplamente usado em cremes e sabonetes.', 5),

-- Fenol (a6ee5567-9eaa-4311-b38d-0d558fc20104)
('a6ee5567-9eaa-4311-b38d-0d558fc20104', 'A função orgânica fenol é caracterizada pela presença do grupo hidroxila (-OH) ligado diretamente a:',
  array['Um carbono de um anel aromático', 'Um carbono saturado, fora de qualquer anel', 'Um átomo de nitrogênio', 'Um átomo de oxigênio de outra hidroxila'], 0,
  'No fenol, diferentemente do álcool, a hidroxila está ligada diretamente a um carbono do anel aromático.', 1),
('a6ee5567-9eaa-4311-b38d-0d558fc20104', 'Uma das principais diferenças entre fenóis e álcoois é que os fenóis apresentam, em geral:',
  array['Maior caráter ácido', 'Menor caráter ácido', 'Ausência total de acidez', 'Nenhuma diferença relevante em relação aos álcoois'], 0,
  'Os fenóis são mais ácidos que os álcoois, devido à estabilização do ânion fenóxido pela ressonância do anel aromático.', 2),
('a6ee5567-9eaa-4311-b38d-0d558fc20104', 'O fenol comum (C₆H₅OH) é historicamente conhecido por seu uso, no século XIX, como:',
  array['Um dos primeiros antissépticos utilizados em cirurgias', 'Um adoçante artificial', 'Um combustível automotivo', 'Um gás utilizado em iluminação'], 0,
  'O fenol foi um dos primeiros compostos utilizados como antisséptico, introduzido por Joseph Lister em práticas cirúrgicas.', 3),
('a6ee5567-9eaa-4311-b38d-0d558fc20104', 'Compostos fenólicos estão presentes naturalmente em diversos alimentos e plantas, sendo associados a propriedades:',
  array['Antioxidantes', 'Exclusivamente tóxicas, sem qualquer benefício', 'Radioativas', 'Metálicas'], 0,
  'Muitos compostos fenólicos naturais, presentes em frutas, chás e vinhos, apresentam propriedades antioxidantes.', 4),
('a6ee5567-9eaa-4311-b38d-0d558fc20104', 'Diferentemente dos álcoois, os fenóis não devem ser nomeados com o sufixo "-ol" associado a um alcano, pois:',
  array['Sua estrutura está fundamentalmente ligada a um anel aromático, com nomenclatura própria', 'Não possuem qualquer grupo hidroxila em sua estrutura', 'São sempre gasosos à temperatura ambiente', 'Não podem ser sintetizados em laboratório'], 0,
  'A presença do anel aromático faz com que os fenóis tenham uma nomenclatura e classificação distintas dos álcoois comuns.', 5),

-- Éter (a1e1464d-452e-4217-b190-6066b91e6084)
('a1e1464d-452e-4217-b190-6066b91e6084', 'A função orgânica éter é caracterizada pela presença de um átomo de oxigênio:',
  array['Ligado a dois grupos orgânicos (carbonos), sem hidrogênio diretamente ligado a ele', 'Ligado a um único átomo de carbono e um hidrogênio', 'Ligado a um átomo de nitrogênio', 'Formando uma dupla ligação com o carbono'], 0,
  'Nos éteres, o oxigênio atua como uma "ponte" entre dois grupos orgânicos, sem hidrogênio ligado diretamente a ele.', 1),
('a1e1464d-452e-4217-b190-6066b91e6084', 'O éter etílico (dietílico) foi historicamente utilizado, na medicina, como:',
  array['Um dos primeiros anestésicos gerais', 'Um antibiótico', 'Um analgésico tópico apenas', 'Um adoçante artificial'], 0,
  'O éter dietílico foi amplamente utilizado como anestésico geral em cirurgias, especialmente no século XIX e início do XX.', 2),
('a1e1464d-452e-4217-b190-6066b91e6084', 'Os éteres são geralmente considerados compostos com baixa reatividade química, principalmente por:',
  array['Não possuírem hidrogênio ligado diretamente ao oxigênio', 'Serem extremamente instáveis', 'Possuírem carga elétrica elevada', 'Reagirem espontaneamente com qualquer substância'], 0,
  'A ausência de hidrogênio ligado ao oxigênio reduz a capacidade de formar ligações de hidrogênio intensas, tornando os éteres pouco reativos.', 3),
('a1e1464d-452e-4217-b190-6066b91e6084', 'Um éter e um álcool podem apresentar a mesma fórmula molecular, sendo, nesse caso, considerados:',
  array['Isômeros de função', 'Isótopos', 'Substâncias idênticas', 'Alótropos'], 0,
  'Éter dimetílico e álcool etílico, por exemplo, compartilham a fórmula C₂H₆O, mas pertencem a funções orgânicas diferentes.', 4),
('a1e1464d-452e-4217-b190-6066b91e6084', 'Os éteres são frequentemente utilizados como solventes em laboratórios químicos devido a:',
  array['Sua baixa reatividade e boa capacidade de dissolver compostos orgânicos', 'Sua alta reatividade com quase todas as substâncias', 'Sua incapacidade de dissolver qualquer substância', 'Sua toxicidade extrema, que impede qualquer manuseio'], 0,
  'A baixa reatividade dos éteres os torna solventes úteis, embora exijam cuidado por serem inflamáveis.', 5),

-- Aldeído (bf6b8661-333d-4328-a787-c65089ba7e26)
('bf6b8661-333d-4328-a787-c65089ba7e26', 'A função orgânica aldeído é caracterizada pela presença do grupo carbonila (C=O) ligado a:',
  array['Um átomo de hidrogênio e, no máximo, um radical orgânico, sempre na extremidade da cadeia', 'Dois radicais orgânicos, sem hidrogênio', 'Um grupo hidroxila', 'Um átomo de nitrogênio'], 0,
  'No aldeído, a carbonila está sempre na extremidade da cadeia, ligada a pelo menos um hidrogênio.', 1),
('bf6b8661-333d-4328-a787-c65089ba7e26', 'O formaldeído (metanal), um dos aldeídos mais simples, é amplamente conhecido por seu uso em:',
  array['Soluções conservantes de tecidos biológicos (formol)', 'Bebidas alcoólicas', 'Adoçantes artificiais', 'Combustíveis automotivos'], 0,
  'O formaldeído, em solução aquosa (formol), é utilizado como conservante de tecidos biológicos e desinfetante.', 2),
('bf6b8661-333d-4328-a787-c65089ba7e26', 'O acetaldeído (etanal) é um composto intermediário importante formado durante:',
  array['O metabolismo do álcool etílico no organismo humano', 'A fotossíntese das plantas', 'A formação de gases nobres', 'A produção industrial de sal de cozinha'], 0,
  'No fígado, o etanol é metabolizado em acetaldeído, substância associada a muitos dos efeitos negativos da ressaca.', 3),
('bf6b8661-333d-4328-a787-c65089ba7e26', 'Aldeídos podem ser identificados em laboratório por meio de testes específicos, como o teste de Tollens, que se baseia em sua capacidade de atuar como:',
  array['Agentes redutores', 'Agentes oxidantes fortes', 'Bases fortes', 'Substâncias completamente inertes'], 0,
  'Aldeídos são facilmente oxidados, atuando como agentes redutores em reações como o teste de Tollens (espelho de prata).', 4),
('bf6b8661-333d-4328-a787-c65089ba7e26', 'A vanilina, composto responsável pelo aroma característico da baunilha, pertence à função orgânica:',
  array['Aldeído', 'Éter', 'Amina', 'Ácido carboxílico'], 0,
  'A vanilina possui um grupo aldeído em sua estrutura, sendo um dos compostos aromáticos naturais mais conhecidos.', 5),

-- Cetona (0247a3f8-16d1-47df-b712-4862d0f1282f)
('0247a3f8-16d1-47df-b712-4862d0f1282f', 'A função orgânica cetona é caracterizada pela presença do grupo carbonila (C=O) ligado a:',
  array['Dois radicais orgânicos (carbonos), nunca na extremidade da cadeia', 'Um átomo de hidrogênio, obrigatoriamente', 'Um grupo hidroxila', 'Um átomo de nitrogênio'], 0,
  'Diferentemente do aldeído, na cetona a carbonila está sempre entre dois carbonos, nunca na extremidade da cadeia.', 1),
('0247a3f8-16d1-47df-b712-4862d0f1282f', 'A acetona (propanona), cetona mais simples e amplamente conhecida, é comumente utilizada como:',
  array['Solvente, inclusive em removedores de esmalte', 'Conservante alimentar', 'Combustível de aviação', 'Adoçante artificial'], 0,
  'A acetona é um solvente comum, presente, por exemplo, em removedores de esmalte de unha.', 2),
('0247a3f8-16d1-47df-b712-4862d0f1282f', 'Diferentemente dos aldeídos, as cetonas geralmente:',
  array['Não são facilmente oxidadas por reagentes brandos, como o de Tollens', 'São sempre mais reativas que os aldeídos', 'Não podem ser sintetizadas a partir de álcoois secundários', 'Possuem hidrogênio diretamente ligado à carbonila'], 0,
  'A ausência de hidrogênio diretamente ligado à carbonila torna as cetonas mais resistentes à oxidação que os aldeídos.', 3),
('0247a3f8-16d1-47df-b712-4862d0f1282f', 'As cetonas podem ser obtidas, entre outras formas, pela oxidação de:',
  array['Álcoois secundários', 'Álcoois primários, exclusivamente', 'Hidrocarbonetos saturados, sem qualquer outro reagente', 'Gases nobres'], 0,
  'A oxidação controlada de um álcool secundário produz uma cetona, enquanto a de um álcool primário tende a formar um aldeído.', 4),
('0247a3f8-16d1-47df-b712-4862d0f1282f', 'Níveis elevados de corpos cetônicos no organismo, condição chamada de cetose, podem estar associados a:',
  array['Jejum prolongado, dietas com baixo teor de carboidratos ou diabetes descompensada', 'Excesso de consumo de água', 'Exposição excessiva à luz solar', 'Uma dieta rica exclusivamente em carboidratos'], 0,
  'A cetose ocorre quando o corpo passa a utilizar gordura como fonte principal de energia, produzindo corpos cetônicos.', 5),

-- Ácido carboxílico (a9d41e8f-b75b-480b-bbe4-6539427e297c)
('a9d41e8f-b75b-480b-bbe4-6539427e297c', 'A função orgânica ácido carboxílico é caracterizada pela presença do grupo funcional:',
  array['Carboxila (-COOH)', 'Hidroxila (-OH), isoladamente', 'Carbonila (C=O), isoladamente', 'Amina (-NH₂)'], 0,
  'A carboxila (-COOH) é a combinação de uma carbonila e uma hidroxila no mesmo carbono, característica dos ácidos carboxílicos.', 1),
('a9d41e8f-b75b-480b-bbe4-6539427e297c', 'O ácido acético, presente no vinagre, é responsável por seu:',
  array['Sabor azedo e caráter ácido', 'Sabor doce', 'Cor característica', 'Odor adocicado'], 0,
  'O ácido acético (CH₃COOH) é o principal componente responsável pela acidez e pelo sabor característico do vinagre.', 2),
('a9d41e8f-b75b-480b-bbe4-6539427e297c', 'Os ácidos carboxílicos, em comparação com álcoois de cadeia semelhante, apresentam caráter ácido:',
  array['Mais acentuado', 'Muito menos acentuado', 'Idêntico, sem diferença', 'Nulo, sem qualquer acidez'], 0,
  'O grupo carboxila confere aos ácidos carboxílicos um caráter ácido bem mais evidente do que o observado em álcoois.', 3),
('a9d41e8f-b75b-480b-bbe4-6539427e297c', 'O ácido cítrico, presente em frutas como limão e laranja, é responsável, entre outros aspectos, por:',
  array['Conferir o sabor ácido característico dessas frutas', 'Conferir a cor amarela às frutas', 'Ser um álcool amplamente utilizado como combustível', 'Não ter qualquer relação com o sabor das frutas'], 0,
  'O ácido cítrico, um ácido carboxílico natural, é responsável pelo sabor azedo característico de frutas cítricas.', 4),
('a9d41e8f-b75b-480b-bbe4-6539427e297c', 'Os ácidos graxos, presentes em óleos e gorduras, são exemplos de:',
  array['Ácidos carboxílicos de cadeia longa', 'Álcoois de cadeia curta', 'Éteres complexos', 'Aminas aromáticas'], 0,
  'Os ácidos graxos são ácidos carboxílicos com longas cadeias carbônicas, componentes fundamentais de óleos e gorduras.', 5),

-- Éster (28c43ed0-e18f-41ac-84f3-0035879e636e)
('28c43ed0-e18f-41ac-84f3-0035879e636e', 'A função orgânica éster é formada, principalmente, a partir da reação entre:',
  array['Um ácido carboxílico e um álcool, com liberação de água', 'Dois álcoois diferentes', 'Um éter e uma amina', 'Um hidrocarboneto e um gás nobre'], 0,
  'A reação de esterificação combina um ácido carboxílico e um álcool, formando um éster e água.', 1),
('28c43ed0-e18f-41ac-84f3-0035879e636e', 'Muitos ésteres são conhecidos por apresentarem:',
  array['Odores agradáveis, frequentemente associados a frutas', 'Odores extremamente desagradáveis, sem exceção', 'Ausência total de qualquer odor', 'Cor característica avermelhada'], 0,
  'Diversos ésteres naturais são responsáveis pelos aromas característicos de frutas, usados também em perfumaria.', 2),
('28c43ed0-e18f-41ac-84f3-0035879e636e', 'As gorduras e os óleos vegetais são, quimicamente, formados principalmente por:',
  array['Ésteres de ácidos graxos com glicerol (triglicerídeos)', 'Éteres simples de cadeia curta', 'Aminas de cadeia longa', 'Hidrocarbonetos aromáticos'], 0,
  'Triglicerídeos, presentes em gorduras e óleos, são ésteres formados pela combinação de glicerol com três ácidos graxos.', 3),
('28c43ed0-e18f-41ac-84f3-0035879e636e', 'A reação inversa à esterificação, que decompõe um éster em ácido carboxílico e álcool na presença de água, é chamada de:',
  array['Hidrólise', 'Oxidação', 'Halogenação', 'Nitração'], 0,
  'A hidrólise do éster, na presença de água, regenera o ácido carboxílico e o álcool originais.', 4),
('28c43ed0-e18f-41ac-84f3-0035879e636e', 'O aspartame, um adoçante artificial amplamente utilizado, é um exemplo de composto que contém, em sua estrutura, a função:',
  array['Éster, entre outras funções presentes', 'Apenas hidrocarboneto puro', 'Apenas um gás nobre ligado a carbono', 'Nenhuma função orgânica reconhecida'], 0,
  'O aspartame é uma molécula complexa que inclui, entre suas funções orgânicas, um grupo éster em sua estrutura.', 5),

-- Amina (46421855-4463-49fe-8248-16700eb7b3ac)
('46421855-4463-49fe-8248-16700eb7b3ac', 'A função orgânica amina é caracterizada por derivar estruturalmente de qual composto inorgânico, pela substituição de hidrogênios por radicais orgânicos?',
  array['Amônia (NH₃)', 'Água (H₂O)', 'Gás carbônico (CO₂)', 'Ácido sulfúrico (H₂SO₄)'], 0,
  'As aminas são consideradas derivadas da amônia, com um ou mais hidrogênios substituídos por radicais orgânicos.', 1),
('46421855-4463-49fe-8248-16700eb7b3ac', 'As aminas são classificadas em primárias, secundárias ou terciárias de acordo com:',
  array['O número de radicais orgânicos ligados diretamente ao átomo de nitrogênio', 'O número total de átomos de carbono na molécula', 'O estado físico do composto', 'A presença de anéis aromáticos, exclusivamente'], 0,
  'A classificação depende de quantos hidrogênios da amônia original foram substituídos por radicais orgânicos.', 2),
('46421855-4463-49fe-8248-16700eb7b3ac', 'Muitas aminas são conhecidas por apresentarem odores característicos, frequentemente associados a:',
  array['Peixe em decomposição', 'Frutas frescas e doces', 'Ausência total de odor', 'Perfumes florais suaves, exclusivamente'], 0,
  'Muitas aminas de cadeia curta apresentam odores desagradáveis, lembrando peixe em decomposição.', 3),
('46421855-4463-49fe-8248-16700eb7b3ac', 'As aminas apresentam caráter básico devido à presença de:',
  array['Um par de elétrons não compartilhado no átomo de nitrogênio', 'Um grupo carboxila em sua estrutura', 'Uma carga elétrica positiva permanente', 'Nenhuma característica relacionada ao nitrogênio'], 0,
  'O par de elétrons livre no nitrogênio permite que as aminas atuem como bases, aceitando prótons (H⁺).', 4),
('46421855-4463-49fe-8248-16700eb7b3ac', 'A histamina, uma amina biologicamente importante, está diretamente relacionada a:',
  array['Reações alérgicas e inflamatórias no organismo', 'Processos exclusivamente digestivos, sem outra função', 'A formação da cor da pele', 'A produção de energia muscular'], 0,
  'A histamina é liberada pelo organismo durante reações alérgicas e inflamatórias, alvo de anti-histamínicos.', 5),

-- Amida (32224fa9-22dd-40b6-a5da-43f6996544ce)
('32224fa9-22dd-40b6-a5da-43f6996544ce', 'A função orgânica amida é caracterizada pela presença do grupo funcional formado pela combinação de:',
  array['Uma carbonila (C=O) ligada a um átomo de nitrogênio', 'Uma hidroxila ligada a um átomo de nitrogênio', 'Dois átomos de oxigênio ligados ao mesmo carbono', 'Um átomo de enxofre ligado ao carbono'], 0,
  'A amida apresenta o grupo -CONH₂ (ou variações), com a carbonila diretamente ligada ao nitrogênio.', 1),
('32224fa9-22dd-40b6-a5da-43f6996544ce', 'As ligações peptídicas, responsáveis por unir aminoácidos na formação de proteínas, são estruturalmente classificadas como:',
  array['Amidas', 'Ésteres', 'Éteres', 'Cetonas'], 0,
  'A ligação peptídica é, quimicamente, uma amida formada entre o grupo carboxila de um aminoácido e o grupo amina de outro.', 2),
('32224fa9-22dd-40b6-a5da-43f6996544ce', 'A ureia, importante composto nitrogenado eliminado pelo organismo humano na urina, é classificada como uma:',
  array['Diamida', 'Éster simples', 'Cetona aromática', 'Substância exclusivamente inorgânica'], 0,
  'A ureia possui dois grupos amida ligados a um mesmo átomo de carbono central, sendo classificada como uma diamida.', 3),
('32224fa9-22dd-40b6-a5da-43f6996544ce', 'Diferentemente das aminas, as amidas geralmente apresentam caráter:',
  array['Muito menos básico, sendo consideradas praticamente neutras', 'Extremamente mais básico que as aminas', 'Fortemente ácido, semelhante a ácidos minerais fortes', 'Idêntico ao das aminas, sem qualquer diferença'], 0,
  'A presença da carbonila junto ao nitrogênio reduz a disponibilidade do par de elétrons, tornando as amidas muito menos básicas.', 4),
('32224fa9-22dd-40b6-a5da-43f6996544ce', 'O paracetamol, um dos analgésicos mais utilizados no mundo, apresenta em sua estrutura química a função:',
  array['Amida, entre outras funções presentes na molécula', 'Apenas hidrocarboneto puro, sem outras funções', 'Apenas um gás nobre ligado a carbono', 'Nenhuma função orgânica reconhecida'], 0,
  'O paracetamol possui um grupo amida em sua estrutura molecular, além de outras funções orgânicas.', 5);
