-- Física — Óptica: Espelhos esféricos + Lentes (10 leaves, 5 questões cada)
insert into questions (catalog_node_id, prompt, options, correct_index, explanation, order_index) values
-- Espelho côncavo (3d47f86a-ebcd-4a53-8742-71245315dc79)
('3d47f86a-ebcd-4a53-8742-71245315dc79', 'O espelho côncavo é caracterizado por ter a superfície refletora voltada para:',
  array['O centro de curvatura, sendo convergente', 'Fora do centro de curvatura, sendo divergente', 'Uma superfície plana, sem curvatura', 'Duas direções simultaneamente'], 0,
  'O espelho côncavo tem a face refletora voltada para dentro, sendo classificado como espelho convergente.', 1),
('3d47f86a-ebcd-4a53-8742-71245315dc79', 'Quando um objeto é colocado além do centro de curvatura de um espelho côncavo, a imagem formada é:',
  array['Real, invertida e menor que o objeto', 'Virtual, direita e maior que o objeto', 'Real, direita e do mesmo tamanho', 'Virtual, invertida e menor'], 0,
  'Além do centro de curvatura, o espelho côncavo forma imagens reais, invertidas e reduzidas.', 2),
('3d47f86a-ebcd-4a53-8742-71245315dc79', 'Quando um objeto é colocado entre o foco e o vértice de um espelho côncavo, a imagem formada é:',
  array['Virtual, direita e maior que o objeto', 'Real, invertida e menor', 'Real, direita e menor', 'Virtual, invertida e maior'], 0,
  'Nessa posição, o espelho côncavo atua como uma lupa, formando imagem virtual, direita e ampliada.', 3),
('3d47f86a-ebcd-4a53-8742-71245315dc79', 'Espelhos côncavos são comumente utilizados em qual aplicação, por concentrar os raios de luz refletidos em um ponto?',
  array['Faróis de carro e antenas parabólicas', 'Espelhos retrovisores de carro', 'Espelhos de banheiro planos', 'Vitrines de lojas'], 0,
  'A propriedade convergente do espelho côncavo é aproveitada em faróis e antenas parabólicas.', 4),
('3d47f86a-ebcd-4a53-8742-71245315dc79', 'Se um objeto for colocado exatamente sobre o foco de um espelho côncavo, a imagem formada é considerada:',
  array['Imprópria, formada no infinito (raios refletidos paralelos)', 'Real e do mesmo tamanho do objeto', 'Virtual e invertida', 'Sempre invisível, sem qualquer formação de imagem'], 0,
  'Quando o objeto está no foco, os raios refletidos saem paralelos entre si, e a imagem é considerada imprópria, formada no infinito.', 5),

-- Espelho convexo (9cd02d29-4fa4-4a9e-ac80-69ac42eb183a)
('9cd02d29-4fa4-4a9e-ac80-69ac42eb183a', 'O espelho convexo é caracterizado por ter a superfície refletora voltada para:',
  array['Fora do centro de curvatura, sendo divergente', 'O centro de curvatura, sendo convergente', 'Uma superfície perfeitamente plana', 'Duas direções simultaneamente'], 0,
  'O espelho convexo reflete a luz a partir da parte externa da superfície esférica, sendo classificado como divergente.', 1),
('9cd02d29-4fa4-4a9e-ac80-69ac42eb183a', 'A imagem formada por um espelho convexo, para qualquer posição do objeto, é sempre:',
  array['Virtual, direita e menor que o objeto', 'Real, invertida e maior', 'Real, direita e do mesmo tamanho', 'Virtual, invertida e maior'], 0,
  'Diferentemente do côncavo, o espelho convexo sempre forma imagens virtuais, direitas e reduzidas.', 2),
('9cd02d29-4fa4-4a9e-ac80-69ac42eb183a', 'Espelhos convexos são frequentemente utilizados como espelhos retrovisores de veículos porque:',
  array['Proporcionam um campo de visão mais amplo, embora reduzam o tamanho da imagem', 'Ampliam consideravelmente a imagem, facilitando a visualização', 'Formam sempre imagens reais e invertidas', 'Eliminam totalmente os pontos cegos, sem qualquer distorção'], 0,
  'O espelho convexo amplia o campo de visão, mesmo reduzindo o tamanho aparente dos objetos refletidos.', 3),
('9cd02d29-4fa4-4a9e-ac80-69ac42eb183a', 'O foco de um espelho convexo é considerado:',
  array['Virtual, localizado atrás do espelho', 'Real, localizado à frente do espelho', 'Inexistente, pois espelhos convexos não possuem foco', 'Sempre coincidente com o centro de curvatura'], 0,
  'No espelho convexo, o foco é virtual, situado atrás da superfície refletora.', 4),
('9cd02d29-4fa4-4a9e-ac80-69ac42eb183a', 'Comparando o campo de visão de um espelho convexo com o de um espelho plano de mesmo tamanho, o espelho convexo apresenta campo de visão:',
  array['Maior', 'Menor', 'Idêntico', 'Nulo'], 0,
  'A curvatura do espelho convexo permite captar um ângulo de visão mais amplo do que um espelho plano equivalente.', 5),

-- Foco e centro de curvatura (2e7f9326-dd6b-4cf9-820b-df10c38fef0c)
('2e7f9326-dd6b-4cf9-820b-df10c38fef0c', 'Em espelhos esféricos, o centro de curvatura corresponde a:',
  array['O centro da esfera que deu origem ao espelho', 'O ponto onde os raios refletidos sempre se cruzam', 'A distância entre o objeto e o espelho', 'O ponto médio entre o objeto e sua imagem'], 0,
  'O centro de curvatura (C) é o centro da esfera geométrica da qual o espelho é uma parte.', 1),
('2e7f9326-dd6b-4cf9-820b-df10c38fef0c', 'A distância focal de um espelho esférico corresponde a:',
  array['Metade do raio de curvatura', 'O dobro do raio de curvatura', 'O mesmo valor do raio de curvatura', 'Um valor independente do raio de curvatura'], 0,
  'A distância focal (f) é igual à metade do raio de curvatura (R): f = R/2.', 2),
('2e7f9326-dd6b-4cf9-820b-df10c38fef0c', 'Um espelho esférico possui raio de curvatura de 40 cm. Qual é sua distância focal?',
  array['20 cm', '40 cm', '80 cm', '10 cm'], 0,
  'f = R/2 = 40/2 = 20 cm.', 3),
('2e7f9326-dd6b-4cf9-820b-df10c38fef0c', 'O foco principal de um espelho côncavo é o ponto onde:',
  array['Convergem os raios de luz paralelos ao eixo principal, após a reflexão', 'Divergem os raios de luz refletidos', 'Se localiza sempre atrás do espelho', 'O objeto deve obrigatoriamente estar posicionado'], 0,
  'No espelho côncavo, raios paralelos ao eixo principal convergem para o foco após a reflexão.', 4),
('2e7f9326-dd6b-4cf9-820b-df10c38fef0c', 'O eixo principal de um espelho esférico é definido como:',
  array['A reta que passa pelo centro de curvatura e pelo vértice do espelho', 'Qualquer reta que passe pelo objeto', 'A linha que representa a altura do objeto', 'A distância entre o objeto e sua imagem'], 0,
  'O eixo principal é a reta imaginária que passa pelo centro de curvatura (C) e pelo vértice (V) do espelho.', 5),

-- Raios notáveis (7d71354e-4686-4b6b-8825-be631b2ad042)
('7d71354e-4686-4b6b-8825-be631b2ad042', 'Um dos raios notáveis utilizados na construção de imagens em espelhos esféricos afirma que todo raio que incide paralelo ao eixo principal:',
  array['Reflete passando pelo foco (espelho côncavo) ou parece vir do foco (espelho convexo)', 'Sempre reflete paralelamente ao eixo principal', 'Nunca é refletido', 'Reflete perpendicularmente ao eixo principal'], 0,
  'Esse é um dos raios notáveis fundamentais na construção geométrica de imagens em espelhos esféricos.', 1),
('7d71354e-4686-4b6b-8825-be631b2ad042', 'Segundo os raios notáveis, um raio de luz que incide passando pelo centro de curvatura de um espelho esférico:',
  array['Retorna sobre si mesmo, pelo mesmo caminho', 'Reflete paralelamente ao eixo principal', 'Reflete perpendicularmente ao eixo principal', 'Nunca atinge o espelho'], 0,
  'Como incide perpendicularmente à superfície do espelho nesse ponto, o raio retorna exatamente pelo mesmo caminho.', 2),
('7d71354e-4686-4b6b-8825-be631b2ad042', 'Um raio de luz que incide sobre o vértice de um espelho esférico:',
  array['Reflete simetricamente em relação ao eixo principal', 'É sempre absorvido pelo espelho', 'Reflete sempre paralelamente ao eixo principal', 'Nunca é utilizado na construção de imagens'], 0,
  'O raio que incide no vértice obedece à lei da reflexão, refletindo simetricamente em relação ao eixo principal.', 3),
('7d71354e-4686-4b6b-8825-be631b2ad042', 'Um raio de luz que passa pelo foco de um espelho côncavo, antes de incidir sobre o espelho, é refletido:',
  array['Paralelamente ao eixo principal', 'Passando novamente pelo foco', 'Perpendicularmente ao eixo principal', 'Sempre absorvido pelo espelho'], 0,
  'Esse é o raio notável inverso ao primeiro: quem passa pelo foco antes de incidir, reflete paralelo ao eixo principal.', 4),
('7d71354e-4686-4b6b-8825-be631b2ad042', 'A utilização de raios notáveis na óptica geométrica tem como principal finalidade:',
  array['Determinar graficamente a posição, o tamanho e a natureza da imagem formada', 'Calcular exclusivamente a velocidade da luz', 'Medir a temperatura da fonte luminosa', 'Determinar a cor da luz refletida'], 0,
  'Os raios notáveis são ferramentas geométricas para construir e determinar as características da imagem formada.', 5),

-- Formação de imagens (cff09107-8f47-44a2-a166-8ba7a3c3d6ca)
('cff09107-8f47-44a2-a166-8ba7a3c3d6ca', 'Uma imagem é classificada como real quando:',
  array['É formada pelo cruzamento efetivo dos raios de luz refletidos ou refratados', 'É formada pelo prolongamento imaginário dos raios de luz', 'Nunca pode ser projetada em um anteparo', 'É sempre invertida em relação ao objeto'], 0,
  'Imagens reais resultam do encontro efetivo dos raios de luz, podendo ser projetadas em um anteparo.', 1),
('cff09107-8f47-44a2-a166-8ba7a3c3d6ca', 'Uma imagem é classificada como virtual quando:',
  array['É formada pelo prolongamento imaginário dos raios de luz, sem encontro real', 'Pode sempre ser projetada em um anteparo', 'É formada exclusivamente por espelhos côncavos', 'É sempre maior que o objeto'], 0,
  'Imagens virtuais surgem do prolongamento dos raios refletidos ou refratados, sem que eles realmente se cruzem.', 2),
('cff09107-8f47-44a2-a166-8ba7a3c3d6ca', 'Em relação ao objeto, uma imagem pode ser classificada, quanto à orientação, como:',
  array['Direita (mesmo sentido do objeto) ou invertida (sentido oposto)', 'Apenas real ou apenas virtual', 'Apenas maior ou apenas menor', 'Apenas colorida ou apenas em preto e branco'], 0,
  'Quanto à orientação, a imagem pode ser direita (congruente ao objeto) ou invertida em relação a ele.', 3),
('cff09107-8f47-44a2-a166-8ba7a3c3d6ca', 'Imagens reais formadas por espelhos côncavos são, em relação ao objeto, geralmente:',
  array['Invertidas', 'Sempre diretas', 'Sempre do mesmo tamanho, independentemente da posição', 'Impossíveis de serem projetadas'], 0,
  'Quando o espelho côncavo forma imagens reais, elas são invertidas em relação ao objeto original.', 4),
('cff09107-8f47-44a2-a166-8ba7a3c3d6ca', 'Quanto ao tamanho, a imagem formada por um espelho pode ser classificada como:',
  array['Maior, menor ou igual ao objeto, dependendo da posição e do tipo de espelho', 'Sempre maior que o objeto, independentemente da situação', 'Sempre menor que o objeto, sem exceções', 'Sempre do mesmo tamanho do objeto, em qualquer espelho'], 0,
  'O tamanho da imagem varia conforme a posição do objeto e o tipo de espelho.', 5),

-- Lentes convergentes (b124402a-4ae1-486c-abee-1db66cc184a6)
('b124402a-4ae1-486c-abee-1db66cc184a6', 'As lentes convergentes são caracterizadas por serem, em sua forma mais comum:',
  array['Mais espessas no centro do que nas bordas', 'Mais espessas nas bordas do que no centro', 'Perfeitamente planas, sem espessura variável', 'Sempre opacas, sem transparência'], 0,
  'As lentes convergentes são geralmente mais espessas no centro, o que faz os raios de luz convergirem.', 1),
('b124402a-4ae1-486c-abee-1db66cc184a6', 'Uma lente convergente, ao contrário da lente divergente, tem a capacidade de:',
  array['Concentrar os raios de luz paralelos em um único ponto (foco real)', 'Sempre espalhar os raios de luz', 'Impedir totalmente a passagem da luz', 'Formar apenas imagens virtuais, em qualquer situação'], 0,
  'A lente convergente refrata os raios de luz de forma a concentrá-los em um foco real.', 2),
('b124402a-4ae1-486c-abee-1db66cc184a6', 'Quando um objeto é colocado além do dobro da distância focal de uma lente convergente, a imagem formada é:',
  array['Real, invertida e menor que o objeto', 'Virtual, direita e maior', 'Real, direita e maior', 'Virtual, invertida e menor'], 0,
  'Nessa posição, a lente convergente forma uma imagem real, invertida e reduzida.', 3),
('b124402a-4ae1-486c-abee-1db66cc184a6', 'Quando um objeto é colocado entre o foco e a lente convergente, a imagem formada é:',
  array['Virtual, direita e maior que o objeto', 'Real, invertida e menor', 'Real, direita e do mesmo tamanho', 'Virtual, invertida e menor'], 0,
  'Nessa posição, a lente convergente atua como uma lupa, formando imagem virtual, direita e ampliada.', 4),
('b124402a-4ae1-486c-abee-1db66cc184a6', 'As lentes convergentes são utilizadas, entre outras aplicações, na correção de qual problema de visão?',
  array['Hipermetropia', 'Miopia', 'Daltonismo', 'Astigmatismo, exclusivamente'], 0,
  'A hipermetropia, dificuldade de enxergar de perto, é corrigida com lentes convergentes.', 5),

-- Lentes divergentes (4531a57b-6384-4e17-ac73-6ebbe7849d71)
('4531a57b-6384-4e17-ac73-6ebbe7849d71', 'As lentes divergentes são caracterizadas por serem, em sua forma mais comum:',
  array['Mais espessas nas bordas do que no centro', 'Mais espessas no centro do que nas bordas', 'Perfeitamente planas, sem espessura variável', 'Sempre opacas, sem transparência'], 0,
  'As lentes divergentes são mais finas no centro, o que faz os raios de luz se espalharem após a refração.', 1),
('4531a57b-6384-4e17-ac73-6ebbe7849d71', 'A imagem formada por uma lente divergente, para qualquer posição do objeto, é sempre:',
  array['Virtual, direita e menor que o objeto', 'Real, invertida e maior', 'Real, direita e do mesmo tamanho', 'Virtual, invertida e maior'], 0,
  'Assim como o espelho convexo, a lente divergente sempre forma imagens virtuais, direitas e reduzidas.', 2),
('4531a57b-6384-4e17-ac73-6ebbe7849d71', 'O foco de uma lente divergente é considerado:',
  array['Virtual', 'Real', 'Inexistente', 'Sempre igual ao centro óptico'], 0,
  'Na lente divergente, os raios de luz se afastam após a refração, e o foco é virtual, obtido pelo prolongamento dos raios.', 3),
('4531a57b-6384-4e17-ac73-6ebbe7849d71', 'As lentes divergentes são utilizadas, entre outras aplicações, na correção de qual problema de visão?',
  array['Miopia', 'Hipermetropia', 'Presbiopia, exclusivamente', 'Daltonismo'], 0,
  'A miopia, dificuldade de enxergar de longe, é corrigida com lentes divergentes.', 4),
('4531a57b-6384-4e17-ac73-6ebbe7849d71', 'Comparando lentes convergentes e divergentes quanto à formação de imagens reais, pode-se afirmar que:',
  array['Apenas a lente convergente é capaz de formar imagens reais, dependendo da posição do objeto', 'Ambas formam imagens reais em qualquer posição do objeto', 'Apenas a lente divergente forma imagens reais', 'Nenhuma das duas é capaz de formar qualquer tipo de imagem'], 0,
  'A lente divergente forma exclusivamente imagens virtuais, enquanto a convergente pode formar imagens reais ou virtuais.', 5),

-- Miopia (267de3da-1b72-4c3d-af98-0a38a3bedc32)
('267de3da-1b72-4c3d-af98-0a38a3bedc32', 'A miopia é um defeito visual caracterizado pela dificuldade de:',
  array['Enxergar objetos distantes com nitidez', 'Enxergar objetos próximos com nitidez', 'Distinguir cores', 'Enxergar em ambientes escuros'], 0,
  'Na miopia, a imagem se forma antes da retina, dificultando a visão nítida de objetos distantes.', 1),
('267de3da-1b72-4c3d-af98-0a38a3bedc32', 'Na miopia, a imagem dos objetos distantes se forma:',
  array['Antes da retina', 'Exatamente sobre a retina', 'Atrás da retina', 'Fora do olho, sem qualquer formação'], 0,
  'No olho míope, geralmente mais alongado, a imagem converge antes de atingir a retina.', 2),
('267de3da-1b72-4c3d-af98-0a38a3bedc32', 'A miopia pode ser corrigida com o uso de lentes:',
  array['Divergentes, que afastam o ponto de convergência da imagem', 'Convergentes, que aproximam o ponto de convergência', 'Apenas cirurgicamente, sem uso de lentes', 'De qualquer tipo, sem diferença significativa'], 0,
  'Lentes divergentes fazem com que a imagem passe a se formar exatamente sobre a retina, corrigindo a miopia.', 3),
('267de3da-1b72-4c3d-af98-0a38a3bedc32', 'Uma das causas comuns da miopia está relacionada a:',
  array['Um globo ocular mais alongado que o normal', 'Um globo ocular mais curto que o normal', 'A ausência total de cristalino', 'Um excesso de luz ambiente'], 0,
  'O alongamento do globo ocular é uma das principais causas da miopia.', 4),
('267de3da-1b72-4c3d-af98-0a38a3bedc32', 'Uma pessoa míope tem mais dificuldade para:',
  array['Ler uma placa de trânsito distante', 'Ler um livro segurado próximo aos olhos', 'Distinguir cores em qualquer distância', 'Enxergar em ambientes muito iluminados'], 0,
  'A miopia prejudica principalmente a visão de longe, dificultando a leitura de objetos distantes.', 5),

-- Hipermetropia (d28fdc19-50a8-4dca-9d0e-98407bfc325b)
('d28fdc19-50a8-4dca-9d0e-98407bfc325b', 'A hipermetropia é um defeito visual caracterizado pela dificuldade de:',
  array['Enxergar objetos próximos com nitidez', 'Enxergar objetos distantes com nitidez', 'Distinguir formas geométricas', 'Enxergar durante o dia'], 0,
  'Na hipermetropia, a imagem tende a se formar atrás da retina, dificultando a visão nítida de objetos próximos.', 1),
('d28fdc19-50a8-4dca-9d0e-98407bfc325b', 'Na hipermetropia, a imagem dos objetos próximos se forma:',
  array['Atrás da retina', 'Exatamente sobre a retina', 'Antes da retina', 'Fora do olho, sem qualquer formação'], 0,
  'No olho hipermétrope, geralmente mais curto, a imagem tenderia a convergir atrás da retina.', 2),
('d28fdc19-50a8-4dca-9d0e-98407bfc325b', 'A hipermetropia pode ser corrigida com o uso de lentes:',
  array['Convergentes, que aproximam o ponto de convergência da imagem', 'Divergentes, que afastam o ponto de convergência', 'Apenas cirurgicamente, sem uso de lentes', 'De qualquer tipo, sem diferença significativa'], 0,
  'Lentes convergentes ajudam a focar a imagem corretamente sobre a retina, corrigindo a hipermetropia.', 3),
('d28fdc19-50a8-4dca-9d0e-98407bfc325b', 'Uma das causas comuns da hipermetropia está relacionada a:',
  array['Um globo ocular mais curto que o normal', 'Um globo ocular mais alongado que o normal', 'A ausência total de cristalino', 'Um excesso de luz ambiente'], 0,
  'O encurtamento do globo ocular é uma das principais causas da hipermetropia.', 4),
('d28fdc19-50a8-4dca-9d0e-98407bfc325b', 'Uma pessoa hipermetrope tem mais dificuldade para:',
  array['Ler um livro segurado próximo aos olhos', 'Ler uma placa de trânsito distante', 'Distinguir cores em qualquer distância', 'Enxergar em ambientes muito escuros'], 0,
  'A hipermetropia prejudica principalmente a visão de perto, dificultando atividades como a leitura de um livro próximo.', 5),

-- Presbiopia (c7c85039-59ec-4178-8acd-9d672c717542)
('c7c85039-59ec-4178-8acd-9d672c717542', 'A presbiopia, popularmente conhecida como "vista cansada", está associada principalmente a:',
  array['O envelhecimento natural do cristalino, que perde elasticidade', 'Um alongamento excessivo do globo ocular', 'Uma infecção ocular comum', 'Uma exposição excessiva à luz solar'], 0,
  'Com o envelhecimento, o cristalino perde a capacidade de acomodação, dificultando o foco em objetos próximos.', 1),
('c7c85039-59ec-4178-8acd-9d672c717542', 'A presbiopia geralmente se manifesta com maior frequência a partir de qual faixa etária aproximada?',
  array['40 anos', '10 anos', '20 anos', '70 anos, exclusivamente'], 0,
  'A presbiopia costuma se manifestar a partir dos 40 anos, devido à perda progressiva de elasticidade do cristalino.', 2),
('c7c85039-59ec-4178-8acd-9d672c717542', 'A presbiopia é corrigida, de forma semelhante à hipermetropia, com o uso de lentes:',
  array['Convergentes', 'Divergentes', 'Cilíndricas, exclusivamente', 'Nenhum tipo de lente é eficaz nesse caso'], 0,
  'Assim como na hipermetropia, lentes convergentes ajudam a compensar a dificuldade de foco em objetos próximos.', 3),
('c7c85039-59ec-4178-8acd-9d672c717542', 'Diferentemente da hipermetropia, a presbiopia está associada a:',
  array['Um processo natural de envelhecimento do olho, e não ao formato do globo ocular', 'Um formato anormal do globo ocular desde o nascimento', 'Uma doença infecciosa', 'Uma característica exclusivamente genética não relacionada à idade'], 0,
  'Enquanto a hipermetropia pode estar presente desde a infância, a presbiopia decorre do envelhecimento do cristalino.', 4),
('c7c85039-59ec-4178-8acd-9d672c717542', 'É comum que uma mesma pessoa apresente, ao mesmo tempo, presbiopia e outro defeito visual, como a miopia. Nesse caso, geralmente é indicado o uso de:',
  array['Lentes multifocais, que corrigem diferentes distâncias em uma única lente', 'Nenhuma correção, pois os efeitos se anulariam', 'Apenas lentes divergentes, ignorando a presbiopia', 'Cirurgia obrigatória, sem alternativa de lentes'], 0,
  'Lentes multifocais combinam diferentes graus em uma mesma lente, corrigindo tanto a visão de perto quanto a de longe.', 5);
