-- New "dificil" questions for quimica: 24 questions, each already
-- with its en/es translation (48 translation rows).
--
-- ids are deterministic (uuid5 of the pt-BR prompt), so running this twice
-- inserts nothing new: questions use on conflict do nothing, translations
-- on conflict do update. The translation join refuses any row whose option
-- count differs from the original (correct_index is positional).

insert into questions (id, catalog_node_id, prompt, options, correct_index, explanation, order_index, difficulty)
select v.id::uuid, v.node::uuid, v.prompt, v.options, v.correct_index, v.explanation, v.order_index, 'dificil'
from (values
  ('b1ea9add-9df9-5b71-8c15-91c65d6eaba4', '1694b662-d892-4687-8727-9f74c2715b11',
   'Na combustão completa do metano (CH₄ + 2 O₂ → CO₂ + 2 H₂O), qual massa de CO₂ se forma a partir de 32 g de CH₄? (Massas molares: C = 12, H = 1, O = 16 g/mol.)',
   array['176 g', '44 g', '88 g', '22 g'], 2,
   'CH₄ tem 16 g/mol, então 32 g são 2 mol. A proporção CH₄ : CO₂ é 1 : 1, logo formam-se 2 mol de CO₂ = 2 · 44 = 88 g.', 100),
  ('d907b7bc-f207-5ac2-a877-4dd65132abe1', '1694b662-d892-4687-8727-9f74c2715b11',
   'Misturam-se 4 g de H₂ e 16 g de O₂, que reagem segundo 2 H₂ + O₂ → 2 H₂O. Qual massa de água se forma? (H = 1, O = 16 g/mol.)',
   array['36 g', '20 g', '18 g', '9 g'], 2,
   '4 g de H₂ = 2 mol, que exigiriam 1 mol (32 g) de O₂. Só há 16 g = 0,5 mol de O₂: ele é o reagente limitante. 0,5 mol de O₂ formam 1 mol de H₂O = 18 g, e sobra H₂.', 101),
  ('6974ddae-d102-5504-8e4a-9f30321475db', '8c2a2d8d-fbff-4b4a-8010-a79227baf853',
   'Na distribuição eletrônica do ferro (Z = 26) pelo diagrama de Linus Pauling, qual é o subnível mais energético?',
   array['4p⁶', '3d⁸', '3d⁶', '4s²'], 2,
   '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d⁶. Pela ordem de energia, o 3d é preenchido depois do 4s, por isso 3d⁶ é o mais energético, embora o 4s seja a camada mais externa (camada de valência).', 102),
  ('854e0475-e2f3-5c34-93d2-5a4f3767044f', '7ff92853-53ea-456f-81d2-d266d9a2cb74',
   'Qual é a configuração eletrônica do íon Fe³⁺ (Z = 26)?',
   array['[Ar] 3d⁵', '[Ar] 3d⁶', '[Ar] 4s² 3d³', '[Ar] 4s¹ 3d⁴'], 0,
   'O Fe neutro é [Ar] 4s² 3d⁶. Ao formar cátions, os elétrons saem primeiro da camada mais externa (4s) e só depois do 3d: Fe³⁺ perde os dois 4s e um 3d, ficando [Ar] 3d⁵.', 103),
  ('b508b827-b8fb-548d-ae8d-5e19724d2ec2', 'f7d3367f-0ede-4557-b30c-9ff239249e46',
   'As espécies F⁻, Ne, Na⁺ e Mg²⁺ são isoeletrônicas (10 elétrons cada). Qual delas tem o maior número de prótons e, por isso, o menor raio?',
   array['F⁻', 'Na⁺', 'Ne', 'Mg²⁺'], 3,
   'Com o mesmo número de elétrons, quem tem mais prótons atrai mais a eletrosfera e fica menor. Os números atômicos são F = 9, Ne = 10, Na = 11 e Mg = 12: o Mg²⁺ tem 12 prótons.', 104),
  ('66864ef1-d999-5750-80ed-96438cbbe3cf', '1d7027f0-9cb2-46bc-a969-71fb69e1c2c5',
   'Qual postulado do modelo atômico de Dalton foi contrariado pela descoberta dos isótopos?',
   array['Os compostos se formam em proporções fixas de átomos.', 'A matéria é formada por átomos.', 'Átomos de um mesmo elemento são idênticos em massa e propriedades.', 'Nas reações químicas, os átomos se recombinam, sem ser criados nem destruídos.'], 2,
   'Isótopos são átomos do mesmo elemento (mesmo número de prótons) com massas diferentes (números de nêutrons diferentes). Isso contradiz a ideia de Dalton de que todos os átomos de um elemento seriam idênticos.', 105),
  ('8ac673f1-8b23-5c62-a8d9-1c504ceedfae', '2880a5d7-04f0-4587-8c21-6225dba9a778',
   'Um elemento cuja camada de valência é 4s² 4p⁵ pertence a:',
   array['Grupo 17 (halogênios), 5º período', 'Grupo 15, 4º período', 'Grupo 17 (halogênios), 4º período', 'Grupo 7, 5º período'], 2,
   'A camada de valência é a 4 (4º período) e tem 7 elétrons (s² p⁵), característica dos halogênios, grupo 17. É o bromo.', 106),
  ('39d823f6-ded7-54a6-bd73-8049546d04e7', '8388a421-a787-4bf0-9e15-fee32a78e884',
   'Na reação de um metal alcalino (como o sódio) com a água, formam-se:',
   array['Óxido do metal e gás oxigênio', 'Um sal e água', 'Hidróxido do metal e gás hidrogênio', 'Hidreto do metal e gás oxigênio'], 2,
   'Exemplo: 2 Na + 2 H₂O → 2 NaOH + H₂. A reação é muito exotérmica e fica mais violenta descendo o grupo (K, Rb, Cs), porque o elétron de valência sai com mais facilidade.', 107),
  ('b67e3695-6f52-5832-ad47-91def621275a', 'db4c138e-2f1d-4b62-9c05-772bbfcd8a7e',
   'Qual destes elementos é classificado como semimetal (metaloide) e é a base da indústria de semicondutores?',
   array['Ferro', 'Alumínio', 'Enxofre', 'Silício'], 3,
   'O silício tem propriedades intermediárias entre metais e ametais: conduz eletricidade de forma controlável, o que o torna ideal para chips. Ferro e alumínio são metais; enxofre é ametal.', 108),
  ('d76054db-9707-5396-8074-5f703c78db9a', 'e0d8da54-8dd1-478e-98ed-1c168d697958',
   'Qual é a ordem crescente da primeira energia de ionização entre sódio, magnésio e alumínio (3º período)?',
   array['Mg < Na < Al', 'Na < Mg < Al', 'Na < Al < Mg', 'Al < Mg < Na'], 2,
   'A tendência é crescer no período, mas há uma exceção: o Al (3s² 3p¹) perde com facilidade seu único elétron 3p, que é mais energético e mais afastado que os 3s² do Mg. Por isso EI(Al) < EI(Mg), e a ordem é Na < Al < Mg.', 109),
  ('d1efe2d1-9537-5613-968e-0821103849f6', '732824ff-da40-4a2a-9f16-44c5274ba4b8',
   'No experimento de Rutherford com a lâmina de ouro, o fato de pouquíssimas partículas alfa serem refletidas indicou que:',
   array['A carga positiva e quase toda a massa do átomo se concentram num núcleo muito pequeno', 'Os elétrons giram em órbitas de energia quantizada', 'Os elétrons têm carga positiva', 'O átomo é maciço e indivisível'], 0,
   'A maioria das partículas atravessou a lâmina (o átomo é quase todo vazio), mas algumas voltaram: isso só se explica por uma região minúscula, densa e positiva, o núcleo. Órbitas quantizadas vêm depois, com Bohr.', 110),
  ('0cf90330-9cdf-5c82-a281-314e6dbbd844', '8dabaafe-27a9-467e-907c-7ed9aa0236b8',
   'Segundo o modelo de Bohr, um átomo emite luz quando:',
   array['Um elétron absorve energia e sobe de nível', 'Um elétron colide com o núcleo', 'Um elétron passa de um nível de maior energia para um de menor energia, liberando um fóton de energia bem definida', 'O núcleo se desintegra'], 2,
   'A energia do fóton emitido é a diferença entre os dois níveis. Como os níveis são quantizados, só algumas energias (cores) aparecem: por isso o espectro de emissão é descontínuo, em linhas. Absorver energia e subir de nível é o processo inverso.', 111),
  ('3885b88b-a71e-53fb-94d6-14df63d08812', '73cac530-0e0d-4775-b9c0-ae6ce4912b8c',
   'A chuva ácida está associada principalmente à emissão de:',
   array['Clorofluorcarbonetos (CFCs)', 'Metano (CH₄)', 'Gás carbônico (CO₂), apenas', 'Óxidos de enxofre e de nitrogênio, que formam H₂SO₄ e HNO₃ na atmosfera'], 3,
   'SO₂ e NOₓ, vindos da queima de combustíveis fósseis e da indústria, reagem com água e oxigênio e formam ácidos fortes. O CO₂ deixa a chuva levemente ácida mesmo sem poluição; CFCs afetam a camada de ozônio e o metano o efeito estufa.', 112),
  ('39f5277b-af6e-5b36-aac3-307de91a556d', 'f41ba2d7-4462-4a77-8362-272bb8313c47',
   'Misturam-se 200 mL de solução de NaCl 0,5 mol/L com 300 mL de solução de NaCl 1 mol/L. Qual é a concentração da solução final?',
   array['1,5 mol/L', '0,75 mol/L', '0,6 mol/L', '0,8 mol/L'], 3,
   'Soma-se a quantidade de soluto: 0,2 · 0,5 = 0,1 mol e 0,3 · 1 = 0,3 mol, total 0,4 mol. Volume final: 0,5 L. Concentração: 0,4 / 0,5 = 0,8 mol/L. (0,75 seria a média simples, que ignora os volumes.)', 113),
  ('85e6d466-47ca-55c7-8f11-5c2eef6ce9c3', 'f41ba2d7-4462-4a77-8362-272bb8313c47',
   '100 mL de uma solução 2 mol/L são diluídos com água até 500 mL. Qual é a nova concentração?',
   array['10 mol/L', '0,2 mol/L', '1 mol/L', '0,4 mol/L'], 3,
   'Na diluição a quantidade de soluto não muda: C₁ · V₁ = C₂ · V₂, então 2 · 100 = C₂ · 500 e C₂ = 0,4 mol/L.', 114),
  ('36da46eb-3e71-5b3d-9f9e-6aad5c17c011', '0b38a8c8-d003-4a83-a64c-e9d13a55d2f2',
   'Um hidrocarboneto de cadeia aberta com fórmula C₅H₈ pode ser:',
   array['Um alceno', 'Um alcano', 'Um cicloalcano', 'Um alcino ou um alcadieno'], 3,
   'C₅H₈ segue CₙH₂ₙ₋₂. Em cadeia aberta, isso corresponde a uma ligação tripla (alcino) ou a duas duplas (alcadieno). Alcanos são CₙH₂ₙ₊₂; alcenos e cicloalcanos, CₙH₂ₙ.', 115),
  ('7b378b4f-1bfd-5b0a-b677-43c4c6009312', '5a184c6f-1a60-4351-afa3-dbd35050d165',
   'Qual é o nome oficial (IUPAC) do composto CH₃–CH(CH₃)–CH₂–CH₃?',
   array['Pentano', '2-metilpropano', '3-metilbutano', '2-metilbutano'], 3,
   'A cadeia principal tem 4 carbonos (butano), com um metil. Numera-se pela extremidade mais próxima da ramificação, o que dá posição 2: 2-metilbutano. É isômero do pentano (C₅H₁₂), mas não é o pentano.', 116),
  ('223ed992-bc0f-5717-a97a-55a745d759fe', '4d4f08dd-12b7-447c-8a16-17a5ec57eb26',
   'Na adição de HBr ao propeno (CH₂=CH–CH₃), sem peróxidos, o produto principal é:',
   array['Bromopropeno', '1-bromopropano', '1,2-dibromopropano', '2-bromopropano'], 3,
   'Pela regra de Markovnikov, o hidrogênio entra no carbono da dupla que já tem mais hidrogênios (C1), e o bromo no outro (C2), que forma o carbocátion mais estável. Produto: 2-bromopropano.', 117),
  ('d9773b1e-4487-51e2-9100-de7905ba4858', '6e3937ec-84c9-4de7-86ea-ffb98fb8f93f',
   'Qual destes compostos apresenta isomeria geométrica (cis-trans)?',
   array['but-1-eno', 'Propeno', 'but-2-eno', '2-metilpropeno'], 2,
   'Para haver cis-trans, cada carbono da dupla precisa ter dois ligantes diferentes. No but-2-eno (CH₃–CH=CH–CH₃), cada carbono da dupla tem H e CH₃. Nos demais, um dos carbonos da dupla tem dois ligantes iguais (dois H ou dois CH₃).', 118),
  ('ae5fcb42-5195-5ee3-8f42-d6a3b39b275c', '28c43ed0-e18f-41ac-84f3-0035879e636e',
   'Na esterificação entre ácido etanoico (acético) e etanol, formam-se:',
   array['Etanoato de metila e água', 'Etanoato de etila e água', 'Ácido etanoico e etano', 'Éter dietílico e água'], 1,
   'Ácido carboxílico + álcool → éster + água. A parte do ácido dá o "etanoato", e a do álcool, o "etila": CH₃COOH + CH₃CH₂OH ⇌ CH₃COOCH₂CH₃ + H₂O.', 119),
  ('389445f8-fd2d-5aba-8e1c-97dddb800587', 'a9d41e8f-b75b-480b-bbe4-6539427e297c',
   'O ácido tricloroacético (Cl₃C–COOH) é muito mais forte que o ácido acético (H₃C–COOH) porque:',
   array['Tem mais hidrogênios ionizáveis', 'Os átomos de cloro atraem elétrons e estabilizam o ânion carboxilato (efeito indutivo)', 'Tem maior massa molar', 'Forma ligações de hidrogênio mais fortes com a água'], 1,
   'O cloro é muito eletronegativo e puxa densidade eletrônica pela cadeia, espalhando a carga negativa do ânion formado. Um ânion mais estável significa um ácido que ioniza mais. Os dois ácidos têm só um H ionizável.', 120),
  ('596502cf-b5dd-52c1-89c2-bebd0d595be1', '46421855-4463-49fe-8248-16700eb7b3ac',
   'O caráter básico das aminas se deve:',
   array['À presença de um grupo hidroxila (–OH)', 'À liberação de íons H⁺ em água', 'À ligação dupla C=O', 'Ao par de elétrons não ligante do nitrogênio, que pode receber um próton (H⁺)'], 3,
   'Como a amônia, o nitrogênio das aminas tem um par de elétrons livre que capta H⁺ (base de Brønsted-Lowry) e doa elétrons (base de Lewis). Liberar H⁺ é comportamento de ácido, e C=O não faz parte das aminas.', 121),
  ('286733f6-663c-525e-b2df-3f118fe35e8a', '0f844d56-03ad-4c25-b48b-ce3ce4a5715e',
   'A cadeia carbônica do composto CH₂=CH–CH₂–O–CH₃ é classificada como:',
   array['Fechada, saturada e homogênea', 'Aberta, insaturada, homogênea e normal', 'Aberta, saturada, heterogênea e ramificada', 'Aberta, insaturada, heterogênea e normal'], 3,
   'Não forma anel (aberta), tem uma dupla entre carbonos (insaturada), tem um heteroátomo, o oxigênio, entre dois carbonos (heterogênea) e não tem ramificações (normal).', 122),
  ('39cc00c3-bddf-5fd0-b770-e446542cb35d', 'bfab5e46-9539-4913-9b74-9caa035c2ee2',
   'Na oxidação branda (por exemplo, com K₂Cr₂O₇ em meio ácido), o propan-2-ol forma:',
   array['Nada, pois não sofre oxidação', 'Ácido propanoico', 'Propanona (uma cetona)', 'Propanal'], 2,
   'O propan-2-ol é um álcool secundário: a hidroxila está num carbono ligado a outros dois carbonos. Álcoois secundários oxidam a cetonas. Primários formariam aldeído (e depois ácido), e terciários não oxidam nessas condições.', 123)
) as v(id, node, prompt, options, correct_index, explanation, order_index)
join catalog_nodes c on c.id = v.node::uuid
on conflict (id) do nothing;

insert into question_translations (question_id, locale, prompt, options, explanation)
select v.id::uuid, v.locale, v.prompt, v.options, v.explanation
from (values
  ('b1ea9add-9df9-5b71-8c15-91c65d6eaba4', 'en',
   'In the complete combustion of methane (CH₄ + 2 O₂ → CO₂ + 2 H₂O), what mass of CO₂ is formed from 32 g of CH₄? (Molar masses: C = 12, H = 1, O = 16 g/mol.)',
   array['176 g', '44 g', '88 g', '22 g'],
   'CH₄ is 16 g/mol, so 32 g is 2 mol. The CH₄ : CO₂ ratio is 1 : 1, so 2 mol of CO₂ form = 2 · 44 = 88 g.'),
  ('b1ea9add-9df9-5b71-8c15-91c65d6eaba4', 'es',
   'En la combustión completa del metano (CH₄ + 2 O₂ → CO₂ + 2 H₂O), ¿qué masa de CO₂ se forma a partir de 32 g de CH₄? (Masas molares: C = 12, H = 1, O = 16 g/mol.)',
   array['176 g', '44 g', '88 g', '22 g'],
   'El CH₄ tiene 16 g/mol, así que 32 g son 2 mol. La proporción CH₄ : CO₂ es 1 : 1, por lo que se forman 2 mol de CO₂ = 2 · 44 = 88 g.'),
  ('d907b7bc-f207-5ac2-a877-4dd65132abe1', 'en',
   '4 g of H₂ and 16 g of O₂ are mixed and react according to 2 H₂ + O₂ → 2 H₂O. What mass of water is formed? (H = 1, O = 16 g/mol.)',
   array['36 g', '20 g', '18 g', '9 g'],
   '4 g of H₂ = 2 mol, which would need 1 mol (32 g) of O₂. There is only 16 g = 0.5 mol of O₂: it is the limiting reactant. 0.5 mol of O₂ forms 1 mol of H₂O = 18 g, and H₂ is left over.'),
  ('d907b7bc-f207-5ac2-a877-4dd65132abe1', 'es',
   'Se mezclan 4 g de H₂ y 16 g de O₂, que reaccionan según 2 H₂ + O₂ → 2 H₂O. ¿Qué masa de agua se forma? (H = 1, O = 16 g/mol.)',
   array['36 g', '20 g', '18 g', '9 g'],
   '4 g de H₂ = 2 mol, que necesitarían 1 mol (32 g) de O₂. Solo hay 16 g = 0,5 mol de O₂: es el reactivo limitante. 0,5 mol de O₂ forman 1 mol de H₂O = 18 g, y sobra H₂.'),
  ('6974ddae-d102-5504-8e4a-9f30321475db', 'en',
   'In the electron configuration of iron (Z = 26) following the Aufbau (Madelung) order, which is the highest-energy sublevel?',
   array['4p⁶', '3d⁸', '3d⁶', '4s²'],
   '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d⁶. In energy order, 3d fills after 4s, so 3d⁶ is the highest-energy sublevel, even though 4s is the outermost shell (valence shell).'),
  ('6974ddae-d102-5504-8e4a-9f30321475db', 'es',
   'En la configuración electrónica del hierro (Z = 26) según el diagrama de Moeller (Linus Pauling), ¿cuál es el subnivel de mayor energía?',
   array['4p⁶', '3d⁸', '3d⁶', '4s²'],
   '1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d⁶. En orden de energía, el 3d se llena después del 4s, por eso 3d⁶ es el de mayor energía, aunque el 4s sea la capa más externa (capa de valencia).'),
  ('854e0475-e2f3-5c34-93d2-5a4f3767044f', 'en',
   'What is the electron configuration of the Fe³⁺ ion (Z = 26)?',
   array['[Ar] 3d⁵', '[Ar] 3d⁶', '[Ar] 4s² 3d³', '[Ar] 4s¹ 3d⁴'],
   'Neutral Fe is [Ar] 4s² 3d⁶. When cations form, electrons leave the outermost shell (4s) first and only then 3d: Fe³⁺ loses both 4s electrons and one 3d electron, ending up as [Ar] 3d⁵.'),
  ('854e0475-e2f3-5c34-93d2-5a4f3767044f', 'es',
   '¿Cuál es la configuración electrónica del ion Fe³⁺ (Z = 26)?',
   array['[Ar] 3d⁵', '[Ar] 3d⁶', '[Ar] 4s² 3d³', '[Ar] 4s¹ 3d⁴'],
   'El Fe neutro es [Ar] 4s² 3d⁶. Al formar cationes, los electrones salen primero de la capa más externa (4s) y después del 3d: el Fe³⁺ pierde los dos 4s y un 3d, y queda [Ar] 3d⁵.'),
  ('b508b827-b8fb-548d-ae8d-5e19724d2ec2', 'en',
   'The species F⁻, Ne, Na⁺ and Mg²⁺ are isoelectronic (10 electrons each). Which has the most protons and therefore the smallest radius?',
   array['F⁻', 'Na⁺', 'Ne', 'Mg²⁺'],
   'With the same number of electrons, the species with more protons pulls the electron cloud in harder and is smaller. Atomic numbers are F = 9, Ne = 10, Na = 11 and Mg = 12: Mg²⁺ has 12 protons.'),
  ('b508b827-b8fb-548d-ae8d-5e19724d2ec2', 'es',
   'Las especies F⁻, Ne, Na⁺ y Mg²⁺ son isoelectrónicas (10 electrones cada una). ¿Cuál tiene el mayor número de protones y, por eso, el menor radio?',
   array['F⁻', 'Na⁺', 'Ne', 'Mg²⁺'],
   'Con el mismo número de electrones, la que tiene más protones atrae más la nube electrónica y es más pequeña. Los números atómicos son F = 9, Ne = 10, Na = 11 y Mg = 12: el Mg²⁺ tiene 12 protones.'),
  ('66864ef1-d999-5750-80ed-96438cbbe3cf', 'en',
   'Which postulate of Dalton''s atomic model was contradicted by the discovery of isotopes?',
   array['Compounds form in fixed ratios of atoms.', 'Matter is made of atoms.', 'Atoms of the same element are identical in mass and properties.', 'In chemical reactions, atoms rearrange without being created or destroyed.'],
   'Isotopes are atoms of the same element (same number of protons) with different masses (different numbers of neutrons). This contradicts Dalton''s idea that all atoms of an element would be identical.'),
  ('66864ef1-d999-5750-80ed-96438cbbe3cf', 'es',
   '¿Qué postulado del modelo atómico de Dalton fue contradicho por el descubrimiento de los isótopos?',
   array['Los compuestos se forman en proporciones fijas de átomos.', 'La materia está formada por átomos.', 'Los átomos de un mismo elemento son idénticos en masa y propiedades.', 'En las reacciones químicas, los átomos se recombinan, sin crearse ni destruirse.'],
   'Los isótopos son átomos del mismo elemento (mismo número de protones) con masas diferentes (distinto número de neutrones). Eso contradice la idea de Dalton de que todos los átomos de un elemento serían idénticos.'),
  ('8ac673f1-8b23-5c62-a8d9-1c504ceedfae', 'en',
   'An element whose valence shell is 4s² 4p⁵ belongs to:',
   array['Group 17 (halogens), period 5', 'Group 15, period 4', 'Group 17 (halogens), period 4', 'Group 7, period 5'],
   'The valence shell is shell 4 (period 4) and holds 7 electrons (s² p⁵), the signature of the halogens, group 17. The element is bromine.'),
  ('8ac673f1-8b23-5c62-a8d9-1c504ceedfae', 'es',
   'Un elemento cuya capa de valencia es 4s² 4p⁵ pertenece al:',
   array['Grupo 17 (halógenos), 5.º período', 'Grupo 15, 4.º período', 'Grupo 17 (halógenos), 4.º período', 'Grupo 7, 5.º período'],
   'La capa de valencia es la 4 (4.º período) y tiene 7 electrones (s² p⁵), característica de los halógenos, grupo 17. Es el bromo.'),
  ('39d823f6-ded7-54a6-bd73-8049546d04e7', 'en',
   'When an alkali metal (such as sodium) reacts with water, the products are:',
   array['The metal oxide and oxygen gas', 'A salt and water', 'The metal hydroxide and hydrogen gas', 'The metal hydride and oxygen gas'],
   'For example: 2 Na + 2 H₂O → 2 NaOH + H₂. The reaction is highly exothermic and becomes more violent down the group (K, Rb, Cs), because the valence electron is lost more easily.'),
  ('39d823f6-ded7-54a6-bd73-8049546d04e7', 'es',
   'En la reacción de un metal alcalino (como el sodio) con el agua, se forman:',
   array['Óxido del metal y oxígeno gaseoso', 'Una sal y agua', 'Hidróxido del metal e hidrógeno gaseoso', 'Hidruro del metal y oxígeno gaseoso'],
   'Ejemplo: 2 Na + 2 H₂O → 2 NaOH + H₂. La reacción es muy exotérmica y se vuelve más violenta al bajar en el grupo (K, Rb, Cs), porque el electrón de valencia se pierde con más facilidad.'),
  ('b67e3695-6f52-5832-ad47-91def621275a', 'en',
   'Which of these elements is classified as a metalloid (semimetal) and is the basis of the semiconductor industry?',
   array['Iron', 'Aluminum', 'Sulfur', 'Silicon'],
   'Silicon has properties between those of metals and nonmetals: its electrical conductivity can be controlled, which makes it ideal for chips. Iron and aluminum are metals; sulfur is a nonmetal.'),
  ('b67e3695-6f52-5832-ad47-91def621275a', 'es',
   '¿Cuál de estos elementos se clasifica como semimetal (metaloide) y es la base de la industria de los semiconductores?',
   array['Hierro', 'Aluminio', 'Azufre', 'Silicio'],
   'El silicio tiene propiedades intermedias entre metales y no metales: conduce la electricidad de forma controlable, lo que lo hace ideal para los chips. Hierro y aluminio son metales; el azufre es un no metal.'),
  ('d76054db-9707-5396-8074-5f703c78db9a', 'en',
   'What is the increasing order of first ionization energy among sodium, magnesium and aluminum (period 3)?',
   array['Mg < Na < Al', 'Na < Mg < Al', 'Na < Al < Mg', 'Al < Mg < Na'],
   'The trend is to increase across the period, but there is an exception: Al (3s² 3p¹) easily loses its single 3p electron, which is higher in energy and farther out than Mg''s 3s² pair. So IE(Al) < IE(Mg), and the order is Na < Al < Mg.'),
  ('d76054db-9707-5396-8074-5f703c78db9a', 'es',
   '¿Cuál es el orden creciente de la primera energía de ionización entre el sodio, el magnesio y el aluminio (3.er período)?',
   array['Mg < Na < Al', 'Na < Mg < Al', 'Na < Al < Mg', 'Al < Mg < Na'],
   'La tendencia es aumentar en el período, pero hay una excepción: el Al (3s² 3p¹) pierde con facilidad su único electrón 3p, que tiene más energía y está más alejado que el par 3s² del Mg. Por eso EI(Al) < EI(Mg), y el orden es Na < Al < Mg.'),
  ('d1efe2d1-9537-5613-968e-0821103849f6', 'en',
   'In Rutherford''s gold foil experiment, the fact that very few alpha particles bounced back indicated that:',
   array['The positive charge and nearly all of the atom''s mass are concentrated in a very small nucleus', 'Electrons move in orbits of quantized energy', 'Electrons have a positive charge', 'The atom is solid and indivisible'],
   'Most particles went through the foil (the atom is mostly empty space), but a few bounced back: that can only be explained by a tiny, dense, positive region, the nucleus. Quantized orbits came later, with Bohr.'),
  ('d1efe2d1-9537-5613-968e-0821103849f6', 'es',
   'En el experimento de Rutherford con la lámina de oro, el hecho de que muy pocas partículas alfa rebotaran indicó que:',
   array['La carga positiva y casi toda la masa del átomo se concentran en un núcleo muy pequeño', 'Los electrones giran en órbitas de energía cuantizada', 'Los electrones tienen carga positiva', 'El átomo es macizo e indivisible'],
   'La mayoría de las partículas atravesó la lámina (el átomo está casi vacío), pero algunas rebotaron: eso solo se explica por una región diminuta, densa y positiva, el núcleo. Las órbitas cuantizadas llegaron después, con Bohr.'),
  ('0cf90330-9cdf-5c82-a281-314e6dbbd844', 'en',
   'According to Bohr''s model, an atom emits light when:',
   array['An electron absorbs energy and moves up a level', 'An electron collides with the nucleus', 'An electron moves from a higher-energy level to a lower-energy level, releasing a photon of well-defined energy', 'The nucleus disintegrates'],
   'The photon''s energy equals the difference between the two levels. Because the levels are quantized, only certain energies (colors) appear, which is why the emission spectrum is made of discrete lines. Absorbing energy and moving up a level is the reverse process.'),
  ('0cf90330-9cdf-5c82-a281-314e6dbbd844', 'es',
   'Según el modelo de Bohr, un átomo emite luz cuando:',
   array['Un electrón absorbe energía y sube de nivel', 'Un electrón choca con el núcleo', 'Un electrón pasa de un nivel de mayor energía a uno de menor energía, liberando un fotón de energía bien definida', 'El núcleo se desintegra'],
   'La energía del fotón emitido es la diferencia entre los dos niveles. Como los niveles están cuantizados, solo aparecen algunas energías (colores): por eso el espectro de emisión es discontinuo, en líneas. Absorber energía y subir de nivel es el proceso inverso.'),
  ('3885b88b-a71e-53fb-94d6-14df63d08812', 'en',
   'Acid rain is mainly associated with emissions of:',
   array['Chlorofluorocarbons (CFCs)', 'Methane (CH₄)', 'Carbon dioxide (CO₂) alone', 'Sulfur and nitrogen oxides, which form H₂SO₄ and HNO₃ in the atmosphere'],
   'SO₂ and NOₓ, from burning fossil fuels and from industry, react with water and oxygen to form strong acids. CO₂ makes rain slightly acidic even without pollution; CFCs affect the ozone layer and methane the greenhouse effect.'),
  ('3885b88b-a71e-53fb-94d6-14df63d08812', 'es',
   'La lluvia ácida está asociada principalmente a la emisión de:',
   array['Clorofluorocarbonos (CFC)', 'Metano (CH₄)', 'Dióxido de carbono (CO₂), únicamente', 'Óxidos de azufre y de nitrógeno, que forman H₂SO₄ y HNO₃ en la atmósfera'],
   'El SO₂ y los NOₓ, procedentes de la quema de combustibles fósiles y de la industria, reaccionan con agua y oxígeno y forman ácidos fuertes. El CO₂ vuelve la lluvia levemente ácida incluso sin contaminación; los CFC afectan la capa de ozono y el metano el efecto invernadero.'),
  ('39f5277b-af6e-5b36-aac3-307de91a556d', 'en',
   '200 mL of 0.5 mol/L NaCl solution is mixed with 300 mL of 1 mol/L NaCl solution. What is the concentration of the final solution?',
   array['1.5 mol/L', '0.75 mol/L', '0.6 mol/L', '0.8 mol/L'],
   'Add up the solute: 0.2 · 0.5 = 0.1 mol and 0.3 · 1 = 0.3 mol, 0.4 mol in total. Final volume: 0.5 L. Concentration: 0.4 / 0.5 = 0.8 mol/L. (0.75 would be the simple average, which ignores the volumes.)'),
  ('39f5277b-af6e-5b36-aac3-307de91a556d', 'es',
   'Se mezclan 200 mL de solución de NaCl 0,5 mol/L con 300 mL de solución de NaCl 1 mol/L. ¿Cuál es la concentración de la solución final?',
   array['1,5 mol/L', '0,75 mol/L', '0,6 mol/L', '0,8 mol/L'],
   'Se suma la cantidad de soluto: 0,2 · 0,5 = 0,1 mol y 0,3 · 1 = 0,3 mol, en total 0,4 mol. Volumen final: 0,5 L. Concentración: 0,4 / 0,5 = 0,8 mol/L. (0,75 sería el promedio simple, que ignora los volúmenes.)'),
  ('85e6d466-47ca-55c7-8f11-5c2eef6ce9c3', 'en',
   '100 mL of a 2 mol/L solution is diluted with water to 500 mL. What is the new concentration?',
   array['10 mol/L', '0.2 mol/L', '1 mol/L', '0.4 mol/L'],
   'In a dilution the amount of solute does not change: C₁ · V₁ = C₂ · V₂, so 2 · 100 = C₂ · 500 and C₂ = 0.4 mol/L.'),
  ('85e6d466-47ca-55c7-8f11-5c2eef6ce9c3', 'es',
   '100 mL de una solución 2 mol/L se diluyen con agua hasta 500 mL. ¿Cuál es la nueva concentración?',
   array['10 mol/L', '0,2 mol/L', '1 mol/L', '0,4 mol/L'],
   'En la dilución la cantidad de soluto no cambia: C₁ · V₁ = C₂ · V₂, entonces 2 · 100 = C₂ · 500 y C₂ = 0,4 mol/L.'),
  ('36da46eb-3e71-5b3d-9f9e-6aad5c17c011', 'en',
   'An open-chain hydrocarbon with the formula C₅H₈ can be:',
   array['An alkene', 'An alkane', 'A cycloalkane', 'An alkyne or a diene'],
   'C₅H₈ fits CₙH₂ₙ₋₂. In an open chain, that means one triple bond (alkyne) or two double bonds (diene). Alkanes are CₙH₂ₙ₊₂; alkenes and cycloalkanes, CₙH₂ₙ.'),
  ('36da46eb-3e71-5b3d-9f9e-6aad5c17c011', 'es',
   'Un hidrocarburo de cadena abierta con fórmula C₅H₈ puede ser:',
   array['Un alqueno', 'Un alcano', 'Un cicloalcano', 'Un alquino o un alcadieno'],
   'C₅H₈ sigue CₙH₂ₙ₋₂. En cadena abierta, eso corresponde a un triple enlace (alquino) o a dos dobles (alcadieno). Los alcanos son CₙH₂ₙ₊₂; los alquenos y cicloalcanos, CₙH₂ₙ.'),
  ('7b378b4f-1bfd-5b0a-b677-43c4c6009312', 'en',
   'What is the official (IUPAC) name of the compound CH₃–CH(CH₃)–CH₂–CH₃?',
   array['Pentane', '2-methylpropane', '3-methylbutane', '2-methylbutane'],
   'The main chain has 4 carbons (butane) with one methyl group. Numbering starts from the end closest to the branch, giving position 2: 2-methylbutane. It is an isomer of pentane (C₅H₁₂), but it is not pentane.'),
  ('7b378b4f-1bfd-5b0a-b677-43c4c6009312', 'es',
   '¿Cuál es el nombre oficial (IUPAC) del compuesto CH₃–CH(CH₃)–CH₂–CH₃?',
   array['Pentano', '2-metilpropano', '3-metilbutano', '2-metilbutano'],
   'La cadena principal tiene 4 carbonos (butano), con un metilo. Se numera desde el extremo más cercano a la ramificación, lo que da la posición 2: 2-metilbutano. Es isómero del pentano (C₅H₁₂), pero no es el pentano.'),
  ('223ed992-bc0f-5717-a97a-55a745d759fe', 'en',
   'When HBr is added to propene (CH₂=CH–CH₃) without peroxides, the main product is:',
   array['Bromopropene', '1-bromopropane', '1,2-dibromopropane', '2-bromopropane'],
   'By Markovnikov''s rule, hydrogen adds to the double-bond carbon that already has more hydrogens (C1) and bromine to the other (C2), which forms the more stable carbocation. Product: 2-bromopropane.'),
  ('223ed992-bc0f-5717-a97a-55a745d759fe', 'es',
   'En la adición de HBr al propeno (CH₂=CH–CH₃), sin peróxidos, el producto principal es:',
   array['Bromopropeno', '1-bromopropano', '1,2-dibromopropano', '2-bromopropano'],
   'Por la regla de Markovnikov, el hidrógeno se une al carbono del doble enlace que ya tiene más hidrógenos (C1) y el bromo al otro (C2), que forma el carbocatión más estable. Producto: 2-bromopropano.'),
  ('d9773b1e-4487-51e2-9100-de7905ba4858', 'en',
   'Which of these compounds shows geometric (cis-trans) isomerism?',
   array['but-1-ene', 'Propene', 'but-2-ene', '2-methylpropene'],
   'For cis-trans isomerism, each double-bond carbon needs two different substituents. In but-2-ene (CH₃–CH=CH–CH₃), each double-bond carbon has an H and a CH₃. In the others, one of the double-bond carbons has two identical substituents (two H or two CH₃).'),
  ('d9773b1e-4487-51e2-9100-de7905ba4858', 'es',
   '¿Cuál de estos compuestos presenta isomería geométrica (cis-trans)?',
   array['but-1-eno', 'Propeno', 'but-2-eno', '2-metilpropeno'],
   'Para que haya cis-trans, cada carbono del doble enlace debe tener dos sustituyentes distintos. En el but-2-eno (CH₃–CH=CH–CH₃), cada carbono del doble enlace tiene H y CH₃. En los demás, uno de los carbonos del doble enlace tiene dos sustituyentes iguales (dos H o dos CH₃).'),
  ('ae5fcb42-5195-5ee3-8f42-d6a3b39b275c', 'en',
   'In the esterification of ethanoic (acetic) acid with ethanol, the products are:',
   array['Methyl ethanoate and water', 'Ethyl ethanoate and water', 'Ethanoic acid and ethane', 'Diethyl ether and water'],
   'Carboxylic acid + alcohol → ester + water. The acid part gives "ethanoate" and the alcohol part "ethyl": CH₃COOH + CH₃CH₂OH ⇌ CH₃COOCH₂CH₃ + H₂O.'),
  ('ae5fcb42-5195-5ee3-8f42-d6a3b39b275c', 'es',
   'En la esterificación entre el ácido etanoico (acético) y el etanol, se forman:',
   array['Etanoato de metilo y agua', 'Etanoato de etilo y agua', 'Ácido etanoico y etano', 'Éter dietílico y agua'],
   'Ácido carboxílico + alcohol → éster + agua. La parte del ácido da el "etanoato", y la del alcohol, el "etilo": CH₃COOH + CH₃CH₂OH ⇌ CH₃COOCH₂CH₃ + H₂O.'),
  ('389445f8-fd2d-5aba-8e1c-97dddb800587', 'en',
   'Trichloroacetic acid (Cl₃C–COOH) is much stronger than acetic acid (H₃C–COOH) because:',
   array['It has more ionizable hydrogens', 'The chlorine atoms withdraw electrons and stabilize the carboxylate anion (inductive effect)', 'It has a higher molar mass', 'It forms stronger hydrogen bonds with water'],
   'Chlorine is highly electronegative and pulls electron density along the chain, spreading out the negative charge of the resulting anion. A more stable anion means an acid that ionizes more. Both acids have only one ionizable H.'),
  ('389445f8-fd2d-5aba-8e1c-97dddb800587', 'es',
   'El ácido tricloroacético (Cl₃C–COOH) es mucho más fuerte que el ácido acético (H₃C–COOH) porque:',
   array['Tiene más hidrógenos ionizables', 'Los átomos de cloro atraen electrones y estabilizan el anión carboxilato (efecto inductivo)', 'Tiene mayor masa molar', 'Forma enlaces de hidrógeno más fuertes con el agua'],
   'El cloro es muy electronegativo y atrae densidad electrónica a lo largo de la cadena, distribuyendo la carga negativa del anión formado. Un anión más estable significa un ácido que se ioniza más. Los dos ácidos tienen un solo H ionizable.'),
  ('596502cf-b5dd-52c1-89c2-bebd0d595be1', 'en',
   'The basic character of amines is due to:',
   array['The presence of a hydroxyl group (–OH)', 'The release of H⁺ ions in water', 'the C=O double bond', 'The nitrogen''s lone pair of electrons, which can accept a proton (H⁺)'],
   'As in ammonia, the nitrogen in amines has a lone pair that picks up H⁺ (a Brønsted-Lowry base) and donates electrons (a Lewis base). Releasing H⁺ is acidic behavior, and C=O is not part of amines.'),
  ('596502cf-b5dd-52c1-89c2-bebd0d595be1', 'es',
   'El carácter básico de las aminas se debe:',
   array['A la presencia de un grupo hidroxilo (–OH)', 'A la liberación de iones H⁺ en agua', 'al doble enlace C=O', 'Al par de electrones no enlazante del nitrógeno, que puede aceptar un protón (H⁺)'],
   'Como en el amoníaco, el nitrógeno de las aminas tiene un par de electrones libre que capta H⁺ (base de Brønsted-Lowry) y dona electrones (base de Lewis). Liberar H⁺ es un comportamiento ácido, y el C=O no forma parte de las aminas.'),
  ('286733f6-663c-525e-b2df-3f118fe35e8a', 'en',
   'The carbon chain of the compound CH₂=CH–CH₂–O–CH₃ is classified as:',
   array['Closed, saturated and homogeneous', 'Open, unsaturated, homogeneous and unbranched', 'Open, saturated, heterogeneous and branched', 'Open, unsaturated, heterogeneous and unbranched'],
   'It forms no ring (open), has a carbon–carbon double bond (unsaturated), has a heteroatom, oxygen, between two carbons (heterogeneous) and has no branches (unbranched).'),
  ('286733f6-663c-525e-b2df-3f118fe35e8a', 'es',
   'La cadena carbonada del compuesto CH₂=CH–CH₂–O–CH₃ se clasifica como:',
   array['Cerrada, saturada y homogénea', 'Abierta, insaturada, homogénea y normal', 'Abierta, saturada, heterogénea y ramificada', 'Abierta, insaturada, heterogénea y normal'],
   'No forma anillo (abierta), tiene un doble enlace entre carbonos (insaturada), tiene un heteroátomo, el oxígeno, entre dos carbonos (heterogénea) y no tiene ramificaciones (normal).'),
  ('39cc00c3-bddf-5fd0-b770-e446542cb35d', 'en',
   'Under mild oxidation (for example, with K₂Cr₂O₇ in acid), propan-2-ol forms:',
   array['Nothing, since it does not oxidize', 'Propanoic acid', 'Propanone (a ketone)', 'Propanal'],
   'Propan-2-ol is a secondary alcohol: the hydroxyl sits on a carbon bonded to two other carbons. Secondary alcohols oxidize to ketones. Primary ones would give an aldehyde (and then an acid), and tertiary ones do not oxidize under these conditions.'),
  ('39cc00c3-bddf-5fd0-b770-e446542cb35d', 'es',
   'En la oxidación suave (por ejemplo, con K₂Cr₂O₇ en medio ácido), el propan-2-ol forma:',
   array['Nada, porque no se oxida', 'Ácido propanoico', 'Propanona (una cetona)', 'Propanal'],
   'El propan-2-ol es un alcohol secundario: el hidroxilo está en un carbono unido a otros dos carbonos. Los alcoholes secundarios se oxidan a cetonas. Los primarios formarían aldehído (y luego ácido), y los terciarios no se oxidan en estas condiciones.')
) as v(id, locale, prompt, options, explanation)
join questions q
  on q.id = v.id::uuid
 and cardinality(q.options) = cardinality(v.options)
on conflict (question_id, locale) do update
  set prompt = excluded.prompt,
      options = excluded.options,
      explanation = excluded.explanation;
