-- Português — Concordância e regência, exceto Crase (4 leaves, 5 questões cada)
insert into questions (catalog_node_id, prompt, options, correct_index, explanation, order_index) values
-- Concordância verbal (bab8c7fa-d87c-40af-9233-15430973131c)
('bab8c7fa-d87c-40af-9233-15430973131c', 'Assinale a alternativa em que a concordância verbal está de acordo com a norma-padrão:',
  array['Faz dois anos que ele se mudou.', 'Fazem dois anos que ele se mudou.', 'Haviam muitos problemas naquela empresa.', 'Deve haverem soluções para isso.'], 0,
  'Os verbos "fazer" (indicando tempo) e "haver" (no sentido de existir) são impessoais e devem permanecer sempre na 3ª pessoa do singular.', 1),
('bab8c7fa-d87c-40af-9233-15430973131c', 'Assinale a alternativa em que a concordância verbal está correta:',
  array['Nós vamos ao cinema hoje.', 'Nós vai ao cinema hoje.', 'Eu vamos ao cinema hoje.', 'Vós vai ao cinema hoje.'], 0,
  'O verbo deve concordar em pessoa e número com o sujeito; "nós" exige a forma "vamos".', 2),
('bab8c7fa-d87c-40af-9233-15430973131c', 'Assinale a alternativa em que a concordância verbal segue a norma-padrão:',
  array['Mais de um aluno faltou à prova.', 'Mais de um aluno faltaram à prova.', 'Um dos aluno faltou à prova.', 'Mais de um alunos faltou à prova.'], 0,
  'A expressão "mais de um" seguida de substantivo no singular exige, em regra, verbo no singular.', 3),
('bab8c7fa-d87c-40af-9233-15430973131c', 'Assinale a alternativa correta quanto à concordância verbal:',
  array['Fazia dez anos que não nos víamos.', 'Faziam dez anos que não nos víamos.', 'Fazem dez anos que não nos víamos.', 'Faziam dez anos atrás que não nos víamos.'], 0,
  'O verbo "fazer", indicando tempo decorrido, é impessoal e permanece na 3ª pessoa do singular, mesmo no passado ("fazia").', 4),
('bab8c7fa-d87c-40af-9233-15430973131c', 'Assinale a alternativa em que a concordância verbal está correta:',
  array['Precisa-se de funcionários experientes.', 'Precisam-se de funcionários experientes.', 'Preciso-se de funcionários experientes.', 'Precisam-se funcionários experientes.'], 0,
  'Com o verbo transitivo indireto "precisar" seguido de "de", o "se" é índice de indeterminação do sujeito, e o verbo permanece no singular.', 5),

-- Concordância nominal (722ebf8c-3c85-43e1-a1c9-8469fa704939)
('722ebf8c-3c85-43e1-a1c9-8469fa704939', 'Assinale a alternativa em que a concordância nominal está correta:',
  array['Ela mesma resolveu o problema.', 'Ela mesmo resolveu o problema.', 'Elas mesmo resolveram o problema.', 'Ele mesma resolveu o problema.'], 0,
  '"Mesmo(a)" usado como reforço concorda em gênero e número com o substantivo/pronome a que se refere; "ela" exige "mesma".', 1),
('722ebf8c-3c85-43e1-a1c9-8469fa704939', 'Assinale a alternativa correta quanto à concordância nominal:',
  array['Fizeram um trabalho bem feito.', 'Fizeram um trabalho bem feita.', 'Fizeram uma trabalho bem feito.', 'Fizeram um trabalho bens feito.'], 0,
  'O adjetivo "feito" deve concordar em gênero e número com o substantivo "trabalho" (masculino singular).', 2),
('722ebf8c-3c85-43e1-a1c9-8469fa704939', 'Assinale a alternativa em que a concordância nominal está correta:',
  array['Estão anexas ao processo as certidões solicitadas.', 'Estão anexo ao processo as certidões solicitadas.', 'Está anexas ao processo as certidões solicitadas.', 'Estão anexos ao processo as certidões solicitadas.'], 0,
  'O adjetivo "anexo" varia em gênero e número; como "certidões" é feminino plural, a forma correta é "anexas".', 3),
('722ebf8c-3c85-43e1-a1c9-8469fa704939', 'Assinale a alternativa correta quanto à concordância nominal:',
  array['É proibida a entrada de visitantes.', 'É proibido a entrada de visitantes.', 'É proibidos a entrada de visitantes.', 'É proibida entrada de visitantes.'], 0,
  'Diante de substantivo precedido de artigo definido ("a entrada"), a expressão "é proibido" deve concordar em gênero e número: "é proibida a entrada".', 4),
('722ebf8c-3c85-43e1-a1c9-8469fa704939', 'Assinale a alternativa em que a concordância nominal está correta:',
  array['Segue anexo o comprovante de pagamento.', 'Segue anexa o comprovante de pagamento.', 'Seguem anexo os comprovante de pagamento.', 'Segue anexos o comprovante de pagamento.'], 0,
  '"Anexo" deve concordar com o substantivo a que se refere; como "comprovante" é masculino singular, a forma correta é "anexo".', 5),

-- Regência verbal (68cee128-2eef-4976-9666-bd7f350ede5b)
('68cee128-2eef-4976-9666-bd7f350ede5b', 'Assinale a alternativa em que a regência verbal está de acordo com a norma-padrão:',
  array['Assisti ao filme ontem à noite.', 'Assisti o filme ontem à noite.', 'Assisti no filme ontem à noite.', 'Assisti para o filme ontem à noite.'], 0,
  'O verbo "assistir", no sentido de "ver", é transitivo indireto e exige a preposição "a": "assistir ao filme".', 1),
('68cee128-2eef-4976-9666-bd7f350ede5b', 'Assinale a alternativa correta quanto à regência verbal:',
  array['Cheguei à escola atrasado.', 'Cheguei na escola atrasado.', 'Cheguei a escola atrasado.', 'Cheguei em a escola atrasado.'], 0,
  'O verbo "chegar" rege a preposição "a"; diante de palavra feminina que também admite o artigo "a", ocorre a crase: "cheguei à escola".', 2),
('68cee128-2eef-4976-9666-bd7f350ede5b', 'Assinale a alternativa em que a regência verbal está correta:',
  array['Ele obedece aos pais em tudo.', 'Ele obedece os pais em tudo.', 'Ele obedece com os pais em tudo.', 'Ele obedece para os pais em tudo.'], 0,
  'O verbo "obedecer" é transitivo indireto e exige a preposição "a": "obedecer aos pais".', 3),
('68cee128-2eef-4976-9666-bd7f350ede5b', 'Assinale a alternativa correta quanto à regência verbal:',
  array['Prefiro chá a café.', 'Prefiro chá do que café.', 'Prefiro mais chá do que café.', 'Prefiro chá que café.'], 0,
  'O verbo "preferir", na norma-padrão, rege a preposição "a" e não deve ser usado com "do que": "prefiro chá a café".', 4),
('68cee128-2eef-4976-9666-bd7f350ede5b', 'Assinale a alternativa em que a regência verbal está correta, considerando o sentido de "pretender":',
  array['O projeto visa a melhorar a qualidade de vida dos moradores.', 'O projeto visa melhorar a qualidade de vida dos moradores.', 'O projeto visa em melhorar a qualidade de vida dos moradores.', 'O projeto visa para melhorar a qualidade de vida dos moradores.'], 0,
  'O verbo "visar", no sentido de "ter como objetivo", é transitivo indireto e exige a preposição "a": "visa a melhorar".', 5),

-- Regência nominal (bfef7570-b2ba-4900-a90d-0f20290faa61)
('bfef7570-b2ba-4900-a90d-0f20290faa61', 'Assinale a alternativa em que a regência nominal está correta:',
  array['Ele é fiel aos seus princípios.', 'Ele é fiel dos seus princípios.', 'Ele é fiel com seus princípios.', 'Ele é fiel em seus princípios.'], 0,
  'O adjetivo "fiel" rege a preposição "a": "fiel a algo/alguém".', 1),
('bfef7570-b2ba-4900-a90d-0f20290faa61', 'Assinale a alternativa em que a regência nominal está correta:',
  array['Ele tem necessidade de apoio profissional.', 'Ele tem necessidade em apoio profissional.', 'Ele tem necessidade com apoio profissional.', 'Ele tem necessidade para apoio profissional.'], 0,
  'O substantivo "necessidade" rege a preposição "de": "necessidade de algo".', 2),
('bfef7570-b2ba-4900-a90d-0f20290faa61', 'Assinale a alternativa correta quanto à regência nominal:',
  array['Os alunos estavam ansiosos por boas notícias.', 'Os alunos estavam ansiosos com boas notícias.', 'Os alunos estavam ansiosos de boas notícias.', 'Os alunos estavam ansiosos em boas notícias.'], 0,
  'O adjetivo "ansioso", no sentido de expectativa, rege a preposição "por": "ansioso por algo".', 3),
('bfef7570-b2ba-4900-a90d-0f20290faa61', 'Assinale a alternativa em que a regência nominal está correta:',
  array['Ele é grato aos amigos pela ajuda.', 'Ele é grato dos amigos pela ajuda.', 'Ele é grato com os amigos pela ajuda.', 'Ele é grato para os amigos pela ajuda.'], 0,
  'O adjetivo "grato" rege a preposição "a": "grato a alguém".', 4),
('bfef7570-b2ba-4900-a90d-0f20290faa61', 'Assinale a alternativa correta quanto à regência nominal:',
  array['O time estava confiante na vitória.', 'O time estava confiante da vitória.', 'O time estava confiante para a vitória.', 'O time estava confiante com a vitória.'], 0,
  'O adjetivo "confiante" rege a preposição "em": "confiante em algo".', 5);
