-- Física — Áreas gerais sem subdivisão (6 leaves, 8 questões cada)
insert into questions (catalog_node_id, prompt, options, correct_index, explanation, order_index) values
-- Termologia e Termodinâmica (c11d5ba1-65e8-487a-96e0-38e15a64af15)
('c11d5ba1-65e8-487a-96e0-38e15a64af15', 'A temperatura de um corpo está relacionada, microscopicamente, com:',
  array['O grau de agitação das partículas que o constituem', 'A quantidade total de matéria do corpo', 'A cor da superfície do corpo', 'O volume ocupado pelo corpo'], 0,
  'A temperatura reflete o grau médio de agitação (energia cinética) das moléculas de um corpo.', 1),
('c11d5ba1-65e8-487a-96e0-38e15a64af15', 'Na escala Celsius, a água entra em ebulição, ao nível do mar, a:',
  array['100°C', '0°C', '212°C', '50°C'], 0,
  'Ao nível do mar (pressão de 1 atm), a água ferve a 100°C na escala Celsius.', 2),
('c11d5ba1-65e8-487a-96e0-38e15a64af15', 'Para converter uma temperatura de Celsius para Kelvin, deve-se:',
  array['Somar 273 ao valor em Celsius', 'Multiplicar o valor em Celsius por 1,8', 'Subtrair 32 do valor em Celsius', 'Dividir o valor em Celsius por 2'], 0,
  'A relação entre Celsius e Kelvin é K = °C + 273.', 3),
('c11d5ba1-65e8-487a-96e0-38e15a64af15', 'O calor é uma forma de energia que se transfere espontaneamente:',
  array['De um corpo de maior temperatura para um de menor temperatura', 'De um corpo de menor temperatura para um de maior temperatura', 'Apenas entre corpos de mesma temperatura', 'Independentemente da diferença de temperatura entre os corpos'], 0,
  'O calor flui espontaneamente do corpo mais quente para o mais frio, até que ambos atinjam o equilíbrio térmico.', 4),
('c11d5ba1-65e8-487a-96e0-38e15a64af15', 'A Primeira Lei da Termodinâmica estabelece que a variação da energia interna de um sistema é igual a:',
  array['O calor trocado menos o trabalho realizado pelo sistema', 'Apenas o calor trocado, sem relação com o trabalho', 'Apenas o trabalho realizado, sem relação com o calor', 'Sempre igual a zero, em qualquer processo'], 0,
  'A Primeira Lei da Termodinâmica é uma forma de conservação de energia: ΔU = Q - W.', 5),
('c11d5ba1-65e8-487a-96e0-38e15a64af15', 'A dilatação térmica de um sólido ocorre porque, ao ser aquecido, suas partículas:',
  array['Passam a vibrar mais intensamente, aumentando a distância média entre elas', 'Diminuem de tamanho individualmente', 'Perdem massa gradualmente', 'Param completamente de se mover'], 0,
  'O aumento da temperatura intensifica a vibração das partículas, aumentando o espaçamento médio entre elas.', 6),
('c11d5ba1-65e8-487a-96e0-38e15a64af15', 'A Segunda Lei da Termodinâmica estabelece que, em um sistema isolado, a entropia (grau de desordem) tende a:',
  array['Aumentar ou, no máximo, permanecer constante ao longo do tempo', 'Diminuir sempre ao longo do tempo', 'Permanecer sempre em zero', 'Não ter qualquer relação com processos espontâneos'], 0,
  'A Segunda Lei estabelece que a entropia de um sistema isolado nunca diminui espontaneamente.', 7),
('c11d5ba1-65e8-487a-96e0-38e15a64af15', 'Uma máquina térmica converte calor em trabalho, mas, segundo a Segunda Lei da Termodinâmica, nenhuma máquina térmica pode ter eficiência de:',
  array['100%, pois sempre haverá alguma perda de energia na forma de calor rejeitado', 'Mais de 50%, em qualquer condição', 'Menos de 10%, obrigatoriamente', 'Zero, tornando qualquer máquina térmica inútil'], 0,
  'Nenhuma máquina térmica real pode converter todo o calor recebido em trabalho útil.', 8),

-- Ondulatória (8f3b95a7-93f3-4d62-b383-d9b66d005f08)
('8f3b95a7-93f3-4d62-b383-d9b66d005f08', 'Uma onda é definida, na física, como:',
  array['Uma perturbação que se propaga transportando energia, sem necessariamente transportar matéria', 'Um deslocamento de matéria de um ponto a outro', 'Uma força que atua exclusivamente em sólidos', 'Uma partícula com massa definida'], 0,
  'Ondas transportam energia através de um meio (ou do vácuo) sem que a matéria se desloque com elas.', 1),
('8f3b95a7-93f3-4d62-b383-d9b66d005f08', 'Quanto à necessidade de meio material para se propagar, as ondas podem ser classificadas em:',
  array['Mecânicas (precisam de meio) e eletromagnéticas (não precisam de meio)', 'Apenas mecânicas, pois toda onda precisa de meio material', 'Apenas eletromagnéticas, pois nenhuma onda precisa de meio', 'Transversais e longitudinais, exclusivamente quanto a esse critério'], 0,
  'Ondas mecânicas, como o som, precisam de um meio material; ondas eletromagnéticas propagam-se até no vácuo.', 2),
('8f3b95a7-93f3-4d62-b383-d9b66d005f08', 'A frequência de uma onda é definida como:',
  array['O número de oscilações completas realizadas por unidade de tempo', 'A distância entre duas cristas consecutivas', 'A velocidade de propagação da onda', 'A amplitude máxima da oscilação'], 0,
  'A frequência mede quantos ciclos completos a onda realiza a cada segundo, medida em hertz (Hz).', 3),
('8f3b95a7-93f3-4d62-b383-d9b66d005f08', 'A relação entre velocidade (v), frequência (f) e comprimento de onda (λ) é dada pela equação fundamental da ondulatória:',
  array['v = λ · f', 'v = λ / f', 'v = λ + f', 'v = f / λ'], 0,
  'A velocidade de propagação de uma onda é o produto de seu comprimento de onda pela frequência.', 4),
('8f3b95a7-93f3-4d62-b383-d9b66d005f08', 'Uma onda sonora se propaga a 340 m/s em determinado meio, com frequência de 170 Hz. Qual é o seu comprimento de onda, usando v = λ · f?',
  array['2 m', '0,5 m', '170 m', '510 m'], 0,
  'λ = v/f = 340/170 = 2 m.', 5),
('8f3b95a7-93f3-4d62-b383-d9b66d005f08', 'O som é classificado como uma onda:',
  array['Mecânica e longitudinal', 'Eletromagnética e transversal', 'Eletromagnética e longitudinal', 'Mecânica e transversal, exclusivamente'], 0,
  'O som é uma onda mecânica (precisa de meio material) e longitudinal (a vibração ocorre na mesma direção da propagação).', 6),
('8f3b95a7-93f3-4d62-b383-d9b66d005f08', 'O timbre de um som é a característica que permite distinguir:',
  array['Dois sons de mesma altura e intensidade, produzidos por fontes diferentes', 'Sons agudos de sons graves', 'Sons fortes de sons fracos', 'A velocidade de propagação de diferentes sons'], 0,
  'O timbre é o que permite diferenciar, por exemplo, a mesma nota tocada por um violão e por um piano.', 7),
('8f3b95a7-93f3-4d62-b383-d9b66d005f08', 'O fenômeno da ressonância ocorre quando:',
  array['Um sistema oscilante recebe energia em uma frequência igual à sua frequência natural, amplificando a oscilação', 'Duas ondas se anulam completamente, sem qualquer amplificação', 'Uma onda muda de meio sem alterar sua velocidade', 'O som deixa de se propagar em qualquer meio'], 0,
  'A ressonância amplifica a oscilação de um sistema quando a frequência da força aplicada coincide com sua frequência natural.', 8),

-- Eletricidade (89939da9-3bec-40f4-826d-514c063a9351)
('89939da9-3bec-40f4-826d-514c063a9351', 'A carga elétrica elementar, presente no elétron e no próton (com sinais opostos), tem valor aproximado de:',
  array['1,6 × 10⁻¹⁹ C', '9,1 × 10⁻³¹ C', '6,02 × 10²³ C', '3 × 10⁸ C'], 0,
  'A carga elementar (e) vale aproximadamente 1,6 × 10⁻¹⁹ coulombs.', 1),
('89939da9-3bec-40f4-826d-514c063a9351', 'A Primeira Lei de Ohm relaciona a tensão (U), a resistência (R) e a corrente elétrica (i) por meio da fórmula:',
  array['U = R · i', 'U = R / i', 'U = R + i', 'U = i / R'], 0,
  'A Primeira Lei de Ohm estabelece que a tensão é o produto da resistência pela corrente elétrica.', 2),
('89939da9-3bec-40f4-826d-514c063a9351', 'Um resistor de 10 Ω é percorrido por uma corrente elétrica de 2 A. Qual é a tensão aplicada sobre ele, segundo a Lei de Ohm?',
  array['20 V', '5 V', '12 V', '8 V'], 0,
  'U = R × i = 10 × 2 = 20 V.', 3),
('89939da9-3bec-40f4-826d-514c063a9351', 'Em um circuito com resistores associados em série, a corrente elétrica que percorre cada resistor é:',
  array['A mesma em todos os resistores', 'Diferente em cada resistor, proporcional à sua resistência', 'Sempre nula em pelo menos um dos resistores', 'Igual à soma das correntes individuais'], 0,
  'Na associação em série, há um único caminho para a corrente, que é a mesma em todos os componentes.', 4),
('89939da9-3bec-40f4-826d-514c063a9351', 'Em um circuito com resistores associados em paralelo, a tensão elétrica sobre cada resistor é:',
  array['A mesma em todos os resistores', 'Diferente em cada resistor, proporcional à sua resistência', 'Sempre igual a zero em pelo menos um deles', 'Igual à soma das tensões individuais'], 0,
  'Na associação em paralelo, todos os resistores estão sujeitos à mesma diferença de potencial (tensão).', 5),
('89939da9-3bec-40f4-826d-514c063a9351', 'A potência elétrica dissipada por um resistor pode ser calculada pela fórmula:',
  array['P = U · i', 'P = U / i', 'P = U + i', 'P = i / U'], 0,
  'A potência elétrica é o produto da tensão pela corrente elétrica.', 6),
('89939da9-3bec-40f4-826d-514c063a9351', 'Um chuveiro elétrico opera sob tensão de 220 V e corrente de 20 A. Qual é a potência dissipada por esse chuveiro?',
  array['4.400 W', '11 W', '240 W', '44 W'], 0,
  'P = U × i = 220 × 20 = 4.400 W.', 7),
('89939da9-3bec-40f4-826d-514c063a9351', 'Materiais condutores, como os metais, permitem a passagem de corrente elétrica com facilidade porque possuem:',
  array['Elétrons livres, capazes de se mover com facilidade pela estrutura do material', 'Ausência total de elétrons', 'Uma estrutura molecular sem qualquer carga elétrica', 'Apenas prótons em sua estrutura'], 0,
  'Nos condutores, os elétrons de valência se movem livremente, permitindo a condução de corrente elétrica.', 8),

-- Magnetismo e Eletromagnetismo (2678423c-4c04-4815-aea0-c4568078732e)
('2678423c-4c04-4815-aea0-c4568078732e', 'Um ímã, independentemente de seu tamanho, sempre possui:',
  array['Dois polos magnéticos (norte e sul), que não podem ser separados', 'Apenas um polo magnético', 'Três ou mais polos magnéticos', 'Nenhum polo definido'], 0,
  'Todo ímã possui um polo norte e um polo sul inseparáveis, mesmo quando dividido em partes menores.', 1),
('2678423c-4c04-4815-aea0-c4568078732e', 'Polos magnéticos de mesmo nome (norte-norte ou sul-sul), quando aproximados, tendem a:',
  array['Se repelir', 'Se atrair fortemente', 'Não interagir de forma alguma', 'Se fundir em um único polo'], 0,
  'Assim como cargas elétricas de mesmo sinal, polos magnéticos iguais se repelem.', 2),
('2678423c-4c04-4815-aea0-c4568078732e', 'A Experiência de Oersted, no início do século XIX, demonstrou que:',
  array['Uma corrente elétrica é capaz de gerar um campo magnético ao seu redor', 'Ímãs não têm qualquer relação com a eletricidade', 'O campo magnético terrestre é constante e imutável', 'A luz é uma onda eletromagnética'], 0,
  'Oersted observou que uma corrente elétrica desviava a agulha de uma bússola próxima, ligando eletricidade e magnetismo.', 3),
('2678423c-4c04-4815-aea0-c4568078732e', 'O fenômeno da indução eletromagnética, descrito por Faraday, consiste em:',
  array['A geração de corrente elétrica em um condutor devido à variação de um campo magnético', 'A atração entre dois ímãs de polos opostos', 'A repulsão entre cargas elétricas de mesmo sinal', 'A ausência de qualquer relação entre eletricidade e magnetismo'], 0,
  'A indução eletromagnética ocorre quando um campo magnético variável induz corrente em um condutor.', 4),
('2678423c-4c04-4815-aea0-c4568078732e', 'Os motores elétricos funcionam com base no princípio de que:',
  array['Um condutor percorrido por corrente elétrica, imerso em um campo magnético, sofre uma força', 'Ímãs perdem magnetismo ao entrar em contato com corrente elétrica', 'A eletricidade e o magnetismo são fenômenos completamente independentes', 'Correntes elétricas nunca interagem com campos magnéticos'], 0,
  'A força magnética sobre um condutor percorrido por corrente, dentro de um campo magnético, é o princípio de funcionamento dos motores elétricos.', 5),
('2678423c-4c04-4815-aea0-c4568078732e', 'As ondas eletromagnéticas, como a luz visível e as ondas de rádio, são formadas por:',
  array['Campos elétricos e magnéticos oscilantes e perpendiculares entre si', 'Apenas partículas de matéria em vibração', 'Exclusivamente campos elétricos, sem qualquer componente magnética', 'Exclusivamente campos magnéticos, sem qualquer componente elétrica'], 0,
  'Ondas eletromagnéticas resultam da oscilação conjunta e perpendicular de campos elétricos e magnéticos.', 6),
('2678423c-4c04-4815-aea0-c4568078732e', 'O campo magnético terrestre é frequentemente comparado ao de um grande ímã, sendo responsável, entre outros efeitos, por:',
  array['Orientar bússolas e proteger a Terra parcialmente de partículas do vento solar', 'Impedir totalmente a formação de auroras polares', 'Não ter qualquer influência sobre a navegação', 'Atrair objetos não magnéticos, como madeira e plástico'], 0,
  'O campo magnético terrestre orienta bússolas e desvia partículas carregadas do vento solar.', 7),
('2678423c-4c04-4815-aea0-c4568078732e', 'Um eletroímã é criado ao se enrolar um fio condutor em espiral (bobina) e fazer passar corrente elétrica por ele, geralmente ao redor de um núcleo de:',
  array['Material ferromagnético, como o ferro', 'Vidro', 'Borracha', 'Plástico'], 0,
  'O núcleo de ferro (material ferromagnético) intensifica o campo magnético gerado pela corrente elétrica na bobina.', 8),

-- Fluidos (bf4b630c-1de1-4cdd-9cbf-f31c70007234)
('bf4b630c-1de1-4cdd-9cbf-f31c70007234', 'A pressão exercida por um fluido em repouso, em determinado ponto, é definida como:',
  array['A força exercida por unidade de área', 'A força exercida por unidade de volume', 'A massa do fluido dividida pelo tempo', 'A velocidade do fluido naquele ponto'], 0,
  'Pressão é a razão entre a força exercida perpendicularmente e a área sobre a qual ela atua (P = F/A).', 1),
('bf4b630c-1de1-4cdd-9cbf-f31c70007234', 'O Princípio de Stevin, aplicado à hidrostática, estabelece que a pressão em um fluido em repouso aumenta:',
  array['Com o aumento da profundidade', 'Com a diminuição da profundidade', 'Independentemente da profundidade', 'Apenas na superfície do fluido'], 0,
  'Segundo o Princípio de Stevin, quanto maior a profundidade em um fluido, maior a pressão exercida sobre um ponto.', 2),
('bf4b630c-1de1-4cdd-9cbf-f31c70007234', 'O Princípio de Pascal estabelece que uma variação de pressão aplicada a um fluido em um recipiente fechado:',
  array['Se transmite integralmente a todos os pontos do fluido', 'Se dissipa completamente antes de atingir as extremidades do recipiente', 'Afeta apenas o ponto onde a força foi aplicada', 'Nunca se propaga em líquidos, apenas em gases'], 0,
  'O Princípio de Pascal é a base de funcionamento de prensas e elevadores hidráulicos.', 3),
('bf4b630c-1de1-4cdd-9cbf-f31c70007234', 'O Princípio de Arquimedes afirma que todo corpo imerso, total ou parcialmente, em um fluido recebe um empuxo igual a:',
  array['O peso do volume de fluido deslocado pelo corpo', 'O peso total do corpo, independentemente do fluido', 'A metade do peso do corpo', 'Zero, em qualquer situação'], 0,
  'O empuxo é uma força vertical para cima, com intensidade igual ao peso do volume de fluido deslocado pelo corpo.', 4),
('bf4b630c-1de1-4cdd-9cbf-f31c70007234', 'Um corpo flutua em um líquido quando:',
  array['Sua densidade média é menor que a densidade do líquido', 'Sua densidade média é maior que a densidade do líquido', 'Sua massa é igual à massa do líquido deslocado, independentemente da densidade', 'Ele não desloca nenhuma quantidade de líquido'], 0,
  'Um corpo flutua quando é menos denso que o fluido em que está imerso.', 5),
('bf4b630c-1de1-4cdd-9cbf-f31c70007234', 'Um navio de aço, material mais denso que a água, consegue flutuar porque:',
  array['Seu formato faz com que a densidade média do conjunto (incluindo o ar interno) seja menor que a da água', 'O aço se torna menos denso ao entrar em contato com a água', 'A água doce sempre sustenta qualquer objeto, independentemente da densidade', 'Navios não deslocam volume de água'], 0,
  'O formato do casco faz a densidade média do navio (incluindo os espaços vazios) ser menor que a da água.', 6),
('bf4b630c-1de1-4cdd-9cbf-f31c70007234', 'A prensa hidráulica é uma aplicação prática do:',
  array['Princípio de Pascal', 'Princípio de Arquimedes', 'Princípio de Stevin, exclusivamente', 'Princípio da Inércia'], 0,
  'A prensa hidráulica utiliza o Princípio de Pascal para multiplicar forças aplicadas em um fluido confinado.', 7),
('bf4b630c-1de1-4cdd-9cbf-f31c70007234', 'Em um fluido em repouso, a pressão exercida sobre um ponto atua:',
  array['Em todas as direções, com igual intensidade (pressão isotrópica)', 'Apenas na direção vertical, de cima para baixo', 'Apenas na direção horizontal', 'Somente na superfície do fluido'], 0,
  'Em um fluido em repouso, a pressão em um ponto se distribui igualmente em todas as direções.', 8),

-- Física Moderna (85e6f278-d298-4e1f-aca8-e602debf1051)
('85e6f278-d298-4e1f-aca8-e602debf1051', 'A Teoria da Relatividade Restrita, formulada por Albert Einstein, estabelece que a velocidade da luz no vácuo:',
  array['É constante para todos os observadores, independentemente de seu movimento', 'Varia conforme a velocidade do observador', 'É infinita, sem qualquer limite', 'Depende exclusivamente da cor da luz'], 0,
  'Um dos postulados centrais da Relatividade Restrita é que a velocidade da luz no vácuo é constante para todos os referenciais inerciais.', 1),
('85e6f278-d298-4e1f-aca8-e602debf1051', 'A famosa equação E = m·c², proposta por Einstein, expressa a relação entre:',
  array['Massa e energia', 'Força e aceleração', 'Velocidade e tempo', 'Pressão e volume'], 0,
  'Essa equação mostra que massa e energia são formas equivalentes e podem se converter uma na outra.', 2),
('85e6f278-d298-4e1f-aca8-e602debf1051', 'A radioatividade é o fenômeno em que núcleos atômicos instáveis:',
  array['Emitem espontaneamente partículas ou radiação, transformando-se em outros núcleos', 'Permanecem sempre estáveis, sem qualquer alteração', 'Absorvem elétrons do ambiente, tornando-se neutros', 'Perdem toda sua massa instantaneamente'], 0,
  'Núcleos radioativos se desintegram espontaneamente, emitindo partículas ou radiação, até atingirem estabilidade.', 3),
('85e6f278-d298-4e1f-aca8-e602debf1051', 'A meia-vida de um material radioativo é definida como o tempo necessário para que:',
  array['Metade dos núcleos radioativos presentes na amostra se desintegre', 'Todos os núcleos radioativos se desintegrem completamente', 'A amostra dobre de massa', 'A amostra pare completamente de emitir radiação'], 0,
  'A meia-vida é o intervalo de tempo em que a quantidade de núcleos radioativos se reduz à metade.', 4),
('85e6f278-d298-4e1f-aca8-e602debf1051', 'A Física Quântica, diferentemente da física clássica, propõe que a energia é emitida e absorvida em:',
  array['Pacotes discretos, chamados de quanta (ou fótons, no caso da luz)', 'Quantidades contínuas, sem qualquer limitação', 'Quantidades sempre infinitas', 'Uma única unidade fixa, igual para qualquer fenômeno'], 0,
  'Max Planck propôs que a energia é quantizada, emitida em pacotes discretos, rompendo com a visão contínua da física clássica.', 5),
('85e6f278-d298-4e1f-aca8-e602debf1051', 'O efeito fotoelétrico, explicado por Einstein, consiste em:',
  array['A emissão de elétrons por uma superfície metálica quando exposta à luz de frequência suficiente', 'A absorção total da luz por qualquer material, sem qualquer emissão', 'A criação espontânea de novos átomos a partir da luz', 'Um fenômeno exclusivo de materiais não condutores'], 0,
  'Einstein explicou o efeito fotoelétrico considerando a luz composta por fótons, capazes de arrancar elétrons de um metal.', 6),
('85e6f278-d298-4e1f-aca8-e602debf1051', 'O modelo atômico de Bohr introduziu a ideia de que os elétrons se movem em torno do núcleo em:',
  array['Órbitas com níveis de energia bem definidos (quantizados)', 'Trajetórias completamente aleatórias, sem qualquer padrão', 'Uma única órbita fixa, igual para todos os átomos', 'Órbitas que variam continuamente de energia, sem restrição'], 0,
  'Bohr propôs que os elétrons só podem ocupar órbitas específicas, associadas a níveis discretos de energia.', 7),
('85e6f278-d298-4e1f-aca8-e602debf1051', 'Reatores nucleares geram energia elétrica a partir do processo de:',
  array['Fissão nuclear, na qual núcleos pesados se dividem, liberando grande quantidade de energia', 'Fusão nuclear controlada em larga escala comercial, já plenamente estabelecida', 'Combustão química convencional, semelhante à queima de carvão', 'Absorção de luz solar por painéis especiais'], 0,
  'A maioria dos reatores nucleares comerciais atuais utiliza a fissão de núcleos pesados, como o urânio.', 8);
