-- Química — Estrutura atômica + Modelos atômicos (9 leaves, 5 questões cada)
insert into questions (catalog_node_id, prompt, options, correct_index, explanation, order_index) values
-- Prótons (f7d3367f-0ede-4557-b30c-9ff239249e46)
('f7d3367f-0ede-4557-b30c-9ff239249e46', 'Os prótons são partículas subatômicas localizadas:',
  array['No núcleo do átomo, com carga elétrica positiva', 'Na eletrosfera, com carga elétrica negativa', 'No núcleo do átomo, sem carga elétrica', 'Fora do átomo, orbitando livremente'], 0,
  'Os prótons, de carga positiva, estão localizados no núcleo atômico, junto com os nêutrons.', 1),
('f7d3367f-0ede-4557-b30c-9ff239249e46', 'O número atômico (Z) de um elemento químico corresponde ao número de:',
  array['Prótons presentes no núcleo do átomo', 'Nêutrons presentes no núcleo', 'Elétrons na última camada', 'Isótopos conhecidos do elemento'], 0,
  'O número atômico é definido pela quantidade de prótons, característica que identifica cada elemento químico.', 2),
('f7d3367f-0ede-4557-b30c-9ff239249e46', 'Um átomo neutro deve ter necessariamente:',
  array['O mesmo número de prótons e elétrons', 'O mesmo número de prótons e nêutrons', 'Mais elétrons do que prótons', 'Mais prótons do que elétrons'], 0,
  'Para que um átomo seja eletricamente neutro, o número de prótons deve igualar o de elétrons.', 3),
('f7d3367f-0ede-4557-b30c-9ff239249e46', 'A massa de um próton é aproximadamente:',
  array['1 unidade de massa atômica (u)', '1/1836 da massa de um elétron', 'Igual à massa de um elétron', 'Desprezível, semelhante à do elétron'], 0,
  'O próton tem massa aproximadamente igual a 1 u, muito maior que a massa do elétron.', 4),
('f7d3367f-0ede-4557-b30c-9ff239249e46', 'A carga elétrica de um próton, em relação à do elétron, é:',
  array['De mesma intensidade, porém de sinal oposto', 'Duas vezes maior', 'Metade da intensidade', 'Nula, sem qualquer carga'], 0,
  'Prótons e elétrons possuem cargas de mesma intensidade, mas de sinais opostos.', 5),

-- Nêutrons (923a07a3-fe07-459f-bb12-d7487ee924ee)
('923a07a3-fe07-459f-bb12-d7487ee924ee', 'Os nêutrons são partículas subatômicas caracterizadas por:',
  array['Estarem no núcleo do átomo e não possuírem carga elétrica', 'Estarem na eletrosfera e possuírem carga negativa', 'Possuírem carga elétrica positiva', 'Não existirem em átomos neutros'], 0,
  'Os nêutrons, junto com os prótons, formam o núcleo atômico, mas não possuem carga elétrica.', 1),
('923a07a3-fe07-459f-bb12-d7487ee924ee', 'O número de massa (A) de um átomo é calculado por:',
  array['A soma do número de prótons e nêutrons', 'Apenas o número de prótons', 'Apenas o número de nêutrons', 'A soma de prótons, nêutrons e elétrons'], 0,
  'O número de massa representa o total de partículas no núcleo (prótons + nêutrons).', 2),
('923a07a3-fe07-459f-bb12-d7487ee924ee', 'Um átomo de sódio (Na) possui número atômico 11 e número de massa 23. Quantos nêutrons esse átomo possui?',
  array['12', '11', '23', '34'], 0,
  'Número de nêutrons = número de massa - número atômico = 23 - 11 = 12.', 3),
('923a07a3-fe07-459f-bb12-d7487ee924ee', 'Os nêutrons contribuem para a estabilidade do núcleo atômico principalmente porque:',
  array['Ajudam a neutralizar a repulsão elétrica entre os prótons', 'Atraem eletricamente os prótons', 'Repelem os elétrons da eletrosfera', 'Não têm qualquer papel na estabilidade nuclear'], 0,
  'Os nêutrons contribuem para a força nuclear forte, ajudando a manter os prótons unidos apesar da repulsão elétrica.', 4),
('923a07a3-fe07-459f-bb12-d7487ee924ee', 'A massa de um nêutron, em comparação com a de um próton, é:',
  array['Aproximadamente igual', 'Muito menor', 'Muito maior', 'Nula'], 0,
  'Prótons e nêutrons têm massas muito próximas, ambas de aproximadamente 1 unidade de massa atômica.', 5),

-- Elétrons (8c2a2d8d-fbff-4b4a-8010-a79227baf853)
('8c2a2d8d-fbff-4b4a-8010-a79227baf853', 'Os elétrons são partículas subatômicas localizadas:',
  array['Na eletrosfera, ao redor do núcleo, com carga elétrica negativa', 'No núcleo, com carga elétrica positiva', 'No núcleo, sem carga elétrica', 'Fora do átomo, em qualquer posição fixa'], 0,
  'Os elétrons orbitam o núcleo na eletrosfera e possuem carga elétrica negativa.', 1),
('8c2a2d8d-fbff-4b4a-8010-a79227baf853', 'Os elétrons localizados na camada mais externa de um átomo são chamados de:',
  array['Elétrons de valência', 'Elétrons livres', 'Elétrons de núcleo', 'Elétrons neutros'], 0,
  'Os elétrons de valência, na camada mais externa, são os principais responsáveis pelas ligações químicas.', 2),
('8c2a2d8d-fbff-4b4a-8010-a79227baf853', 'Um cátion se forma quando um átomo:',
  array['Perde um ou mais elétrons', 'Ganha um ou mais elétrons', 'Perde um ou mais prótons', 'Ganha um ou mais nêutrons'], 0,
  'A perda de elétrons resulta em um íon de carga positiva, chamado cátion.', 3),
('8c2a2d8d-fbff-4b4a-8010-a79227baf853', 'A massa do elétron, em comparação com a do próton, é:',
  array['Muito menor, cerca de 1836 vezes menor', 'Aproximadamente igual', 'Muito maior', 'O dobro da massa do próton'], 0,
  'O elétron possui massa muito pequena em relação ao próton, praticamente desprezível na massa atômica total.', 4),
('8c2a2d8d-fbff-4b4a-8010-a79227baf853', 'Os elétrons de valência são responsáveis, principalmente, por:',
  array['Determinar o comportamento químico e as ligações do átomo', 'Definir a massa total do átomo', 'Determinar o número de nêutrons do átomo', 'Fixar o número atômico do elemento'], 0,
  'São os elétrons da camada de valência que participam das ligações químicas, determinando a reatividade do elemento.', 5),

-- Íons (cátion e ânion) (7ff92853-53ea-456f-81d2-d266d9a2cb74)
('7ff92853-53ea-456f-81d2-d266d9a2cb74', 'Um átomo que ganha um ou mais elétrons, tornando-se negativamente carregado, é chamado de:',
  array['Ânion', 'Cátion', 'Isótopo', 'Isóbaro'], 0,
  'O ânion se forma pelo ganho de elétrons, resultando em carga elétrica líquida negativa.', 1),
('7ff92853-53ea-456f-81d2-d266d9a2cb74', 'Um átomo que perde um ou mais elétrons, tornando-se positivamente carregado, é chamado de:',
  array['Cátion', 'Ânion', 'Isótopo', 'Isóbaro'], 0,
  'O cátion se forma pela perda de elétrons, resultando em carga elétrica líquida positiva.', 2),
('7ff92853-53ea-456f-81d2-d266d9a2cb74', 'O íon Na⁺ (sódio) se forma a partir do átomo neutro de sódio por meio de:',
  array['Perda de um elétron', 'Ganho de um elétron', 'Perda de um próton', 'Ganho de um nêutron'], 0,
  'O símbolo Na⁺ indica carga positiva, resultado da perda de um elétron pelo átomo neutro de sódio.', 3),
('7ff92853-53ea-456f-81d2-d266d9a2cb74', 'O íon Cl⁻ (cloreto) se forma a partir do átomo neutro de cloro por meio de:',
  array['Ganho de um elétron', 'Perda de um elétron', 'Ganho de um próton', 'Perda de um nêutron'], 0,
  'O símbolo Cl⁻ indica carga negativa, resultado do ganho de um elétron pelo átomo neutro de cloro.', 4),
('7ff92853-53ea-456f-81d2-d266d9a2cb74', 'Em uma ligação iônica, como a formada entre sódio e cloro (NaCl), ocorre:',
  array['Transferência de elétrons de um átomo para outro, formando cátion e ânion', 'Compartilhamento igualitário de elétrons entre os átomos', 'Ausência total de interação entre os átomos', 'Transferência de prótons entre os átomos'], 0,
  'Na ligação iônica, um átomo cede elétrons a outro, formando um cátion e um ânion que se atraem eletricamente.', 5),

-- Isótopos (4523e44f-8897-4776-a810-64248b111623)
('4523e44f-8897-4776-a810-64248b111623', 'Isótopos são átomos de um mesmo elemento químico que apresentam:',
  array['O mesmo número atômico (Z) e diferentes números de massa (A)', 'O mesmo número de massa e diferentes números atômicos', 'Diferentes números atômicos e de massa', 'O mesmo número de elétrons de valência apenas'], 0,
  'Isótopos possuem o mesmo número de prótons, mas diferem no número de nêutrons, alterando o número de massa.', 1),
('4523e44f-8897-4776-a810-64248b111623', 'O carbono-12 e o carbono-14 são exemplos de:',
  array['Isótopos do elemento carbono', 'Elementos químicos diferentes', 'Isóbaros', 'Isótonos'], 0,
  'Ambos possuem 6 prótons (mesmo elemento), mas diferem no número de nêutrons, sendo isótopos.', 2),
('4523e44f-8897-4776-a810-64248b111623', 'O carbono-14, um isótopo radioativo, é amplamente utilizado para:',
  array['Datação de materiais orgânicos (datação por radiocarbono)', 'Produção de energia nuclear em larga escala', 'Fabricação de vidros especiais', 'Purificação de água potável'], 0,
  'A datação por radiocarbono utiliza a desintegração do carbono-14 para estimar a idade de materiais orgânicos antigos.', 3),
('4523e44f-8897-4776-a810-64248b111623', 'Como os isótopos de um mesmo elemento têm o mesmo número de prótons e elétrons, suas propriedades químicas são:',
  array['Muito semelhantes, já que dependem principalmente da estrutura eletrônica', 'Completamente diferentes', 'Sempre opostas', 'Inexistentes, pois isótopos não reagem quimicamente'], 0,
  'Como o comportamento químico depende essencialmente dos elétrons, isótopos de um mesmo elemento têm propriedades químicas muito semelhantes.', 4),
('4523e44f-8897-4776-a810-64248b111623', 'Um átomo de urânio-238 (U-238) possui número atômico 92. Quantos nêutrons esse átomo possui?',
  array['146', '92', '238', '330'], 0,
  'Número de nêutrons = número de massa - número atômico = 238 - 92 = 146.', 5),

-- Dalton (1d7027f0-9cb2-46bc-a969-71fb69e1c2c5)
('1d7027f0-9cb2-46bc-a969-71fb69e1c2c5', 'O modelo atômico de Dalton, proposto no início do século XIX, concebia o átomo como:',
  array['Uma esfera maciça, indivisível e indestrutível', 'Uma esfera com carga positiva contendo elétrons dispersos', 'Um núcleo pequeno e denso cercado por uma eletrosfera', 'Um sistema de órbitas quantizadas para os elétrons'], 0,
  'Dalton propôs o átomo como uma esfera maciça e indivisível, semelhante a uma "bola de bilhar".', 1),
('1d7027f0-9cb2-46bc-a969-71fb69e1c2c5', 'Um dos postulados do modelo de Dalton afirmava que:',
  array['Átomos de um mesmo elemento químico são idênticos entre si', 'Átomos podem ser divididos em partículas menores', 'Átomos de elementos diferentes têm sempre a mesma massa', 'A matéria não é composta por átomos'], 0,
  'Dalton postulava que todos os átomos de um mesmo elemento eram idênticos em massa e propriedades.', 2),
('1d7027f0-9cb2-46bc-a969-71fb69e1c2c5', 'O modelo atômico de Dalton foi posteriormente superado, principalmente, pela descoberta de:',
  array['Partículas subatômicas, como o elétron', 'Novos elementos químicos', 'A tabela periódica', 'Reações químicas orgânicas'], 0,
  'A descoberta do elétron, por Thomson, mostrou que o átomo não era indivisível como Dalton propunha.', 3),
('1d7027f0-9cb2-46bc-a969-71fb69e1c2c5', 'Segundo o modelo de Dalton, as reações químicas consistiam em:',
  array['Rearranjos de átomos, sem criação ou destruição deles', 'Destruição completa dos átomos envolvidos', 'Criação espontânea de novos átomos', 'Fenômenos sem qualquer relação com os átomos'], 0,
  'Dalton explicava as reações químicas como simples reorganizações de átomos preexistentes.', 4),
('1d7027f0-9cb2-46bc-a969-71fb69e1c2c5', 'O modelo atômico de Dalton é frequentemente representado, de forma simplificada, pela imagem de:',
  array['Uma bola de bilhar', 'Um pudim com passas', 'Um sistema planetário', 'Uma nuvem de probabilidade'], 0,
  'A analogia com a "bola de bilhar" ilustra a ideia de esfera maciça, indivisível, proposta por Dalton.', 5),

-- Thomson (a6800379-be79-4f16-a0d5-9f741c728963)
('a6800379-be79-4f16-a0d5-9f741c728963', 'O modelo atômico de Thomson, proposto após a descoberta do elétron, é popularmente conhecido como:',
  array['Modelo do "pudim de passas"', 'Modelo planetário', 'Modelo da bola de bilhar', 'Modelo quântico'], 0,
  'Thomson imaginava o átomo como uma esfera de carga positiva com elétrons (as "passas") dispersos em seu interior.', 1),
('a6800379-be79-4f16-a0d5-9f741c728963', 'O modelo de Thomson representou um avanço em relação ao de Dalton por reconhecer que o átomo:',
  array['É divisível e possui partículas subatômicas com carga elétrica', 'É totalmente maciço e indivisível', 'Não possui qualquer carga elétrica', 'É formado exclusivamente por prótons'], 0,
  'Thomson demonstrou, com a descoberta do elétron, que o átomo possui estrutura interna e partículas carregadas.', 2),
('a6800379-be79-4f16-a0d5-9f741c728963', 'No modelo de Thomson, a carga positiva do átomo estaria distribuída:',
  array['De forma difusa por toda a esfera atômica', 'Concentrada em um núcleo pequeno e denso', 'Apenas na superfície externa do átomo', 'Inexistente, pois o átomo seria totalmente neutro em qualquer ponto'], 0,
  'Diferentemente do modelo posterior de Rutherford, Thomson imaginava a carga positiva espalhada por toda a esfera atômica.', 3),
('a6800379-be79-4f16-a0d5-9f741c728963', 'O modelo de Thomson foi posteriormente refutado pela experiência de:',
  array['Rutherford, com o espalhamento de partículas alfa', 'Dalton, com a lei das proporções definidas', 'Bohr, com os níveis de energia', 'Mendeleev, com a tabela periódica'], 0,
  'O experimento de Rutherford mostrou que a carga positiva estava concentrada em um núcleo, refutando o modelo de Thomson.', 4),
('a6800379-be79-4f16-a0d5-9f741c728963', 'A principal contribuição do modelo de Thomson para a evolução da teoria atômica foi:',
  array['Reconhecer a existência do elétron como partícula subatômica', 'Propor a existência do núcleo atômico', 'Estabelecer os níveis quantizados de energia', 'Determinar o número de nêutrons dos elementos'], 0,
  'A principal contribuição de Thomson foi incorporar o elétron, por ele descoberto, ao modelo atômico.', 5),

-- Rutherford (732824ff-da40-4a2a-9f16-44c5274ba4b8)
('732824ff-da40-4a2a-9f16-44c5274ba4b8', 'O modelo atômico de Rutherford, resultado de seu famoso experimento com folha de ouro, propôs a existência de:',
  array['Um núcleo pequeno, denso e positivo, cercado por uma eletrosfera com grande espaço vazio', 'Um átomo totalmente maciço, sem espaços vazios', 'Elétrons distribuídos uniformemente por toda a esfera atômica', 'Órbitas eletrônicas com níveis de energia fixos'], 0,
  'Rutherford concluiu que o átomo possui um núcleo pequeno e denso, com grande espaço vazio ao redor.', 1),
('732824ff-da40-4a2a-9f16-44c5274ba4b8', 'No experimento de Rutherford, a maioria das partículas alfa lançadas contra a folha de ouro:',
  array['Atravessou a folha sem sofrer desvios significativos', 'Foi completamente refletida', 'Ficou presa dentro da folha', 'Transformou-se em elétrons'], 0,
  'A grande maioria das partículas atravessou a folha sem desvio, evidenciando que o átomo é composto majoritariamente por espaço vazio.', 2),
('732824ff-da40-4a2a-9f16-44c5274ba4b8', 'O pequeno desvio observado em algumas partículas alfa no experimento de Rutherford indicava:',
  array['A existência de um núcleo pequeno, denso e positivamente carregado', 'A ausência total de carga no átomo', 'Que o átomo era totalmente maciço', 'Que os elétrons possuíam carga positiva'], 0,
  'O desvio de algumas partículas revelou a presença de uma região concentrada de carga positiva, o núcleo.', 3),
('732824ff-da40-4a2a-9f16-44c5274ba4b8', 'O modelo de Rutherford é frequentemente comparado a um sistema:',
  array['Planetário, com os elétrons orbitando o núcleo', 'De pudim de passas', 'De esfera maciça sem estrutura interna', 'De ondas estacionárias'], 0,
  'A comparação com o sistema solar é a analogia clássica para o modelo de Rutherford.', 4),
('732824ff-da40-4a2a-9f16-44c5274ba4b8', 'Uma limitação do modelo de Rutherford, posteriormente resolvida por Bohr, era:',
  array['Não explicar por que os elétrons não colapsavam sobre o núcleo', 'Não considerar a existência do núcleo atômico', 'Não reconhecer a existência de prótons', 'Não admitir espaços vazios no átomo'], 0,
  'Segundo a física clássica, elétrons em órbita deveriam perder energia e colapsar no núcleo — problema resolvido pelo modelo de Bohr.', 5),

-- Bohr (8dabaafe-27a9-467e-907c-7ed9aa0236b8)
('8dabaafe-27a9-467e-907c-7ed9aa0236b8', 'O modelo atômico de Bohr introduziu a ideia central de que os elétrons:',
  array['Ocupam órbitas específicas, com níveis de energia bem definidos (quantizados)', 'Se movem de forma totalmente aleatória ao redor do núcleo', 'Estão localizados dentro do próprio núcleo', 'Não possuem qualquer relação com a energia do átomo'], 0,
  'Bohr propôs que os elétrons só podem ocupar certas órbitas permitidas, cada uma associada a um nível específico de energia.', 1),
('8dabaafe-27a9-467e-907c-7ed9aa0236b8', 'Segundo o modelo de Bohr, um elétron emite energia na forma de luz quando:',
  array['Salta de um nível de energia mais alto para um mais baixo', 'Permanece parado em uma única órbita', 'Salta de um nível de energia mais baixo para um mais alto', 'É completamente removido do átomo'], 0,
  'A emissão de luz (fóton) ocorre quando o elétron retorna de um nível de energia mais alto para um mais baixo.', 2),
('8dabaafe-27a9-467e-907c-7ed9aa0236b8', 'Para que um elétron salte de uma órbita mais interna para uma mais externa, segundo Bohr, ele deve:',
  array['Absorver uma quantidade específica de energia', 'Perder energia espontaneamente', 'Permanecer inalterado, sem qualquer troca de energia', 'Colidir com outro elétron da mesma órbita'], 0,
  'A transição para um nível de maior energia exige a absorção de uma quantidade exata (quantizada) de energia.', 3),
('8dabaafe-27a9-467e-907c-7ed9aa0236b8', 'O modelo de Bohr foi desenvolvido especialmente para explicar com sucesso o espectro de emissão do átomo de:',
  array['Hidrogênio', 'Ouro', 'Carbono', 'Urânio'], 0,
  'O modelo de Bohr teve grande êxito ao explicar o espectro de linhas do átomo de hidrogênio, o mais simples de todos.', 4),
('8dabaafe-27a9-467e-907c-7ed9aa0236b8', 'O modelo de Bohr representa uma transição importante na história da física atômica por incorporar, pela primeira vez, conceitos da:',
  array['Física quântica, com a ideia de quantização de energia', 'Física clássica newtoniana, exclusivamente', 'Teoria da relatividade geral', 'Termodinâmica clássica'], 0,
  'Bohr foi pioneiro ao aplicar a ideia de quantização de energia à estrutura atômica.', 5);
