-- New "dificil" questions for historia: 24 questions, each already
-- with its en/es translation (48 translation rows).
--
-- ids are deterministic (uuid5 of the pt-BR prompt), so running this twice
-- inserts nothing new: questions use on conflict do nothing, translations
-- on conflict do update. The translation join refuses any row whose option
-- count differs from the original (correct_index is positional).

insert into questions (id, catalog_node_id, prompt, options, correct_index, explanation, order_index, difficulty)
select v.id::uuid, v.node::uuid, v.prompt, v.options, v.correct_index, v.explanation, v.order_index, 'dificil'
from (values
  ('7947ef16-626a-5843-b991-57f9c287e6f9', '143ae168-abcf-4512-a0c7-3c67e34e9fcb',
   'O ostracismo, instituído em Atenas no contexto das reformas de Clístenes, consistia em:',
   array['condenar à morte os cidadãos acusados de traição', 'exilar temporariamente, por votação dos cidadãos, quem fosse considerado ameaça à democracia', 'confiscar as terras da aristocracia', 'impedir que estrangeiros participassem da assembleia'], 1,
   'No ostracismo, os cidadãos escreviam em cacos de cerâmica (óstracos) o nome de quem consideravam perigoso; o mais votado era exilado por dez anos, sem perder os bens. Era uma defesa contra a volta da tirania.', 100),
  ('56df408d-d2ca-5939-ad59-9ac921a91999', '43bff7ca-8f49-46a3-b757-e20105c00ad2',
   'A peregrinação de Mansa Musa, governante do Império do Mali, a Meca (1324) ficou célebre porque:',
   array['marcou a conversão do Mali ao cristianismo', 'levou à fundação da cidade de Grande Zimbábue', 'a quantidade de ouro que ele distribuiu no caminho chegou a derrubar o valor do metal no Cairo', 'deu início ao tráfico atlântico de escravizados'], 2,
   'Mansa Musa levou tanto ouro que, ao distribuí-lo no Cairo, provocou queda no valor do metal por anos. O episódio mostrou à Europa e ao mundo islâmico a riqueza do Mali, que já era muçulmano.', 101),
  ('add91609-47ba-5640-b64a-4d36c32d4968', '3a6764c6-67a5-4941-b3c0-aa0b5e17a190',
   'A independência do Haiti (1804) se distingue das demais independências americanas porque:',
   array['foi conduzida pela elite criolla, que manteve a escravidão', 'foi concedida pacificamente pela Espanha', 'deu origem a uma monarquia governada pela dinastia de Bragança', 'resultou de uma revolta de escravizados, que aboliu a escravidão e criou um país governado por ex-escravizados'], 3,
   'A Revolução Haitiana, iniciada em 1791 na colônia francesa de São Domingos, foi a única revolta de escravizados vitoriosa a fundar um Estado. O Haiti aboliu a escravidão e virou símbolo temido pelas elites escravistas das Américas.', 102),
  ('409dcfe0-8ee6-519e-8c48-a6b7e7fcd2c2', 'ad10464d-0d11-4255-9fef-d341a0f856d6',
   'O Tratado de Madri (1750), entre Portugal e Espanha, baseou-se no princípio do uti possidetis, segundo o qual:',
   array['a terra pertenceria a quem de fato a ocupasse', 'continuaria valendo a linha do Tratado de Tordesilhas', 'o papa arbitraria as disputas de fronteira', 'as terras indígenas seriam declaradas neutras'], 0,
   'Pelo uti possidetis ("como possuís"), cada Coroa ficava com as terras que efetivamente ocupava. Isso legitimou a expansão luso-brasileira para além de Tordesilhas, feita por bandeirantes, missões e fortes.', 103),
  ('1a9b7a27-fe56-5489-8a02-5fb081732280', 'f479bffd-9b8d-4b42-aa90-b17fb95862f4',
   'A Lei de Terras de 1850 é associada à manutenção da concentração fundiária no Brasil porque:',
   array['distribuiu terras gratuitamente aos imigrantes europeus', 'determinou que as terras devolutas só poderiam ser adquiridas por compra, dificultando o acesso dos pobres e dos futuros libertos', 'aboliu o latifúndio e criou pequenas propriedades', 'proibiu a venda de terras a estrangeiros'], 1,
   'Aprovada no mesmo ano da Lei Eusébio de Queirós, a Lei de Terras transformou a terra em mercadoria: só quem tinha dinheiro podia comprá-la. Sem acesso à terra, trabalhadores livres e ex-escravizados continuaram dependentes dos grandes proprietários.', 104),
  ('a52dddea-3d92-566f-8be1-cd47cd0ee303', '5bc5ce90-bf36-45a1-97fc-156a2423ae89',
   'Entre as medidas do Ato Institucional nº 5 (dezembro de 1968), está:',
   array['a criação do bipartidarismo (ARENA e MDB)', 'o restabelecimento das eleições diretas para presidente', 'a suspensão do habeas corpus nos casos de crimes políticos', 'a anistia aos exilados políticos'], 2,
   'O AI-5 permitiu fechar o Congresso, cassar mandatos e suspendeu o habeas corpus para crimes políticos, abrindo caminho aos anos mais repressivos. O bipartidarismo veio com o AI-2 (1965) e a anistia em 1979.', 105),
  ('35dcfadd-c0b2-5285-b1b3-ca55ed9782cd', '3a099505-6721-49f2-8633-8aa2b613a762',
   'A Constituição de 1937, outorgada no golpe do Estado Novo, recebeu o apelido de "Polaca" porque:',
   array['foi redigida por imigrantes poloneses', 'foi aprovada em plebiscito popular', 'restabeleceu o federalismo da República Velha', 'foi inspirada na Constituição autoritária da Polônia de 1935'], 3,
   'Redigida por Francisco Campos, a Carta de 1937 se inspirou na constituição autoritária polonesa: concentrou poderes no Executivo, dissolveu o Legislativo e suprimiu a autonomia dos estados. O plebiscito que ela previa nunca foi realizado.', 106),
  ('1d518a42-9c1a-5f48-907e-c0d2b3bdeda3', '8cdb0962-4694-476e-9c83-9cb807353e6c',
   'O DIP (Departamento de Imprensa e Propaganda), criado em 1939, tinha entre suas funções:',
   array['censurar a imprensa e as artes e produzir a propaganda do regime, como o programa "A Hora do Brasil"', 'organizar e financiar os sindicatos', 'administrar a Companhia Siderúrgica Nacional', 'fiscalizar as eleições estaduais'], 0,
   'O DIP centralizou a censura e a propaganda do Estado Novo: controlava jornais, rádio, cinema e artes, e cultivava a imagem de Vargas como "pai dos pobres", inclusive pelo programa radiofônico oficial.', 107),
  ('b9704caa-d2fe-5b95-843b-445f06378091', '0384be9b-0291-4535-b984-c77bb61c1611',
   'Um fator que contribuiu para o fim do Estado Novo, em 1945, foi:',
   array['a vitória do Integralismo nas eleições de 1945', 'a contradição de o Brasil lutar contra regimes autoritários na Segunda Guerra enquanto vivia uma ditadura', 'a Revolução Constitucionalista de São Paulo', 'a renúncia de Vargas para assumir um cargo na ONU'], 1,
   'Ao combater o nazifascismo ao lado dos Aliados, o regime ficou exposto à própria contradição. Cresceram as pressões por redemocratização (como o Manifesto dos Mineiros), e Vargas acabou deposto pelos militares em outubro de 1945.', 108),
  ('19623bdc-8211-5c84-84d3-29723eed44d6', 'b134a54a-0add-4719-8e97-0f28c82bc7a5',
   'A Ação Integralista Brasileira, liderada por Plínio Salgado, caracterizava-se por:',
   array['defender a revolução proletária e a reforma agrária radical', 'pregar o liberalismo econômico e o federalismo', 'um ideário nacionalista, autoritário e anticomunista, inspirado no fascismo, com o lema "Deus, Pátria e Família"', 'apoiar a restauração da monarquia'], 2,
   'Os integralistas, os "camisas-verdes", imitavam a estética e a organização fascistas. Apoiaram inicialmente o golpe de 1937, mas foram postos na ilegalidade e tentaram um levante fracassado em 1938.', 109),
  ('8ffe29e3-415f-5853-a914-4ef89a025d35', '87dcdeae-bf22-493e-a53a-6f09c878f224',
   'A Intentona Comunista de 1935 foi organizada por militantes ligados à:',
   array['Ação Integralista Brasileira (AIB)', 'União Democrática Nacional (UDN)', 'Partido Social Democrático (PSD)', 'Aliança Nacional Libertadora (ANL), com Luís Carlos Prestes'], 3,
   'A ANL, frente antifascista e anti-imperialista com participação comunista, foi fechada por Vargas; parte de seus militantes, com Prestes, tentou levantes militares em Natal, Recife e no Rio. A derrota serviu de pretexto para endurecer o regime.', 110),
  ('77788a8f-9b4a-5e3f-bdad-9f2342c2dfa9', '2065151d-f988-43b0-b8d9-f784cbec1278',
   'Um traço do trabalhismo varguista era o sindicalismo atrelado ao Estado, porque:',
   array['os sindicatos dependiam do reconhecimento do Ministério do Trabalho e eram sustentados pelo imposto sindical', 'os sindicatos eram proibidos e substituídos por conselhos de fábrica', 'as greves eram incentivadas pelo governo como forma de pressão', 'os sindicatos eram subordinados à Igreja Católica'], 0,
   'O modelo corporativista exigia registro no Ministério do Trabalho e financiava os sindicatos com o imposto sindical obrigatório. Em troca de direitos (depois reunidos na CLT, de 1943), o Estado controlava o movimento operário.', 111),
  ('d3f569ea-d733-5d25-bdc0-cc0a8c483d0e', 'b0581df7-1582-41b8-95f9-c2addfb47ddf',
   'A Constituição de 1934 incorporou:',
   array['o voto censitário e o voto aberto', 'o sistema parlamentarista de governo', 'o voto secreto e o voto feminino, além de prever a criação da Justiça do Trabalho', 'o Poder Moderador'], 2,
   'A Carta de 1934 consagrou conquistas do Código Eleitoral de 1932 (voto secreto e feminino) e previu a Justiça do Trabalho e direitos trabalhistas. Durou pouco: foi substituída pela de 1937.', 112),
  ('4f4daa34-f914-5418-96a8-bb8e9f329555', 'b75f4f86-6f0d-4ebd-895f-5fb3118d35ca',
   'A Revolução Constitucionalista de 1932 foi um movimento:',
   array['gaúcho que exigia a volta de Washington Luís à Presidência', 'comunista liderado pela Aliança Nacional Libertadora', 'integralista contra a Constituição de 1934', 'paulista que exigia uma Assembleia Constituinte e o fim do Governo Provisório de Vargas'], 3,
   'São Paulo, afastado do poder desde 1930 e sob interventores, pegou em armas por uma nova Constituição. Foi derrotado militarmente, mas a Constituinte foi convocada e a Constituição saiu em 1934.', 113),
  ('819d7d9d-e9ec-5940-bd49-a205a4e612c5', 'd8a3ff73-b95d-4c49-8438-a6f562936779',
   'Um dos estopins da Revolução de 1930 foi:',
   array['a Revolta da Vacina', 'o assassinato de João Pessoa, candidato a vice-presidente na chapa de Getúlio Vargas', 'a morte de Washington Luís', 'a crise do Encilhamento'], 1,
   'Após a derrota da Aliança Liberal nas eleições de 1930, o assassinato de João Pessoa (por motivos também locais) inflamou a oposição e precipitou o movimento armado que levou Vargas ao poder.', 114),
  ('a093ad44-d1a4-5114-a098-0bd29673d1c4', '8e6bf89f-70bf-4ecd-b680-e2ee171d41fc',
   'O "Dia do Fico" (9 de janeiro de 1822) refere-se:',
   array['à coroação de D. Pedro I como imperador', 'ao retorno de D. João VI a Portugal', 'à decisão de D. Pedro de permanecer no Brasil, contrariando as Cortes de Lisboa', 'ao reconhecimento da independência por Portugal'], 2,
   'As Cortes de Lisboa exigiam a volta do príncipe regente para recolonizar o Brasil. Ao declarar que ficaria, D. Pedro rompeu com elas, num passo decisivo rumo à independência de setembro de 1822.', 115),
  ('72281f63-4c5c-5ff5-b8e6-3bbd3c8fa2b9', '7740f68e-21bc-47e1-8052-848e287f27dd',
   'A Constituição de 1988 ficou conhecida como "Constituição Cidadã" principalmente por:',
   array['ampliar direitos sociais e individuais após o fim da ditadura', 'instituir o parlamentarismo', 'restabelecer a eleição indireta para presidente', 'reduzir o papel do Estado na saúde e na educação'], 0,
   'Promulgada sob a presidência de Ulysses Guimarães na Constituinte, a Carta de 1988 ampliou direitos (como o SUS universal), criminalizou o racismo e fortaleceu as garantias individuais depois de 21 anos de regime militar.', 116),
  ('d8728fc0-a3d2-58fa-86d7-78c3ef0fd2bd', '4387fdad-2724-4b69-be79-970eaf8f168a',
   'O Diretório dos Índios, implantado no período pombalino (1757), determinou:',
   array['a entrega das aldeias ao controle dos jesuítas', 'a abolição imediata de todo trabalho indígena', 'a demarcação de terras indígenas pela Coroa', 'a obrigatoriedade da língua portuguesa e a proibição da língua geral nas aldeias'], 3,
   'A política de Pombal buscava "civilizar" e integrar os indígenas como vassalos: impôs o português, proibiu a língua geral (de base tupi), incentivou casamentos mistos e pôs as aldeias sob diretores leigos, após a expulsão dos jesuítas.', 117),
  ('99276aa2-334d-5d65-b032-3c972172ef77', '5508a9c1-91a7-463b-bf08-a36f296d2251',
   'O Plano de Metas de Juscelino Kubitschek (1956–1961) priorizou:',
   array['a reforma agrária e a nacionalização de empresas estrangeiras', 'energia, transportes e indústria de base, com forte entrada de capital estrangeiro', 'a criação da Petrobras e o monopólio estatal do petróleo', 'o controle da inflação por meio de cortes de gastos'], 1,
   'Com o lema "50 anos em 5", JK investiu em energia, transportes e indústria (como a automobilística), atraindo capital estrangeiro, e construiu Brasília. O custo foi inflação e endividamento. A Petrobras é de 1953, no governo Vargas.', 118),
  ('e2b82773-4616-5ce0-babb-519027f01ac5', '602710f8-5c91-44c0-adf0-88b0cf87f333',
   'A "política dos governadores", articulada por Campos Sales, consistia em:',
   array['um apoio mútuo: o governo federal favorecia as oligarquias estaduais, que em troca elegiam bancadas fiéis ao presidente', 'a eleição dos governadores pelo Congresso Nacional', 'uma lei que obrigava a alternância entre São Paulo e Minas na Presidência', 'a intervenção federal permanente nos estados'], 0,
   'O presidente apoiava as oligarquias dominantes em cada estado, e elas garantiam deputados governistas, com ajuda da Comissão Verificadora de Poderes. A "política do café com leite" era um arranjo político, não uma lei.', 119),
  ('9f3e9ad2-1d2d-515d-ab6e-fa4e5f3bc550', '9d1627ca-eade-4dcf-83dc-a1acfcd096c8',
   'O Congresso de Viena (1814–1815) orientou-se pelo princípio da legitimidade, que defendia:',
   array['a soberania popular e o sufrágio universal', 'a independência das colônias americanas', 'a restauração das dinastias depostas durante as guerras napoleônicas', 'a unificação imediata da Alemanha'], 2,
   'As potências vencedoras de Napoleão quiseram restaurar o Antigo Regime: pela legitimidade, voltavam ao trono as dinastias "legítimas" (como os Bourbon na França). O equilíbrio foi garantido pela Santa Aliança.', 120),
  ('4b1b4018-615b-5649-995c-96b6191b982d', '9d1627ca-eade-4dcf-83dc-a1acfcd096c8',
   'Como resposta econômica ao Plano Marshall, a União Soviética criou, em 1949:',
   array['a OTAN', 'a ONU', 'o Pacto de Varsóvia', 'o Comecon'], 3,
   'O Comecon (Conselho para Assistência Econômica Mútua) integrou as economias do bloco socialista em resposta à ajuda americana à Europa Ocidental. O Pacto de Varsóvia (1955) foi a resposta militar à OTAN.', 121),
  ('b1db9185-f0f3-5abd-b483-4769868c4880', 'c14f34bc-fdf8-4797-88a6-14fafbad4194',
   'A Querela das Investiduras, disputa entre o papado e o Sacro Império Romano-Germânico, foi encerrada pela:',
   array['Paz de Vestfália', 'Concordata de Worms (1122)', 'bula Unam Sanctam', 'Tratado de Verdun'], 1,
   'A disputa era sobre quem nomeava bispos: o papa ou o imperador. A Concordata de Worms dividiu a investidura: a espiritual ficou com a Igreja, e o imperador manteve a investidura temporal (terras e feudos).', 122),
  ('1112fdf5-f4c1-5875-a710-b6e69ae9487f', 'e93f87be-ca79-4813-9a67-616320aa9a8a',
   'A Paz de Vestfália (1648), que encerrou a Guerra dos Trinta Anos, é considerada marco:',
   array['do sistema de Estados soberanos na Europa', 'da unificação italiana', 'do início da Reforma Protestante', 'da criação do Sacro Império'], 0,
   'Os tratados reconheceram a soberania dos Estados sobre seus territórios e sua religião, a independência das Províncias Unidas e da Suíça, e enfraqueceram o Sacro Império. A ideia de Estados soberanos e iguais vem daí.', 123)
) as v(id, node, prompt, options, correct_index, explanation, order_index)
join catalog_nodes c on c.id = v.node::uuid
on conflict (id) do nothing;

insert into question_translations (question_id, locale, prompt, options, explanation)
select v.id::uuid, v.locale, v.prompt, v.options, v.explanation
from (values
  ('7947ef16-626a-5843-b991-57f9c287e6f9', 'en',
   'Ostracism, introduced in Athens as part of Cleisthenes'' reforms, consisted of:',
   array['sentencing citizens accused of treason to death', 'temporarily exiling, by a vote of the citizens, anyone considered a threat to democracy', 'confiscating the aristocracy''s land', 'barring foreigners from the assembly'],
   'In ostracism, citizens wrote on pottery shards (ostraka) the name of someone they considered dangerous; whoever received the most votes was exiled for ten years without losing their property. It was a safeguard against the return of tyranny.'),
  ('7947ef16-626a-5843-b991-57f9c287e6f9', 'es',
   'El ostracismo, instituido en Atenas en el marco de las reformas de Clístenes, consistía en:',
   array['condenar a muerte a los ciudadanos acusados de traición', 'desterrar temporalmente, por votación de los ciudadanos, a quien se considerara una amenaza para la democracia', 'confiscar las tierras de la aristocracia', 'impedir que los extranjeros participaran en la asamblea'],
   'En el ostracismo, los ciudadanos escribían en fragmentos de cerámica (óstraka) el nombre de quien consideraban peligroso; el más votado era desterrado por diez años, sin perder sus bienes. Era una defensa contra el regreso de la tiranía.'),
  ('56df408d-d2ca-5939-ad59-9ac921a91999', 'en',
   'The pilgrimage to Mecca (1324) by Mansa Musa, ruler of the Mali Empire, became famous because:',
   array['it marked Mali''s conversion to Christianity', 'it led to the founding of Great Zimbabwe', 'the amount of gold he gave away along the way lowered the value of the metal in Cairo', 'it started the Atlantic slave trade'],
   'Mansa Musa carried so much gold that giving it away in Cairo depressed the value of the metal for years. The episode showed Europe and the Islamic world the wealth of Mali, which was already Muslim.'),
  ('56df408d-d2ca-5939-ad59-9ac921a91999', 'es',
   'La peregrinación a La Meca (1324) de Mansa Musa, gobernante del Imperio de Malí, se hizo célebre porque:',
   array['marcó la conversión de Malí al cristianismo', 'llevó a la fundación de la ciudad del Gran Zimbabue', 'la cantidad de oro que repartió en el camino llegó a hacer caer el valor del metal en El Cairo', 'dio inicio a la trata atlántica de esclavos'],
   'Mansa Musa llevó tanto oro que, al repartirlo en El Cairo, provocó una caída del valor del metal durante años. El episodio mostró a Europa y al mundo islámico la riqueza de Malí, que ya era musulmán.'),
  ('add91609-47ba-5640-b64a-4d36c32d4968', 'en',
   'Haiti''s independence (1804) stands apart from the other independence movements in the Americas because:',
   array['it was led by the Creole elite, who kept slavery', 'it was granted peacefully by Spain', 'it created a monarchy ruled by the House of Braganza', 'it resulted from a revolt of enslaved people, which abolished slavery and created a country governed by formerly enslaved people'],
   'The Haitian Revolution, which began in 1791 in the French colony of Saint-Domingue, was the only successful slave revolt to found a state. Haiti abolished slavery and became a symbol feared by slaveholding elites across the Americas.'),
  ('add91609-47ba-5640-b64a-4d36c32d4968', 'es',
   'La independencia de Haití (1804) se distingue de las demás independencias americanas porque:',
   array['fue conducida por la élite criolla, que mantuvo la esclavitud', 'fue concedida pacíficamente por España', 'dio origen a una monarquía gobernada por la dinastía de Braganza', 'resultó de una rebelión de esclavizados, que abolió la esclavitud y creó un país gobernado por antiguos esclavizados'],
   'La Revolución haitiana, iniciada en 1791 en la colonia francesa de Saint-Domingue, fue la única rebelión de esclavizados victoriosa que fundó un Estado. Haití abolió la esclavitud y se convirtió en un símbolo temido por las élites esclavistas de América.'),
  ('409dcfe0-8ee6-519e-8c48-a6b7e7fcd2c2', 'en',
   'The Treaty of Madrid (1750) between Portugal and Spain was based on the principle of uti possidetis, according to which:',
   array['land would belong to whoever actually occupied it', 'the Treaty of Tordesillas line would remain in force', 'the Pope would settle border disputes', 'Indigenous lands would be declared neutral'],
   'Under uti possidetis ("as you possess"), each Crown kept the lands it actually occupied. This legitimized the Luso-Brazilian expansion beyond Tordesillas carried out by bandeirantes, missions and forts.'),
  ('409dcfe0-8ee6-519e-8c48-a6b7e7fcd2c2', 'es',
   'El Tratado de Madrid (1750), entre Portugal y España, se basó en el principio del uti possidetis, según el cual:',
   array['la tierra pertenecería a quien efectivamente la ocupara', 'seguiría vigente la línea del Tratado de Tordesillas', 'el papa arbitraría las disputas fronterizas', 'las tierras indígenas serían declaradas neutrales'],
   'Por el uti possidetis ("como poseéis"), cada Corona se quedaba con las tierras que efectivamente ocupaba. Eso legitimó la expansión lusobrasileña más allá de Tordesillas, hecha por bandeirantes, misiones y fuertes.'),
  ('1a9b7a27-fe56-5489-8a02-5fb081732280', 'en',
   'The Land Law of 1850 is associated with maintaining land concentration in Brazil because:',
   array['it gave land free of charge to European immigrants', 'it determined that public (unclaimed) land could only be acquired by purchase, making access difficult for the poor and for those who would later be freed', 'it abolished large estates and created small farms', 'it banned the sale of land to foreigners'],
   'Passed in the same year as the Eusébio de Queirós Law, the Land Law turned land into a commodity: only those with money could buy it. Without access to land, free workers and formerly enslaved people remained dependent on large landowners.'),
  ('1a9b7a27-fe56-5489-8a02-5fb081732280', 'es',
   'La Ley de Tierras de 1850 se asocia al mantenimiento de la concentración de la tierra en Brasil porque:',
   array['repartió tierras gratuitamente a los inmigrantes europeos', 'determinó que las tierras baldías solo podían adquirirse mediante compra, lo que dificultaba el acceso de los pobres y de los futuros libertos', 'abolió el latifundio y creó pequeñas propiedades', 'prohibió la venta de tierras a extranjeros'],
   'Aprobada el mismo año que la Ley Eusébio de Queirós, la Ley de Tierras convirtió la tierra en mercancía: solo quien tenía dinero podía comprarla. Sin acceso a la tierra, los trabajadores libres y los antiguos esclavizados siguieron dependiendo de los grandes propietarios.'),
  ('a52dddea-3d92-566f-8be1-cd47cd0ee303', 'en',
   'Among the measures of Institutional Act No. 5 (December 1968) was:',
   array['the creation of the two-party system (ARENA and MDB)', 'the return of direct presidential elections', 'the suspension of habeas corpus in cases of political crimes', 'an amnesty for political exiles'],
   'AI-5 allowed Congress to be closed and mandates to be revoked, and it suspended habeas corpus for political crimes, opening the way to the most repressive years. The two-party system came with AI-2 (1965) and the amnesty in 1979.'),
  ('a52dddea-3d92-566f-8be1-cd47cd0ee303', 'es',
   'Entre las medidas del Acta Institucional n.º 5 (diciembre de 1968) está:',
   array['la creación del bipartidismo (ARENA y MDB)', 'el restablecimiento de las elecciones directas para presidente', 'la suspensión del habeas corpus en los casos de delitos políticos', 'la amnistía a los exiliados políticos'],
   'El AI-5 permitió cerrar el Congreso y anular mandatos, y suspendió el habeas corpus para los delitos políticos, abriendo paso a los años más represivos. El bipartidismo llegó con el AI-2 (1965) y la amnistía en 1979.'),
  ('35dcfadd-c0b2-5285-b1b3-ca55ed9782cd', 'en',
   'The 1937 Constitution, imposed with the Estado Novo coup, was nicknamed "Polaca" ("the Polish one") because:',
   array['it was drafted by Polish immigrants', 'it was approved in a popular referendum', 'it restored the federalism of the Old Republic', 'it was inspired by Poland''s authoritarian Constitution of 1935'],
   'Drafted by Francisco Campos, the 1937 Charter drew on the authoritarian Polish constitution: it concentrated power in the Executive, dissolved the Legislature and removed the states'' autonomy. The referendum it provided for was never held.'),
  ('35dcfadd-c0b2-5285-b1b3-ca55ed9782cd', 'es',
   'La Constitución de 1937, otorgada con el golpe del Estado Novo, recibió el apodo de "Polaca" porque:',
   array['fue redactada por inmigrantes polacos', 'fue aprobada en un plebiscito popular', 'restableció el federalismo de la República Vieja', 'se inspiró en la Constitución autoritaria de Polonia de 1935'],
   'Redactada por Francisco Campos, la Carta de 1937 se inspiró en la constitución autoritaria polaca: concentró poderes en el Ejecutivo, disolvió el Legislativo y suprimió la autonomía de los estados. El plebiscito que preveía nunca se realizó.'),
  ('1d518a42-9c1a-5f48-907e-c0d2b3bdeda3', 'en',
   'Among the functions of the DIP (Department of Press and Propaganda), created in 1939, was:',
   array['censoring the press and the arts and producing the regime''s propaganda, such as the radio program "A Hora do Brasil"', 'organizing and funding trade unions', 'running the National Steel Company (CSN)', 'overseeing state elections'],
   'The DIP centralized the Estado Novo''s censorship and propaganda: it controlled newspapers, radio, cinema and the arts, and cultivated Vargas''s image as "father of the poor", including through the official radio program.'),
  ('1d518a42-9c1a-5f48-907e-c0d2b3bdeda3', 'es',
   'El DIP (Departamento de Prensa y Propaganda), creado en 1939, tenía entre sus funciones:',
   array['censurar la prensa y las artes y producir la propaganda del régimen, como el programa "A Hora do Brasil"', 'organizar y financiar los sindicatos', 'administrar la Compañía Siderúrgica Nacional', 'fiscalizar las elecciones estatales'],
   'El DIP centralizó la censura y la propaganda del Estado Novo: controlaba periódicos, radio, cine y artes, y cultivaba la imagen de Vargas como "padre de los pobres", incluso mediante el programa radiofónico oficial.'),
  ('b9704caa-d2fe-5b95-843b-445f06378091', 'en',
   'One factor that contributed to the end of the Estado Novo in 1945 was:',
   array['the victory of Integralism in the 1945 elections', 'the contradiction of Brazil fighting authoritarian regimes in World War II while living under a dictatorship', 'the Constitutionalist Revolution in São Paulo', 'Vargas''s resignation to take up a post at the UN'],
   'By fighting Nazi-fascism alongside the Allies, the regime was exposed to its own contradiction. Pressure for redemocratization grew (as in the Manifesto dos Mineiros), and Vargas was eventually deposed by the military in October 1945.'),
  ('b9704caa-d2fe-5b95-843b-445f06378091', 'es',
   'Un factor que contribuyó al fin del Estado Novo, en 1945, fue:',
   array['la victoria del Integralismo en las elecciones de 1945', 'la contradicción de que Brasil combatiera regímenes autoritarios en la Segunda Guerra Mundial mientras vivía una dictadura', 'la Revolución Constitucionalista de São Paulo', 'la renuncia de Vargas para asumir un cargo en la ONU'],
   'Al combatir el nazifascismo junto a los Aliados, el régimen quedó expuesto a su propia contradicción. Crecieron las presiones por la redemocratización (como el Manifiesto de los Mineros) y Vargas terminó depuesto por los militares en octubre de 1945.'),
  ('19623bdc-8211-5c84-84d3-29723eed44d6', 'en',
   'The Brazilian Integralist Action, led by Plínio Salgado, was characterized by:',
   array['advocating proletarian revolution and radical land reform', 'preaching economic liberalism and federalism', 'a nationalist, authoritarian and anti-communist ideology, inspired by fascism, with the motto "God, Fatherland and Family"', 'supporting the restoration of the monarchy'],
   'The Integralists, the "green shirts", copied fascist aesthetics and organization. They first supported the 1937 coup, but were outlawed and attempted a failed uprising in 1938.'),
  ('19623bdc-8211-5c84-84d3-29723eed44d6', 'es',
   'La Acción Integralista Brasileña, liderada por Plínio Salgado, se caracterizaba por:',
   array['defender la revolución proletaria y la reforma agraria radical', 'predicar el liberalismo económico y el federalismo', 'un ideario nacionalista, autoritario y anticomunista, inspirado en el fascismo, con el lema "Dios, Patria y Familia"', 'apoyar la restauración de la monarquía'],
   'Los integralistas, los "camisas verdes", imitaban la estética y la organización fascistas. Al principio apoyaron el golpe de 1937, pero fueron ilegalizados e intentaron un levantamiento fracasado en 1938.'),
  ('8ffe29e3-415f-5853-a914-4ef89a025d35', 'en',
   'The 1935 Communist Uprising (Intentona Comunista) was organized by militants linked to:',
   array['the Brazilian Integralist Action (AIB)', 'the National Democratic Union (UDN)', 'the Social Democratic Party (PSD)', 'the National Liberation Alliance (ANL), with Luís Carlos Prestes'],
   'The ANL, an anti-fascist and anti-imperialist front with communist participation, was shut down by Vargas; some of its militants, led by Prestes, attempted military uprisings in Natal, Recife and Rio. Their defeat served as a pretext to harden the regime.'),
  ('8ffe29e3-415f-5853-a914-4ef89a025d35', 'es',
   'La Intentona Comunista de 1935 fue organizada por militantes vinculados a:',
   array['la Acción Integralista Brasileña (AIB)', 'la Unión Democrática Nacional (UDN)', 'el Partido Social Democrático (PSD)', 'la Alianza Nacional Libertadora (ANL), con Luís Carlos Prestes'],
   'La ANL, frente antifascista y antiimperialista con participación comunista, fue cerrada por Vargas; parte de sus militantes, con Prestes, intentó levantamientos militares en Natal, Recife y Río. La derrota sirvió de pretexto para endurecer el régimen.'),
  ('77788a8f-9b4a-5e3f-bdad-9f2342c2dfa9', 'en',
   'One feature of Vargas-era trabalhismo (labor politics) was state-controlled unionism, because:',
   array['unions depended on recognition by the Ministry of Labor and were funded by the mandatory union tax', 'unions were banned and replaced by factory councils', 'the government encouraged strikes as a means of pressure', 'unions were subordinated to the Catholic Church'],
   'The corporatist model required registration with the Ministry of Labor and funded unions through the mandatory union tax. In exchange for rights (later gathered in the CLT labor code of 1943), the state controlled the labor movement.'),
  ('77788a8f-9b4a-5e3f-bdad-9f2342c2dfa9', 'es',
   'Un rasgo del laborismo (trabalhismo) varguista era el sindicalismo sometido al Estado, porque:',
   array['los sindicatos dependían del reconocimiento del Ministerio de Trabajo y se sostenían con el impuesto sindical', 'los sindicatos estaban prohibidos y fueron sustituidos por consejos de fábrica', 'el gobierno incentivaba las huelgas como forma de presión', 'los sindicatos estaban subordinados a la Iglesia católica'],
   'El modelo corporativista exigía el registro en el Ministerio de Trabajo y financiaba a los sindicatos con el impuesto sindical obligatorio. A cambio de derechos (luego reunidos en la CLT, de 1943), el Estado controlaba el movimiento obrero.'),
  ('d3f569ea-d733-5d25-bdc0-cc0a8c483d0e', 'en',
   'The 1934 Constitution incorporated:',
   array['income-based voting and open ballots', 'a parliamentary system of government', 'the secret ballot and women''s suffrage, and it provided for a Labor Court system', 'the Moderating Power'],
   'The 1934 Charter enshrined gains from the 1932 Electoral Code (secret ballot and women''s vote) and provided for Labor Courts and labor rights. It did not last long: it was replaced by the 1937 Constitution.'),
  ('d3f569ea-d733-5d25-bdc0-cc0a8c483d0e', 'es',
   'La Constitución de 1934 incorporó:',
   array['el voto censitario y el voto abierto', 'el sistema parlamentario de gobierno', 'el voto secreto y el voto femenino, además de prever la creación de la Justicia del Trabajo', 'el Poder Moderador'],
   'La Carta de 1934 consagró conquistas del Código Electoral de 1932 (voto secreto y femenino) y previó la Justicia del Trabajo y derechos laborales. Duró poco: fue sustituida por la de 1937.'),
  ('4f4daa34-f914-5418-96a8-bb8e9f329555', 'en',
   'The Constitutionalist Revolution of 1932 was a movement:',
   array['from Rio Grande do Sul demanding Washington Luís''s return to the presidency', 'led by communists of the National Liberation Alliance', 'of Integralists against the 1934 Constitution', 'from São Paulo demanding a Constituent Assembly and an end to Vargas''s Provisional Government'],
   'São Paulo, sidelined from power since 1930 and ruled by federal appointees, took up arms for a new Constitution. It was defeated militarily, but the Constituent Assembly was called and the Constitution came out in 1934.'),
  ('4f4daa34-f914-5418-96a8-bb8e9f329555', 'es',
   'La Revolución Constitucionalista de 1932 fue un movimiento:',
   array['gaúcho que exigía el regreso de Washington Luís a la Presidencia', 'comunista liderado por la Alianza Nacional Libertadora', 'integralista contra la Constitución de 1934', 'paulista que exigía una Asamblea Constituyente y el fin del Gobierno Provisional de Vargas'],
   'São Paulo, apartado del poder desde 1930 y bajo interventores, tomó las armas por una nueva Constitución. Fue derrotado militarmente, pero se convocó la Constituyente y la Constitución salió en 1934.'),
  ('819d7d9d-e9ec-5940-bd49-a205a4e612c5', 'en',
   'One of the triggers of the 1930 Revolution was:',
   array['the Vaccine Revolt', 'the assassination of João Pessoa, the vice-presidential candidate on Getúlio Vargas''s ticket', 'the death of Washington Luís', 'the Encilhamento financial crisis'],
   'After the Liberal Alliance lost the 1930 election, the assassination of João Pessoa (partly for local reasons) inflamed the opposition and precipitated the armed movement that brought Vargas to power.'),
  ('819d7d9d-e9ec-5940-bd49-a205a4e612c5', 'es',
   'Uno de los detonantes de la Revolución de 1930 fue:',
   array['la Revuelta de la Vacuna', 'el asesinato de João Pessoa, candidato a vicepresidente en la fórmula de Getúlio Vargas', 'la muerte de Washington Luís', 'la crisis del Encilhamento'],
   'Tras la derrota de la Alianza Liberal en las elecciones de 1930, el asesinato de João Pessoa (también por motivos locales) encendió a la oposición y precipitó el movimiento armado que llevó a Vargas al poder.'),
  ('a093ad44-d1a4-5114-a098-0bd29673d1c4', 'en',
   'The "Dia do Fico" ("I Will Stay Day", January 9, 1822) refers to:',
   array['the coronation of Pedro I as emperor', 'João VI''s return to Portugal', 'Prince Pedro''s decision to stay in Brazil, defying the Cortes of Lisbon', 'Portugal''s recognition of independence'],
   'The Cortes of Lisbon demanded the prince regent''s return in order to recolonize Brazil. By declaring he would stay, Pedro broke with them, a decisive step toward independence in September 1822.'),
  ('a093ad44-d1a4-5114-a098-0bd29673d1c4', 'es',
   'El "Dia do Fico" ("Día del Me Quedo", 9 de enero de 1822) se refiere:',
   array['a la coronación de Pedro I como emperador', 'al regreso de Juan VI a Portugal', 'a la decisión del príncipe Pedro de permanecer en Brasil, desafiando a las Cortes de Lisboa', 'al reconocimiento de la independencia por Portugal'],
   'Las Cortes de Lisboa exigían el regreso del príncipe regente para recolonizar Brasil. Al declarar que se quedaría, Pedro rompió con ellas, un paso decisivo hacia la independencia de septiembre de 1822.'),
  ('72281f63-4c5c-5ff5-b8e6-3bbd3c8fa2b9', 'en',
   'The 1988 Constitution became known as the "Citizen Constitution" mainly because it:',
   array['expanded social and individual rights after the end of the dictatorship', 'established a parliamentary system', 'restored indirect presidential elections', 'reduced the state''s role in health and education'],
   'Promulgated with Ulysses Guimarães presiding over the Constituent Assembly, the 1988 Charter expanded rights (such as universal public health care through the SUS), made racism a crime and strengthened individual guarantees after 21 years of military rule.'),
  ('72281f63-4c5c-5ff5-b8e6-3bbd3c8fa2b9', 'es',
   'La Constitución de 1988 se conoció como "Constitución Ciudadana" principalmente por:',
   array['ampliar los derechos sociales e individuales tras el fin de la dictadura', 'instituir el parlamentarismo', 'restablecer la elección indirecta del presidente', 'reducir el papel del Estado en la salud y la educación'],
   'Promulgada bajo la presidencia de Ulysses Guimarães en la Constituyente, la Carta de 1988 amplió derechos (como el SUS universal), tipificó el racismo como delito y fortaleció las garantías individuales tras 21 años de régimen militar.'),
  ('d8728fc0-a3d2-58fa-86d7-78c3ef0fd2bd', 'en',
   'The Directorate of the Indians (Diretório dos Índios), introduced under Pombal (1757), determined:',
   array['that the villages be handed over to Jesuit control', 'the immediate abolition of all Indigenous labor', 'the demarcation of Indigenous lands by the Crown', 'the mandatory use of Portuguese and a ban on the língua geral in the villages'],
   'Pombal''s policy sought to "civilize" and integrate Indigenous people as subjects of the Crown: it imposed Portuguese, banned the Tupi-based língua geral, encouraged mixed marriages and placed the villages under lay directors after the Jesuits were expelled.'),
  ('d8728fc0-a3d2-58fa-86d7-78c3ef0fd2bd', 'es',
   'El Directorio de los Indios, implantado en el período pombalino (1757), determinó:',
   array['la entrega de las aldeas al control de los jesuitas', 'la abolición inmediata de todo trabajo indígena', 'la demarcación de tierras indígenas por la Corona', 'la obligatoriedad de la lengua portuguesa y la prohibición de la lengua general en las aldeas'],
   'La política de Pombal buscaba "civilizar" e integrar a los indígenas como vasallos: impuso el portugués, prohibió la lengua general (de base tupí), incentivó los matrimonios mixtos y puso las aldeas bajo directores laicos, tras la expulsión de los jesuitas.'),
  ('99276aa2-334d-5d65-b032-3c972172ef77', 'en',
   'Juscelino Kubitschek''s Targets Plan (1956–1961) prioritized:',
   array['land reform and the nationalization of foreign companies', 'energy, transportation and basic industry, with a large inflow of foreign capital', 'the creation of Petrobras and the state oil monopoly', 'fighting inflation through spending cuts'],
   'With the slogan "50 years in 5", JK invested in energy, transportation and industry (such as the auto industry), attracting foreign capital, and built Brasília. The cost was inflation and debt. Petrobras dates from 1953, under Vargas.'),
  ('99276aa2-334d-5d65-b032-3c972172ef77', 'es',
   'El Plan de Metas de Juscelino Kubitschek (1956–1961) priorizó:',
   array['la reforma agraria y la nacionalización de empresas extranjeras', 'la energía, el transporte y la industria de base, con fuerte entrada de capital extranjero', 'la creación de Petrobras y el monopolio estatal del petróleo', 'el control de la inflación mediante recortes de gastos'],
   'Con el lema "50 años en 5", JK invirtió en energía, transporte e industria (como la automotriz), atrajo capital extranjero y construyó Brasilia. El costo fue la inflación y el endeudamiento. Petrobras es de 1953, en el gobierno de Vargas.'),
  ('e2b82773-4616-5ce0-babb-519027f01ac5', 'en',
   'The "politics of the governors", devised by Campos Sales, consisted of:',
   array['mutual support: the federal government favored the state oligarchies, which in return elected delegations loyal to the president', 'the election of governors by the National Congress', 'a law requiring São Paulo and Minas Gerais to alternate in the presidency', 'permanent federal intervention in the states'],
   'The president backed the dominant oligarchy in each state, and they delivered pro-government deputies, with the help of the Credentials Verification Committee. The "coffee with milk" alternation was a political arrangement, not a law.'),
  ('e2b82773-4616-5ce0-babb-519027f01ac5', 'es',
   'La "política de los gobernadores", articulada por Campos Sales, consistía en:',
   array['un apoyo mutuo: el gobierno federal favorecía a las oligarquías estatales, que a cambio elegían bancadas fieles al presidente', 'la elección de los gobernadores por el Congreso Nacional', 'una ley que obligaba a la alternancia entre São Paulo y Minas en la Presidencia', 'la intervención federal permanente en los estados'],
   'El presidente apoyaba a las oligarquías dominantes en cada estado, y estas garantizaban diputados oficialistas, con ayuda de la Comisión Verificadora de Poderes. La "política del café con leche" era un arreglo político, no una ley.'),
  ('9f3e9ad2-1d2d-515d-ab6e-fa4e5f3bc550', 'en',
   'The Congress of Vienna (1814–1815) was guided by the principle of legitimacy, which advocated:',
   array['popular sovereignty and universal suffrage', 'the independence of the American colonies', 'the restoration of the dynasties deposed during the Napoleonic Wars', 'the immediate unification of Germany'],
   'The powers that defeated Napoleon sought to restore the Old Regime: under legitimacy, the "legitimate" dynasties (such as the Bourbons in France) returned to their thrones. The balance was upheld by the Holy Alliance.'),
  ('9f3e9ad2-1d2d-515d-ab6e-fa4e5f3bc550', 'es',
   'El Congreso de Viena (1814–1815) se guio por el principio de legitimidad, que defendía:',
   array['la soberanía popular y el sufragio universal', 'la independencia de las colonias americanas', 'la restauración de las dinastías depuestas durante las guerras napoleónicas', 'la unificación inmediata de Alemania'],
   'Las potencias vencedoras de Napoleón quisieron restaurar el Antiguo Régimen: por la legitimidad, volvían al trono las dinastías "legítimas" (como los Borbones en Francia). El equilibrio lo garantizó la Santa Alianza.'),
  ('4b1b4018-615b-5649-995c-96b6191b982d', 'en',
   'As an economic response to the Marshall Plan, the Soviet Union created, in 1949:',
   array['NATO', 'the UN', 'the Warsaw Pact', 'Comecon'],
   'Comecon (Council for Mutual Economic Assistance) integrated the economies of the socialist bloc in response to American aid to Western Europe. The Warsaw Pact (1955) was the military response to NATO.'),
  ('4b1b4018-615b-5649-995c-96b6191b982d', 'es',
   'Como respuesta económica al Plan Marshall, la Unión Soviética creó, en 1949:',
   array['la OTAN', 'la ONU', 'el Pacto de Varsovia', 'el Comecon'],
   'El Comecon (Consejo de Ayuda Mutua Económica) integró las economías del bloque socialista en respuesta a la ayuda estadounidense a Europa Occidental. El Pacto de Varsovia (1955) fue la respuesta militar a la OTAN.'),
  ('b1db9185-f0f3-5abd-b483-4769868c4880', 'en',
   'The Investiture Controversy, a dispute between the papacy and the Holy Roman Empire, was settled by:',
   array['the Peace of Westphalia', 'the Concordat of Worms (1122)', 'the bull Unam Sanctam', 'the Treaty of Verdun'],
   'The dispute was over who appointed bishops: the Pope or the Emperor. The Concordat of Worms split investiture: spiritual investiture went to the Church, while the Emperor kept temporal investiture (lands and fiefs).'),
  ('b1db9185-f0f3-5abd-b483-4769868c4880', 'es',
   'La Querella de las Investiduras, disputa entre el papado y el Sacro Imperio Romano Germánico, se cerró con:',
   array['la Paz de Westfalia', 'el Concordato de Worms (1122)', 'la bula Unam Sanctam', 'el Tratado de Verdún'],
   'La disputa era sobre quién nombraba a los obispos: el papa o el emperador. El Concordato de Worms dividió la investidura: la espiritual quedó para la Iglesia y el emperador conservó la temporal (tierras y feudos).'),
  ('1112fdf5-f4c1-5875-a710-b6e69ae9487f', 'en',
   'The Peace of Westphalia (1648), which ended the Thirty Years'' War, is considered a landmark of:',
   array['the system of sovereign states in Europe', 'Italian unification', 'the start of the Protestant Reformation', 'the creation of the Holy Roman Empire'],
   'The treaties recognized states'' sovereignty over their territory and religion, the independence of the Dutch Republic and Switzerland, and weakened the Holy Roman Empire. The idea of sovereign, equal states stems from them.'),
  ('1112fdf5-f4c1-5875-a710-b6e69ae9487f', 'es',
   'La Paz de Westfalia (1648), que puso fin a la Guerra de los Treinta Años, se considera un hito:',
   array['del sistema de Estados soberanos en Europa', 'de la unificación italiana', 'del inicio de la Reforma protestante', 'de la creación del Sacro Imperio'],
   'Los tratados reconocieron la soberanía de los Estados sobre su territorio y su religión, la independencia de las Provincias Unidas y de Suiza, y debilitaron al Sacro Imperio. La idea de Estados soberanos e iguales proviene de ahí.')
) as v(id, locale, prompt, options, explanation)
join questions q
  on q.id = v.id::uuid
 and cardinality(q.options) = cardinality(v.options)
on conflict (question_id, locale) do update
  set prompt = excluded.prompt,
      options = excluded.options,
      explanation = excluded.explanation;
