-- Química — Tabela periódica (7 leaves, 5 questões cada)
insert into questions (catalog_node_id, prompt, options, correct_index, explanation, order_index) values
-- Períodos (e0017fec-c1a0-44a2-9501-073e14904f77)
('e0017fec-c1a0-44a2-9501-073e14904f77', 'Na tabela periódica, os períodos correspondem:',
  array['Às linhas horizontais, indicando o número de camadas (níveis) eletrônicas do átomo', 'Às colunas verticais, indicando propriedades químicas semelhantes', 'Apenas aos elementos metálicos', 'Apenas aos elementos representativos'], 0,
  'Cada período (linha horizontal) corresponde ao número de camadas eletrônicas ocupadas pelos átomos daquela linha.', 1),
('e0017fec-c1a0-44a2-9501-073e14904f77', 'Quantos períodos (linhas) a tabela periódica atual possui?',
  array['7', '8', '18', '5'], 0,
  'A tabela periódica moderna é organizada em 7 períodos horizontais.', 2),
('e0017fec-c1a0-44a2-9501-073e14904f77', 'Um elemento localizado no 3º período da tabela periódica possui, em seu estado fundamental:',
  array['3 camadas eletrônicas ocupadas', '3 elétrons de valência, necessariamente', '3 prótons no núcleo', 'Nenhuma relação entre o período e a estrutura eletrônica'], 0,
  'O número do período indica quantas camadas eletrônicas o átomo possui, não o número de elétrons de valência.', 3),
('e0017fec-c1a0-44a2-9501-073e14904f77', 'Ao longo de um mesmo período, da esquerda para a direita, o raio atômico dos elementos tende a:',
  array['Diminuir, devido ao aumento da carga nuclear efetiva', 'Aumentar continuamente', 'Permanecer sempre constante', 'Variar de forma completamente aleatória'], 0,
  'Com o aumento do número atômico ao longo do período, a maior atração nuclear sobre os elétrons reduz o raio atômico.', 4),
('e0017fec-c1a0-44a2-9501-073e14904f77', 'Os elementos de um mesmo período pertencem, em geral, a:',
  array['Famílias (grupos) diferentes, com propriedades químicas distintas', 'Uma única e mesma família', 'O mesmo estado físico obrigatoriamente', 'A mesma configuração eletrônica de valência'], 0,
  'Elementos de um mesmo período têm o mesmo número de camadas, mas pertencem a famílias diferentes.', 5),

-- Famílias (2880a5d7-04f0-4587-8c21-6225dba9a778)
('2880a5d7-04f0-4587-8c21-6225dba9a778', 'Na tabela periódica, as famílias (ou grupos) correspondem:',
  array['Às colunas verticais, reunindo elementos com propriedades químicas semelhantes', 'Às linhas horizontais', 'Apenas aos elementos de transição', 'A uma divisão baseada exclusivamente na massa atômica'], 0,
  'Os elementos de uma mesma família (coluna) compartilham características químicas semelhantes.', 1),
('2880a5d7-04f0-4587-8c21-6225dba9a778', 'Elementos de uma mesma família compartilham, geralmente, o mesmo número de:',
  array['Elétrons na camada de valência', 'Camadas eletrônicas totais', 'Nêutrons no núcleo', 'Isótopos conhecidos'], 0,
  'O número de elétrons de valência, semelhante entre os elementos de uma família, é o principal responsável pela semelhança em suas propriedades.', 2),
('2880a5d7-04f0-4587-8c21-6225dba9a778', 'A família 1 (ou IA) da tabela periódica, formada pelos metais alcalinos, é caracterizada por possuir:',
  array['Um elétron na camada de valência', 'Sete elétrons na camada de valência', 'Oito elétrons na camada de valência', 'Nenhum elétron na camada de valência'], 0,
  'Os metais alcalinos possuem apenas 1 elétron de valência, o que os torna altamente reativos.', 3),
('2880a5d7-04f0-4587-8c21-6225dba9a778', 'A família 17 (ou VIIA) da tabela periódica, formada pelos halogênios, é caracterizada por possuir:',
  array['Sete elétrons na camada de valência', 'Um elétron na camada de valência', 'Oito elétrons na camada de valência', 'Dois elétrons na camada de valência'], 0,
  'Os halogênios possuem 7 elétrons de valência, faltando apenas 1 elétron para completar o octeto.', 4),
('2880a5d7-04f0-4587-8c21-6225dba9a778', 'Elementos de uma mesma família geralmente apresentam propriedades químicas semelhantes porque:',
  array['Possuem configurações eletrônicas de valência semelhantes', 'Possuem sempre o mesmo número de prótons', 'Estão sempre no mesmo período', 'Têm sempre a mesma massa atômica'], 0,
  'A semelhança na configuração eletrônica da camada de valência determina o comportamento químico semelhante dentro de uma família.', 5),

-- Metais, ametais e semimetais (db4c138e-2f1d-4b62-9c05-772bbfcd8a7e)
('db4c138e-2f1d-4b62-9c05-772bbfcd8a7e', 'Na tabela periódica, a maioria dos elementos químicos é classificada como:',
  array['Metais', 'Ametais', 'Semimetais', 'Gases nobres'], 0,
  'Os metais representam a maior parte dos elementos conhecidos, ocupando a maior área da tabela periódica.', 1),
('db4c138e-2f1d-4b62-9c05-772bbfcd8a7e', 'Uma característica típica dos metais, em contraste com os ametais, é:',
  array['Boa condutividade elétrica e térmica', 'Baixa condutividade elétrica', 'Tendência a ganhar elétrons em ligações', 'Estado gasoso à temperatura ambiente, em geral'], 0,
  'Os metais são, em geral, bons condutores de eletricidade e calor, além de dúcteis e maleáveis.', 2),
('db4c138e-2f1d-4b62-9c05-772bbfcd8a7e', 'Os semimetais (ou metaloides), como o silício e o germânio, apresentam propriedades:',
  array['Intermediárias entre metais e ametais', 'Idênticas às dos metais em todos os aspectos', 'Idênticas às dos ametais em todos os aspectos', 'Exclusivas de gases nobres'], 0,
  'Os semimetais combinam características de metais e ametais, sendo muito usados como semicondutores.', 3),
('db4c138e-2f1d-4b62-9c05-772bbfcd8a7e', 'Os ametais, em comparação com os metais, tendem a apresentar, em reações químicas, maior tendência a:',
  array['Ganhar elétrons, formando ânions', 'Perder elétrons, formando cátions', 'Não participar de nenhuma ligação química', 'Formar apenas ligações metálicas'], 0,
  'Os ametais, por terem maior eletronegatividade, tendem a ganhar elétrons e formar ânions em ligações iônicas.', 4),
('db4c138e-2f1d-4b62-9c05-772bbfcd8a7e', 'O silício, amplamente utilizado na fabricação de componentes eletrônicos, é classificado como:',
  array['Semimetal (metaloide)', 'Metal alcalino', 'Gás nobre', 'Halogênio'], 0,
  'O silício é um semimetal, cujas propriedades de semicondutor o tornam essencial na indústria eletrônica.', 5),

-- Gases nobres (61b08c3e-7325-4199-9fb1-3b1a891d2b5b)
('61b08c3e-7325-4199-9fb1-3b1a891d2b5b', 'Os gases nobres, localizados na última família (18 ou VIIIA) da tabela periódica, caracterizam-se principalmente por:',
  array['Possuírem a camada de valência completa, sendo pouco reativos', 'Serem os elementos mais reativos da tabela periódica', 'Possuírem apenas 1 elétron de valência', 'Não existirem naturalmente, sendo todos sintéticos'], 0,
  'Com a camada de valência completa, os gases nobres apresentam grande estabilidade química e baixa reatividade.', 1),
('61b08c3e-7325-4199-9fb1-3b1a891d2b5b', 'O hélio, um gás nobre amplamente utilizado para encher balões, é caracterizado por:',
  array['Ser mais leve que o ar e quimicamente pouco reativo', 'Ser altamente reativo e inflamável', 'Ser mais denso que o ar', 'Reagir facilmente com a água'], 0,
  'O hélio é leve, inerte e não inflamável, características que o tornam seguro para uso em balões.', 2),
('61b08c3e-7325-4199-9fb1-3b1a891d2b5b', 'O neônio, outro gás nobre, é bastante conhecido por sua aplicação em:',
  array['Iluminação de letreiros luminosos (luzes de neon)', 'Produção de energia nuclear', 'Fabricação de baterias', 'Purificação de água'], 0,
  'Ao ser submetido a descargas elétricas em tubos, o neônio emite uma luz avermelhada característica, usada em letreiros luminosos.', 3),
('61b08c3e-7325-4199-9fb1-3b1a891d2b5b', 'Diferentemente da maioria dos elementos, os gases nobres dificilmente formam compostos químicos porque:',
  array['Já possuem configuração eletrônica estável, com a camada de valência completa', 'Não possuem elétrons de valência', 'São sempre encontrados em estado líquido', 'Reagem apenas com metais alcalinos'], 0,
  'A estabilidade eletrônica reduz drasticamente a tendência dos gases nobres a formar ligações químicas.', 4),
('61b08c3e-7325-4199-9fb1-3b1a891d2b5b', 'O argônio, gás nobre presente em maior quantidade na atmosfera terrestre entre os gases nobres, é utilizado, por exemplo, em:',
  array['Lâmpadas incandescentes, como gás de proteção do filamento', 'Reatores nucleares como combustível principal', 'Produção de fertilizantes agrícolas', 'Fabricação de explosivos'], 0,
  'O argônio, por ser inerte, é utilizado dentro de lâmpadas incandescentes para evitar a oxidação do filamento aquecido.', 5),

-- Metais alcalinos (8388a421-a787-4bf0-9e15-fee32a78e884)
('8388a421-a787-4bf0-9e15-fee32a78e884', 'Os metais alcalinos, localizados na família 1 (IA) da tabela periódica, caracterizam-se por:',
  array['Possuírem apenas 1 elétron na camada de valência, sendo muito reativos', 'Possuírem 7 elétrons na camada de valência', 'Serem extremamente inertes quimicamente', 'Não reagirem com a água em nenhuma condição'], 0,
  'Com apenas 1 elétron de valência, os metais alcalinos tendem a perdê-lo facilmente, tornando-os altamente reativos.', 1),
('8388a421-a787-4bf0-9e15-fee32a78e884', 'Metais alcalinos, como o sódio e o potássio, reagem vigorosamente ao entrarem em contato com:',
  array['Água', 'Óleo mineral', 'Nitrogênio gasoso', 'Gases nobres'], 0,
  'Metais alcalinos reagem violentamente com a água, liberando gás hidrogênio e calor.', 2),
('8388a421-a787-4bf0-9e15-fee32a78e884', 'Por serem altamente reativos, os metais alcalinos são geralmente armazenados:',
  array['Imersos em óleo mineral, para evitar contato com o ar e a umidade', 'Expostos livremente ao ar', 'Em recipientes com água', 'Sob alta pressão de oxigênio puro'], 0,
  'O armazenamento em óleo mineral evita a reação desses metais com o oxigênio e a umidade do ar.', 3),
('8388a421-a787-4bf0-9e15-fee32a78e884', 'Ao perderem seu único elétron de valência, os metais alcalinos formam íons com carga:',
  array['+1 (cátions monovalentes)', '-1 (ânions monovalentes)', '+2', 'Neutra, sem carga'], 0,
  'A perda do único elétron de valência resulta em um cátion de carga +1, como Na⁺ e K⁺.', 4),
('8388a421-a787-4bf0-9e15-fee32a78e884', 'O sódio (Na) e o potássio (K) são exemplos de:',
  array['Metais alcalinos', 'Gases nobres', 'Halogênios', 'Semimetais'], 0,
  'Sódio e potássio pertencem à família 1 (IA) da tabela periódica, classificados como metais alcalinos.', 5),

-- Halogênios (7a0bf96c-65fd-4af6-b8c1-a69d0f51b0a3)
('7a0bf96c-65fd-4af6-b8c1-a69d0f51b0a3', 'Os halogênios, localizados na família 17 (VIIA) da tabela periódica, caracterizam-se por:',
  array['Possuírem 7 elétrons na camada de valência, sendo altamente reativos', 'Possuírem apenas 1 elétron na camada de valência', 'Serem extremamente inertes quimicamente', 'Formarem exclusivamente cátions'], 0,
  'Com 7 elétrons de valência, os halogênios tendem a ganhar 1 elétron para completar o octeto, tornando-os muito reativos.', 1),
('7a0bf96c-65fd-4af6-b8c1-a69d0f51b0a3', 'Ao ganharem um elétron, os halogênios formam íons com carga:',
  array['-1 (ânions monovalentes)', '+1 (cátions monovalentes)', '-2', 'Neutra, sem carga'], 0,
  'O ganho de 1 elétron resulta em um ânion de carga -1, como Cl⁻ (cloreto) e F⁻ (fluoreto).', 2),
('7a0bf96c-65fd-4af6-b8c1-a69d0f51b0a3', 'O cloro, um halogênio amplamente utilizado, é comumente empregado em:',
  array['Tratamento e desinfecção de água potável', 'Fabricação de balões infláveis', 'Produção de gases nobres sintéticos', 'Iluminação de letreiros luminosos'], 0,
  'O cloro é amplamente utilizado como desinfetante, sobretudo no tratamento de água para consumo e em piscinas.', 3),
('7a0bf96c-65fd-4af6-b8c1-a69d0f51b0a3', 'O flúor, halogênio mais reativo de toda a tabela periódica, é comumente adicionado a produtos de higiene bucal por:',
  array['Ajudar na prevenção de cáries dentárias', 'Ser um conservante alimentar', 'Clarear os dentes instantaneamente', 'Substituir totalmente o cálcio dos dentes'], 0,
  'O flúor fortalece o esmalte dentário, sendo amplamente utilizado em cremes dentais para prevenir cáries.', 4),
('7a0bf96c-65fd-4af6-b8c1-a69d0f51b0a3', 'Os halogênios podem ser encontrados na natureza nos três estados físicos, como o flúor (gás), o bromo (líquido) e o iodo (sólido), o que ilustra:',
  array['A grande variação de propriedades físicas dentro de uma mesma família química', 'Que todos os elementos de uma família têm sempre o mesmo estado físico', 'Que halogênios não podem existir em estado sólido', 'Que a família dos halogênios é composta por gases nobres'], 0,
  'Apesar de compartilharem propriedades químicas semelhantes, os halogênios apresentam estados físicos distintos à temperatura ambiente.', 5),

-- Propriedades periódicas (e0d8da54-8dd1-478e-98ed-1c168d697958)
('e0d8da54-8dd1-478e-98ed-1c168d697958', 'O raio atômico, ao longo de um grupo (família) da tabela periódica, de cima para baixo, tende a:',
  array['Aumentar, devido ao acréscimo de camadas eletrônicas', 'Diminuir continuamente', 'Permanecer sempre constante', 'Variar de forma completamente aleatória'], 0,
  'Descendo em uma família, o aumento do número de camadas eletrônicas faz o raio atômico crescer.', 1),
('e0d8da54-8dd1-478e-98ed-1c168d697958', 'A eletronegatividade de um elemento representa:',
  array['A capacidade de um átomo atrair elétrons em uma ligação química', 'O raio total do átomo', 'A energia necessária para remover um elétron do átomo', 'A quantidade de nêutrons presentes no núcleo'], 0,
  'A eletronegatividade mede a tendência de um átomo de atrair para si os elétrons compartilhados em uma ligação.', 2),
('e0d8da54-8dd1-478e-98ed-1c168d697958', 'De modo geral, a eletronegatividade dos elementos, ao longo de um período (da esquerda para a direita), tende a:',
  array['Aumentar', 'Diminuir', 'Permanecer constante', 'Não seguir nenhum padrão'], 0,
  'Ao longo de um período, o aumento da carga nuclear efetiva geralmente aumenta a eletronegatividade dos elementos.', 3),
('e0d8da54-8dd1-478e-98ed-1c168d697958', 'A energia de ionização é definida como a energia necessária para:',
  array['Remover um elétron de um átomo no estado gasoso', 'Adicionar um elétron a um átomo', 'Remover um próton do núcleo', 'Fundir um sólido'], 0,
  'A energia de ionização mede a dificuldade de retirar um elétron de um átomo neutro, transformando-o em um cátion.', 4),
('e0d8da54-8dd1-478e-98ed-1c168d697958', 'O flúor é geralmente apontado como o elemento de maior eletronegatividade da tabela periódica, sendo localizado:',
  array['Próximo ao canto superior direito da tabela periódica', 'Próximo ao canto inferior esquerdo', 'No centro exato da tabela periódica', 'Entre os gases nobres'], 0,
  'A eletronegatividade tende a ser maior próximo ao canto superior direito da tabela (excluindo os gases nobres), região onde está o flúor.', 5);
