-- Biologia — Corpo Humano e Fisiologia (15 leaves, 5 questões cada)
insert into questions (catalog_node_id, prompt, options, correct_index, explanation, order_index) values
-- Coração (e53efaa2-9b86-4ffb-a802-7981ff47cf0f)
('e53efaa2-9b86-4ffb-a802-7981ff47cf0f', 'O coração humano é um órgão muscular dividido internamente em:',
  array['Quatro cavidades — dois átrios e dois ventrículos', 'Duas cavidades apenas', 'Seis cavidades', 'Uma única cavidade contínua'], 0,
  'O coração humano possui quatro câmaras: átrio direito, átrio esquerdo, ventrículo direito e ventrículo esquerdo.', 1),
('e53efaa2-9b86-4ffb-a802-7981ff47cf0f', 'Os átrios, câmaras superiores do coração, têm como principal função:',
  array['Receber o sangue proveniente das veias, antes de bombeá-lo para os ventrículos', 'Bombear o sangue diretamente para as artérias do corpo', 'Produzir células sanguíneas', 'Filtrar o sangue antes de sua circulação'], 0,
  'Os átrios recebem o sangue venoso e o transferem para os ventrículos, responsáveis pelo bombeamento mais vigoroso.', 2),
('e53efaa2-9b86-4ffb-a802-7981ff47cf0f', 'O ventrículo esquerdo, geralmente a câmara com paredes musculares mais espessas do coração, é responsável por bombear sangue para:',
  array['Todo o corpo, através da circulação sistêmica', 'Apenas os pulmões, através da circulação pulmonar', 'O átrio direito diretamente', 'Nenhuma parte do corpo, apenas armazenar sangue'], 0,
  'Por impulsionar o sangue por todo o corpo, o ventrículo esquerdo possui a musculatura mais desenvolvida.', 3),
('e53efaa2-9b86-4ffb-a802-7981ff47cf0f', 'O nó sinoatrial, estrutura responsável por iniciar os batimentos cardíacos, é frequentemente chamado de:',
  array['Marca-passo natural do coração', 'Válvula cardíaca principal', 'Artéria coronária', 'Veia cava'], 0,
  'O nó sinoatrial gera os impulsos elétricos que determinam o ritmo dos batimentos cardíacos.', 4),
('e53efaa2-9b86-4ffb-a802-7981ff47cf0f', 'As artérias coronárias têm a função específica de:',
  array['Irrigar o próprio músculo cardíaco com sangue oxigenado', 'Levar sangue do coração para os pulmões', 'Coletar sangue venoso de todo o corpo', 'Substituir totalmente a função dos ventrículos'], 0,
  'As coronárias fornecem oxigênio e nutrientes diretamente ao músculo cardíaco (miocárdio).', 5),

-- Válvulas (a1858027-f953-4d1b-8b40-3e2ff2456097)
('a1858027-f953-4d1b-8b40-3e2ff2456097', 'A principal função das válvulas cardíacas é:',
  array['Garantir que o sangue flua em uma única direção, impedindo o refluxo', 'Bombear ativamente o sangue pelo corpo', 'Produzir os impulsos elétricos do coração', 'Filtrar impurezas do sangue'], 0,
  'As válvulas cardíacas abrem e fecham conforme as diferenças de pressão, garantindo o fluxo unidirecional do sangue.', 1),
('a1858027-f953-4d1b-8b40-3e2ff2456097', 'A válvula mitral (ou bicúspide) está localizada entre:',
  array['O átrio esquerdo e o ventrículo esquerdo', 'O átrio direito e o ventrículo direito', 'O ventrículo esquerdo e a aorta', 'O ventrículo direito e a artéria pulmonar'], 0,
  'A válvula mitral controla a passagem de sangue do átrio esquerdo para o ventrículo esquerdo.', 2),
('a1858027-f953-4d1b-8b40-3e2ff2456097', 'A válvula tricúspide está localizada entre:',
  array['O átrio direito e o ventrículo direito', 'O átrio esquerdo e o ventrículo esquerdo', 'O ventrículo esquerdo e a aorta', 'O átrio direito e a veia cava'], 0,
  'A válvula tricúspide controla a passagem de sangue do átrio direito para o ventrículo direito.', 3),
('a1858027-f953-4d1b-8b40-3e2ff2456097', 'O funcionamento inadequado de uma válvula cardíaca, permitindo o refluxo de sangue, é uma condição médica conhecida como:',
  array['Insuficiência valvar', 'Arritmia exclusivamente', 'Anemia', 'Hipertensão arterial, exclusivamente'], 0,
  'Quando uma válvula não fecha adequadamente, ocorre refluxo de sangue, condição chamada de insuficiência valvar.', 4),
('a1858027-f953-4d1b-8b40-3e2ff2456097', 'O som característico dos batimentos cardíacos, ouvido com o auxílio de um estetoscópio, é causado principalmente pelo(a):',
  array['Fechamento das válvulas cardíacas', 'Abertura das válvulas cardíacas', 'Contração dos músculos das pernas', 'Passagem de ar pelos pulmões'], 0,
  'Os sons cardíacos característicos são produzidos principalmente pelo fechamento sequencial das válvulas cardíacas.', 5),

-- Artérias (95373244-bfd4-4ba0-aa81-0d7cb89f8805)
('95373244-bfd4-4ba0-aa81-0d7cb89f8805', 'As artérias são vasos sanguíneos responsáveis por:',
  array['Conduzir o sangue do coração para os demais órgãos e tecidos do corpo', 'Conduzir o sangue dos tecidos de volta para o coração', 'Realizar a troca direta de gases com o meio externo', 'Produzir novas células sanguíneas'], 0,
  'As artérias transportam o sangue que sai do coração em direção aos tecidos do corpo.', 1),
('95373244-bfd4-4ba0-aa81-0d7cb89f8805', 'Em comparação com as veias, as artérias apresentam paredes:',
  array['Mais espessas e musculosas, para suportar a alta pressão do sangue bombeado pelo coração', 'Mais finas e menos musculosas', 'Idênticas às das veias, sem qualquer diferença estrutural', 'Compostas exclusivamente por tecido ósseo'], 0,
  'A necessidade de suportar a alta pressão do bombeamento cardíaco torna as paredes arteriais mais espessas.', 2),
('95373244-bfd4-4ba0-aa81-0d7cb89f8805', 'A aorta, a maior artéria do corpo humano, tem origem diretamente:',
  array['No ventrículo esquerdo do coração', 'No átrio direito do coração', 'Nos pulmões', 'No ventrículo direito do coração'], 0,
  'A aorta sai do ventrículo esquerdo, distribuindo sangue oxigenado para praticamente todo o corpo.', 3),
('95373244-bfd4-4ba0-aa81-0d7cb89f8805', 'A exceção mais conhecida quanto ao tipo de sangue transportado pelas artérias ocorre na:',
  array['Artéria pulmonar, que transporta sangue pobre em oxigênio até os pulmões', 'Aorta, que transportaria sangue pobre em oxigênio', 'Artéria coronária, que transportaria sangue venoso', 'Nenhuma exceção existe entre as artérias do corpo'], 0,
  'Diferentemente da maioria das artérias, a artéria pulmonar transporta sangue pobre em oxigênio até os pulmões.', 4),
('95373244-bfd4-4ba0-aa81-0d7cb89f8805', 'O acúmulo de placas de gordura nas paredes arteriais, condição conhecida como aterosclerose, pode causar:',
  array['Estreitamento e endurecimento das artérias, aumentando o risco de infartos e derrames', 'Um aumento imediato da elasticidade arterial', 'Nenhum impacto relevante para a saúde cardiovascular', 'A dilatação permanente e saudável das artérias'], 0,
  'A aterosclerose reduz o calibre das artérias e compromete sua elasticidade, aumentando o risco cardiovascular.', 5),

-- Veias (3bdaccc7-106a-488d-a95b-8b42e9b29cc7)
('3bdaccc7-106a-488d-a95b-8b42e9b29cc7', 'As veias são vasos sanguíneos responsáveis por:',
  array['Conduzir o sangue dos tecidos de volta para o coração', 'Conduzir o sangue do coração para os tecidos', 'Bombear ativamente o sangue com alta pressão', 'Produzir hemácias e leucócitos'], 0,
  'As veias transportam o sangue de volta ao coração, geralmente pobre em oxigênio (exceto as veias pulmonares).', 1),
('3bdaccc7-106a-488d-a95b-8b42e9b29cc7', 'Muitas veias, especialmente nos membros inferiores, possuem estruturas internas chamadas:',
  array['Válvulas venosas, que impedem o refluxo do sangue', 'Nós sinoatriais', 'Alvéolos', 'Cristas mitocondriais'], 0,
  'As válvulas venosas ajudam a impedir o retorno do sangue pela gravidade, auxiliando o fluxo em direção ao coração.', 2),
('3bdaccc7-106a-488d-a95b-8b42e9b29cc7', 'A veia cava, um dos principais vasos venosos do corpo, é responsável por conduzir sangue diretamente para:',
  array['O átrio direito do coração', 'O ventrículo esquerdo do coração', 'Os pulmões diretamente', 'A aorta'], 0,
  'As veias cavas superior e inferior desembocam no átrio direito, trazendo de volta o sangue venoso de todo o corpo.', 3),
('3bdaccc7-106a-488d-a95b-8b42e9b29cc7', 'Diferentemente da maioria das veias do corpo, as veias pulmonares transportam sangue:',
  array['Rico em oxigênio, dos pulmões para o átrio esquerdo do coração', 'Pobre em oxigênio, do coração para os pulmões', 'Idêntico ao transportado pela veia cava', 'Exclusivamente para os rins'], 0,
  'As veias pulmonares são uma exceção, transportando sangue oxigenado dos pulmões de volta ao coração.', 4),
('3bdaccc7-106a-488d-a95b-8b42e9b29cc7', 'A contração dos músculos esqueléticos, especialmente nas pernas, auxilia o retorno do sangue venoso ao coração porque:',
  array['Comprime as veias, ajudando a impulsionar o sangue contra a gravidade', 'Bloqueia completamente o fluxo sanguíneo nas veias', 'Não tem qualquer relação com a circulação venosa', 'Reduz a pressão arterial de forma permanente'], 0,
  'A movimentação muscular comprime as veias adjacentes, auxiliando o retorno do sangue ao coração.', 5),

-- Capilares (7d0ed443-aa25-429f-89cd-b5ce672f22d2)
('7d0ed443-aa25-429f-89cd-b5ce672f22d2', 'Os capilares sanguíneos são caracterizados por serem:',
  array['Vasos extremamente finos, com paredes de apenas uma célula de espessura', 'Os maiores vasos sanguíneos do corpo', 'Estruturas exclusivamente musculares, sem qualquer função de troca', 'Idênticos às artérias em estrutura e função'], 0,
  'Os capilares possuem paredes muito finas, formadas por uma única camada de células, facilitando as trocas.', 1),
('7d0ed443-aa25-429f-89cd-b5ce672f22d2', 'A principal função dos capilares é:',
  array['Permitir a troca de gases, nutrientes e resíduos entre o sangue e as células dos tecidos', 'Bombear ativamente o sangue com alta pressão', 'Armazenar grandes quantidades de sangue', 'Produzir hormônios diretamente'], 0,
  'É nos capilares que ocorrem as trocas essenciais entre o sangue e as células.', 2),
('7d0ed443-aa25-429f-89cd-b5ce672f22d2', 'Os capilares conectam, dentro do sistema circulatório, os seguintes tipos de vasos:',
  array['Arteríolas e vênulas', 'Apenas artérias de grande calibre', 'Apenas veias de grande calibre', 'Diretamente o coração aos pulmões, sem qualquer vaso intermediário'], 0,
  'Os capilares formam a ponte entre o sistema arterial (arteríolas) e o sistema venoso (vênulas).', 3),
('7d0ed443-aa25-429f-89cd-b5ce672f22d2', 'A grande quantidade de capilares presente nos tecidos do corpo está relacionada, principalmente, a:',
  array['Maximizar a área de superfície disponível para as trocas entre sangue e tecidos', 'Aumentar exclusivamente a pressão arterial', 'Reduzir a necessidade de oxigênio dos tecidos', 'Substituir totalmente a função do coração'], 0,
  'A extensa rede de capilares amplia a área de contato entre o sangue e as células, otimizando as trocas.', 4),
('7d0ed443-aa25-429f-89cd-b5ce672f22d2', 'A velocidade do fluxo sanguíneo nos capilares, em comparação com as artérias, é geralmente:',
  array['Mais lenta, o que favorece o tempo necessário para as trocas com os tecidos', 'Muito mais rápida', 'Exatamente idêntica à das artérias', 'Nula, sem qualquer fluxo sanguíneo'], 0,
  'O fluxo mais lento nos capilares permite tempo suficiente para as trocas essenciais com as células.', 5),

-- Circulação pulmonar (bfeb4cb7-a05a-4d9b-a38d-a6e6815a808f)
('bfeb4cb7-a05a-4d9b-a38d-a6e6815a808f', 'A circulação pulmonar é o trajeto do sangue entre:',
  array['O coração e os pulmões, responsável pela oxigenação do sangue', 'O coração e todos os demais órgãos do corpo, exceto os pulmões', 'Apenas os pulmões e o cérebro', 'O sistema digestório e o coração'], 0,
  'Na circulação pulmonar, o sangue sai do coração em direção aos pulmões, onde é oxigenado.', 1),
('bfeb4cb7-a05a-4d9b-a38d-a6e6815a808f', 'Na circulação pulmonar, o sangue sai do coração pelo(a):',
  array['Ventrículo direito, através da artéria pulmonar', 'Ventrículo esquerdo, através da aorta', 'Átrio direito, diretamente', 'Átrio esquerdo, diretamente'], 0,
  'O ventrículo direito bombeia o sangue pobre em oxigênio para os pulmões através da artéria pulmonar.', 2),
('bfeb4cb7-a05a-4d9b-a38d-a6e6815a808f', 'Após ser oxigenado nos pulmões, o sangue retorna ao coração por meio:',
  array['Das veias pulmonares, chegando ao átrio esquerdo', 'Da veia cava, chegando ao átrio direito', 'Da aorta, chegando ao ventrículo esquerdo', 'Da artéria pulmonar, chegando ao ventrículo direito'], 0,
  'O sangue oxigenado retorna dos pulmões pelas veias pulmonares, entrando no coração pelo átrio esquerdo.', 3),
('bfeb4cb7-a05a-4d9b-a38d-a6e6815a808f', 'A circulação pulmonar é também chamada de "pequena circulação" porque:',
  array['Percorre um trajeto mais curto, entre o coração e os pulmões apenas', 'Envolve uma quantidade menor de sangue do que a circulação sistêmica', 'Ocorre apenas em bebês, e não em adultos', 'Não envolve qualquer vaso sanguíneo'], 0,
  'Por se restringir ao trajeto entre o coração e os pulmões, é chamada de "pequena circulação".', 4),
('bfeb4cb7-a05a-4d9b-a38d-a6e6815a808f', 'A oxigenação do sangue durante a circulação pulmonar ocorre especificamente:',
  array['Nos alvéolos pulmonares, através da troca gasosa com o ar inspirado', 'No próprio coração, sem qualquer participação dos pulmões', 'Nos rins, durante a filtração sanguínea', 'No fígado, durante a metabolização de nutrientes'], 0,
  'É nos alvéolos pulmonares que ocorre a troca gasosa entre o sangue e o ar inspirado.', 5),

-- Circulação sistêmica (c71f4bd6-9a85-47d3-b979-b99d2626971a)
('c71f4bd6-9a85-47d3-b979-b99d2626971a', 'A circulação sistêmica é o trajeto do sangue entre:',
  array['O coração e todos os demais órgãos e tecidos do corpo (exceto os pulmões)', 'Exclusivamente o coração e os pulmões', 'Apenas o cérebro e o coração', 'O sistema digestório e os rins'], 0,
  'A circulação sistêmica leva sangue oxigenado do coração para todo o corpo e traz de volta o sangue pobre em oxigênio.', 1),
('c71f4bd6-9a85-47d3-b979-b99d2626971a', 'Na circulação sistêmica, o sangue oxigenado sai do coração pelo(a):',
  array['Ventrículo esquerdo, através da aorta', 'Ventrículo direito, através da artéria pulmonar', 'Átrio esquerdo, diretamente', 'Átrio direito, diretamente'], 0,
  'O ventrículo esquerdo bombeia sangue rico em oxigênio para o corpo por meio da aorta.', 2),
('c71f4bd6-9a85-47d3-b979-b99d2626971a', 'Após percorrer os tecidos do corpo, o sangue pobre em oxigênio retorna ao coração pela(s):',
  array['Veias cavas, chegando ao átrio direito', 'Veias pulmonares, chegando ao átrio esquerdo', 'Artéria pulmonar, chegando ao ventrículo direito', 'Aorta, chegando ao ventrículo esquerdo'], 0,
  'O sangue venoso de todo o corpo retorna ao coração através das veias cavas, chegando ao átrio direito.', 3),
('c71f4bd6-9a85-47d3-b979-b99d2626971a', 'A circulação sistêmica é também chamada de "grande circulação" porque:',
  array['Percorre um trajeto muito mais longo, alcançando todos os órgãos e tecidos do corpo', 'Envolve uma quantidade menor de sangue do que a circulação pulmonar', 'Ocorre apenas nos pulmões', 'Não envolve qualquer vaso sanguíneo'], 0,
  'Por abranger todo o corpo, a circulação sistêmica é chamada de "grande circulação".', 4),
('c71f4bd6-9a85-47d3-b979-b99d2626971a', 'Durante a circulação sistêmica, os capilares dos tecidos realizam trocas essenciais, como:',
  array['A entrega de oxigênio e nutrientes às células, e a captação de gás carbônico e resíduos metabólicos', 'A oxigenação direta do sangue, semelhante ao que ocorre nos pulmões', 'A produção de novas células sanguíneas', 'Nenhuma troca relevante ocorre nesse trajeto'], 0,
  'É nos capilares sistêmicos que ocorrem as trocas fundamentais entre o sangue e as células dos tecidos.', 5),

-- Neurônio (9480bb3f-8a4e-44dc-8040-c969d518bc77)
('9480bb3f-8a4e-44dc-8040-c969d518bc77', 'O neurônio é a célula fundamental do sistema nervoso, especializada em:',
  array['Receber, processar e transmitir impulsos nervosos', 'Produzir hormônios exclusivamente', 'Realizar a digestão de nutrientes', 'Contrair-se para gerar movimento muscular'], 0,
  'Os neurônios conduzem sinais elétricos e químicos que permitem a comunicação entre partes do organismo.', 1),
('9480bb3f-8a4e-44dc-8040-c969d518bc77', 'As principais partes estruturais de um neurônio incluem:',
  array['Corpo celular (soma), dendritos e axônio', 'Apenas núcleo e citoplasma, sem qualquer estrutura adicional', 'Exclusivamente mitocôndrias e ribossomos', 'Apenas membrana plasmática, sem organelas internas'], 0,
  'O corpo celular contém núcleo e organelas; os dendritos recebem estímulos; o axônio conduz o impulso nervoso.', 2),
('9480bb3f-8a4e-44dc-8040-c969d518bc77', 'A bainha de mielina, presente ao redor de muitos axônios, tem como principal função:',
  array['Acelerar a condução do impulso nervoso ao longo do axônio', 'Impedir totalmente a condução de qualquer impulso nervoso', 'Produzir neurotransmissores', 'Substituir a função do corpo celular'], 0,
  'A mielina isola o axônio, permitindo condução mais rápida, por meio da condução saltatória.', 3),
('9480bb3f-8a4e-44dc-8040-c969d518bc77', 'Os dendritos, estruturas ramificadas presentes nos neurônios, têm como principal função:',
  array['Receber estímulos de outros neurônios ou do ambiente', 'Conduzir o impulso nervoso para longas distâncias', 'Produzir energia celular', 'Armazenar o material genético do neurônio'], 0,
  'Os dendritos captam sinais de outros neurônios ou receptores sensoriais, transmitindo-os ao corpo celular.', 4),
('9480bb3f-8a4e-44dc-8040-c969d518bc77', 'Os neurônios se comunicam entre si, ou com outras células (como as musculares), principalmente por meio de:',
  array['Sinapses, envolvendo a liberação de neurotransmissores', 'Contato físico direto entre seus núcleos', 'Fusão completa de suas membranas celulares', 'Trocas diretas de material genético'], 0,
  'A comunicação neuronal ocorre principalmente nas sinapses, com liberação de neurotransmissores.', 5),

-- Sistema nervoso central (3802e1b8-5448-4536-87de-e4bc3341c3b0)
('3802e1b8-5448-4536-87de-e4bc3341c3b0', 'O Sistema Nervoso Central (SNC) é formado por:',
  array['O encéfalo e a medula espinhal', 'Apenas os nervos periféricos', 'Exclusivamente os órgãos dos sentidos', 'Apenas o coração e os pulmões'], 0,
  'O SNC, composto pelo encéfalo e pela medula espinhal, é o centro de processamento do sistema nervoso.', 1),
('3802e1b8-5448-4536-87de-e4bc3341c3b0', 'O cérebro, principal estrutura do encéfalo, é responsável, entre outras funções, por:',
  array['Processos cognitivos complexos, como pensamento, memória e linguagem', 'Apenas a produção de células sanguíneas', 'A digestão de alimentos', 'A filtração do sangue, semelhante aos rins'], 0,
  'O cérebro coordena funções superiores, como raciocínio, memória, linguagem e controle voluntário dos movimentos.', 2),
('3802e1b8-5448-4536-87de-e4bc3341c3b0', 'O cerebelo, outra estrutura importante do encéfalo, tem como principal função:',
  array['Coordenar o equilíbrio e a precisão dos movimentos corporais', 'Processar exclusivamente informações visuais', 'Produzir hormônios sexuais', 'Controlar diretamente a digestão de alimentos'], 0,
  'O cerebelo é essencial para a coordenação motora fina, o equilíbrio e a postura corporal.', 3),
('3802e1b8-5448-4536-87de-e4bc3341c3b0', 'A medula espinhal, protegida pela coluna vertebral, tem como funções principais:',
  array['Conduzir impulsos nervosos entre o encéfalo e o restante do corpo, além de mediar reflexos simples', 'Produzir exclusivamente células ósseas', 'Substituir totalmente a função do encéfalo', 'Realizar a digestão de proteínas'], 0,
  'A medula espinhal conecta o encéfalo ao corpo e coordena diretamente certos reflexos.', 4),
('3802e1b8-5448-4536-87de-e4bc3341c3b0', 'O SNC é protegido por estruturas ósseas específicas, sendo elas:',
  array['O crânio (protegendo o encéfalo) e a coluna vertebral (protegendo a medula espinhal)', 'Apenas as costelas', 'Exclusivamente os ossos dos braços e pernas', 'Nenhuma estrutura óssea protege o SNC'], 0,
  'O crânio e a coluna vertebral formam uma proteção óssea rígida para as estruturas do SNC.', 5),

-- Sistema nervoso periférico (9af22c5f-f2e2-4112-bc80-077daa270068)
('9af22c5f-f2e2-4112-bc80-077daa270068', 'O Sistema Nervoso Periférico (SNP) é formado principalmente por:',
  array['Nervos que conectam o Sistema Nervoso Central aos demais órgãos e tecidos do corpo', 'Apenas o encéfalo', 'Exclusivamente a medula espinhal', 'Somente os órgãos dos sentidos, sem qualquer nervo'], 0,
  'O SNP é composto pelos nervos cranianos e espinhais, conectando o SNC ao restante do corpo.', 1),
('9af22c5f-f2e2-4112-bc80-077daa270068', 'O SNP pode ser dividido, quanto à função, em sistema nervoso somático e sistema nervoso autônomo, sendo o somático responsável principalmente por:',
  array['Controlar movimentos voluntários, relacionados à musculatura esquelética', 'Controlar exclusivamente funções involuntárias, como batimentos cardíacos', 'Produzir hormônios', 'Realizar a digestão de alimentos'], 0,
  'O sistema nervoso somático controla ações voluntárias, por meio da musculatura esquelética.', 2),
('9af22c5f-f2e2-4112-bc80-077daa270068', 'O sistema nervoso autônomo, por sua vez, é responsável por controlar:',
  array['Funções involuntárias, como batimentos cardíacos, digestão e respiração', 'Exclusivamente movimentos voluntários', 'Apenas a visão e a audição', 'Nenhuma função relevante do organismo'], 0,
  'O sistema nervoso autônomo regula processos sem controle consciente, essenciais à homeostase.', 3),
('9af22c5f-f2e2-4112-bc80-077daa270068', 'O sistema nervoso autônomo é subdividido em sistema simpático e parassimpático, sendo o simpático geralmente responsável por:',
  array['Preparar o corpo para situações de estresse ou emergência ("luta ou fuga")', 'Promover exclusivamente o relaxamento e a digestão', 'Controlar apenas os movimentos voluntários dos braços', 'Produzir hormônios sexuais'], 0,
  'O sistema simpático ativa respostas de alerta, como aumento da frequência cardíaca, em situações de estresse.', 4),
('9af22c5f-f2e2-4112-bc80-077daa270068', 'O sistema parassimpático, em contraste com o simpático, geralmente está associado a:',
  array['Funções de relaxamento e conservação de energia, como a digestão', 'Respostas exclusivas de "luta ou fuga"', 'O aumento constante da frequência cardíaca', 'Nenhuma função relevante do organismo'], 0,
  'O sistema parassimpático promove estados de repouso e recuperação, favorecendo a digestão.', 5),

-- Sinapses (df20c43e-9e92-4cbe-bd39-2a79e44e981e)
('df20c43e-9e92-4cbe-bd39-2a79e44e981e', 'A sinapse é definida como:',
  array['A região de comunicação entre um neurônio e outra célula (neurônio, músculo ou glândula)', 'O núcleo do neurônio', 'A bainha de mielina que envolve o axônio', 'Uma organela citoplasmática presente no neurônio'], 0,
  'A sinapse é o ponto de contato funcional onde ocorre a transmissão do impulso nervoso entre células.', 1),
('df20c43e-9e92-4cbe-bd39-2a79e44e981e', 'Nas sinapses químicas, a comunicação entre os neurônios ocorre principalmente por meio da liberação de:',
  array['Neurotransmissores, substâncias químicas que atravessam a fenda sináptica', 'Impulsos elétricos diretos, sem qualquer substância química', 'Hormônios produzidos exclusivamente pelo fígado', 'Enzimas digestivas'], 0,
  'O neurônio pré-sináptico libera neurotransmissores na fenda sináptica, que se ligam a receptores da célula seguinte.', 2),
('df20c43e-9e92-4cbe-bd39-2a79e44e981e', 'A fenda sináptica corresponde a:',
  array['O pequeno espaço entre a membrana do neurônio pré-sináptico e a do neurônio pós-sináptico', 'O núcleo do neurônio', 'A extremidade do axônio, sem qualquer separação entre células', 'Uma região dentro do próprio corpo celular do neurônio'], 0,
  'A fenda sináptica é o espaço onde os neurotransmissores são liberados e se ligam aos receptores.', 3),
('df20c43e-9e92-4cbe-bd39-2a79e44e981e', 'A acetilcolina é um exemplo bem conhecido de:',
  array['Neurotransmissor, envolvido, entre outras funções, na contração muscular', 'Hormônio produzido pelo pâncreas', 'Enzima digestiva', 'Proteína estrutural da membrana celular'], 0,
  'A acetilcolina é um neurotransmissor essencial nas sinapses neuromusculares, envolvido na contração muscular.', 4),
('df20c43e-9e92-4cbe-bd39-2a79e44e981e', 'Após atuar na célula pós-sináptica, os neurotransmissores geralmente são:',
  array['Removidos da fenda sináptica, por reabsorção ou degradação enzimática', 'Permanentemente acumulados na fenda sináptica, sem qualquer remoção', 'Transformados diretamente em novas células nervosas', 'Ignorados pela célula pós-sináptica, sem qualquer efeito'], 0,
  'A remoção dos neurotransmissores encerra o sinal e permite novas transmissões subsequentes.', 5),

-- Arco reflexo (3a31c349-9503-413e-b5bb-908655f4bc6b)
('3a31c349-9503-413e-b5bb-908655f4bc6b', 'O arco reflexo é definido como:',
  array['O caminho neural percorrido por um impulso nervoso durante uma resposta reflexa, geralmente rápida e involuntária', 'Um tipo de sinapse exclusivamente química', 'A estrutura responsável pela produção de hormônios', 'Uma organela presente nos neurônios'], 0,
  'O arco reflexo é o trajeto percorrido pelo impulso nervoso em uma resposta automática, sem processamento cerebral consciente.', 1),
('3a31c349-9503-413e-b5bb-908655f4bc6b', 'Um exemplo clássico de arco reflexo é a reação de retirar rapidamente a mão ao tocar em algo muito quente, resposta que ocorre principalmente por meio:',
  array['Da medula espinhal, sem necessidade de processamento cerebral imediato', 'Exclusivamente do cérebro, com processamento consciente completo', 'Do sistema digestório', 'Dos pulmões'], 0,
  'Em muitos reflexos, a resposta motora é coordenada diretamente pela medula espinhal, tornando a reação mais rápida.', 2),
('3a31c349-9503-413e-b5bb-908655f4bc6b', 'Os principais componentes de um arco reflexo incluem, na sequência:',
  array['Receptor sensorial, neurônio sensitivo, centro de integração (geralmente medula), neurônio motor e efetor', 'Apenas o cérebro e os músculos, sem qualquer outra estrutura', 'Exclusivamente órgãos do sistema digestório', 'Apenas vasos sanguíneos'], 0,
  'O arco reflexo segue essa sequência estrutural, garantindo uma resposta rápida e automática a determinados estímulos.', 3),
('3a31c349-9503-413e-b5bb-908655f4bc6b', 'A principal vantagem evolutiva dos reflexos, mediados pelo arco reflexo, é:',
  array['Permitir respostas muito rápidas a estímulos potencialmente perigosos, sem depender do processamento cerebral mais lento', 'Tornar todas as respostas do corpo mais lentas', 'Eliminar totalmente a necessidade do sistema nervoso', 'Impedir qualquer tipo de movimento voluntário'], 0,
  'Reflexos rápidos aumentam as chances de proteção do organismo diante de estímulos nocivos.', 4),
('3a31c349-9503-413e-b5bb-908655f4bc6b', 'Embora muitos reflexos sejam processados na medula espinhal, o cérebro geralmente:',
  array['Também recebe a informação sensorial, permitindo a percepção consciente do estímulo, mesmo após a resposta reflexa', 'Nunca recebe qualquer informação sobre reflexos', 'Impede totalmente a ocorrência do reflexo', 'É a única estrutura capaz de processar qualquer tipo de reflexo'], 0,
  'Apesar de a resposta motora ocorrer via medula, o cérebro também recebe a informação, permitindo percepção consciente.', 5),

-- Sistema digestório (73124495-e312-4308-9edf-71f1edbfd5a5)
('73124495-e312-4308-9edf-71f1edbfd5a5', 'A função principal do sistema digestório é:',
  array['Processar os alimentos, transformando-os em nutrientes que possam ser absorvidos pelo organismo', 'Produzir hormônios exclusivamente', 'Realizar as trocas gasosas do corpo', 'Filtrar o sangue, eliminando resíduos metabólicos'], 0,
  'O sistema digestório quebra os alimentos em moléculas menores, absorvíveis pelo organismo.', 1),
('73124495-e312-4308-9edf-71f1edbfd5a5', 'A digestão dos alimentos tem início ainda na boca, principalmente por meio:',
  array['Da mastigação e da ação de enzimas presentes na saliva, como a amilase salivar', 'Exclusivamente da ação do suco gástrico', 'Da absorção direta de nutrientes pela língua', 'De processos que ocorrem apenas no intestino'], 0,
  'A mastigação fragmenta o alimento, enquanto a amilase salivar já inicia a quebra de carboidratos.', 2),
('73124495-e312-4308-9edf-71f1edbfd5a5', 'O estômago, órgão fundamental do sistema digestório, é responsável, entre outras funções, por:',
  array['Produzir suco gástrico, rico em ácido clorídrico e enzimas digestivas', 'Absorver a maior parte dos nutrientes dos alimentos', 'Produzir insulina diretamente', 'Realizar a filtração do sangue'], 0,
  'O estômago secreta suco gástrico, que auxilia na digestão de proteínas e na eliminação de microrganismos.', 3),
('73124495-e312-4308-9edf-71f1edbfd5a5', 'A maior parte da absorção de nutrientes provenientes dos alimentos ocorre principalmente:',
  array['No intestino delgado', 'No estômago', 'No intestino grosso', 'No esôfago'], 0,
  'O intestino delgado, com sua grande superfície de absorção, é o principal local de absorção de nutrientes.', 4),
('73124495-e312-4308-9edf-71f1edbfd5a5', 'O fígado e o pâncreas, embora não façam parte diretamente do "tubo digestivo", contribuem para a digestão ao produzir, respectivamente:',
  array['Bile (que auxilia na digestão de gorduras) e enzimas digestivas', 'Apenas hormônios sexuais', 'Exclusivamente células sanguíneas', 'Nenhuma substância relevante para a digestão'], 0,
  'O fígado produz bile, essencial para emulsificar gorduras; o pâncreas secreta enzimas digestivas importantes.', 5),

-- Sistema endócrino (2436eaec-370e-4bca-8451-cc835788a34f)
('2436eaec-370e-4bca-8451-cc835788a34f', 'O sistema endócrino é responsável principalmente por:',
  array['Produzir e secretar hormônios, que regulam diversas funções do organismo', 'Conduzir impulsos nervosos rapidamente pelo corpo', 'Realizar a digestão de alimentos', 'Filtrar o sangue de impurezas'], 0,
  'O sistema endócrino atua por meio de hormônios, liberados na corrente sanguínea, regulando processos fisiológicos.', 1),
('2436eaec-370e-4bca-8451-cc835788a34f', 'Diferentemente do sistema nervoso, que atua por impulsos elétricos rápidos, o sistema endócrino geralmente promove respostas:',
  array['Mais lentas, porém frequentemente mais duradouras', 'Instantâneas, sem qualquer atraso', 'Idênticas em velocidade às do sistema nervoso', 'Que nunca afetam o corpo de forma significativa'], 0,
  'A ação hormonal costuma ser mais lenta que a nervosa, mas seus efeitos tendem a ser mais prolongados.', 2),
('2436eaec-370e-4bca-8451-cc835788a34f', 'A insulina, hormônio produzido pelo pâncreas, tem como principal função:',
  array['Regular os níveis de glicose no sangue, facilitando sua entrada nas células', 'Controlar exclusivamente a pressão arterial', 'Produzir células sanguíneas', 'Regular a temperatura corporal'], 0,
  'A insulina permite que a glicose presente no sangue seja absorvida pelas células, reduzindo a glicemia.', 3),
('2436eaec-370e-4bca-8451-cc835788a34f', 'A glândula tireoide, importante componente do sistema endócrino, produz hormônios que regulam principalmente:',
  array['O metabolismo geral do corpo', 'Exclusivamente a digestão de gorduras', 'A produção de células nervosas', 'A filtração renal'], 0,
  'Os hormônios tireoidianos influenciam diretamente a taxa metabólica basal do organismo.', 4),
('2436eaec-370e-4bca-8451-cc835788a34f', 'Distúrbios no funcionamento das glândulas endócrinas, como a produção excessiva ou insuficiente de determinado hormônio, podem causar:',
  array['Diversas doenças e desequilíbrios fisiológicos no organismo', 'Nenhum impacto relevante para a saúde', 'Uma melhoria automática do funcionamento corporal', 'Apenas alterações estéticas, sem qualquer efeito interno'], 0,
  'O desequilíbrio hormonal pode afetar significativamente diversas funções corporais, gerando doenças como diabetes.', 5),

-- Sistema imunológico (d717ee10-b8f6-4406-8314-3d4a9c9ed7d1)
('d717ee10-b8f6-4406-8314-3d4a9c9ed7d1', 'A principal função do sistema imunológico é:',
  array['Defender o organismo contra agentes invasores, como bactérias, vírus e outros patógenos', 'Realizar a digestão dos alimentos', 'Produzir hormônios sexuais', 'Conduzir impulsos nervosos'], 0,
  'O sistema imunológico identifica e combate microrganismos e substâncias potencialmente nocivas.', 1),
('d717ee10-b8f6-4406-8314-3d4a9c9ed7d1', 'Os glóbulos brancos (leucócitos) desempenham papel fundamental no sistema imunológico ao:',
  array['Identificar e combater diretamente agentes patogênicos no organismo', 'Transportar oxigênio pelo sangue', 'Produzir a coagulação sanguínea, exclusivamente', 'Absorver nutrientes do intestino'], 0,
  'Diferentes tipos de leucócitos atuam na defesa do organismo, fagocitando patógenos ou produzindo anticorpos.', 2),
('d717ee10-b8f6-4406-8314-3d4a9c9ed7d1', 'Os anticorpos, produzidos por certas células do sistema imunológico (linfócitos B), têm como principal função:',
  array['Reconhecer e neutralizar especificamente antígenos, como os presentes em vírus e bactérias', 'Produzir energia para as células', 'Substituir totalmente a função dos glóbulos vermelhos', 'Digerir macromoléculas dentro do organismo'], 0,
  'Os anticorpos se ligam especificamente a antígenos, marcando-os para destruição ou neutralizando sua ação.', 3),
('d717ee10-b8f6-4406-8314-3d4a9c9ed7d1', 'A vacinação atua estimulando o sistema imunológico ao:',
  array['Introduzir uma versão enfraquecida, inativada ou parte de um patógeno, estimulando a produção de memória imunológica', 'Eliminar completamente a necessidade de resposta imune', 'Introduzir diretamente anticorpos prontos e permanentes, sem qualquer estímulo ao organismo', 'Enfraquecer permanentemente o sistema imunológico'], 0,
  'As vacinas treinam o sistema imunológico a reconhecer um patógeno, gerando memória para respostas futuras mais rápidas.', 4),
('d717ee10-b8f6-4406-8314-3d4a9c9ed7d1', 'Doenças autoimunes ocorrem quando o sistema imunológico:',
  array['Ataca erroneamente células e tecidos do próprio organismo', 'Deixa de funcionar completamente, sem qualquer atividade', 'Atua exclusivamente contra agentes externos, sem qualquer erro possível', 'Produz exclusivamente células sanguíneas saudáveis'], 0,
  'Em doenças autoimunes, o sistema imunológico erroneamente ataca tecidos saudáveis do próprio corpo.', 5);
