-- New "dificil" questions for portugues: 24 questions, each already
-- with its en/es translation (48 translation rows).
--
-- ids are deterministic (uuid5 of the pt-BR prompt), so running this twice
-- inserts nothing new: questions use on conflict do nothing, translations
-- on conflict do update. The translation join refuses any row whose option
-- count differs from the original (correct_index is positional).

insert into questions (id, catalog_node_id, prompt, options, correct_index, explanation, order_index, difficulty)
select v.id::uuid, v.node::uuid, v.prompt, v.options, v.correct_index, v.explanation, v.order_index, 'dificil'
from (values
  ('d10ab15e-5b80-51cf-8ed6-f707807735dc', 'bab8c7fa-d87c-40af-9233-15430973131c',
   'Assinale a alternativa em que o verbo concorda corretamente com o antecedente do pronome relativo "que":',
   array['Fui eu que resolveu o problema.', 'Fomos nós que resolveu o problema.', 'Foram eles que resolvi o problema.', 'Fui eu que resolvi o problema.'], 3,
   'Depois de "que", o verbo concorda com o antecedente do pronome — aqui, "eu": "fui eu que resolvi". Com "quem", iria para a 3ª pessoa do singular.', 100),
  ('ffc797b2-cb3f-5fe6-8de1-253106a9478b', '722ebf8c-3c85-43e1-a1c9-8469fa704939',
   'Assinale a frase correta quanto à concordância nominal.',
   array['É proibido a entrada de estranhos.', 'É proibida a entrada de estranhos.', 'É proibida entrada de estranhos.', 'Seguem anexo os documentos.'], 1,
   'Com "é proibido", o adjetivo concorda com o substantivo quando este vem determinado por artigo: "É proibida a entrada". Sem artigo, fica invariável: "É proibido entrada". E "anexo" é adjetivo, concorda com "documentos": "seguem anexos".', 101),
  ('7f9c0223-0c95-5c5c-9110-c4f11dc4e055', '68cee128-2eef-4976-9666-bd7f350ede5b',
   'Assinale a frase que respeita a regência verbal da norma-padrão.',
   array['Prefiro estudar do que trabalhar.', 'Aspiramos ao cargo de diretor.', 'Obedeça o regulamento.', 'Assisti o filme ontem.'], 1,
   '"Aspirar", no sentido de "desejar", pede a preposição "a": "aspirar ao cargo". Na norma-padrão, "assistir" (ver) pede "a" (assisti ao filme), "preferir" pede "a" (prefiro estudar a trabalhar) e "obedecer" também (obedeça ao regulamento).', 102),
  ('c2a50a05-71b6-5f01-a521-dee4b79f89e4', 'bfef7570-b2ba-4900-a90d-0f20290faa61',
   'Assinale a frase correta quanto à regência nominal.',
   array['Ela é residente à Rua das Flores.', 'O filme é preferível do que o livro.', 'Ele tem aversão com mentiras.', 'Tenho aversão a mentiras.'], 3,
   '"Aversão" rege a preposição "a" (ou "por"). "Preferível" pede "a" (preferível ao livro), e "residente" pede "em" (residente na Rua das Flores).', 103),
  ('91177660-3bd3-5452-aa5c-bbb81d3285cf', '4eea3b08-cfd1-4658-98b0-98af83d3df62',
   'Em qual frase o uso do acento grave (crase) é facultativo?',
   array['Fui à feira ontem.', 'Entreguei o convite à minha irmã.', 'Chegamos à uma hora da tarde.', 'Refiro-me à professora nova.'], 1,
   'Antes de pronome possessivo feminino a crase é facultativa: "à minha irmã" ou "a minha irmã". Nas demais é obrigatória: "ir à feira", "referir-se à professora" e na indicação de hora ("à uma hora").', 104),
  ('04eae447-3b64-554d-80e5-fb89cfe8ce90', '9ce83537-830c-4917-81f7-34ecdd190e04',
   'Em qual frase o acento grave (crase) foi usado INCORRETAMENTE?',
   array['Fiz um bolo à moda mineira.', 'Às vezes saio mais cedo.', 'Voltei à escola depois das férias.', 'Ele começou à estudar cedo.'], 3,
   'Não há crase antes de verbo, porque verbo não admite artigo: "começou a estudar". "Voltar à escola", "às vezes" e "à moda mineira" estão corretos.', 105),
  ('7e414ca4-cbf3-53a3-b448-57fc9bcdd4df', '1badbb7e-4488-4334-bbf5-6403153e2872',
   'Assinale a frase em que o acento grave (crase) foi empregado corretamente.',
   array['Comprou tudo à prazo.', 'À medida que estudava, aprendia mais.', 'Ficaram frente à frente.', 'Saiu à cavalo pela manhã.'], 1,
   '"À medida que" é locução conjuntiva feminina e leva crase. Não há crase antes de palavra masculina ("a cavalo", "a prazo") nem entre palavras repetidas ("frente a frente").', 106),
  ('1c2f1741-7721-5636-8c98-a4b24d81819a', 'dcb45577-a87e-4388-8653-846ef83e2e15',
   'Em qual frase o "a" deveria receber o acento grave (crase)?',
   array['Viajou a Portugal no verão.', 'Referiu-se a diretora da escola.', 'Começou a chover cedo.', 'Entregou o livro a ela.'], 1,
   '"Referir-se" pede a preposição "a", e "diretora" admite o artigo "a": a + a = à, então "referiu-se à diretora". Não há crase antes de pronome pessoal ("a ela"), de verbo ("a chover") nem de "Portugal", que não admite artigo feminino.', 107),
  ('07150010-f793-5e51-a879-59ca73a56e67', '282f04a3-1ac5-45ca-93d0-79ebb055890c',
   'Na frase "É preciso que você venha", a palavra "que" é classificada como:',
   array['Pronome relativo', 'Advérbio', 'Conjunção integrante', 'Preposição'], 2,
   'Introduz uma oração subordinada substantiva ("que você venha" funciona como sujeito de "é preciso"), por isso é conjunção integrante. Pronome relativo retomaria um termo anterior, o que não acontece aqui.', 108),
  ('7e966574-fdbc-5139-ae32-893e90d86d92', '7715e4c7-fa79-47be-9cdf-ea20ca7b2db6',
   'Leia: "Segundo uma instituição de pesquisa em saúde, estudos associam a privação crônica de sono a maior risco de problemas cardiovasculares; portanto, o sono deve ser tratado como questão de saúde pública." O autor sustenta sua tese principalmente por meio de:',
   array['Comparação entre dois países', 'Apelo emocional ao leitor', 'Exemplificação com uma experiência pessoal', 'Argumento de autoridade'], 3,
   'A tese se apoia na autoridade de uma instituição de pesquisa e nos estudos que ela cita, o que caracteriza o argumento de autoridade. Não há relato pessoal, comparação nem apelo à emoção.', 109),
  ('7fde73b2-752e-5876-a352-52da57e4bf1e', 'c158ce9d-b7ad-4cc6-ab9c-8ad373022d8a',
   'No período "O projeto era ambicioso; contudo, faltaram recursos para concluí-lo", o conectivo "contudo" estabelece relação de:',
   array['Explicação', 'Causa', 'Oposição (adversidade)', 'Conclusão'], 2,
   '"Contudo" equivale a "mas" e "porém": introduz uma ideia que contraria a expectativa criada pela anterior (o projeto era ambicioso, mas não foi concluído). É uma conjunção adversativa.', 110),
  ('ab1bfe60-1b7e-5116-bc15-54b6ffccf83d', '8fe5bf1c-3e9f-4d21-9a31-f993693afaac',
   '"Não é que a leitura tenha perdido espaço para as telas; o que mudou foi o suporte, e não o hábito." De acordo com o trecho:',
   array['O hábito de ler diminuiu, mas o suporte continuou o mesmo', 'As telas eliminaram o hábito da leitura', 'O hábito de ler continua; mudou o meio em que se lê', 'A leitura em papel é superior à leitura digital'], 2,
   'O trecho nega que a leitura tenha perdido espaço e afirma que só mudou o suporte (papel para tela). Não compara qualidade entre os meios nem diz que o hábito diminuiu.', 111),
  ('eed7d4ff-751e-55fe-b668-6d7263e75001', '6528814e-981a-48c0-959c-b4969beb0ebd',
   'Qual das frases expressa uma opinião, e não um fato?',
   array['O Congresso Nacional tem duas casas.', 'A capital do país fica no Distrito Federal.', 'O Brasil tem 27 unidades federativas.', 'Brasília é a cidade mais bem planejada do mundo.'], 3,
   'As demais podem ser verificadas objetivamente. "A mais bem planejada do mundo" é um juízo de valor: depende de critérios e de quem avalia, portanto é opinião.', 112),
  ('aed7dc09-60e4-5a93-a63b-fd7817795125', '5ba08373-5941-4b7f-8cd7-596108ce31d3',
   '"Em 2020, a cidade plantou 5 mil árvores; em 2021, o dobro. A meta para 2022, porém, foi reduzida à metade do plantio de 2021." Quantas árvores a meta de 2022 previa?',
   array['2,5 mil', '5 mil', '15 mil', '10 mil'], 1,
   'Em 2021 foram plantadas 10 mil árvores (o dobro de 5 mil). A meta de 2022 é metade disso: 5 mil. A resposta está no texto, mas exige encadear as duas informações.', 113),
  ('0d2fccbc-2141-5c37-8a53-867b67037fe6', '6a66a026-2fd0-4874-8216-4cdc03e6744e',
   '"Você ainda paga caro pela energia? Com o painel SolarMax, sua conta pode cair até 90%." A intenção predominante do texto é:',
   array['Informar dados científicos sobre energia solar', 'Narrar a experiência de um consumidor', 'Descrever o funcionamento de um painel', 'Persuadir o leitor a comprar o produto'], 3,
   'A pergunta dirigida ao leitor, o nome do produto e a promessa de economia são marcas do texto publicitário, cuja intenção é convencer o leitor a consumir.', 114),
  ('08cb7802-9566-5550-9d62-56deda7d5bb3', 'cb1d24d0-03e9-4017-ab28-d5fc087bcedb',
   '"Pedro chegou encharcado e deixou o guarda-chuva, ainda fechado, no canto da sala." Pode-se inferir que:',
   array['Pedro tinha um guarda-chuva, mas não o abriu', 'Não estava chovendo quando Pedro saiu', 'O guarda-chuva pertencia a outra pessoa', 'Pedro comprou o guarda-chuva no caminho'], 0,
   'Ele chegou molhado e o guarda-chuva estava "ainda fechado": logo, não o usou. As outras alternativas não têm apoio no texto (e a segunda contradiz o "encharcado").', 115),
  ('b68415f2-f35e-52d1-b261-3ef761721091', '44d0f715-a155-43e0-8b7b-96afdfaa2cdd',
   '"Plásticos descartados chegam aos oceanos e se fragmentam em microplásticos, ingeridos por peixes que, depois, chegam ao nosso prato." O tema do trecho é:',
   array['A pesca industrial', 'A reciclagem de garrafas', 'A culinária de frutos do mar', 'Os efeitos do descarte de plástico na cadeia alimentar'], 3,
   'O trecho encadeia descarte, oceano, peixes e alimentação humana: o foco é como o plástico descartado volta a nós pela cadeia alimentar. Pesca e culinária são só elementos do percurso.', 116),
  ('8857f9e9-103f-5c6c-8e2e-8e21634a8abe', 'a0caa678-52be-4ae4-9251-8f26e0ca476c',
   'A obra que marca o início do Realismo no Brasil (1881), narrada por um "defunto autor", é:',
   array['Iracema', 'Memórias Póstumas de Brás Cubas', 'O Cortiço', 'Dom Casmurro'], 1,
   'Memórias Póstumas de Brás Cubas, de Machado de Assis, é narrada por Brás Cubas depois de morto e é o marco inicial do Realismo brasileiro. O Cortiço é naturalista, Dom Casmurro é posterior (1899) e Iracema é romântica.', 117),
  ('35f9a755-1ceb-51d4-8266-fd3bb67b3d12', 'a0caa678-52be-4ae4-9251-8f26e0ca476c',
   'A Semana de Arte Moderna de 1922, marco do Modernismo brasileiro, ocorreu em:',
   array['Salvador', 'Recife', 'Rio de Janeiro', 'São Paulo'], 3,
   'A Semana foi realizada no Theatro Municipal de São Paulo, em fevereiro de 1922, com Mário de Andrade, Oswald de Andrade, Anita Malfatti e outros.', 118),
  ('9fe949dc-fd41-5588-81aa-23e693ae14fc', '7a5990be-75cb-47a5-a2c9-2ecafee8af28',
   'Assinale a alternativa em que todas as palavras estão grafadas de acordo com o Acordo Ortográfico vigente.',
   array['Ideia, heroico, voo', 'Idéia, heroico, voo', 'Idéia, heróico, vôo', 'Ideia, herói, vôo'], 0,
   'O Acordo eliminou o acento dos ditongos abertos "ei" e "oi" em paroxítonas (ideia, heroico) e o circunflexo de "oo" (voo). "Herói" mantém o acento por ser oxítona, mas "vôo" já não leva circunflexo.', 119),
  ('d69cb890-40f1-501f-afa5-284bd41125db', '3489b617-c328-4af1-bd3d-7a84dd343f79',
   'Na redação do ENEM, a Competência 5 avalia:',
   array['O uso de mecanismos de coesão', 'O domínio da norma-padrão da língua escrita', 'A compreensão da proposta e a aplicação de conceitos de várias áreas', 'A elaboração de proposta de intervenção que respeite os direitos humanos'], 3,
   'A Competência 5 avalia a proposta de intervenção para o problema discutido: agente, ação, meio, efeito e detalhamento, sempre respeitando os direitos humanos. Norma-padrão é a Competência 1, compreensão da proposta a 2 e coesão a 4.', 120),
  ('4ef9cc68-3121-5da8-af27-18192701a9e6', 'f25a58d3-8d53-4fda-abee-4ee3cb708b26',
   'Na frase "Li Machado de Assis nas férias", há uma figura de linguagem chamada:',
   array['Metáfora', 'Metonímia', 'Eufemismo', 'Catacrese'], 1,
   'Usa-se o nome do autor no lugar da obra (leu os livros de Machado de Assis). Essa substituição por relação de proximidade de sentido é a metonímia.', 121),
  ('e6b2ea2c-4ded-54ba-aa8b-83e335e68d50', '6328fd95-8026-4dc2-8cdc-40bcaf543628',
   'Na oração "Choveu muito ontem", o sujeito é:',
   array['Inexistente (oração sem sujeito)', 'Simples', 'Oculto', 'Indeterminado'], 0,
   'Verbos que indicam fenômenos da natureza, como "chover", são impessoais: não há ser a quem atribuir a ação. Por isso a oração não tem sujeito.', 122),
  ('522037db-69b5-59d8-ba93-df39aa887d28', '6328fd95-8026-4dc2-8cdc-40bcaf543628',
   'Na oração "Precisa-se de funcionários", o sujeito é:',
   array['Inexistente', 'Oculto', 'Simples ("funcionários")', 'Indeterminado'], 3,
   '"Precisar" aqui é transitivo indireto (precisar de), e com verbo transitivo indireto o "se" é índice de indeterminação do sujeito: o verbo fica no singular e o sujeito é indeterminado. "De funcionários" é objeto indireto, não sujeito.', 123)
) as v(id, node, prompt, options, correct_index, explanation, order_index)
join catalog_nodes c on c.id = v.node::uuid
on conflict (id) do nothing;

insert into question_translations (question_id, locale, prompt, options, explanation)
select v.id::uuid, v.locale, v.prompt, v.options, v.explanation
from (values
  ('d10ab15e-5b80-51cf-8ed6-f707807735dc', 'en',
   'Choose the option in which the verb correctly agrees with the antecedent of the Portuguese relative pronoun "que":',
   array['Fui eu que resolveu o problema.', 'Fomos nós que resolveu o problema.', 'Foram eles que resolvi o problema.', 'Fui eu que resolvi o problema.'],
   'After "que", the verb agrees with the pronoun''s antecedent — here "eu": "fui eu que resolvi". With "quem" it would go to the 3rd person singular.'),
  ('d10ab15e-5b80-51cf-8ed6-f707807735dc', 'es',
   'Señala la alternativa en la que el verbo concuerda correctamente con el antecedente del pronombre relativo portugués "que":',
   array['Fui eu que resolveu o problema.', 'Fomos nós que resolveu o problema.', 'Foram eles que resolvi o problema.', 'Fui eu que resolvi o problema.'],
   'Tras "que", el verbo concuerda con el antecedente del pronombre — aquí "eu": "fui eu que resolvi". Con "quem" iría a la 3.ª persona del singular.'),
  ('ffc797b2-cb3f-5fe6-8de1-253106a9478b', 'en',
   'In Portuguese, which sentence is correct in terms of noun–adjective agreement?',
   array['É proibido a entrada de estranhos.', 'É proibida a entrada de estranhos.', 'É proibida entrada de estranhos.', 'Seguem anexo os documentos.'],
   'With "é proibido", the adjective agrees with the noun when the noun has an article: "É proibida a entrada". Without the article it stays invariable: "É proibido entrada". "Anexo" is an adjective and agrees with "documentos": "seguem anexos".'),
  ('ffc797b2-cb3f-5fe6-8de1-253106a9478b', 'es',
   'En portugués, ¿qué oración es correcta en cuanto a la concordancia nominal?',
   array['É proibido a entrada de estranhos.', 'É proibida a entrada de estranhos.', 'É proibida entrada de estranhos.', 'Seguem anexo os documentos.'],
   'Con "é proibido", el adjetivo concuerda con el sustantivo cuando este lleva artículo: "É proibida a entrada". Sin artículo, queda invariable: "É proibido entrada". "Anexo" es adjetivo y concuerda con "documentos": "seguem anexos".'),
  ('7f9c0223-0c95-5c5c-9110-c4f11dc4e055', 'en',
   'In Portuguese, which sentence follows standard verb government (the preposition each verb requires)?',
   array['Prefiro estudar do que trabalhar.', 'Aspiramos ao cargo de diretor.', 'Obedeça o regulamento.', 'Assisti o filme ontem.'],
   '"Aspirar", meaning "to aspire to", requires the preposition "a": "aspirar ao cargo". In standard Portuguese, "assistir" (to watch) requires "a" (assisti ao filme), "preferir" requires "a" (prefiro estudar a trabalhar), and so does "obedecer" (obedeça ao regulamento).'),
  ('7f9c0223-0c95-5c5c-9110-c4f11dc4e055', 'es',
   'En portugués, ¿qué oración respeta el régimen verbal (la preposición que exige cada verbo) de la norma culta?',
   array['Prefiro estudar do que trabalhar.', 'Aspiramos ao cargo de diretor.', 'Obedeça o regulamento.', 'Assisti o filme ontem.'],
   '"Aspirar", con el sentido de "desear", exige la preposición "a": "aspirar ao cargo". En la norma culta, "assistir" (ver) exige "a" (assisti ao filme), "preferir" exige "a" (prefiro estudar a trabalhar) y "obedecer" también (obedeça ao regulamento).'),
  ('c2a50a05-71b6-5f01-a521-dee4b79f89e4', 'en',
   'In Portuguese, which sentence is correct in terms of noun and adjective government (the preposition each word requires)?',
   array['Ela é residente à Rua das Flores.', 'O filme é preferível do que o livro.', 'Ele tem aversão com mentiras.', 'Tenho aversão a mentiras.'],
   '"Aversão" takes the preposition "a" (or "por"). "Preferível" takes "a" (preferível ao livro), and "residente" takes "em" (residente na Rua das Flores).'),
  ('c2a50a05-71b6-5f01-a521-dee4b79f89e4', 'es',
   'En portugués, ¿qué oración es correcta en cuanto al régimen nominal (la preposición que exige cada palabra)?',
   array['Ela é residente à Rua das Flores.', 'O filme é preferível do que o livro.', 'Ele tem aversão com mentiras.', 'Tenho aversão a mentiras.'],
   '"Aversão" rige la preposición "a" (o "por"). "Preferível" exige "a" (preferível ao livro) y "residente" exige "em" (residente na Rua das Flores).'),
  ('91177660-3bd3-5452-aa5c-bbb81d3285cf', 'en',
   'In Portuguese, in which sentence is the grave accent (crase) optional?',
   array['Fui à feira ontem.', 'Entreguei o convite à minha irmã.', 'Chegamos à uma hora da tarde.', 'Refiro-me à professora nova.'],
   'Before a feminine possessive pronoun the crase is optional: "à minha irmã" or "a minha irmã". In the other sentences it is required: "ir à feira", "referir-se à professora", and when stating the time ("à uma hora").'),
  ('91177660-3bd3-5452-aa5c-bbb81d3285cf', 'es',
   'En portugués, ¿en qué oración el acento grave (crase) es opcional?',
   array['Fui à feira ontem.', 'Entreguei o convite à minha irmã.', 'Chegamos à uma hora da tarde.', 'Refiro-me à professora nova.'],
   'Antes de un pronombre posesivo femenino la crase es opcional: "à minha irmã" o "a minha irmã". En las demás es obligatoria: "ir à feira", "referir-se à professora" y al indicar la hora ("à uma hora").'),
  ('04eae447-3b64-554d-80e5-fb89cfe8ce90', 'en',
   'In Portuguese, in which sentence was the grave accent (crase) used INCORRECTLY?',
   array['Fiz um bolo à moda mineira.', 'Às vezes saio mais cedo.', 'Voltei à escola depois das férias.', 'Ele começou à estudar cedo.'],
   'There is no crase before a verb, because verbs do not take an article: "começou a estudar". "Voltar à escola", "às vezes" and "à moda mineira" are correct.'),
  ('04eae447-3b64-554d-80e5-fb89cfe8ce90', 'es',
   'En portugués, ¿en qué oración se usó INCORRECTAMENTE el acento grave (crase)?',
   array['Fiz um bolo à moda mineira.', 'Às vezes saio mais cedo.', 'Voltei à escola depois das férias.', 'Ele começou à estudar cedo.'],
   'No hay crase antes de un verbo, porque el verbo no admite artículo: "começou a estudar". "Voltar à escola", "às vezes" y "à moda mineira" son correctos.'),
  ('7e414ca4-cbf3-53a3-b448-57fc9bcdd4df', 'en',
   'In Portuguese, in which sentence was the grave accent (crase) used correctly?',
   array['Comprou tudo à prazo.', 'À medida que estudava, aprendia mais.', 'Ficaram frente à frente.', 'Saiu à cavalo pela manhã.'],
   '"À medida que" is a feminine conjunctive phrase and takes the crase. There is no crase before a masculine word ("a cavalo", "a prazo") or between repeated words ("frente a frente").'),
  ('7e414ca4-cbf3-53a3-b448-57fc9bcdd4df', 'es',
   'En portugués, ¿en qué oración se empleó correctamente el acento grave (crase)?',
   array['Comprou tudo à prazo.', 'À medida que estudava, aprendia mais.', 'Ficaram frente à frente.', 'Saiu à cavalo pela manhã.'],
   '"À medida que" es una locución conjuntiva femenina y lleva crase. No hay crase antes de palabra masculina ("a cavalo", "a prazo") ni entre palabras repetidas ("frente a frente").'),
  ('1c2f1741-7721-5636-8c98-a4b24d81819a', 'en',
   'In Portuguese, in which sentence should the "a" take the grave accent (crase)?',
   array['Viajou a Portugal no verão.', 'Referiu-se a diretora da escola.', 'Começou a chover cedo.', 'Entregou o livro a ela.'],
   '"Referir-se" requires the preposition "a", and "diretora" takes the article "a": a + a = à, so "referiu-se à diretora". There is no crase before a personal pronoun ("a ela"), a verb ("a chover") or "Portugal", which takes no feminine article.'),
  ('1c2f1741-7721-5636-8c98-a4b24d81819a', 'es',
   'En portugués, ¿en qué oración la "a" debería llevar el acento grave (crase)?',
   array['Viajou a Portugal no verão.', 'Referiu-se a diretora da escola.', 'Começou a chover cedo.', 'Entregou o livro a ela.'],
   '"Referir-se" exige la preposición "a", y "diretora" admite el artículo "a": a + a = à, así que "referiu-se à diretora". No hay crase antes de pronombre personal ("a ela"), de verbo ("a chover") ni de "Portugal", que no admite artículo femenino.'),
  ('07150010-f793-5e51-a879-59ca73a56e67', 'en',
   'In the Portuguese sentence "É preciso que você venha" ("You need to come"), the word "que" is classified as:',
   array['A relative pronoun', 'An adverb', 'A complementizer (conjunção integrante)', 'A preposition'],
   'It introduces a noun clause ("que você venha" is the subject of "é preciso"), so it is a complementizer, which Portuguese grammar calls "conjunção integrante". A relative pronoun would refer back to an earlier term, which does not happen here.'),
  ('07150010-f793-5e51-a879-59ca73a56e67', 'es',
   'En la oración portuguesa "É preciso que você venha" ("Es necesario que vengas"), la palabra "que" se clasifica como:',
   array['Pronombre relativo', 'Adverbio', 'Conjunción completiva (conjunção integrante)', 'Preposición'],
   'Introduce una oración subordinada sustantiva ("que você venha" es el sujeto de "é preciso"), por eso es una conjunción completiva, que la gramática portuguesa llama "conjunção integrante". Un pronombre relativo retomaría un término anterior, lo que no ocurre aquí.'),
  ('7e966574-fdbc-5139-ae32-893e90d86d92', 'en',
   'Read: "According to a health research institution, studies link chronic sleep deprivation to a higher risk of cardiovascular problems; therefore, sleep should be treated as a public health issue." The author supports the thesis mainly through:',
   array['A comparison between two countries', 'An emotional appeal to the reader', 'An example from personal experience', 'An argument from authority'],
   'The thesis rests on the authority of a research institution and the studies it cites, which is an argument from authority. There is no personal account, comparison or appeal to emotion.'),
  ('7e966574-fdbc-5139-ae32-893e90d86d92', 'es',
   'Lee: "Según una institución de investigación en salud, los estudios asocian la privación crónica de sueño a un mayor riesgo de problemas cardiovasculares; por lo tanto, el sueño debe tratarse como una cuestión de salud pública." El autor sostiene su tesis principalmente mediante:',
   array['Una comparación entre dos países', 'Un llamado emocional al lector', 'Un ejemplo de experiencia personal', 'Un argumento de autoridad'],
   'La tesis se apoya en la autoridad de una institución de investigación y en los estudios que cita, lo que caracteriza el argumento de autoridad. No hay relato personal, comparación ni llamado a la emoción.'),
  ('7fde73b2-752e-5876-a352-52da57e4bf1e', 'en',
   'In the sentence "The project was ambitious; however, there were not enough resources to finish it", the connective "however" expresses a relation of:',
   array['Explanation', 'Cause', 'Contrast (opposition)', 'Conclusion'],
   '"However" works like "but": it introduces an idea that goes against the expectation set by the previous one (the project was ambitious, but it was not finished). It is an adversative connective.'),
  ('7fde73b2-752e-5876-a352-52da57e4bf1e', 'es',
   'En la oración "El proyecto era ambicioso; sin embargo, faltaron recursos para concluirlo", el conector "sin embargo" establece una relación de:',
   array['Explicación', 'Causa', 'Oposición (adversidad)', 'Conclusión'],
   '"Sin embargo" equivale a "pero": introduce una idea que contradice la expectativa creada por la anterior (el proyecto era ambicioso, pero no se concluyó). Es un conector adversativo.'),
  ('ab1bfe60-1b7e-5116-bc15-54b6ffccf83d', 'en',
   '"It is not that reading has lost ground to screens; what changed was the medium, not the habit." According to the passage:',
   array['The reading habit has declined, but the medium stayed the same', 'Screens have eliminated the reading habit', 'The reading habit continues; what changed is the medium people read on', 'Reading on paper is better than reading on screens'],
   'The passage denies that reading has lost ground and states that only the medium changed (from paper to screen). It does not compare the quality of the media or say the habit declined.'),
  ('ab1bfe60-1b7e-5116-bc15-54b6ffccf83d', 'es',
   '"No es que la lectura haya perdido espacio frente a las pantallas; lo que cambió fue el soporte, y no el hábito." Según el fragmento:',
   array['El hábito de leer disminuyó, pero el soporte siguió siendo el mismo', 'Las pantallas eliminaron el hábito de la lectura', 'El hábito de leer continúa; cambió el medio en el que se lee', 'La lectura en papel es superior a la lectura digital'],
   'El fragmento niega que la lectura haya perdido espacio y afirma que solo cambió el soporte (del papel a la pantalla). No compara la calidad de los medios ni dice que el hábito haya disminuido.'),
  ('eed7d4ff-751e-55fe-b668-6d7263e75001', 'en',
   'Which sentence expresses an opinion rather than a fact?',
   array['The National Congress has two houses.', 'The country''s capital is in the Federal District.', 'Brazil has 27 federative units.', 'Brasília is the best-planned city in the world.'],
   'The others can be checked objectively. "The best-planned city in the world" is a value judgment: it depends on criteria and on who is judging, so it is an opinion.'),
  ('eed7d4ff-751e-55fe-b668-6d7263e75001', 'es',
   '¿Cuál de las oraciones expresa una opinión y no un hecho?',
   array['El Congreso Nacional tiene dos cámaras.', 'La capital del país está en el Distrito Federal.', 'Brasil tiene 27 unidades federativas.', 'Brasilia es la ciudad mejor planificada del mundo.'],
   'Las demás pueden verificarse objetivamente. "La mejor planificada del mundo" es un juicio de valor: depende de los criterios y de quién evalúa, por lo tanto es una opinión.'),
  ('aed7dc09-60e4-5a93-a63b-fd7817795125', 'en',
   '"In 2020, the city planted 5,000 trees; in 2021, twice as many. The 2022 target, however, was cut to half of what was planted in 2021." How many trees did the 2022 target call for?',
   array['2,500', '5,000', '15,000', '10,000'],
   'In 2021, 10,000 trees were planted (twice 5,000). The 2022 target is half of that: 5,000. The answer is in the text, but it requires linking both pieces of information.'),
  ('aed7dc09-60e4-5a93-a63b-fd7817795125', 'es',
   '"En 2020, la ciudad plantó 5 mil árboles; en 2021, el doble. La meta para 2022, sin embargo, se redujo a la mitad de lo plantado en 2021." ¿Cuántos árboles preveía la meta de 2022?',
   array['2,5 mil', '5 mil', '15 mil', '10 mil'],
   'En 2021 se plantaron 10 mil árboles (el doble de 5 mil). La meta de 2022 es la mitad: 5 mil. La respuesta está en el texto, pero exige encadenar las dos informaciones.'),
  ('0d2fccbc-2141-5c37-8a53-867b67037fe6', 'en',
   '"Are you still paying too much for electricity? With the SolarMax panel, your bill can drop by up to 90%." The main purpose of the text is to:',
   array['Report scientific data on solar energy', 'Narrate a consumer''s experience', 'Describe how a panel works', 'Persuade the reader to buy the product'],
   'The question addressed to the reader, the product name and the promise of savings are marks of advertising, whose purpose is to convince the reader to buy.'),
  ('0d2fccbc-2141-5c37-8a53-867b67037fe6', 'es',
   '"¿Todavía pagas caro por la energía? Con el panel SolarMax, tu factura puede bajar hasta un 90 %." La intención predominante del texto es:',
   array['Informar datos científicos sobre la energía solar', 'Narrar la experiencia de un consumidor', 'Describir el funcionamiento de un panel', 'Persuadir al lector de comprar el producto'],
   'La pregunta dirigida al lector, el nombre del producto y la promesa de ahorro son marcas del texto publicitario, cuya intención es convencer al lector de consumir.'),
  ('08cb7802-9566-5550-9d62-56deda7d5bb3', 'en',
   '"Pedro arrived soaking wet and left his umbrella, still closed, in the corner of the room." One can infer that:',
   array['Pedro had an umbrella but did not open it', 'It was not raining when Pedro left', 'The umbrella belonged to someone else', 'Pedro bought the umbrella on the way'],
   'He arrived wet and the umbrella was "still closed", so he did not use it. The other options have no support in the text (and the second contradicts "soaking wet").'),
  ('08cb7802-9566-5550-9d62-56deda7d5bb3', 'es',
   '"Pedro llegó empapado y dejó el paraguas, todavía cerrado, en el rincón de la sala." Se puede inferir que:',
   array['Pedro tenía un paraguas, pero no lo abrió', 'No llovía cuando Pedro salió', 'El paraguas pertenecía a otra persona', 'Pedro compró el paraguas en el camino'],
   'Llegó mojado y el paraguas estaba "todavía cerrado": por lo tanto, no lo usó. Las demás opciones no tienen apoyo en el texto (y la segunda contradice el "empapado").'),
  ('b68415f2-f35e-52d1-b261-3ef761721091', 'en',
   '"Discarded plastics reach the oceans and break down into microplastics, which are eaten by fish that later end up on our plates." The topic of the passage is:',
   array['Industrial fishing', 'Bottle recycling', 'Seafood cooking', 'The effects of plastic waste on the food chain'],
   'The passage links waste, ocean, fish and human food: the focus is on how discarded plastic comes back to us through the food chain. Fishing and cooking are only steps along the way.'),
  ('b68415f2-f35e-52d1-b261-3ef761721091', 'es',
   '"Los plásticos desechados llegan a los océanos y se fragmentan en microplásticos, que ingieren peces que luego llegan a nuestro plato." El tema del fragmento es:',
   array['La pesca industrial', 'El reciclaje de botellas', 'La cocina de mariscos', 'Los efectos del desecho de plástico en la cadena alimentaria'],
   'El fragmento encadena desecho, océano, peces y alimentación humana: el foco es cómo el plástico desechado vuelve a nosotros por la cadena alimentaria. La pesca y la cocina son solo etapas del recorrido.'),
  ('8857f9e9-103f-5c6c-8e2e-8e21634a8abe', 'en',
   'The work that marks the beginning of Realism in Brazil (1881), narrated by a "dead author", is:',
   array['Iracema', 'Memórias Póstumas de Brás Cubas', 'O Cortiço', 'Dom Casmurro'],
   'Memórias Póstumas de Brás Cubas (The Posthumous Memoirs of Brás Cubas), by Machado de Assis, is narrated by Brás Cubas after his death and marks the start of Brazilian Realism. O Cortiço is naturalist, Dom Casmurro came later (1899) and Iracema is Romantic.'),
  ('8857f9e9-103f-5c6c-8e2e-8e21634a8abe', 'es',
   'La obra que marca el inicio del Realismo en Brasil (1881), narrada por un "difunto autor", es:',
   array['Iracema', 'Memórias Póstumas de Brás Cubas', 'O Cortiço', 'Dom Casmurro'],
   'Memórias Póstumas de Brás Cubas (Memorias póstumas de Blas Cubas), de Machado de Assis, está narrada por Brás Cubas después de muerto y es el hito inicial del Realismo brasileño. O Cortiço es naturalista, Dom Casmurro es posterior (1899) y Iracema es romántica.'),
  ('35f9a755-1ceb-51d4-8266-fd3bb67b3d12', 'en',
   'The 1922 Modern Art Week, a landmark of Brazilian Modernism, took place in:',
   array['Salvador', 'Recife', 'Rio de Janeiro', 'São Paulo'],
   'The Week was held at the Theatro Municipal in São Paulo in February 1922, with Mário de Andrade, Oswald de Andrade, Anita Malfatti and others.'),
  ('35f9a755-1ceb-51d4-8266-fd3bb67b3d12', 'es',
   'La Semana de Arte Moderno de 1922, hito del Modernismo brasileño, tuvo lugar en:',
   array['Salvador', 'Recife', 'Río de Janeiro', 'São Paulo'],
   'La Semana se realizó en el Theatro Municipal de São Paulo, en febrero de 1922, con Mário de Andrade, Oswald de Andrade, Anita Malfatti y otros.'),
  ('9fe949dc-fd41-5588-81aa-23e693ae14fc', 'en',
   'In Portuguese, which option has all words spelled according to the current Spelling Agreement?',
   array['Ideia, heroico, voo', 'Idéia, heroico, voo', 'Idéia, heróico, vôo', 'Ideia, herói, vôo'],
   'The Agreement dropped the accent on the open diphthongs "ei" and "oi" in paroxytone words (ideia, heroico) and the circumflex on "oo" (voo). "Herói" keeps its accent because the stress falls on the last syllable, but "vôo" no longer takes a circumflex.'),
  ('9fe949dc-fd41-5588-81aa-23e693ae14fc', 'es',
   'En portugués, ¿en qué opción todas las palabras están escritas según el Acuerdo Ortográfico vigente?',
   array['Ideia, heroico, voo', 'Idéia, heroico, voo', 'Idéia, heróico, vôo', 'Ideia, herói, vôo'],
   'El Acuerdo eliminó la tilde de los diptongos abiertos "ei" y "oi" en palabras llanas (ideia, heroico) y el circunflejo de "oo" (voo). "Herói" mantiene la tilde por ser aguda, pero "vôo" ya no lleva circunflejo.'),
  ('d69cb890-40f1-501f-afa5-284bd41125db', 'en',
   'In the ENEM essay, Competency 5 assesses:',
   array['The use of cohesive devices', 'Command of standard written Portuguese', 'Understanding of the prompt and use of concepts from different fields', 'An intervention proposal that respects human rights'],
   'Competency 5 assesses the intervention proposal for the problem discussed: agent, action, means, effect and detail, always respecting human rights. Standard language is Competency 1, understanding the prompt is 2 and cohesion is 4.'),
  ('d69cb890-40f1-501f-afa5-284bd41125db', 'es',
   'En la redacción del ENEM, la Competencia 5 evalúa:',
   array['El uso de mecanismos de cohesión', 'El dominio de la norma culta del portugués escrito', 'La comprensión de la propuesta y el uso de conceptos de varias áreas', 'La elaboración de una propuesta de intervención que respete los derechos humanos'],
   'La Competencia 5 evalúa la propuesta de intervención para el problema discutido: agente, acción, medio, efecto y detalle, siempre respetando los derechos humanos. La norma culta es la Competencia 1, la comprensión de la propuesta la 2 y la cohesión la 4.'),
  ('4ef9cc68-3121-5da8-af27-18192701a9e6', 'en',
   'The sentence "I read Machado de Assis over the holidays" contains a figure of speech called:',
   array['Metaphor', 'Metonymy', 'Euphemism', 'Catachresis'],
   'The author''s name stands for his work (the speaker read Machado de Assis''s books). This substitution based on a close association of meaning is metonymy.'),
  ('4ef9cc68-3121-5da8-af27-18192701a9e6', 'es',
   'La oración "Leí a Machado de Assis en las vacaciones" contiene una figura retórica llamada:',
   array['Metáfora', 'Metonimia', 'Eufemismo', 'Catacresis'],
   'Se usa el nombre del autor en lugar de su obra (leyó los libros de Machado de Assis). Esa sustitución por una relación de proximidad de sentido es la metonimia.'),
  ('e6b2ea2c-4ded-54ba-aa8b-83e335e68d50', 'en',
   'In the Portuguese clause "Choveu muito ontem" ("It rained a lot yesterday"), the subject is:',
   array['Nonexistent (a subjectless clause)', 'Simple', 'Implied (oculto)', 'Indeterminate'],
   'Verbs for natural phenomena, such as "chover" (to rain), are impersonal: there is no one to attribute the action to. So the Portuguese clause has no subject (English needs a dummy "it", Portuguese does not).'),
  ('e6b2ea2c-4ded-54ba-aa8b-83e335e68d50', 'es',
   'En la oración portuguesa "Choveu muito ontem" ("Llovió mucho ayer"), el sujeto es:',
   array['Inexistente (oración sin sujeto)', 'Simple', 'Tácito (oculto)', 'Indeterminado'],
   'Los verbos que indican fenómenos de la naturaleza, como "chover" (llover), son impersonales: no hay a quién atribuir la acción. Por eso la oración no tiene sujeto.'),
  ('522037db-69b5-59d8-ba93-df39aa887d28', 'en',
   'In the Portuguese clause "Precisa-se de funcionários" ("Employees needed"), the subject is:',
   array['Nonexistent', 'Implied (oculto)', 'Simple ("funcionários")', 'Indeterminate'],
   'Here "precisar" is used with a preposition ("precisar de"), and with such verbs "se" marks an indeterminate subject: the verb stays singular and the subject is indeterminate. "De funcionários" is an indirect object, not the subject.'),
  ('522037db-69b5-59d8-ba93-df39aa887d28', 'es',
   'En la oración portuguesa "Precisa-se de funcionários" ("Se necesitan empleados"), el sujeto es:',
   array['Inexistente', 'Tácito (oculto)', 'Simple ("funcionários")', 'Indeterminado'],
   'Aquí "precisar" es transitivo indirecto ("precisar de"), y con verbo transitivo indirecto el "se" indica sujeto indeterminado: el verbo queda en singular y el sujeto es indeterminado. "De funcionários" es objeto indirecto, no sujeto.')
) as v(id, locale, prompt, options, explanation)
join questions q
  on q.id = v.id::uuid
 and cardinality(q.options) = cardinality(v.options)
on conflict (question_id, locale) do update
  set prompt = excluded.prompt,
      options = excluded.options,
      explanation = excluded.explanation;
