-- Biologia — Citologia (14 leaves, 5 questões cada)
insert into questions (catalog_node_id, prompt, options, correct_index, explanation, order_index) values
-- Difusão (953f689f-2c4f-47c2-9b7d-afce1fd27e7e)
('953f689f-2c4f-47c2-9b7d-afce1fd27e7e', 'A difusão simples é um tipo de transporte pela membrana celular caracterizado por:',
  array['Movimento de substâncias a favor do gradiente de concentração, sem gasto de energia', 'Movimento de substâncias contra o gradiente de concentração, com gasto de energia', 'Necessidade obrigatória de proteínas carreadoras', 'Ocorrência exclusiva de água através da membrana'], 0,
  'Na difusão simples, moléculas pequenas e/ou lipossolúveis atravessam a membrana espontaneamente, sem consumo de energia.', 1),
('953f689f-2c4f-47c2-9b7d-afce1fd27e7e', 'O oxigênio e o gás carbônico atravessam a membrana plasmática principalmente por:',
  array['Difusão simples, devido ao seu pequeno tamanho e caráter apolar', 'Transporte ativo, com gasto de ATP', 'Endocitose', 'Exocitose'], 0,
  'Gases como O₂ e CO₂ são pequenos e apolares, atravessando a bicamada lipídica livremente por difusão simples.', 2),
('953f689f-2c4f-47c2-9b7d-afce1fd27e7e', 'A difusão facilitada se diferencia da difusão simples por:',
  array['Utilizar proteínas de membrana (canais ou carreadoras) para auxiliar a passagem das substâncias', 'Ocorrer contra o gradiente de concentração', 'Exigir gasto direto de energia (ATP)', 'Ser exclusiva de macromoléculas'], 0,
  'Na difusão facilitada, proteínas de membrana auxiliam a passagem de substâncias, ainda a favor do gradiente.', 3),
('953f689f-2c4f-47c2-9b7d-afce1fd27e7e', 'A velocidade da difusão de uma substância através da membrana é influenciada, entre outros fatores, por:',
  array['A diferença de concentração entre os dois lados da membrana (gradiente)', 'Exclusivamente a cor da substância', 'A ausência total de energia celular', 'O tamanho do núcleo celular'], 0,
  'Quanto maior o gradiente de concentração, mais rápida tende a ser a difusão, até que o equilíbrio seja atingido.', 4),
('953f689f-2c4f-47c2-9b7d-afce1fd27e7e', 'A glicose, apesar de ser uma molécula relativamente grande e polar, geralmente entra nas células por:',
  array['Difusão facilitada, com auxílio de proteínas transportadoras específicas', 'Difusão simples, sem qualquer auxílio', 'Exclusivamente por fagocitose', 'Não consegue atravessar a membrana celular'], 0,
  'Por ser polar e relativamente grande, a glicose depende de proteínas transportadoras específicas (como GLUT).', 5),

-- Osmose (b6e6a404-ea29-44dd-a791-84fe0afd6075)
('b6e6a404-ea29-44dd-a791-84fe0afd6075', 'A osmose é definida como a passagem de:',
  array['Água através de uma membrana semipermeável, do meio menos concentrado para o mais concentrado em soluto', 'Solutos através de uma membrana, do meio mais concentrado para o menos concentrado', 'Íons através de canais proteicos, com gasto de energia', 'Macromoléculas por meio de vesículas'], 0,
  'Na osmose, a água se move através da membrana no sentido de equilibrar as concentrações de soluto entre os dois meios.', 1),
('b6e6a404-ea29-44dd-a791-84fe0afd6075', 'Uma célula colocada em uma solução hipertônica (mais concentrada que seu interior) tende a:',
  array['Perder água para o meio externo, podendo murchar (crenar ou plasmolisar)', 'Ganhar água do meio externo, podendo inchar e estourar', 'Não sofrer qualquer alteração de volume', 'Ganhar solutos diretamente, sem qualquer movimento de água'], 0,
  'Em meio hipertônico, a água sai da célula por osmose, podendo causar sua desidratação.', 2),
('b6e6a404-ea29-44dd-a791-84fe0afd6075', 'Uma hemácia colocada em água pura (meio hipotônico) tende a:',
  array['Ganhar água e sofrer hemólise (rompimento da membrana)', 'Perder água e murchar', 'Permanecer completamente inalterada', 'Perder solutos imediatamente'], 0,
  'Em meio hipotônico, a água entra na célula por osmose, podendo causar a hemólise, já que a hemácia não tem parede celular.', 3),
('b6e6a404-ea29-44dd-a791-84fe0afd6075', 'Em células vegetais, a presença da parede celular impede que a célula:',
  array['Estoure ao absorver água em excesso, gerando apenas a pressão de turgor', 'Perca água por osmose em qualquer situação', 'Realize a fotossíntese normalmente', 'Sofra qualquer tipo de osmose'], 0,
  'A parede celular rígida resiste à pressão gerada pela entrada de água, gerando a turgescência sem romper a célula.', 4),
('b6e6a404-ea29-44dd-a791-84fe0afd6075', 'O processo de osmose é fundamental para explicar, por exemplo, por que:',
  array['Frutas e verduras murcham quando expostas a soluções muito concentradas de sal ou açúcar', 'Plantas nunca perdem água para o ambiente', 'Água nunca se move através de membranas celulares', 'Osmose não tem relação com a concentração de solutos'], 0,
  'Ao serem expostas a meios hipertônicos, as células perdem água por osmose, causando o murchamento.', 5),

-- Transporte ativo (01231beb-4568-4adf-81ec-cd7f6625ac75)
('01231beb-4568-4adf-81ec-cd7f6625ac75', 'O transporte ativo é caracterizado por:',
  array['Mover substâncias contra o gradiente de concentração, com gasto de energia (ATP)', 'Mover substâncias a favor do gradiente de concentração, sem gasto de energia', 'Ocorrer exclusivamente com moléculas de água', 'Não envolver proteínas de membrana'], 0,
  'Diferentemente da difusão, o transporte ativo movimenta substâncias contra o gradiente, exigindo ATP.', 1),
('01231beb-4568-4adf-81ec-cd7f6625ac75', 'A bomba de sódio e potássio (Na⁺/K⁺-ATPase) é um exemplo clássico de:',
  array['Transporte ativo, que mantém o gradiente iônico das células', 'Difusão simples', 'Osmose', 'Fagocitose'], 0,
  'Essa bomba utiliza ATP para transportar sódio para fora e potássio para dentro da célula, contra seus gradientes.', 2),
('01231beb-4568-4adf-81ec-cd7f6625ac75', 'A bomba de sódio e potássio transporta, a cada ciclo, tipicamente:',
  array['3 íons sódio para fora e 2 íons potássio para dentro da célula', '2 íons sódio para fora e 3 íons potássio para dentro', 'Apenas água, sem qualquer íon', 'Glicose exclusivamente'], 0,
  'A proporção clássica é de 3 Na⁺ para fora e 2 K⁺ para dentro, a cada molécula de ATP consumida.', 3),
('01231beb-4568-4adf-81ec-cd7f6625ac75', 'O transporte ativo é essencial para funções celulares como:',
  array['A manutenção do potencial de membrana em células nervosas e musculares', 'A eliminação total da necessidade de energia celular', 'O impedimento de qualquer troca com o meio externo', 'A produção direta de proteínas'], 0,
  'O gradiente iônico mantido pelo transporte ativo é essencial para impulsos nervosos e contrações musculares.', 4),
('01231beb-4568-4adf-81ec-cd7f6625ac75', 'Sem o fornecimento contínuo de energia (ATP), o transporte ativo em uma célula:',
  array['Seria interrompido, comprometendo o equilíbrio iônico celular', 'Continuaria normalmente, sem qualquer prejuízo', 'Se tornaria ainda mais eficiente', 'Não tem qualquer relação com o ATP'], 0,
  'Como depende diretamente de energia, a interrupção do ATP paralisa o transporte ativo.', 5),

-- Endocitose (a0579b4d-2452-400c-b231-5657f7ae4cd1)
('a0579b4d-2452-400c-b231-5657f7ae4cd1', 'A endocitose é o processo pelo qual a célula:',
  array['Engloba substâncias do meio externo, formando uma vesícula a partir da membrana plasmática', 'Expulsa substâncias para o meio externo', 'Realiza a divisão celular', 'Sintetiza novas proteínas'], 0,
  'Na endocitose, a membrana plasmática se invagina, formando uma vesícula que é internalizada pela célula.', 1),
('a0579b4d-2452-400c-b231-5657f7ae4cd1', 'A fagocitose, um tipo de endocitose, é caracterizada pela captura de:',
  array['Partículas sólidas relativamente grandes, como bactérias ou restos celulares', 'Apenas líquidos e solutos dissolvidos', 'Apenas moléculas de água', 'Nenhum tipo de material externo'], 0,
  'Na fagocitose, a célula engloba partículas sólidas maiores, como leucócitos fazem no combate a patógenos.', 2),
('a0579b4d-2452-400c-b231-5657f7ae4cd1', 'A pinocitose, outro tipo de endocitose, é caracterizada pela captura de:',
  array['Líquidos e substâncias dissolvidas no meio extracelular', 'Apenas partículas sólidas grandes', 'Exclusivamente bactérias', 'Nenhum tipo de substância'], 0,
  'Na pinocitose, a célula "bebe" pequenas quantidades de líquido extracelular, envolvendo-o em vesículas.', 3),
('a0579b4d-2452-400c-b231-5657f7ae4cd1', 'Os leucócitos (glóbulos brancos) utilizam a fagocitose principalmente para:',
  array['Combater microrganismos invasores, como bactérias', 'Produzir hormônios', 'Realizar a fotossíntese', 'Armazenar energia na forma de gordura'], 0,
  'A fagocitose é um mecanismo de defesa fundamental, no qual leucócitos englobam e destroem patógenos.', 4),
('a0579b4d-2452-400c-b231-5657f7ae4cd1', 'A endocitose mediada por receptor se caracteriza por:',
  array['Envolver proteínas receptoras específicas na membrana, que reconhecem determinadas moléculas antes da internalização', 'Ocorrer de forma completamente aleatória, sem qualquer especificidade', 'Não envolver a formação de vesículas', 'Ser idêntica à exocitose'], 0,
  'Receptores específicos na membrana se ligam a determinadas moléculas, aumentando a seletividade da internalização.', 5),

-- Exocitose (2cc4c95d-0ae8-43ea-9bc3-94d735b6ffd2)
('2cc4c95d-0ae8-43ea-9bc3-94d735b6ffd2', 'A exocitose é o processo pelo qual a célula:',
  array['Expulsa substâncias para o meio externo, por meio da fusão de vesículas com a membrana plasmática', 'Engloba substâncias do meio externo', 'Realiza a divisão celular', 'Absorve água por osmose'], 0,
  'Na exocitose, vesículas com substâncias se fundem à membrana plasmática, liberando seu conteúdo para fora.', 1),
('2cc4c95d-0ae8-43ea-9bc3-94d735b6ffd2', 'A exocitose é o mecanismo responsável, por exemplo, pela liberação de:',
  array['Neurotransmissores nas sinapses nervosas', 'Oxigênio diretamente do núcleo celular', 'DNA para fora do núcleo continuamente', 'Nenhuma substância relevante para o organismo'], 0,
  'Nas sinapses, os neurotransmissores armazenados em vesículas são liberados no espaço sináptico por exocitose.', 2),
('2cc4c95d-0ae8-43ea-9bc3-94d735b6ffd2', 'Além dos neurotransmissores, a exocitose também é responsável pela secreção de:',
  array['Hormônios e enzimas digestivas produzidos por diversas glândulas', 'Apenas resíduos metabólicos tóxicos', 'Exclusivamente gases respiratórios', 'Nenhuma substância útil ao organismo'], 0,
  'Muitas glândulas utilizam a exocitose para secretar hormônios, enzimas e outras substâncias importantes.', 3),
('2cc4c95d-0ae8-43ea-9bc3-94d735b6ffd2', 'A exocitose e a endocitose são processos que, em conjunto, contribuem para:',
  array['A renovação e o equilíbrio da membrana plasmática, além do transporte de substâncias', 'A destruição definitiva da membrana plasmática', 'A eliminação completa do citoplasma celular', 'A parada total do metabolismo celular'], 0,
  'Ao adicionar e remover porções de membrana, esses processos ajudam a manter o equilíbrio da membrana plasmática.', 4),
('2cc4c95d-0ae8-43ea-9bc3-94d735b6ffd2', 'O complexo golgiense está diretamente relacionado à exocitose por:',
  array['Empacotar substâncias em vesículas que serão posteriormente secretadas pela célula', 'Produzir energia na forma de ATP', 'Realizar a duplicação do material genético', 'Não ter qualquer relação com o processo de secreção celular'], 0,
  'O complexo golgiense processa e empacota moléculas em vesículas, direcionadas para exocitose.', 5),

-- Núcleo (3b5d566c-f5a1-4d2a-a367-4e10fd9aee10)
('3b5d566c-f5a1-4d2a-a367-4e10fd9aee10', 'O núcleo celular, presente nas células eucarióticas, tem como principal função:',
  array['Armazenar e proteger o material genético (DNA) da célula', 'Produzir energia na forma de ATP', 'Realizar a digestão intracelular', 'Sintetizar diretamente proteínas, sem qualquer intermediário'], 0,
  'O núcleo abriga o DNA, controlando as atividades celulares e a transmissão da informação genética.', 1),
('3b5d566c-f5a1-4d2a-a367-4e10fd9aee10', 'O envoltório nuclear, que separa o núcleo do citoplasma, é caracterizado por possuir:',
  array['Poros nucleares, que permitem a troca controlada de substâncias', 'Uma estrutura totalmente impermeável, sem qualquer abertura', 'Ausência total de membrana', 'Uma única camada lipídica, ao invés de duas'], 0,
  'Os poros nucleares regulam a passagem de moléculas, como RNA e proteínas, entre núcleo e citoplasma.', 2),
('3b5d566c-f5a1-4d2a-a367-4e10fd9aee10', 'O nucléolo, estrutura presente dentro do núcleo, é responsável principalmente pela:',
  array['Produção de ribossomos', 'Produção de energia celular', 'Digestão de macromoléculas', 'Síntese de lipídios de membrana'], 0,
  'O nucléolo é o local de síntese e montagem dos ribossomos, essenciais para a produção de proteínas.', 3),
('3b5d566c-f5a1-4d2a-a367-4e10fd9aee10', 'A cromatina, presente no interior do núcleo, corresponde a:',
  array['O DNA associado a proteínas, em sua forma descondensada (fora da divisão celular)', 'Uma estrutura formada exclusivamente por proteínas, sem DNA', 'O envoltório nuclear', 'Uma organela citoplasmática independente do núcleo'], 0,
  'A cromatina é o material genético associado a proteínas histonas, em forma descondensada.', 4),
('3b5d566c-f5a1-4d2a-a367-4e10fd9aee10', 'Durante a divisão celular, a cromatina se condensa, formando estruturas visíveis ao microscópio chamadas de:',
  array['Cromossomos', 'Ribossomos', 'Mitocôndrias', 'Lisossomos'], 0,
  'Antes da divisão celular, a cromatina se condensa em cromossomos, facilitando a distribuição do material genético.', 5),

-- Ribossomos (227e8f6a-30c1-4f98-8258-caad221e1b9b)
('227e8f6a-30c1-4f98-8258-caad221e1b9b', 'A principal função dos ribossomos, presentes em todas as células vivas, é:',
  array['Realizar a síntese de proteínas', 'Produzir energia na forma de ATP', 'Armazenar o material genético', 'Realizar a digestão intracelular'], 0,
  'Os ribossomos traduzem o RNA mensageiro em cadeias de aminoácidos, formando proteínas.', 1),
('227e8f6a-30c1-4f98-8258-caad221e1b9b', 'Os ribossomos podem ser encontrados na célula:',
  array['Livres no citoplasma ou aderidos ao retículo endoplasmático rugoso', 'Apenas dentro do núcleo celular', 'Exclusivamente dentro das mitocôndrias', 'Apenas fora da célula'], 0,
  'Ribossomos livres sintetizam proteínas para o citoplasma; os aderidos ao retículo rugoso produzem proteínas para secreção ou organelas específicas.', 2),
('227e8f6a-30c1-4f98-8258-caad221e1b9b', 'Diferentemente de outras organelas, os ribossomos são caracterizados por:',
  array['Não possuírem membrana envolvendo sua estrutura', 'Possuírem uma dupla membrana', 'Serem exclusivos de células vegetais', 'Serem visíveis a olho nu'], 0,
  'Os ribossomos são estruturas não membranosas, formadas por RNA ribossômico e proteínas.', 3),
('227e8f6a-30c1-4f98-8258-caad221e1b9b', 'Os ribossomos estão presentes tanto em células procarióticas quanto em eucarióticas, o que evidencia:',
  array['A importância universal da síntese de proteínas para todos os seres vivos', 'Que apenas células eucarióticas produzem proteínas', 'Que ribossomos não são essenciais para a vida celular', 'Que apenas bactérias possuem ribossomos'], 0,
  'A presença de ribossomos em todos os tipos celulares reflete a necessidade universal de síntese proteica.', 4),
('227e8f6a-30c1-4f98-8258-caad221e1b9b', 'O processo pelo qual os ribossomos "leem" o RNA mensageiro para produzir uma proteína é chamado de:',
  array['Tradução', 'Transcrição', 'Replicação', 'Fermentação'], 0,
  'A tradução é a etapa em que os ribossomos decodificam a sequência do RNA mensageiro, formando a proteína.', 5),

-- Mitocôndrias (53997b60-6c93-406c-86c1-61ae5144284f)
('53997b60-6c93-406c-86c1-61ae5144284f', 'A principal função das mitocôndrias é:',
  array['Produzir energia (ATP) por meio da respiração celular', 'Armazenar o material genético principal da célula', 'Realizar a fotossíntese', 'Digerir macromoléculas intracelulares'], 0,
  'As mitocôndrias são responsáveis pela respiração celular aeróbica, produzindo grande parte do ATP celular.', 1),
('53997b60-6c93-406c-86c1-61ae5144284f', 'As mitocôndrias são estruturas caracterizadas por possuírem:',
  array['Dupla membrana, sendo a interna dobrada em cristas', 'Apenas uma única membrana simples', 'Nenhuma membrana, sendo estruturas completamente abertas', 'Uma membrana composta exclusivamente de proteínas'], 0,
  'A membrana interna, dobrada em cristas, aumenta a superfície para as reações da respiração celular.', 2),
('53997b60-6c93-406c-86c1-61ae5144284f', 'Segundo a teoria endossimbiótica, as mitocôndrias teriam se originado a partir de:',
  array['Bactérias ancestrais incorporadas por células maiores há bilhões de anos', 'Fragmentos do núcleo celular', 'Vírus que infectaram células eucarióticas', 'Restos de membrana plasmática'], 0,
  'A teoria endossimbiótica sugere que mitocôndrias descendem de bactérias incorporadas por células maiores.', 3),
('53997b60-6c93-406c-86c1-61ae5144284f', 'Um indício que sustenta a teoria endossimbiótica das mitocôndrias é o fato de elas possuírem:',
  array['DNA e ribossomos próprios, semelhantes aos de bactérias', 'Nenhum material genético próprio', 'Apenas uma membrana simples, como as bactérias', 'Ausência total de qualquer estrutura interna'], 0,
  'As mitocôndrias possuem DNA circular e ribossomos próprios, reforçando a teoria endossimbiótica.', 4),
('53997b60-6c93-406c-86c1-61ae5144284f', 'Células com alta demanda energética, como as musculares, tendem a apresentar:',
  array['Maior quantidade de mitocôndrias', 'Ausência total de mitocôndrias', 'Menor quantidade de mitocôndrias, em comparação com outras células', 'Nenhuma relação entre mitocôndrias e demanda energética'], 0,
  'Células que necessitam de mais energia, como musculares e cardíacas, possuem grande quantidade de mitocôndrias.', 5),

-- Lisossomos (bc066aa7-c7cc-4dda-99b5-2261662b2911)
('bc066aa7-c7cc-4dda-99b5-2261662b2911', 'Os lisossomos são organelas responsáveis principalmente por:',
  array['Realizar a digestão intracelular de macromoléculas e estruturas celulares', 'Produzir energia na forma de ATP', 'Sintetizar proteínas', 'Armazenar o material genético'], 0,
  'Os lisossomos contêm enzimas digestivas capazes de degradar proteínas, lipídios, carboidratos e ácidos nucleicos.', 1),
('bc066aa7-c7cc-4dda-99b5-2261662b2911', 'Os lisossomos são formados a partir de vesículas originadas principalmente:',
  array['Do complexo golgiense', 'Do núcleo celular', 'Das mitocôndrias', 'Da membrana plasmática, exclusivamente'], 0,
  'O complexo golgiense processa e empacota as enzimas digestivas, formando os lisossomos.', 2),
('bc066aa7-c7cc-4dda-99b5-2261662b2911', 'Durante a fagocitose, os lisossomos atuam:',
  array['Digerindo o material englobado pela célula, presente nos fagossomos', 'Impedindo qualquer digestão do material capturado', 'Produzindo energia adicional para a célula', 'Realizando a divisão celular'], 0,
  'Após a formação do fagossomo, os lisossomos se fundem a ele, liberando enzimas que digerem seu conteúdo.', 3),
('bc066aa7-c7cc-4dda-99b5-2261662b2911', 'A "autofagia", processo em que a própria célula degrada organelas ou componentes danificados, envolve diretamente a ação de:',
  array['Lisossomos', 'Ribossomos', 'Cloroplastos', 'Centríolos'], 0,
  'Na autofagia, os lisossomos digerem componentes celulares desgastados, contribuindo para a renovação celular.', 4),
('bc066aa7-c7cc-4dda-99b5-2261662b2911', 'Um funcionamento inadequado dos lisossomos, com deficiência em suas enzimas digestivas, pode estar associado a:',
  array['Doenças de acúmulo lisossômico, causadas pelo acúmulo de substâncias não digeridas', 'Um aumento imediato da produção de energia celular', 'Nenhuma consequência relevante para a célula', 'Uma maior resistência da célula a infecções'], 0,
  'A deficiência de enzimas lisossômicas específicas pode causar doenças genéticas graves de acúmulo.', 5),

-- Complexo golgiense (ae5f9b1f-c63d-48ac-8317-92c213efdfab)
('ae5f9b1f-c63d-48ac-8317-92c213efdfab', 'O complexo golgiense (ou aparelho de Golgi) tem como principal função:',
  array['Modificar, empacotar e distribuir proteínas e outras macromoléculas produzidas na célula', 'Produzir energia na forma de ATP', 'Armazenar diretamente o material genético', 'Realizar a fotossíntese'], 0,
  'O complexo golgiense processa moléculas recebidas do retículo endoplasmático, empacotando-as em vesículas.', 1),
('ae5f9b1f-c63d-48ac-8317-92c213efdfab', 'Estruturalmente, o complexo golgiense é formado por:',
  array['Uma série de sacos membranosos achatados, empilhados (cisternas)', 'Uma única grande vesícula esférica', 'Filamentos proteicos sem qualquer membrana', 'Uma estrutura idêntica ao núcleo celular'], 0,
  'O complexo golgiense é composto por cisternas membranosas empilhadas, com faces de recepção e de saída.', 2),
('ae5f9b1f-c63d-48ac-8317-92c213efdfab', 'O complexo golgiense recebe substâncias produzidas principalmente:',
  array['No retículo endoplasmático', 'No núcleo celular diretamente', 'Nas mitocôndrias', 'Fora da célula, pelo meio extracelular'], 0,
  'Proteínas sintetizadas no retículo endoplasmático rugoso são transportadas até o complexo golgiense.', 3),
('ae5f9b1f-c63d-48ac-8317-92c213efdfab', 'Entre as substâncias processadas e liberadas pelo complexo golgiense, incluem-se:',
  array['Enzimas digestivas que formarão os lisossomos', 'Apenas moléculas de DNA', 'Exclusivamente moléculas de água', 'Nenhuma substância relevante para a célula'], 0,
  'Um dos principais produtos do complexo golgiense são as enzimas digestivas, empacotadas nos lisossomos.', 4),
('ae5f9b1f-c63d-48ac-8317-92c213efdfab', 'Em células secretoras, como as glandulares, o complexo golgiense costuma ser:',
  array['Especialmente desenvolvido, devido à intensa atividade de processamento e secreção', 'Praticamente ausente', 'Idêntico ao encontrado em células que não secretam substâncias', 'Substituído completamente pelos lisossomos'], 0,
  'Células com alta atividade secretora apresentam complexo golgiense bem desenvolvido.', 5),

-- Retículo endoplasmático (200ba258-f3fa-4a2e-a3ca-be9f6679f885)
('200ba258-f3fa-4a2e-a3ca-be9f6679f885', 'O retículo endoplasmático rugoso se diferencia do liso principalmente por:',
  array['Possuir ribossomos aderidos à sua superfície', 'Não possuir qualquer membrana', 'Ser encontrado apenas em células vegetais', 'Produzir diretamente energia celular'], 0,
  'A presença de ribossomos na superfície externa caracteriza o retículo rugoso, ligado à síntese de proteínas.', 1),
('200ba258-f3fa-4a2e-a3ca-be9f6679f885', 'O retículo endoplasmático rugoso está diretamente envolvido na:',
  array['Síntese de proteínas destinadas à secreção ou a outras organelas', 'Produção de energia na forma de ATP', 'Digestão de macromoléculas', 'Duplicação do material genético'], 0,
  'As proteínas sintetizadas pelos ribossomos aderidos ao retículo rugoso são processadas antes de seguir para o Golgi.', 2),
('200ba258-f3fa-4a2e-a3ca-be9f6679f885', 'O retículo endoplasmático liso, sem ribossomos em sua superfície, está principalmente relacionado à:',
  array['Síntese de lipídios e à desintoxicação celular', 'Síntese direta de proteínas', 'Digestão de restos celulares', 'Produção do material genético'], 0,
  'O retículo liso participa da síntese de lipídios e de processos de desintoxicação, como no fígado.', 3),
('200ba258-f3fa-4a2e-a3ca-be9f6679f885', 'Em células musculares, uma variação especializada do retículo endoplasmático liso, chamada retículo sarcoplasmático, tem papel fundamental no(a):',
  array['Armazenamento e liberação de íons cálcio, essenciais para a contração muscular', 'Produção direta de energia muscular', 'Formação de novos núcleos celulares', 'Digestão de proteínas musculares'], 0,
  'O retículo sarcoplasmático regula os níveis de cálcio no citoplasma das células musculares, essencial à contração.', 4),
('200ba258-f3fa-4a2e-a3ca-be9f6679f885', 'O retículo endoplasmático, tanto rugoso quanto liso, é estruturalmente formado por:',
  array['Uma rede de membranas interconectadas, formando canais e sacos', 'Uma única vesícula esférica isolada', 'Filamentos proteicos sem qualquer membrana', 'Estruturas idênticas às mitocôndrias'], 0,
  'O retículo endoplasmático forma uma extensa rede de membranas interconectadas dentro do citoplasma.', 5),

-- Centríolos (4af454c7-1cd0-481e-bd5c-9701185a49c3)
('4af454c7-1cd0-481e-bd5c-9701185a49c3', 'Os centríolos são estruturas celulares diretamente relacionadas à:',
  array['Organização do fuso mitótico durante a divisão celular', 'Produção de energia celular', 'Síntese de proteínas', 'Digestão intracelular'], 0,
  'Durante a divisão celular, os centríolos ajudam a organizar os microtúbulos do fuso mitótico.', 1),
('4af454c7-1cd0-481e-bd5c-9701185a49c3', 'Estruturalmente, os centríolos são formados por:',
  array['Microtúbulos organizados em uma estrutura cilíndrica', 'Uma membrana dupla, como as mitocôndrias', 'Material genético próprio, semelhante ao DNA nuclear', 'Enzimas digestivas concentradas'], 0,
  'Cada centríolo é composto por nove conjuntos de microtúbulos organizados em forma de cilindro.', 2),
('4af454c7-1cd0-481e-bd5c-9701185a49c3', 'Além de sua função na divisão celular, os centríolos também estão relacionados à formação de:',
  array['Cílios e flagelos em determinadas células', 'Novas mitocôndrias', 'Novo material genético', 'Enzimas digestivas'], 0,
  'Os centríolos atuam como corpos basais na formação de cílios e flagelos, estruturas de movimentação celular.', 3),
('4af454c7-1cd0-481e-bd5c-9701185a49c3', 'Diferentemente das células animais, muitas células vegetais são caracterizadas por:',
  array['Não possuírem centríolos, mesmo realizando divisão celular normalmente', 'Possuírem centríolos idênticos aos das células animais', 'Nunca se dividirem', 'Possuírem o dobro de centríolos das células animais'], 0,
  'A maioria das células vegetais se divide sem centríolos, organizando o fuso mitótico por outros mecanismos.', 4),
('4af454c7-1cd0-481e-bd5c-9701185a49c3', 'Um par de centríolos, geralmente organizados perpendicularmente entre si, forma uma estrutura chamada de:',
  array['Centrossomo', 'Nucléolo', 'Peroxissomo', 'Vacúolo'], 0,
  'O centrossomo, formado por um par de centríolos, é o principal centro organizador de microtúbulos da célula animal.', 5),

-- Cloroplastos (47233064-12a0-4db3-893c-d357da648432)
('47233064-12a0-4db3-893c-d357da648432', 'A principal função dos cloroplastos, presentes em células vegetais e de algumas algas, é:',
  array['Realizar a fotossíntese, convertendo luz solar em energia química', 'Produzir energia exclusivamente por respiração celular', 'Digerir macromoléculas intracelulares', 'Armazenar o material genético principal da célula'], 0,
  'Os cloroplastos captam a energia luminosa e a convertem em energia química (glicose) durante a fotossíntese.', 1),
('47233064-12a0-4db3-893c-d357da648432', 'A coloração verde característica dos cloroplastos deve-se principalmente à presença do pigmento:',
  array['Clorofila', 'Hemoglobina', 'Melanina', 'Caroteno, exclusivamente'], 0,
  'A clorofila, pigmento fundamental na fotossíntese, confere a cor verde característica aos cloroplastos.', 2),
('47233064-12a0-4db3-893c-d357da648432', 'Assim como as mitocôndrias, os cloroplastos possuem:',
  array['DNA e ribossomos próprios, sustentando também a teoria endossimbiótica', 'Nenhum material genético próprio', 'Apenas uma única membrana simples', 'Estrutura idêntica aos lisossomos'], 0,
  'Os cloroplastos possuem DNA circular e ribossomos próprios, reforçando sua origem endossimbiótica.', 3),
('47233064-12a0-4db3-893c-d357da648432', 'Os cloroplastos são estruturalmente organizados internamente em pilhas de membranas chamadas:',
  array['Grana (formadas por tilacoides)', 'Cristas', 'Cisternas golgienses', 'Ribossomos'], 0,
  'No interior dos cloroplastos, os tilacoides se organizam em pilhas chamadas grana, onde ocorrem reações fotoquímicas.', 4),
('47233064-12a0-4db3-893c-d357da648432', 'Diferentemente das células vegetais, as células animais:',
  array['Não possuem cloroplastos, obtendo energia principalmente por meio da alimentação', 'Possuem cloroplastos idênticos aos vegetais', 'Realizam fotossíntese normalmente', 'Não realizam respiração celular'], 0,
  'Por não possuírem cloroplastos, as células animais dependem da alimentação (heterotrofismo) para obter energia.', 5),

-- Ciclo celular, mitose e meiose (4c802fad-3592-4adb-9031-5b7f4cf48fe0)
('4c802fad-3592-4adb-9031-5b7f4cf48fe0', 'O ciclo celular é dividido em duas grandes fases principais:',
  array['Interfase e divisão celular (mitose ou meiose)', 'Apenas mitose e meiose, sem qualquer outra fase', 'Apenas replicação do DNA, sem divisão celular', 'Fase de repouso absoluto, sem qualquer atividade'], 0,
  'O ciclo celular alterna entre a interfase (crescimento e duplicação do DNA) e a fase de divisão celular.', 1),
('4c802fad-3592-4adb-9031-5b7f4cf48fe0', 'A mitose é um tipo de divisão celular que resulta em:',
  array['Duas células-filhas geneticamente idênticas à célula-mãe', 'Quatro células-filhas com metade do material genético', 'Uma única célula, sem qualquer divisão', 'Células-filhas geneticamente distintas entre si'], 0,
  'Na mitose, uma célula se divide em duas células-filhas com o mesmo material genético da original.', 2),
('4c802fad-3592-4adb-9031-5b7f4cf48fe0', 'A meiose, diferentemente da mitose, resulta na formação de:',
  array['Quatro células-filhas com metade do número de cromossomos da célula original', 'Duas células-filhas idênticas à célula-mãe', 'Uma única célula com o dobro de cromossomos', 'Células sem qualquer material genético'], 0,
  'A meiose reduz o número de cromossomos à metade, sendo essencial para a formação de gametas.', 3),
('4c802fad-3592-4adb-9031-5b7f4cf48fe0', 'A mitose é o tipo de divisão celular responsável, principalmente, por:',
  array['O crescimento do organismo e a reposição de células', 'A formação exclusiva de gametas', 'A redução do número de cromossomos', 'A destruição de células danificadas, exclusivamente'], 0,
  'A mitose permite o crescimento dos organismos multicelulares e a substituição de células desgastadas.', 4),
('4c802fad-3592-4adb-9031-5b7f4cf48fe0', 'A meiose é essencial para a reprodução sexuada porque:',
  array['Garante que, ao se unirem, os gametas restabeleçam o número normal de cromossomos da espécie', 'Produz células geneticamente idênticas para a reprodução', 'Impede qualquer variabilidade genética entre os descendentes', 'Não tem qualquer relação com a formação de gametas'], 0,
  'Como reduz o número de cromossomos à metade nos gametas, a meiose permite que a fecundação restaure o número cromossômico da espécie.', 5);
