-- História — Era Vargas (10 leaves, 5 questões cada)
insert into questions (catalog_node_id, prompt, options, correct_index, explanation, order_index) values
-- Revolução de 1930 (d8a3ff73-b95d-4c49-8438-a6f562936779)
('d8a3ff73-b95d-4c49-8438-a6f562936779', 'A Aliança Liberal, formada para a eleição presidencial de 1930, tinha como candidato a presidente:',
  array['Getúlio Vargas', 'Júlio Prestes', 'Washington Luís', 'João Pessoa'], 0,
  'A Aliança Liberal reunia oposições oligárquicas e lançou a chapa Getúlio Vargas (presidente) e João Pessoa (vice).', 1),
('d8a3ff73-b95d-4c49-8438-a6f562936779', 'Apesar da derrota eleitoral de Vargas em 1930, o movimento armado revolucionário teve início após:',
  array['O assassinato de João Pessoa, em julho de 1930', 'A morte de Washington Luís', 'A Proclamação da República', 'A promulgação da Constituição de 1934'], 0,
  'O assassinato de João Pessoa, vice na chapa de Vargas, serviu de estopim para a articulação do movimento armado.', 2),
('d8a3ff73-b95d-4c49-8438-a6f562936779', 'A Revolução de 1930 depôs o presidente:',
  array['Washington Luís', 'Júlio Prestes', 'Artur Bernardes', 'Epitácio Pessoa'], 0,
  'Washington Luís foi deposto em outubro de 1930, e Júlio Prestes, presidente eleito, foi impedido de tomar posse.', 3),
('d8a3ff73-b95d-4c49-8438-a6f562936779', 'Um dos principais efeitos políticos imediatos da Revolução de 1930 foi:',
  array['O fim da hegemonia política das oligarquias de São Paulo e Minas Gerais', 'A imediata proclamação da República', 'A abolição da escravidão', 'A independência do Brasil em relação a Portugal'], 0,
  'A Revolução de 1930 encerrou o predomínio da "política do café com leite", levando Vargas ao poder à frente de um Governo Provisório.', 4),
('d8a3ff73-b95d-4c49-8438-a6f562936779', 'Getúlio Vargas assumiu o poder após a Revolução de 1930 na condição de:',
  array['Chefe do Governo Provisório', 'Presidente eleito por voto direto', 'Imperador constitucional', 'Primeiro-ministro parlamentarista'], 0,
  'Vargas assumiu como chefe do Governo Provisório, concentrando poderes executivo e legislativo até a promulgação de nova Constituição.', 5),

-- Governo Provisório 1930-1934 (b75f4f86-6f0d-4ebd-895f-5fb3118d35ca)
('b75f4f86-6f0d-4ebd-895f-5fb3118d35ca', 'Durante o Governo Provisório, Vargas governou principalmente por meio de:',
  array['Decretos-lei, concentrando poderes executivo e legislativo', 'Um Congresso Nacional eleito e atuante', 'Um parlamento bicameral tradicional', 'Assembleias estaduais autônomas'], 0,
  'No Governo Provisório (1930-1934), Vargas exerceu poder centralizado, legislando por decretos, sem Congresso Nacional em funcionamento.', 1),
('b75f4f86-6f0d-4ebd-895f-5fb3118d35ca', 'A Revolução Constitucionalista de 1932, ocorrida em São Paulo, teve como principal reivindicação:',
  array['A convocação de uma Assembleia Constituinte e o retorno ao regime constitucional', 'A independência de São Paulo em relação ao Brasil', 'A restauração da monarquia', 'A imediata abolição da escravidão'], 0,
  'Paulistas se rebelaram contra o Governo Provisório exigindo uma nova Constituição, sendo derrotados militarmente após cerca de três meses.', 2),
('b75f4f86-6f0d-4ebd-895f-5fb3118d35ca', 'Como consequência da Revolução Constitucionalista de 1932, o governo Vargas:',
  array['Convocou eleições para uma Assembleia Nacional Constituinte', 'Renunciou ao poder imediatamente', 'Anexou o estado de São Paulo à Argentina', 'Aboliu todos os estados federativos'], 0,
  'Apesar de vencer militarmente os paulistas, o governo cedeu à pressão política e convocou eleições constituintes, promulgando a Constituição de 1934.', 3),
('b75f4f86-6f0d-4ebd-895f-5fb3118d35ca', 'No campo trabalhista, o Governo Provisório criou, ainda em 1930, o(a):',
  array['Ministério do Trabalho, Indústria e Comércio', 'Consolidação das Leis do Trabalho (CLT)', 'Departamento de Imprensa e Propaganda (DIP)', 'Instituto Nacional de Previdência Social (INPS)'], 0,
  'Já em novembro de 1930, Vargas criou o Ministério do Trabalho, Indústria e Comércio, sinalizando aproximação com os trabalhadores urbanos.', 4),
('b75f4f86-6f0d-4ebd-895f-5fb3118d35ca', 'A Constituição de 1934, resultado da Assembleia Constituinte, incorporou pela primeira vez ao texto constitucional brasileiro:',
  array['Direitos sociais e trabalhistas, como jornada de 8 horas e salário mínimo', 'O voto censitário obrigatório', 'A pena de morte para crimes políticos', 'O regime parlamentarista'], 0,
  'A Constituição de 1934 foi pioneira ao incluir direitos sociais e trabalhistas, além de instituir o voto feminino e o voto secreto.', 5),

-- Governo Constitucional 1934-1937 (b0581df7-1582-41b8-95f9-c2addfb47ddf)
('b0581df7-1582-41b8-95f9-c2addfb47ddf', 'Após a Constituição de 1934, Getúlio Vargas foi eleito presidente por:',
  array['Voto indireto da Assembleia Nacional Constituinte', 'Voto direto e universal da população', 'Aclamação popular nas ruas', 'Indicação do Exército'], 0,
  'Pela nova Constituição, Vargas foi eleito indiretamente pelos constituintes para exercer a presidência até 1938.', 1),
('b0581df7-1582-41b8-95f9-c2addfb47ddf', 'A Aliança Nacional Libertadora (ANL), fundada em 1935 e ligada a Luís Carlos Prestes, reunia principalmente:',
  array['Setores de esquerda, incluindo comunistas, socialistas e tenentistas', 'Grupos integralistas de extrema-direita', 'A cúpula da Igreja Católica', 'As oligarquias cafeeiras paulistas'], 0,
  'A ANL era uma frente de esquerda contra o fascismo e o imperialismo, tendo Prestes como uma de suas principais lideranças.', 2),
('b0581df7-1582-41b8-95f9-c2addfb47ddf', 'O fechamento da Aliança Nacional Libertadora, ainda em 1935, foi justificado pelo governo Vargas com base em:',
  array['Uma lei de segurança nacional voltada contra atividades consideradas subversivas', 'Uma decisão do Supremo Tribunal Federal sobre eleições', 'Um plebiscito popular', 'Pressão exclusiva de potências estrangeiras'], 0,
  'O governo utilizou a recém-criada Lei de Segurança Nacional para fechar a ANL, alegando conter uma ameaça revolucionária de esquerda.', 3),
('b0581df7-1582-41b8-95f9-c2addfb47ddf', 'O clima de instabilidade e polarização política entre 1934 e 1937 opôs principalmente:',
  array['Integralistas (extrema-direita) e aliancistas/comunistas (esquerda)', 'Monarquistas e republicanos', 'Nordeste e Sudeste em disputa territorial', 'Igreja Católica e Estado, em uma guerra religiosa'], 0,
  'O período foi marcado pela polarização entre a Ação Integralista Brasileira, de inspiração fascista, e a Aliança Nacional Libertadora, de esquerda.', 4),
('b0581df7-1582-41b8-95f9-c2addfb47ddf', 'O chamado "Plano Cohen", documento apresentado em 1937 como suposto plano comunista de tomada do poder, foi posteriormente identificado como:',
  array['Um documento forjado, usado como pretexto para justificar o golpe do Estado Novo', 'Um plano genuíno elaborado pelo Partido Comunista', 'Um acordo comercial entre Brasil e União Soviética', 'Um projeto de reforma agrária aprovado pelo Congresso'], 0,
  'O Plano Cohen foi forjado por integralistas e usado por Vargas como justificativa para o golpe de 1937, que instaurou o Estado Novo.', 5),

-- Constituição de 1937 (3a099505-6721-49f2-8633-8aa2b613a762)
('3a099505-6721-49f2-8633-8aa2b613a762', 'A Constituição de 1937, outorgada por Getúlio Vargas após o golpe que instaurou o Estado Novo, ficou popularmente conhecida como:',
  array['"Polaca", por sua inspiração na Constituição autoritária da Polônia', '"Magna Carta brasileira"', '"Constituição Cidadã"', '"Carta liberal de 1937"'], 0,
  'A Constituição de 1937 recebeu o apelido de "Polaca" por se inspirar na carta autoritária e corporativista da Polônia de então.', 1),
('3a099505-6721-49f2-8633-8aa2b613a762', 'A Constituição de 1937 concentrou poderes principalmente no(a):',
  array['Poder Executivo, nas mãos do presidente da República', 'Poder Legislativo, fortalecendo o Congresso Nacional', 'Poder Judiciário, com autonomia ampliada', 'Governos estaduais, em um modelo fortemente federalista'], 0,
  'A Carta de 1937 concentrou poderes no Executivo, permitindo a Vargas legislar por decretos-lei e enfraquecendo o Legislativo e os estados.', 2),
('3a099505-6721-49f2-8633-8aa2b613a762', 'Sob a Constituição de 1937, o Congresso Nacional e as assembleias estaduais foram:',
  array['Fechados, sendo o Poder Legislativo exercido pelo presidente por decretos', 'Mantidos em pleno funcionamento normal', 'Substituídos por eleições diretas anuais', 'Transformados em tribunais constitucionais'], 0,
  'Com o golpe de 1937, o Congresso e as assembleias estaduais foram fechados, e Vargas passou a legislar por decretos-lei.', 3),
('3a099505-6721-49f2-8633-8aa2b613a762', 'A Constituição de 1937 previa a realização de um plebiscito para referendar a nova Carta, o qual:',
  array['Nunca chegou a ser realizado', 'Foi realizado e aprovou amplamente a Constituição', 'Foi realizado e rejeitou a Constituição', 'Foi substituído por uma eleição direta para presidente'], 0,
  'Apesar de prevista no texto constitucional, o plebiscito de ratificação jamais foi convocado por Vargas.', 4),
('3a099505-6721-49f2-8633-8aa2b613a762', 'O caráter da Constituição de 1937 é geralmente classificado pelos historiadores como:',
  array['Autoritário e corporativista, típico dos regimes de inspiração fascista da época', 'Liberal e democrático', 'Socialista e revolucionário', 'Estritamente parlamentarista'], 0,
  'A Carta de 1937 refletia o ideário autoritário e corporativista do Estado Novo, inspirado em regimes europeus como o fascismo italiano.', 5),

-- Trabalhismo (2065151d-f988-43b0-b8d9-f784cbec1278)
('2065151d-f988-43b0-b8d9-f784cbec1278', 'A Consolidação das Leis do Trabalho (CLT), marco da legislação trabalhista brasileira, foi promulgada em:',
  array['1943, durante o Estado Novo', '1930, no início do Governo Provisório', '1988, com a Constituição Cidadã', '1964, no início do regime militar'], 0,
  'A CLT foi promulgada em maio de 1943, reunindo e sistematizando diversas leis trabalhistas criadas desde 1930.', 1),
('2065151d-f988-43b0-b8d9-f784cbec1278', 'A política trabalhista de Vargas, muitas vezes chamada de "trabalhismo", caracterizava-se por:',
  array['Conceder direitos e benefícios aos trabalhadores urbanos sob forte controle e tutela do Estado', 'Garantir plena autonomia aos sindicatos frente ao governo', 'Excluir totalmente os trabalhadores urbanos de qualquer direito', 'Transferir toda a regulação trabalhista à iniciativa privada'], 0,
  'O trabalhismo varguista concedia direitos sociais, mas mantinha os sindicatos sob controle estatal, em uma relação de tutela e cooptação política.', 2),
('2065151d-f988-43b0-b8d9-f784cbec1278', 'Os sindicatos, durante a Era Vargas, ficaram sujeitos a qual forma de controle estatal?',
  array['Vinculação ao Ministério do Trabalho e subordinação ao sindicato único por categoria', 'Total independência frente ao governo federal', 'Direção exclusiva por representantes patronais', 'Extinção completa até o fim do Estado Novo'], 0,
  'A estrutura sindical corporativista instituída por Vargas vinculava os sindicatos ao Estado, com forte tutela do Ministério do Trabalho.', 3),
('2065151d-f988-43b0-b8d9-f784cbec1278', 'O salário mínimo, instituído no Brasil em 1940, tinha como objetivo declarado:',
  array['Garantir uma remuneração mínima capaz de atender às necessidades básicas do trabalhador', 'Padronizar salários apenas para o funcionalismo público', 'Substituir a carteira de trabalho', 'Financiar exclusivamente a Previdência Social'], 0,
  'O salário mínimo foi criado para assegurar um piso remuneratório que cobrisse as necessidades essenciais do trabalhador e de sua família.', 4),
('2065151d-f988-43b0-b8d9-f784cbec1278', 'A carteira de trabalho, criada em 1932, tornou-se um símbolo do trabalhismo varguista por:',
  array['Formalizar o vínculo empregatício e dar acesso a direitos trabalhistas e previdenciários', 'Substituir o título de eleitor', 'Ser exigida apenas de trabalhadores rurais', 'Conceder automaticamente a cidadania a imigrantes'], 0,
  'A carteira de trabalho registrava o vínculo empregatício formal, dando acesso a direitos como férias e aposentadoria.', 5),

-- DIP (8cdb0962-4694-476e-9c83-9cb807353e6c)
('8cdb0962-4694-476e-9c83-9cb807353e6c', 'O Departamento de Imprensa e Propaganda (DIP), criado em 1939, tinha como principal função:',
  array['Controlar e censurar a imprensa, o rádio e demais meios de comunicação, além de promover a propaganda do regime', 'Administrar a política externa do Brasil', 'Organizar as eleições presidenciais', 'Fiscalizar exclusivamente as finanças públicas'], 0,
  'O DIP centralizava a censura e a propaganda oficial do Estado Novo, controlando jornais, rádio e cinema.', 1),
('8cdb0962-4694-476e-9c83-9cb807353e6c', 'Um dos principais instrumentos de propaganda e doutrinação usados pelo DIP através do rádio foi o programa:',
  array['"Hora do Brasil" (atual "A Voz do Brasil")', '"Jornal Nacional"', '"Repórter Esso"', '"Roda Viva"'], 0,
  'A "Hora do Brasil", transmissão obrigatória em todas as emissoras, era usada para divulgar as ações do governo.', 2),
('8cdb0962-4694-476e-9c83-9cb807353e6c', 'A atuação do DIP durante o Estado Novo é um exemplo característico de:',
  array['Censura estatal e controle da opinião pública em regimes autoritários', 'Liberdade de imprensa plena', 'Pluralismo político incentivado pelo Estado', 'Descentralização da comunicação para os estados'], 0,
  'O DIP exemplifica como regimes autoritários controlam a informação e utilizam a propaganda para legitimar-se e silenciar oposições.', 3),
('8cdb0962-4694-476e-9c83-9cb807353e6c', 'Além da censura política, o DIP também atuava na promoção de:',
  array['Uma identidade nacional e do culto à figura de Getúlio Vargas como "pai dos pobres"', 'Movimentos sindicais independentes', 'Partidos políticos de oposição', 'A imprensa estrangeira crítica ao governo'], 0,
  'O DIP construía e reforçava uma imagem positiva de Vargas e do Estado Novo, associada ao nacionalismo.', 4),
('8cdb0962-4694-476e-9c83-9cb807353e6c', 'Com o fim do Estado Novo em 1945, o DIP foi:',
  array['Extinto, encerrando a estrutura oficial de censura e propaganda daquele formato', 'Transformado no atual Ministério das Comunicações', 'Mantido inalterado até os dias atuais', 'Transferido para controle exclusivo dos estados'], 0,
  'Com a redemocratização de 1945, o DIP foi extinto junto com o aparato repressivo mais visível do Estado Novo.', 5),

-- Intentona Comunista (87dcdeae-bf22-493e-a53a-6f09c878f224)
('87dcdeae-bf22-493e-a53a-6f09c878f224', 'A Intentona Comunista, ocorrida em novembro de 1935, foi um levante:',
  array['Organizado pela Aliança Nacional Libertadora e pelo Partido Comunista, com apoio de militares', 'Liderado por integralistas de extrema-direita', 'Promovido pelas oligarquias cafeeiras', 'Articulado pela Igreja Católica'], 0,
  'A Intentona foi uma tentativa de insurreição armada, com participação de militares ligados à ANL e ao PCB, sob influência de Luís Carlos Prestes.', 1),
('87dcdeae-bf22-493e-a53a-6f09c878f224', 'A Intentona Comunista teve como principais focos de rebelião:',
  array['Natal, Recife e Rio de Janeiro', 'São Paulo e Porto Alegre', 'Belém e Manaus', 'Salvador e Fortaleza'], 0,
  'Os levantes ocorreram principalmente em Natal, Recife e no Rio de Janeiro, sendo rapidamente reprimidos.', 2),
('87dcdeae-bf22-493e-a53a-6f09c878f224', 'O fracasso da Intentona Comunista foi utilizado pelo governo Vargas para:',
  array['Justificar maior repressão política e reforçar o discurso anticomunista', 'Ampliar os direitos políticos da oposição', 'Convocar eleições antecipadas', 'Extinguir a Lei de Segurança Nacional'], 0,
  'A repressão ao levante serviu de pretexto para o governo intensificar a perseguição a opositores, pavimentando o caminho para o golpe de 1937.', 3),
('87dcdeae-bf22-493e-a53a-6f09c878f224', 'Luís Carlos Prestes, uma das principais lideranças ligadas à Intentona Comunista, era conhecido anteriormente por:',
  array['Liderar a Coluna Prestes durante o movimento tenentista da década de 1920', 'Ser ministro da Fazenda de Vargas', 'Comandar as tropas legalistas na Revolução de 1930', 'Fundar a Ação Integralista Brasileira'], 0,
  'Prestes, antigo líder tenentista da Coluna Prestes, tornou-se posteriormente uma das principais figuras do Partido Comunista Brasileiro.', 4),
('87dcdeae-bf22-493e-a53a-6f09c878f224', 'Após a derrota da Intentona Comunista, o governo Vargas decretou:',
  array['Estado de sítio, ampliando os poderes repressivos do Executivo', 'A abertura política imediata', 'A convocação de uma nova Assembleia Constituinte', 'A anistia geral a todos os presos políticos'], 0,
  'O governo decretou estado de sítio, ampliando a repressão que culminaria no golpe de 1937.', 5),

-- Integralismo (b134a54a-0add-4719-8e97-0f28c82bc7a5)
('b134a54a-0add-4719-8e97-0f28c82bc7a5', 'A Ação Integralista Brasileira (AIB), fundada em 1932 por Plínio Salgado, era um movimento político de:',
  array['Extrema-direita, inspirado no fascismo europeu', 'Extrema-esquerda, inspirado no comunismo soviético', 'Centro liberal, defensor do parlamentarismo', 'Caráter puramente religioso, sem atuação política'], 0,
  'O integralismo era um movimento nacionalista e autoritário de extrema-direita, com forte inspiração no fascismo italiano.', 1),
('b134a54a-0add-4719-8e97-0f28c82bc7a5', 'O símbolo e a saudação característicos dos integralistas eram, respectivamente:',
  array['A letra grega sigma (Σ) e a saudação "Anauê!"', 'A foice e o martelo', 'A suástica e a saudação nazista', 'A cruz cristã e o hino nacional'], 0,
  'Os integralistas usavam a letra sigma como símbolo e "Anauê!" (saudação de origem tupi) como cumprimento característico do movimento.', 2),
('b134a54a-0add-4719-8e97-0f28c82bc7a5', 'Após o golpe do Estado Novo, em 1937, a relação entre Vargas e os integralistas:',
  array['Deteriorou-se, culminando na extinção da AIB e em uma tentativa integralista de golpe em 1938', 'Permaneceu de plena aliança durante todo o Estado Novo', 'Resultou na nomeação de Plínio Salgado como vice-presidente', 'Levou à fusão da AIB com o Partido Comunista'], 0,
  'Vargas extinguiu todos os partidos políticos, incluindo a AIB, o que culminou na tentativa de golpe integralista de maio de 1938.', 3),
('b134a54a-0add-4719-8e97-0f28c82bc7a5', 'A tentativa de golpe integralista de maio de 1938 teve como um de seus alvos:',
  array['O Palácio Guanabara, residência oficial de Getúlio Vargas', 'O Congresso Nacional', 'A sede do Partido Comunista', 'O Palácio do Catete, apenas simbolicamente'], 0,
  'Integralistas atacaram o Palácio Guanabara, tentando depor Vargas, mas foram derrotados pela guarda presidencial.', 4),
('b134a54a-0add-4719-8e97-0f28c82bc7a5', 'O integralismo, assim como outros movimentos fascistas da época, defendia como um de seus princípios centrais:',
  array['O nacionalismo exacerbado e o Estado forte e centralizado acima dos interesses individuais', 'A ampliação irrestrita das liberdades individuais', 'O internacionalismo proletário', 'A descentralização máxima do poder político'], 0,
  'Assim como outros movimentos fascistas, o integralismo pregava um Estado forte, nacionalista e hierarquizado.', 5),

-- Brasil na Segunda Guerra Mundial (b32513cb-a94e-4040-a310-2c97c607bed4)
('b32513cb-a94e-4040-a310-2c97c607bed4', 'O Brasil, sob Vargas, inicialmente adotou em relação à Segunda Guerra Mundial uma postura de:',
  array['Neutralidade, buscando vantagens econômicas tanto dos Aliados quanto do Eixo', 'Alinhamento imediato com a Alemanha nazista', 'Declaração de guerra imediata aos Aliados', 'Rompimento total de relações com os Estados Unidos'], 0,
  'Inicialmente neutro, o Brasil negociou vantagens com ambos os lados antes de se alinhar definitivamente aos Aliados.', 1),
('b32513cb-a94e-4040-a310-2c97c607bed4', 'O Brasil declarou guerra às potências do Eixo em 1942, principalmente em razão de:',
  array['O afundamento de navios mercantes brasileiros por submarinos alemães', 'Um ataque direto ao território brasileiro pela Alemanha', 'Pressão exclusiva da União Soviética', 'A adesão espontânea sem motivação externa'], 0,
  'O afundamento de diversos navios brasileiros por submarinos do Eixo, em 1942, gerou forte comoção popular e levou à declaração de guerra.', 2),
('b32513cb-a94e-4040-a310-2c97c607bed4', 'A participação militar brasileira na Segunda Guerra Mundial ocorreu principalmente por meio:',
  array['Da Força Expedicionária Brasileira (FEB), enviada à Itália', 'De tropas enviadas ao Pacífico contra o Japão', 'De uma aliança militar direta com a Alemanha', 'Do envio de tropas exclusivamente para a fronteira com a Argentina'], 0,
  'A FEB, conhecida como "Cobras Fumantes", combateu na Campanha da Itália ao lado dos Aliados entre 1944 e 1945.', 3),
('b32513cb-a94e-4040-a310-2c97c607bed4', 'Em troca do apoio brasileiro aos Estados Unidos na guerra, incluindo a cessão de bases no Nordeste, o Brasil obteve, entre outras contrapartidas:',
  array['Apoio financeiro e técnico para a construção da Companhia Siderúrgica Nacional, em Volta Redonda', 'A anexação de territórios do Paraguai', 'A entrada imediata na Organização das Nações Unidas', 'A doação de armas nucleares'], 0,
  'Como parte dos acordos com os EUA, o Brasil recebeu apoio para desenvolver sua indústria de base, notadamente a siderurgia em Volta Redonda.', 4),
('b32513cb-a94e-4040-a310-2c97c607bed4', 'Um paradoxo frequentemente apontado pela historiografia sobre a participação brasileira na Segunda Guerra Mundial é:',
  array['O Brasil lutar no exterior contra regimes fascistas enquanto mantinha uma ditadura em seu próprio território', 'O Brasil ter permanecido oficialmente neutro durante todo o conflito', 'O Brasil ter enviado tropas apenas depois do fim da guerra', 'A inexistência de qualquer relação entre a guerra e a política interna brasileira'], 0,
  'É comum destacar o paradoxo de o Estado Novo, um regime autoritário, enviar tropas para combater o fascismo, contradição que fortaleceu pressões internas por redemocratização.', 5),

-- Fim do Estado Novo (0384be9b-0291-4535-b984-c77bb61c1611)
('0384be9b-0291-4535-b984-c77bb61c1611', 'A participação do Brasil na Segunda Guerra Mundial, ao lado dos Aliados contra regimes autoritários, contribuiu internamente para:',
  array['Fortalecer as pressões pela redemocratização e o fim do Estado Novo', 'Consolidar definitivamente o regime de Vargas', 'A criação de um novo partido único de caráter fascista', 'O rompimento com os Estados Unidos'], 0,
  'O contraste entre lutar contra o fascismo fora e manter uma ditadura dentro do país fortaleceu o movimento pela redemocratização.', 1),
('0384be9b-0291-4535-b984-c77bb61c1611', 'A queda do Estado Novo, em outubro de 1945, ocorreu por meio de:',
  array['Um golpe militar que depôs Getúlio Vargas', 'Uma revolução popular armada', 'A morte natural de Vargas no cargo', 'Uma intervenção estrangeira direta'], 0,
  'Militares, temendo um possível continuísmo de Vargas no poder, promoveram sua deposição em 29 de outubro de 1945.', 2),
('0384be9b-0291-4535-b984-c77bb61c1611', 'Antes de sua deposição, Getúlio Vargas havia convocado eleições diretas para presidente, marcadas para:',
  array['Dezembro de 1945', '1930', '1937', '1950'], 0,
  'Vargas havia marcado eleições diretas para dezembro de 1945, ainda que sua deposição tenha ocorrido antes desse pleito.', 3),
('0384be9b-0291-4535-b984-c77bb61c1611', 'Após a queda de Vargas em 1945, assumiu a presidência interinamente:',
  array['José Linhares, presidente do Supremo Tribunal Federal', 'Eurico Gaspar Dutra', 'Juscelino Kubitschek', 'Café Filho'], 0,
  'José Linhares, então presidente do STF, assumiu interinamente até a posse do presidente eleito, Eurico Gaspar Dutra, em 1946.', 4),
('0384be9b-0291-4535-b984-c77bb61c1611', 'A eleição presidencial de dezembro de 1945, vencida pelo general Eurico Gaspar Dutra, marcou:',
  array['O início do processo de redemocratização do país após o Estado Novo', 'A continuidade direta do Estado Novo sob nova liderança', 'A instauração de uma nova ditadura militar', 'O retorno da monarquia'], 0,
  'A eleição de 1945 inaugurou o período conhecido como República de 1946, marcado pela redemocratização.', 5);
