-- New "dificil" questions for fisica: 24 questions, each already
-- with its en/es translation (48 translation rows).
--
-- ids are deterministic (uuid5 of the pt-BR prompt), so running this twice
-- inserts nothing new: questions use on conflict do nothing, translations
-- on conflict do update. The translation join refuses any row whose option
-- count differs from the original (correct_index is positional).

insert into questions (id, catalog_node_id, prompt, options, correct_index, explanation, order_index, difficulty)
select v.id::uuid, v.node::uuid, v.prompt, v.options, v.correct_index, v.explanation, v.order_index, 'dificil'
from (values
  ('bb068afe-44f1-5d11-9327-2bfcd56eb829', '2678423c-4c04-4815-aea0-c4568078732e',
   'Uma carga de 2 μC entra com velocidade de 5 × 10³ m/s, perpendicular às linhas de um campo magnético uniforme de 0,4 T. Qual é a intensidade da força magnética sobre ela?',
   array['zero', '4 × 10⁻³ N', '4 × 10⁻⁶ N', '1 × 10⁻² N'], 1,
   'F = q · v · B · sen θ, com θ = 90°: F = 2 × 10⁻⁶ · 5 × 10³ · 0,4 = 4 × 10⁻³ N. Seria zero só se a velocidade fosse paralela ao campo.', 100),
  ('4e6945f2-e6ad-5c4f-a154-2a6164caee66', '2678423c-4c04-4815-aea0-c4568078732e',
   'O polo norte de um ímã é aproximado de uma espira condutora. Segundo a Lei de Lenz, surge na espira uma corrente induzida:',
   array['que atrai o ímã, criando um polo sul na face voltada para ele', 'nula, porque o ímã não toca a espira', 'que se opõe à aproximação, criando um polo norte na face voltada para o ímã', 'contínua, que permanece mesmo com o ímã parado'], 2,
   'A corrente induzida sempre se opõe à variação do fluxo que a produziu. Para "repelir" a aproximação do polo norte, a espira forma um polo norte na face voltada ao ímã. Com o ímã parado, o fluxo não varia e a corrente cessa.', 101),
  ('dceb9030-46e2-5324-b405-eec8ce6cff31', '67153ecb-1781-4067-8650-94cb1de96321',
   'Um carro a 72 km/h freia uniformemente e para em 4 s. Qual é o módulo da aceleração e a distância percorrida durante a frenagem?',
   array['18 m/s² e 144 m', '5 m/s² e 80 m', '2,5 m/s² e 40 m', '5 m/s² e 40 m'], 3,
   '72 km/h = 20 m/s. a = Δv / Δt = 20 / 4 = 5 m/s². A distância é a velocidade média vezes o tempo: (20 + 0)/2 · 4 = 40 m.', 102),
  ('491a908a-80c1-51e2-9ec8-7587a1a6efdb', '88d296cd-2bea-41f5-ad96-3bf158827298',
   'Um astronauta de 70 kg vai à Lua, onde g = 1,6 m/s². Lá, sua massa e seu peso valem, respectivamente:',
   array['70 kg e 112 N', '11,2 kg e 112 N', '70 kg e 700 N', '112 kg e 70 N'], 0,
   'A massa não depende do lugar: continua 70 kg. O peso é P = m · g = 70 · 1,6 = 112 N (na Terra seriam 700 N).', 103),
  ('883c4484-d50b-5f0b-bfc9-6bba996c4dd6', 'a5777654-961e-4813-9fed-c5d835825966',
   'Quando um ônibus freia bruscamente, os passageiros em pé são projetados para frente. Isso acontece porque:',
   array['uma força para frente passa a agir sobre os passageiros', 'a gravidade aumenta durante a frenagem', 'os passageiros tendem a manter o estado de movimento que tinham, por inércia', 'o atrito com o piso empurra os passageiros para frente'], 2,
   'Pela 1ª Lei de Newton, um corpo tende a manter sua velocidade se nenhuma força resultante agir sobre ele. O ônibus desacelera, mas o corpo do passageiro "quer" continuar em movimento: não existe força empurrando-o para frente.', 104),
  ('368838dc-0690-55b6-b79f-c58e891e29b1', 'a1fea6a5-c59f-43d7-8ba9-0e6865d95221',
   'Um cavalo puxa uma carroça. Pela 3ª Lei de Newton, a carroça puxa o cavalo com força de mesma intensidade e sentido oposto. Mesmo assim o conjunto se move porque:',
   array['a força do cavalo é um pouco maior que a da carroça', 'as forças do par ação-reação agem em corpos diferentes; o que acelera o conjunto é o atrito do chão sobre as patas do cavalo', 'ação e reação se anulam, e o conjunto se move por inércia', 'a reação só surge depois que a carroça já está em movimento'], 1,
   'Ação e reação nunca se anulam, porque agem em corpos distintos. Para o sistema cavalo + carroça, a força externa que o acelera é o atrito do solo nas patas do cavalo (a reação ao empurrão que ele dá no chão).', 105),
  ('3ef04855-8eec-5381-9209-4021c9929643', '9cd02d29-4fa4-4a9e-ac80-69ac42eb183a',
   'Espelhos convexos são usados em retrovisores e em saídas de garagem porque formam imagens:',
   array['reais e invertidas', 'virtuais e maiores que o objeto', 'reais e do mesmo tamanho do objeto', 'virtuais, direitas e menores, o que amplia o campo visual'], 3,
   'Para qualquer posição do objeto, o espelho convexo forma imagem virtual, direita e menor. Como as imagens são reduzidas, cabe uma área maior no espelho, ampliando o campo de visão.', 106),
  ('842837e2-a9f3-5640-a8e6-a551f2fa0ebe', 'cff09107-8f47-44a2-a166-8ba7a3c3d6ca',
   'Um objeto está a 30 cm de um espelho côncavo de distância focal 10 cm. A imagem se forma a:',
   array['15 cm do espelho, real, invertida e com metade do tamanho do objeto', '15 cm do espelho, virtual e direita', '30 cm do espelho, real e do mesmo tamanho', '7,5 cm do espelho, real e invertida'], 0,
   '1/p'' = 1/f − 1/p = 1/10 − 1/30 = 2/30, então p'' = 15 cm (positivo: real). Aumento A = −p''/p = −15/30 = −1/2: invertida e com metade do tamanho.', 107),
  ('f3182876-df2a-5fff-a8b6-5c9703020a74', '7d71354e-4686-4b6b-8825-be631b2ad042',
   'Um raio de luz que incide num espelho esférico côncavo passando pelo centro de curvatura reflete-se:',
   array['paralelo ao eixo principal', 'sobre si mesmo', 'passando pelo foco', 'simétrico em relação ao eixo principal'], 1,
   'Um raio que passa pelo centro de curvatura atinge o espelho na direção da normal (o raio da esfera), então volta pelo mesmo caminho. Paralelo ao eixo é o raio que incide passando pelo foco.', 108),
  ('17dab805-4862-53c4-8fc0-3673be576a4f', 'd28fdc19-50a8-4dca-9d0e-98407bfc325b',
   'Uma pessoa hipermetrope tem o ponto próximo a 50 cm. Para ler a 25 cm, ela precisa de lentes com vergência de:',
   array['−2 di', '+4 di', '+2 di', '+0,5 di'], 2,
   'A lente deve formar, de um objeto a 25 cm, uma imagem virtual a 50 cm: V = 1/p + 1/p'' = 1/0,25 − 1/0,5 = 4 − 2 = +2 di. É convergente, como toda correção de hipermetropia.', 109),
  ('582e46d4-4e9c-52f5-8e77-f94d452a5b38', '267de3da-1b72-4c3d-af98-0a38a3bedc32',
   'Uma pessoa míope enxerga nitidamente só até 50 cm (ponto remoto). A lente corretora deve ter vergência de:',
   array['+2 di', '−0,5 di', '−5 di', '−2 di'], 3,
   'A lente divergente deve formar a imagem de objetos no infinito sobre o ponto remoto: f = −50 cm = −0,5 m, e V = 1/f = −2 di.', 110),
  ('dcfaa5f8-44ba-56f4-9a5f-34f3c855d2c1', 'c7c85039-59ec-4178-8acd-9d672c717542',
   'A presbiopia ("vista cansada") ocorre principalmente por:',
   array['perda da capacidade de acomodação do cristalino com a idade', 'alongamento do globo ocular', 'curvatura irregular da córnea', 'opacificação do cristalino'], 0,
   'Com a idade, o cristalino perde elasticidade e não consegue mais aumentar sua curvatura para focalizar objetos próximos. Globo alongado é miopia, córnea irregular é astigmatismo e cristalino opaco é catarata.', 111),
  ('94a5a983-6cea-5b31-be3a-4b23a9b4f98a', '85e6f278-d298-4e1f-aca8-e602debf1051',
   'No efeito fotoelétrico, se a frequência da luz incidente está abaixo da frequência de corte do metal, aumentar a intensidade da luz:',
   array['aumenta a energia cinética dos elétrons emitidos', 'faz os elétrons serem emitidos após algum tempo', 'não provoca emissão de elétrons', 'diminui a função trabalho do metal'], 2,
   'Cada fóton tem energia E = h · f. Se essa energia é menor que a função trabalho, nenhum elétron escapa, não importa quantos fótons cheguem. Mais intensidade é só mais fótons, não fótons mais energéticos. Foi isso que Einstein explicou em 1905.', 112),
  ('f927bea6-bbad-5204-a561-40dbd70c224b', '85e6f278-d298-4e1f-aca8-e602debf1051',
   'Qual é a energia de um fóton de frequência 5 × 10¹⁴ Hz? (Constante de Planck: h = 6,6 × 10⁻³⁴ J·s.)',
   array['3,3 × 10⁻⁴⁸ J', '3,3 × 10⁻¹⁹ J', '1,3 × 10⁻⁴⁸ J', '7,6 × 10⁴⁷ J'], 1,
   'E = h · f = 6,6 × 10⁻³⁴ · 5 × 10¹⁴ = 33 × 10⁻²⁰ = 3,3 × 10⁻¹⁹ J. As demais erram a soma dos expoentes ou dividem em vez de multiplicar.', 113),
  ('47fa07b9-01e4-50a0-855e-a355d692e83e', 'd8f64aef-8abc-45da-9e5d-501798c0d345',
   'Um corpo parte do repouso com aceleração constante de 2 m/s². Qual distância ele percorre apenas durante o 5º segundo do movimento?',
   array['25 m', '16 m', '9 m', '10 m'], 2,
   's = a·t²/2 = t². Até t = 5 s: 25 m; até t = 4 s: 16 m. Durante o 5º segundo: 25 − 16 = 9 m. (25 m é a distância total em 5 s.)', 114),
  ('46e28779-726c-5a8e-8346-4b448eefdb7e', 'd8f64aef-8abc-45da-9e5d-501798c0d345',
   'Um móvel a 10 m/s acelera uniformemente a 3 m/s² ao longo de 16 m. Qual é sua velocidade ao final desse trecho?',
   array['14 m/s', '12 m/s', '19,6 m/s', '16 m/s'], 0,
   'Pela equação de Torricelli, v² = v₀² + 2·a·Δs = 100 + 2 · 3 · 16 = 196, logo v = 14 m/s.', 115),
  ('919fcee4-2beb-5ec8-ba65-d4112024768e', 'fea10bb2-7f2f-40f8-baaf-e398343701aa',
   'Um bloco de 10 kg está em repouso numa superfície horizontal (μe = 0,4; μc = 0,3; g = 10 m/s²) e é empurrado horizontalmente com 30 N. Qual é a força de atrito sobre ele?',
   array['40 N, e o bloco permanece em repouso', '30 N, e o bloco permanece em repouso', '30 N, e o bloco desliza', '0 N'], 1,
   'O atrito estático máximo é μe · N = 0,4 · 100 = 40 N. Como 30 N < 40 N, o bloco não se move, e o atrito estático iguala a força aplicada: 30 N. O atrito só chega a 40 N no limite de escorregar.', 116),
  ('9c066bef-e13d-5485-9231-a1e32d3a64f5', 'ea8116d3-4182-4be6-a7b6-73f969adb43d',
   'Uma pessoa de 60 kg está sobre uma balança dentro de um elevador que sobe acelerando a 2 m/s² (g = 10 m/s²). A força normal que a balança exerce sobre ela vale:',
   array['600 N', '480 N', '120 N', '720 N'], 3,
   'Subindo e acelerando, a resultante aponta para cima: N − P = m · a, então N = m(g + a) = 60 · 12 = 720 N. A balança marca mais do que o peso.', 117),
  ('e4b6f9fe-79e0-522d-99e3-e767a4d3a7ef', '9df1808d-9ac5-4809-8bdb-63e12480aa97',
   'Dois blocos, A (3 kg) e B (2 kg), estão encostados sobre uma superfície sem atrito. Uma força horizontal de 20 N é aplicada em A, empurrando o conjunto. Qual é a força que A exerce sobre B?',
   array['12 N', '20 N', '8 N', '4 N'], 2,
   'Aceleração do conjunto: a = F / (mA + mB) = 20 / 5 = 4 m/s². A única força horizontal em B é a de A: F(AB) = mB · a = 2 · 4 = 8 N.', 118),
  ('cae84771-b646-51b7-9373-f2749360e2ae', '9df1808d-9ac5-4809-8bdb-63e12480aa97',
   'Numa máquina de Atwood ideal, dois blocos de 3 kg e 2 kg estão presos por um fio que passa por uma polia (g = 10 m/s²). A aceleração do sistema e a tração no fio valem:',
   array['2 m/s² e 24 N', '10 m/s² e 20 N', '2 m/s² e 30 N', '5 m/s² e 25 N'], 0,
   'a = (m₁ − m₂) · g / (m₁ + m₂) = 1 · 10 / 5 = 2 m/s². No bloco de 2 kg, que sobe: T − 20 = 2 · 2, logo T = 24 N (conferindo no de 3 kg: 30 − T = 3 · 2).', 119),
  ('92f35e22-ee5d-54d9-974c-b658aeae3345', '2e7f9326-dd6b-4cf9-820b-df10c38fef0c',
   'Um objeto é colocado a 20 cm de um espelho côncavo cujo raio de curvatura mede 40 cm. A imagem será:',
   array['real, a 40 cm do espelho', 'imprópria (formada no infinito)', 'virtual, a 20 cm do espelho', 'real e do mesmo tamanho, a 20 cm do espelho'], 1,
   'O foco fica na metade do raio: f = 20 cm. O objeto está exatamente no foco, então os raios refletidos saem paralelos e não se cruzam: a imagem é imprópria.', 120),
  ('609ba28d-28f3-5281-b8a2-966f5eb06dd9', '4531a57b-6384-4e17-ac73-6ebbe7849d71',
   'Um objeto está a 20 cm de uma lente divergente de distância focal −20 cm. A imagem é:',
   array['real, invertida, a 10 cm da lente', 'virtual, do mesmo tamanho, a 20 cm da lente', 'imprópria', 'virtual, direita, a 10 cm da lente e com metade do tamanho do objeto'], 3,
   '1/p'' = 1/f − 1/p = −1/20 − 1/20 = −1/10, logo p'' = −10 cm (negativo: virtual, do mesmo lado do objeto). A = −p''/p = 10/20 = 1/2: direita e com metade do tamanho.', 121),
  ('800b6e8e-fa70-55b1-9811-c908e0fa669f', '89939da9-3bec-40f4-826d-514c063a9351',
   'Um resistor de 4 Ω está em série com uma associação em paralelo de 6 Ω e 3 Ω, e o conjunto é ligado a uma fonte ideal de 12 V. Qual é a corrente total no circuito?',
   array['1 A', '3 A', '2 A', '0,92 A'], 2,
   'O paralelo de 6 Ω e 3 Ω vale (6 · 3)/(6 + 3) = 2 Ω. Resistência total: 2 + 4 = 6 Ω. Corrente: I = U / R = 12 / 6 = 2 A. (0,92 A seria ligando tudo em série, 13 Ω.)', 122),
  ('bb03b197-88b1-514a-9243-515cd136faa7', '8f3b95a7-93f3-4d62-b383-d9b66d005f08',
   'Uma corda de 1 m, presa nas duas extremidades, transmite ondas a 200 m/s. Qual é a frequência do modo fundamental de vibração?',
   array['100 Hz', '200 Hz', '50 Hz', '400 Hz'], 0,
   'No modo fundamental, a corda forma meio comprimento de onda: λ = 2L = 2 m. Então f = v / λ = 200 / 2 = 100 Hz.', 123)
) as v(id, node, prompt, options, correct_index, explanation, order_index)
join catalog_nodes c on c.id = v.node::uuid
on conflict (id) do nothing;

insert into question_translations (question_id, locale, prompt, options, explanation)
select v.id::uuid, v.locale, v.prompt, v.options, v.explanation
from (values
  ('bb068afe-44f1-5d11-9327-2bfcd56eb829', 'en',
   'A 2 μC charge enters a uniform 0.4 T magnetic field with a speed of 5 × 10³ m/s, perpendicular to the field lines. What is the magnitude of the magnetic force on it?',
   array['zero', '4 × 10⁻³ N', '4 × 10⁻⁶ N', '1 × 10⁻² N'],
   'F = q · v · B · sin θ, with θ = 90°: F = 2 × 10⁻⁶ · 5 × 10³ · 0.4 = 4 × 10⁻³ N. It would be zero only if the velocity were parallel to the field.'),
  ('bb068afe-44f1-5d11-9327-2bfcd56eb829', 'es',
   'Una carga de 2 μC entra con una velocidad de 5 × 10³ m/s, perpendicular a las líneas de un campo magnético uniforme de 0,4 T. ¿Cuál es la intensidad de la fuerza magnética sobre ella?',
   array['cero', '4 × 10⁻³ N', '4 × 10⁻⁶ N', '1 × 10⁻² N'],
   'F = q · v · B · sen θ, con θ = 90°: F = 2 × 10⁻⁶ · 5 × 10³ · 0,4 = 4 × 10⁻³ N. Solo sería cero si la velocidad fuera paralela al campo.'),
  ('4e6945f2-e6ad-5c4f-a154-2a6164caee66', 'en',
   'The north pole of a magnet is moved toward a conducting loop. According to Lenz''s law, an induced current appears in the loop that:',
   array['attracts the magnet, creating a south pole on the face turned toward it', 'is zero, because the magnet does not touch the loop', 'opposes the approach, creating a north pole on the face turned toward the magnet', 'is continuous and remains even when the magnet stops'],
   'The induced current always opposes the change in flux that produced it. To "push back" against the approaching north pole, the loop forms a north pole on the face turned toward the magnet. When the magnet stops, the flux no longer changes and the current stops.'),
  ('4e6945f2-e6ad-5c4f-a154-2a6164caee66', 'es',
   'Se acerca el polo norte de un imán a una espira conductora. Según la ley de Lenz, aparece en la espira una corriente inducida:',
   array['que atrae al imán, creando un polo sur en la cara orientada hacia él', 'nula, porque el imán no toca la espira', 'que se opone al acercamiento, creando un polo norte en la cara orientada hacia el imán', 'continua, que permanece incluso con el imán quieto'],
   'La corriente inducida siempre se opone a la variación del flujo que la produjo. Para "rechazar" el acercamiento del polo norte, la espira forma un polo norte en la cara orientada hacia el imán. Con el imán quieto, el flujo no varía y la corriente cesa.'),
  ('dceb9030-46e2-5324-b405-eec8ce6cff31', 'en',
   'A car traveling at 72 km/h brakes uniformly and stops in 4 s. What are the magnitude of its acceleration and the distance covered while braking?',
   array['18 m/s² and 144 m', '5 m/s² and 80 m', '2.5 m/s² and 40 m', '5 m/s² and 40 m'],
   '72 km/h = 20 m/s. a = Δv / Δt = 20 / 4 = 5 m/s². The distance is the average speed times the time: (20 + 0)/2 · 4 = 40 m.'),
  ('dceb9030-46e2-5324-b405-eec8ce6cff31', 'es',
   'Un auto a 72 km/h frena uniformemente y se detiene en 4 s. ¿Cuáles son el módulo de la aceleración y la distancia recorrida durante el frenado?',
   array['18 m/s² y 144 m', '5 m/s² y 80 m', '2,5 m/s² y 40 m', '5 m/s² y 40 m'],
   '72 km/h = 20 m/s. a = Δv / Δt = 20 / 4 = 5 m/s². La distancia es la velocidad media por el tiempo: (20 + 0)/2 · 4 = 40 m.'),
  ('491a908a-80c1-51e2-9ec8-7587a1a6efdb', 'en',
   'A 70 kg astronaut goes to the Moon, where g = 1.6 m/s². There, the astronaut''s mass and weight are, respectively:',
   array['70 kg and 112 N', '11.2 kg and 112 N', '70 kg and 700 N', '112 kg and 70 N'],
   'Mass does not depend on location: it is still 70 kg. Weight is W = m · g = 70 · 1.6 = 112 N (on Earth it would be 700 N).'),
  ('491a908a-80c1-51e2-9ec8-7587a1a6efdb', 'es',
   'Un astronauta de 70 kg va a la Luna, donde g = 1,6 m/s². Allí, su masa y su peso valen, respectivamente:',
   array['70 kg y 112 N', '11,2 kg y 112 N', '70 kg y 700 N', '112 kg y 70 N'],
   'La masa no depende del lugar: sigue siendo 70 kg. El peso es P = m · g = 70 · 1,6 = 112 N (en la Tierra serían 700 N).'),
  ('883c4484-d50b-5f0b-bfc9-6bba996c4dd6', 'en',
   'When a bus brakes suddenly, standing passengers lurch forward. This happens because:',
   array['a forward force starts acting on the passengers', 'gravity increases during braking', 'the passengers tend to keep the state of motion they had, due to inertia', 'friction with the floor pushes the passengers forward'],
   'By Newton''s first law, a body tends to keep its velocity unless a net force acts on it. The bus slows down, but the passenger''s body "wants" to keep moving: no force is pushing it forward.'),
  ('883c4484-d50b-5f0b-bfc9-6bba996c4dd6', 'es',
   'Cuando un autobús frena bruscamente, los pasajeros de pie se ven proyectados hacia adelante. Esto sucede porque:',
   array['una fuerza hacia adelante comienza a actuar sobre los pasajeros', 'la gravedad aumenta durante el frenado', 'los pasajeros tienden a mantener el estado de movimiento que tenían, por inercia', 'el rozamiento con el piso empuja a los pasajeros hacia adelante'],
   'Por la primera ley de Newton, un cuerpo tiende a mantener su velocidad si ninguna fuerza resultante actúa sobre él. El autobús desacelera, pero el cuerpo del pasajero "quiere" seguir en movimiento: no hay ninguna fuerza que lo empuje hacia adelante.'),
  ('368838dc-0690-55b6-b79f-c58e891e29b1', 'en',
   'A horse pulls a cart. By Newton''s third law, the cart pulls the horse with a force of equal magnitude in the opposite direction. The pair still moves because:',
   array['the horse''s force is slightly greater than the cart''s', 'the action-reaction forces act on different bodies; what accelerates the pair is the friction of the ground on the horse''s hooves', 'action and reaction cancel out, and the pair moves by inertia', 'the reaction only appears after the cart is already moving'],
   'Action and reaction never cancel, because they act on different bodies. For the horse + cart system, the external force that accelerates it is the ground''s friction on the horse''s hooves (the reaction to the horse pushing against the ground).'),
  ('368838dc-0690-55b6-b79f-c58e891e29b1', 'es',
   'Un caballo tira de una carreta. Por la tercera ley de Newton, la carreta tira del caballo con una fuerza de igual intensidad y sentido opuesto. Aun así el conjunto se mueve porque:',
   array['la fuerza del caballo es un poco mayor que la de la carreta', 'las fuerzas del par acción-reacción actúan sobre cuerpos distintos; lo que acelera al conjunto es el rozamiento del suelo sobre las patas del caballo', 'acción y reacción se anulan, y el conjunto se mueve por inercia', 'la reacción solo aparece cuando la carreta ya está en movimiento'],
   'Acción y reacción nunca se anulan, porque actúan sobre cuerpos distintos. Para el sistema caballo + carreta, la fuerza externa que lo acelera es el rozamiento del suelo sobre las patas del caballo (la reacción al empuje que él ejerce sobre el suelo).'),
  ('3ef04855-8eec-5381-9209-4021c9929643', 'en',
   'Convex mirrors are used as rear-view mirrors and at garage exits because they form images that are:',
   array['real and inverted', 'virtual and larger than the object', 'real and the same size as the object', 'virtual, upright and smaller, which widens the field of view'],
   'For any object position, a convex mirror forms a virtual, upright, smaller image. Since the images are reduced, a larger area fits in the mirror, widening the field of view.'),
  ('3ef04855-8eec-5381-9209-4021c9929643', 'es',
   'Los espejos convexos se usan en retrovisores y salidas de garaje porque forman imágenes:',
   array['reales e invertidas', 'virtuales y mayores que el objeto', 'reales y del mismo tamaño que el objeto', 'virtuales, derechas y menores, lo que amplía el campo visual'],
   'Para cualquier posición del objeto, el espejo convexo forma una imagen virtual, derecha y menor. Como las imágenes son reducidas, cabe un área mayor en el espejo, lo que amplía el campo de visión.'),
  ('842837e2-a9f3-5640-a8e6-a551f2fa0ebe', 'en',
   'An object is 30 cm from a concave mirror with a focal length of 10 cm. The image forms:',
   array['15 cm from the mirror, real, inverted and half the size of the object', '15 cm from the mirror, virtual and upright', '30 cm from the mirror, real and the same size', '7.5 cm from the mirror, real and inverted'],
   '1/i = 1/f − 1/o = 1/10 − 1/30 = 2/30, so i = 15 cm (positive: real). Magnification M = −i/o = −15/30 = −1/2: inverted and half the size.'),
  ('842837e2-a9f3-5640-a8e6-a551f2fa0ebe', 'es',
   'Un objeto está a 30 cm de un espejo cóncavo de distancia focal 10 cm. La imagen se forma a:',
   array['15 cm del espejo, real, invertida y con la mitad del tamaño del objeto', '15 cm del espejo, virtual y derecha', '30 cm del espejo, real y del mismo tamaño', '7,5 cm del espejo, real e invertida'],
   '1/p'' = 1/f − 1/p = 1/10 − 1/30 = 2/30, entonces p'' = 15 cm (positivo: real). Aumento A = −p''/p = −15/30 = −1/2: invertida y con la mitad del tamaño.'),
  ('f3182876-df2a-5fff-a8b6-5c9703020a74', 'en',
   'A light ray that strikes a concave spherical mirror after passing through the center of curvature is reflected:',
   array['parallel to the principal axis', 'back along its own path', 'through the focal point', 'symmetrically about the principal axis'],
   'A ray through the center of curvature hits the mirror along the normal (a radius of the sphere), so it returns along the same path. The ray that reflects parallel to the axis is the one that comes in through the focal point.'),
  ('f3182876-df2a-5fff-a8b6-5c9703020a74', 'es',
   'Un rayo de luz que incide en un espejo esférico cóncavo pasando por el centro de curvatura se refleja:',
   array['paralelo al eje principal', 'sobre sí mismo', 'pasando por el foco', 'simétrico respecto al eje principal'],
   'Un rayo que pasa por el centro de curvatura llega al espejo en la dirección de la normal (el radio de la esfera), así que vuelve por el mismo camino. El que se refleja paralelo al eje es el rayo que incide pasando por el foco.'),
  ('17dab805-4862-53c4-8fc0-3673be576a4f', 'en',
   'A farsighted person has a near point of 50 cm. To read at 25 cm, they need lenses with a power of:',
   array['−2 D', '+4 D', '+2 D', '+0.5 D'],
   'The lens must form, from an object at 25 cm, a virtual image at 50 cm: P = 1/o + 1/i = 1/0.25 − 1/0.5 = 4 − 2 = +2 D. It is converging, as every correction for farsightedness is.'),
  ('17dab805-4862-53c4-8fc0-3673be576a4f', 'es',
   'Una persona hipermétrope tiene el punto próximo a 50 cm. Para leer a 25 cm, necesita lentes con una potencia de:',
   array['−2 D', '+4 D', '+2 D', '+0,5 D'],
   'La lente debe formar, a partir de un objeto a 25 cm, una imagen virtual a 50 cm: P = 1/p + 1/p'' = 1/0,25 − 1/0,5 = 4 − 2 = +2 D. Es convergente, como toda corrección de la hipermetropía.'),
  ('582e46d4-4e9c-52f5-8e77-f94d452a5b38', 'en',
   'A nearsighted person sees clearly only up to 50 cm (far point). The corrective lens must have a power of:',
   array['+2 D', '−0.5 D', '−5 D', '−2 D'],
   'The diverging lens must image objects at infinity onto the far point: f = −50 cm = −0.5 m, and P = 1/f = −2 D.'),
  ('582e46d4-4e9c-52f5-8e77-f94d452a5b38', 'es',
   'Una persona miope ve con nitidez solo hasta 50 cm (punto remoto). La lente correctora debe tener una potencia de:',
   array['+2 D', '−0,5 D', '−5 D', '−2 D'],
   'La lente divergente debe formar la imagen de los objetos en el infinito sobre el punto remoto: f = −50 cm = −0,5 m, y P = 1/f = −2 D.'),
  ('dcfaa5f8-44ba-56f4-9a5f-34f3c855d2c1', 'en',
   'Presbyopia ("aging eyes") is mainly caused by:',
   array['the lens losing its ability to accommodate with age', 'elongation of the eyeball', 'irregular curvature of the cornea', 'clouding of the lens'],
   'With age, the lens loses elasticity and can no longer increase its curvature to focus on nearby objects. An elongated eyeball is myopia, an irregular cornea is astigmatism and a cloudy lens is cataract.'),
  ('dcfaa5f8-44ba-56f4-9a5f-34f3c855d2c1', 'es',
   'La presbicia ("vista cansada") se produce principalmente por:',
   array['la pérdida de la capacidad de acomodación del cristalino con la edad', 'el alargamiento del globo ocular', 'la curvatura irregular de la córnea', 'la opacificación del cristalino'],
   'Con la edad, el cristalino pierde elasticidad y ya no puede aumentar su curvatura para enfocar objetos cercanos. El globo alargado es la miopía, la córnea irregular es el astigmatismo y el cristalino opaco es la catarata.'),
  ('94a5a983-6cea-5b31-be3a-4b23a9b4f98a', 'en',
   'In the photoelectric effect, if the frequency of the incident light is below the metal''s threshold frequency, increasing the light''s intensity:',
   array['increases the kinetic energy of the emitted electrons', 'makes electrons come out after some time', 'causes no emission of electrons', 'lowers the metal''s work function'],
   'Each photon has energy E = h · f. If that energy is below the work function, no electron escapes, however many photons arrive. More intensity only means more photons, not more energetic ones. This is what Einstein explained in 1905.'),
  ('94a5a983-6cea-5b31-be3a-4b23a9b4f98a', 'es',
   'En el efecto fotoeléctrico, si la frecuencia de la luz incidente está por debajo de la frecuencia de corte del metal, aumentar la intensidad de la luz:',
   array['aumenta la energía cinética de los electrones emitidos', 'hace que los electrones se emitan después de un tiempo', 'no provoca emisión de electrones', 'disminuye la función de trabajo del metal'],
   'Cada fotón tiene energía E = h · f. Si esa energía es menor que la función de trabajo, ningún electrón escapa, sin importar cuántos fotones lleguen. Más intensidad es solo más fotones, no fotones más energéticos. Eso fue lo que explicó Einstein en 1905.'),
  ('f927bea6-bbad-5204-a561-40dbd70c224b', 'en',
   'What is the energy of a photon with a frequency of 5 × 10¹⁴ Hz? (Planck''s constant: h = 6.6 × 10⁻³⁴ J·s.)',
   array['3.3 × 10⁻⁴⁸ J', '3.3 × 10⁻¹⁹ J', '1.3 × 10⁻⁴⁸ J', '7.6 × 10⁴⁷ J'],
   'E = h · f = 6.6 × 10⁻³⁴ · 5 × 10¹⁴ = 33 × 10⁻²⁰ = 3.3 × 10⁻¹⁹ J. The other options get the exponent sum wrong or divide instead of multiplying.'),
  ('f927bea6-bbad-5204-a561-40dbd70c224b', 'es',
   '¿Cuál es la energía de un fotón de frecuencia 5 × 10¹⁴ Hz? (Constante de Planck: h = 6,6 × 10⁻³⁴ J·s.)',
   array['3,3 × 10⁻⁴⁸ J', '3,3 × 10⁻¹⁹ J', '1,3 × 10⁻⁴⁸ J', '7,6 × 10⁴⁷ J'],
   'E = h · f = 6,6 × 10⁻³⁴ · 5 × 10¹⁴ = 33 × 10⁻²⁰ = 3,3 × 10⁻¹⁹ J. Las demás se equivocan en la suma de los exponentes o dividen en lugar de multiplicar.'),
  ('47fa07b9-01e4-50a0-855e-a355d692e83e', 'en',
   'A body starts from rest with a constant acceleration of 2 m/s². What distance does it cover during the 5th second of motion alone?',
   array['25 m', '16 m', '9 m', '10 m'],
   's = a·t²/2 = t². Up to t = 5 s: 25 m; up to t = 4 s: 16 m. During the 5th second: 25 − 16 = 9 m. (25 m is the total distance in 5 s.)'),
  ('47fa07b9-01e4-50a0-855e-a355d692e83e', 'es',
   'Un cuerpo parte del reposo con aceleración constante de 2 m/s². ¿Qué distancia recorre solo durante el 5.º segundo del movimiento?',
   array['25 m', '16 m', '9 m', '10 m'],
   's = a·t²/2 = t². Hasta t = 5 s: 25 m; hasta t = 4 s: 16 m. Durante el 5.º segundo: 25 − 16 = 9 m. (25 m es la distancia total en 5 s.)'),
  ('46e28779-726c-5a8e-8346-4b448eefdb7e', 'en',
   'A body moving at 10 m/s accelerates uniformly at 3 m/s² over 16 m. What is its speed at the end of that stretch?',
   array['14 m/s', '12 m/s', '19.6 m/s', '16 m/s'],
   'From the Torricelli equation, v² = v₀² + 2·a·Δs = 100 + 2 · 3 · 16 = 196, so v = 14 m/s.'),
  ('46e28779-726c-5a8e-8346-4b448eefdb7e', 'es',
   'Un móvil a 10 m/s acelera uniformemente a 3 m/s² a lo largo de 16 m. ¿Cuál es su velocidad al final de ese tramo?',
   array['14 m/s', '12 m/s', '19,6 m/s', '16 m/s'],
   'Por la ecuación de Torricelli, v² = v₀² + 2·a·Δs = 100 + 2 · 3 · 16 = 196, luego v = 14 m/s.'),
  ('919fcee4-2beb-5ec8-ba65-d4112024768e', 'en',
   'A 10 kg block rests on a horizontal surface (μs = 0.4; μk = 0.3; g = 10 m/s²) and is pushed horizontally with 30 N. What is the friction force on it?',
   array['40 N, and the block stays at rest', '30 N, and the block stays at rest', '30 N, and the block slides', '0 N'],
   'Maximum static friction is μs · N = 0.4 · 100 = 40 N. Since 30 N < 40 N, the block does not move, and static friction equals the applied force: 30 N. Friction only reaches 40 N at the point of slipping.'),
  ('919fcee4-2beb-5ec8-ba65-d4112024768e', 'es',
   'Un bloque de 10 kg está en reposo sobre una superficie horizontal (μe = 0,4; μc = 0,3; g = 10 m/s²) y se lo empuja horizontalmente con 30 N. ¿Cuál es la fuerza de rozamiento sobre él?',
   array['40 N, y el bloque permanece en reposo', '30 N, y el bloque permanece en reposo', '30 N, y el bloque se desliza', '0 N'],
   'El rozamiento estático máximo es μe · N = 0,4 · 100 = 40 N. Como 30 N < 40 N, el bloque no se mueve, y el rozamiento estático iguala a la fuerza aplicada: 30 N. Solo llega a 40 N en el límite de deslizar.'),
  ('9c066bef-e13d-5485-9231-a1e32d3a64f5', 'en',
   'A 60 kg person stands on a scale inside an elevator that is moving up and accelerating at 2 m/s² (g = 10 m/s²). The normal force the scale exerts on the person is:',
   array['600 N', '480 N', '120 N', '720 N'],
   'Moving up and speeding up, the net force points upward: N − W = m · a, so N = m(g + a) = 60 · 12 = 720 N. The scale reads more than the person''s weight.'),
  ('9c066bef-e13d-5485-9231-a1e32d3a64f5', 'es',
   'Una persona de 60 kg está sobre una báscula dentro de un ascensor que sube acelerando a 2 m/s² (g = 10 m/s²). La fuerza normal que la báscula ejerce sobre ella vale:',
   array['600 N', '480 N', '120 N', '720 N'],
   'Subiendo y acelerando, la resultante apunta hacia arriba: N − P = m · a, luego N = m(g + a) = 60 · 12 = 720 N. La báscula marca más que el peso.'),
  ('e4b6f9fe-79e0-522d-99e3-e767a4d3a7ef', 'en',
   'Two blocks, A (3 kg) and B (2 kg), are side by side on a frictionless surface. A 20 N horizontal force is applied to A, pushing both. What force does A exert on B?',
   array['12 N', '20 N', '8 N', '4 N'],
   'Acceleration of the pair: a = F / (mA + mB) = 20 / 5 = 4 m/s². The only horizontal force on B is A''s push: F(AB) = mB · a = 2 · 4 = 8 N.'),
  ('e4b6f9fe-79e0-522d-99e3-e767a4d3a7ef', 'es',
   'Dos bloques, A (3 kg) y B (2 kg), están juntos sobre una superficie sin rozamiento. Se aplica a A una fuerza horizontal de 20 N que empuja al conjunto. ¿Qué fuerza ejerce A sobre B?',
   array['12 N', '20 N', '8 N', '4 N'],
   'Aceleración del conjunto: a = F / (mA + mB) = 20 / 5 = 4 m/s². La única fuerza horizontal sobre B es la de A: F(AB) = mB · a = 2 · 4 = 8 N.'),
  ('cae84771-b646-51b7-9373-f2749360e2ae', 'en',
   'In an ideal Atwood machine, blocks of 3 kg and 2 kg hang from a string over a pulley (g = 10 m/s²). The acceleration of the system and the tension in the string are:',
   array['2 m/s² and 24 N', '10 m/s² and 20 N', '2 m/s² and 30 N', '5 m/s² and 25 N'],
   'a = (m₁ − m₂) · g / (m₁ + m₂) = 1 · 10 / 5 = 2 m/s². For the 2 kg block, which rises: T − 20 = 2 · 2, so T = 24 N (check with the 3 kg block: 30 − T = 3 · 2).'),
  ('cae84771-b646-51b7-9373-f2749360e2ae', 'es',
   'En una máquina de Atwood ideal, dos bloques de 3 kg y 2 kg cuelgan de un hilo que pasa por una polea (g = 10 m/s²). La aceleración del sistema y la tensión del hilo valen:',
   array['2 m/s² y 24 N', '10 m/s² y 20 N', '2 m/s² y 30 N', '5 m/s² y 25 N'],
   'a = (m₁ − m₂) · g / (m₁ + m₂) = 1 · 10 / 5 = 2 m/s². En el bloque de 2 kg, que sube: T − 20 = 2 · 2, luego T = 24 N (comprobando en el de 3 kg: 30 − T = 3 · 2).'),
  ('92f35e22-ee5d-54d9-974c-b658aeae3345', 'en',
   'An object is placed 20 cm from a concave mirror whose radius of curvature is 40 cm. The image will be:',
   array['real, 40 cm from the mirror', 'at infinity (no image forms at a finite distance)', 'virtual, 20 cm from the mirror', 'real and the same size, 20 cm from the mirror'],
   'The focal point is at half the radius: f = 20 cm. The object is exactly at the focus, so the reflected rays come out parallel and never cross: the image is at infinity.'),
  ('92f35e22-ee5d-54d9-974c-b658aeae3345', 'es',
   'Se coloca un objeto a 20 cm de un espejo cóncavo cuyo radio de curvatura mide 40 cm. La imagen será:',
   array['real, a 40 cm del espejo', 'impropia (formada en el infinito)', 'virtual, a 20 cm del espejo', 'real y del mismo tamaño, a 20 cm del espejo'],
   'El foco está en la mitad del radio: f = 20 cm. El objeto está justo en el foco, así que los rayos reflejados salen paralelos y no se cruzan: la imagen es impropia.'),
  ('609ba28d-28f3-5281-b8a2-966f5eb06dd9', 'en',
   'An object is 20 cm from a diverging lens with a focal length of −20 cm. The image is:',
   array['real, inverted, 10 cm from the lens', 'virtual, the same size, 20 cm from the lens', 'at infinity', 'virtual, upright, 10 cm from the lens and half the size of the object'],
   '1/i = 1/f − 1/o = −1/20 − 1/20 = −1/10, so i = −10 cm (negative: virtual, on the same side as the object). M = −i/o = 10/20 = 1/2: upright and half the size.'),
  ('609ba28d-28f3-5281-b8a2-966f5eb06dd9', 'es',
   'Un objeto está a 20 cm de una lente divergente de distancia focal −20 cm. La imagen es:',
   array['real, invertida, a 10 cm de la lente', 'virtual, del mismo tamaño, a 20 cm de la lente', 'impropia', 'virtual, derecha, a 10 cm de la lente y con la mitad del tamaño del objeto'],
   '1/p'' = 1/f − 1/p = −1/20 − 1/20 = −1/10, luego p'' = −10 cm (negativo: virtual, del mismo lado que el objeto). A = −p''/p = 10/20 = 1/2: derecha y con la mitad del tamaño.'),
  ('800b6e8e-fa70-55b1-9811-c908e0fa669f', 'en',
   'A 4 Ω resistor is in series with a parallel combination of 6 Ω and 3 Ω, and the whole circuit is connected to an ideal 12 V source. What is the total current in the circuit?',
   array['1 A', '3 A', '2 A', '0.92 A'],
   'The 6 Ω and 3 Ω in parallel give (6 · 3)/(6 + 3) = 2 Ω. Total resistance: 2 + 4 = 6 Ω. Current: I = V / R = 12 / 6 = 2 A. (0.92 A would be with everything in series, 13 Ω.)'),
  ('800b6e8e-fa70-55b1-9811-c908e0fa669f', 'es',
   'Un resistor de 4 Ω está en serie con una asociación en paralelo de 6 Ω y 3 Ω, y el conjunto se conecta a una fuente ideal de 12 V. ¿Cuál es la corriente total en el circuito?',
   array['1 A', '3 A', '2 A', '0,92 A'],
   'El paralelo de 6 Ω y 3 Ω vale (6 · 3)/(6 + 3) = 2 Ω. Resistencia total: 2 + 4 = 6 Ω. Corriente: I = V / R = 12 / 6 = 2 A. (0,92 A sería conectando todo en serie, 13 Ω.)'),
  ('bb03b197-88b1-514a-9243-515cd136faa7', 'en',
   'A 1 m string fixed at both ends carries waves at 200 m/s. What is the frequency of its fundamental mode of vibration?',
   array['100 Hz', '200 Hz', '50 Hz', '400 Hz'],
   'In the fundamental mode, the string holds half a wavelength: λ = 2L = 2 m. So f = v / λ = 200 / 2 = 100 Hz.'),
  ('bb03b197-88b1-514a-9243-515cd136faa7', 'es',
   'Una cuerda de 1 m, fija en ambos extremos, transmite ondas a 200 m/s. ¿Cuál es la frecuencia del modo fundamental de vibración?',
   array['100 Hz', '200 Hz', '50 Hz', '400 Hz'],
   'En el modo fundamental, la cuerda forma media longitud de onda: λ = 2L = 2 m. Entonces f = v / λ = 200 / 2 = 100 Hz.')
) as v(id, locale, prompt, options, explanation)
join questions q
  on q.id = v.id::uuid
 and cardinality(q.options) = cardinality(v.options)
on conflict (question_id, locale) do update
  set prompt = excluded.prompt,
      options = excluded.options,
      explanation = excluded.explanation;
