-- História — Brasil Contemporâneo (3 leaves, 5 questões cada)
insert into questions (catalog_node_id, prompt, options, correct_index, explanation, order_index) values
-- República de 1946 (5508a9c1-91a7-463b-bf08-a36f296d2251)
('5508a9c1-91a7-463b-bf08-a36f296d2251', 'A Constituição de 1946, promulgada após a redemocratização, restabeleceu:',
  array['O regime democrático, com eleições diretas e divisão de poderes', 'O regime de exceção do Estado Novo', 'A monarquia constitucional', 'O parlamentarismo como forma definitiva de governo'], 0,
  'A Carta de 1946 restaurou princípios democráticos e liberais, revogados durante o Estado Novo, como eleições diretas e liberdades civis.', 1),
('5508a9c1-91a7-463b-bf08-a36f296d2251', 'O suicídio de Getúlio Vargas, então presidente eleito, ocorreu em:',
  array['1954, em meio a uma grave crise política', '1945, no momento de sua deposição', '1961, durante a crise da renúncia de Jânio Quadros', '1964, com o golpe militar'], 0,
  'Vargas, eleito presidente em 1950, suicidou-se em agosto de 1954 diante de intensa pressão política e militar por sua renúncia.', 2),
('5508a9c1-91a7-463b-bf08-a36f296d2251', 'Juscelino Kubitschek, presidente entre 1956 e 1961, ficou marcado principalmente por:',
  array['O Plano de Metas e a construção de Brasília, a nova capital federal', 'A ruptura com os Estados Unidos', 'A implantação de uma ditadura militar', 'A nacionalização imediata de todas as empresas estrangeiras'], 0,
  'JK promoveu forte industrialização com o Plano de Metas ("50 anos em 5") e construiu Brasília, inaugurada em 1960.', 3),
('5508a9c1-91a7-463b-bf08-a36f296d2251', 'A renúncia de Jânio Quadros à presidência, em agosto de 1961, apenas sete meses após assumir o cargo, gerou:',
  array['Uma crise política em torno da posse do vice-presidente João Goulart', 'A imediata dissolução do Congresso Nacional', 'A convocação de novas eleições diretas imediatas', 'A restauração do Estado Novo'], 0,
  'A renúncia de Jânio abriu uma crise de sucessão, resolvida com a adoção do parlamentarismo como solução de compromisso para viabilizar a posse de João Goulart.', 4),
('5508a9c1-91a7-463b-bf08-a36f296d2251', 'Para viabilizar a posse de João Goulart em 1961, diante da resistência de setores militares, foi adotado temporariamente o sistema:',
  array['Parlamentarista, posteriormente revogado por plebiscito em 1963', 'Presidencialista pleno, sem restrições', 'Monárquico constitucional', 'De junta militar provisória'], 0,
  'O parlamentarismo foi uma solução de compromisso para reduzir os poderes de Jango; foi rejeitado em plebiscito popular em 1963, restaurando o presidencialismo.', 5),

-- Ditadura Militar (5bc5ce90-bf36-45a1-97fc-156a2423ae89)
('5bc5ce90-bf36-45a1-97fc-156a2423ae89', 'O golpe civil-militar de 1964, que depôs o presidente João Goulart, teve entre suas principais justificativas alegadas:',
  array['O combate ao avanço do comunismo e às Reformas de Base propostas por Jango', 'A necessidade de restaurar a monarquia', 'A crise do café de 1930', 'A eclosão da Segunda Guerra Mundial'], 0,
  'Setores militares e civis conservadores justificaram o golpe como forma de deter o que consideravam avanço comunista e as reformas de base de Goulart.', 1),
('5bc5ce90-bf36-45a1-97fc-156a2423ae89', 'O Ato Institucional nº 5 (AI-5), decretado em dezembro de 1968, é considerado o instrumento que:',
  array['Endureceu drasticamente o regime, suspendendo garantias constitucionais e fechando o Congresso', 'Iniciou o processo de abertura política', 'Restabeleceu eleições diretas para presidente', 'Extinguiu a censura à imprensa'], 0,
  'O AI-5 marcou o período mais repressivo da ditadura, concedendo poderes excepcionais ao presidente e fechando o Legislativo.', 2),
('5bc5ce90-bf36-45a1-97fc-156a2423ae89', 'O período conhecido como "milagre econômico" (1969-1973), durante a ditadura militar, caracterizou-se por:',
  array['Altas taxas de crescimento econômico combinadas com aumento da concentração de renda', 'Estagnação total da economia brasileira', 'Hiperinflação descontrolada desde o início', 'Redução acentuada da desigualdade social'], 0,
  'O "milagre econômico" trouxe crescimento acelerado do PIB, mas às custas de arrocho salarial e concentração de renda.', 3),
('5bc5ce90-bf36-45a1-97fc-156a2423ae89', 'O movimento "Diretas Já", em 1983-1984, reivindicava:',
  array['Eleições diretas para presidente da República', 'A volta da monarquia', 'A manutenção do regime militar', 'A adoção do parlamentarismo'], 0,
  'O movimento popular pelas Diretas Já mobilizou milhões de brasileiros exigindo eleições diretas, ainda que a emenda tenha sido rejeitada pelo Congresso em 1984.', 4),
('5bc5ce90-bf36-45a1-97fc-156a2423ae89', 'A ditadura militar brasileira (1964-1985) foi marcada pela adoção de vários Atos Institucionais, utilizados para:',
  array['Conceder poderes excepcionais ao Executivo e restringir direitos políticos e civis', 'Ampliar os poderes do Congresso Nacional', 'Fortalecer o Poder Judiciário independente', 'Descentralizar o poder para os estados'], 0,
  'Os Atos Institucionais foram o principal instrumento jurídico usado pelos militares para concentrar poder e reprimir opositores durante o regime.', 5),

-- Nova República (7740f68e-21bc-47e1-8052-848e287f27dd)
('7740f68e-21bc-47e1-8052-848e287f27dd', 'A eleição de Tancredo Neves, em 1985, ocorreu ainda de forma:',
  array['Indireta, por um colégio eleitoral, marcando o fim formal do regime militar', 'Direta, pelo voto popular', 'Por indicação exclusiva dos militares', 'Por plebiscito nacional'], 0,
  'Tancredo Neves foi eleito indiretamente pelo Colégio Eleitoral em 1985, mas faleceu antes de tomar posse, sendo substituído por José Sarney.', 1),
('7740f68e-21bc-47e1-8052-848e287f27dd', 'A Constituição de 1988, conhecida como "Constituição Cidadã", é reconhecida por:',
  array['Ampliar significativamente os direitos individuais, sociais e políticos após o período ditatorial', 'Restringir o direito ao voto a uma pequena parcela da população', 'Manter a censura à imprensa', 'Instituir novamente o regime de exceção'], 0,
  'A Constituição de 1988 ampliou direitos civis, sociais e políticos, consolidando a redemocratização do país após a ditadura militar.', 2),
('7740f68e-21bc-47e1-8052-848e287f27dd', 'A primeira eleição presidencial por voto direto após a ditadura ocorreu em:',
  array['1989, vencida por Fernando Collor de Mello', '1985, vencida por Tancredo Neves', '1994, vencida por Fernando Henrique Cardoso', '1982, ainda sob o regime militar'], 0,
  'Em 1989, os brasileiros voltaram a eleger diretamente o presidente da República, com vitória de Fernando Collor.', 3),
('7740f68e-21bc-47e1-8052-848e287f27dd', 'O processo de impeachment de Fernando Collor, em 1992, foi motivado principalmente por:',
  array['Acusações de corrupção envolvendo um esquema de arrecadação ilegal de recursos', 'A adoção de um plano de estabilização monetária', 'A recusa em realizar eleições', 'Um golpe militar em curso'], 0,
  'Denúncias de um esquema de corrupção liderado por Paulo César Farias levaram à abertura do processo, e Collor renunciou pouco antes da votação final no Senado.', 4),
('7740f68e-21bc-47e1-8052-848e287f27dd', 'O Plano Real, implementado em 1994 no governo Itamar Franco, teve como principal objetivo:',
  array['Estabilizar a economia e controlar a hiperinflação que assolava o país', 'Estatizar todas as empresas privadas', 'Reinstaurar o padrão-ouro', 'Reduzir a jornada de trabalho nacionalmente'], 0,
  'O Plano Real conseguiu debelar a hiperinflação crônica, introduzindo uma nova moeda e mecanismos de estabilização macroeconômica.', 5);
