-- História — Áreas gerais sem subdivisão (7 leaves, 8 questões cada)
insert into questions (catalog_node_id, prompt, options, correct_index, explanation, order_index) values
-- Antiguidade (143ae168-abcf-4512-a0c7-3c67e34e9fcb)
('143ae168-abcf-4512-a0c7-3c67e34e9fcb', 'A Mesopotâmia, uma das primeiras civilizações da história, desenvolveu-se na região banhada pelos rios:',
  array['Tigre e Eufrates', 'Nilo e Jordão', 'Indo e Ganges', 'Amarelo e Yangtzé'], 0,
  'A Mesopotâmia ("terra entre rios") situava-se entre os rios Tigre e Eufrates, no atual Iraque.', 1),
('143ae168-abcf-4512-a0c7-3c67e34e9fcb', 'O Código de Hamurábi, um dos primeiros conjuntos de leis escritas da história, foi elaborado na:',
  array['Babilônia', 'Grécia Antiga', 'Roma Antiga', 'China Antiga'], 0,
  'O Código de Hamurábi, datado de cerca de 1750 a.C., regulava a vida social, econômica e jurídica da Babilônia, baseando-se na lei de talião.', 2),
('143ae168-abcf-4512-a0c7-3c67e34e9fcb', 'A civilização egípcia antiga desenvolveu-se ao longo do rio Nilo, cujas cheias periódicas eram fundamentais para:',
  array['Fertilizar as terras e viabilizar a agricultura', 'Impedir qualquer forma de agricultura', 'Isolar completamente o Egito de outros povos', 'Facilitar apenas a navegação militar'], 0,
  'As cheias anuais do Nilo depositavam limo fértil nas margens, sustentando a agricultura que foi a base da economia egípcia.', 3),
('143ae168-abcf-4512-a0c7-3c67e34e9fcb', 'Na Grécia Antiga, Atenas ficou historicamente conhecida por ser o berço:',
  array['Da democracia direta, com participação política dos cidadãos livres', 'Do sistema republicano representativo moderno', 'Do primeiro império territorial da história', 'Do monoteísmo ocidental'], 0,
  'Atenas desenvolveu a democracia direta, na qual cidadãos (homens livres) participavam diretamente das decisões políticas.', 4),
('143ae168-abcf-4512-a0c7-3c67e34e9fcb', 'Esparta, cidade-estado grega rival de Atenas, era conhecida principalmente por sua organização social voltada para:',
  array['A formação militar rigorosa de seus cidadãos', 'O comércio marítimo intenso', 'O desenvolvimento das artes e da filosofia', 'A democracia direta plena'], 0,
  'Esparta priorizava a disciplina militar, com um sistema educacional (agogé) voltado à formação de guerreiros desde a infância.', 5),
('143ae168-abcf-4512-a0c7-3c67e34e9fcb', 'A Guerra do Peloponeso, travada entre Atenas e Esparta no século V a.C., resultou:',
  array['Na vitória de Esparta e no enfraquecimento geral das cidades-estado gregas', 'Na unificação política permanente da Grécia', 'Na vitória definitiva de Atenas', 'Na formação do Império Macedônico'], 0,
  'A guerra terminou com a vitória espartana, mas enfraqueceu profundamente todas as cidades-estado gregas.', 6),
('143ae168-abcf-4512-a0c7-3c67e34e9fcb', 'Roma, fundada segundo a tradição em 753 a.C., passou ao longo de sua história por três formas principais de governo, na seguinte ordem:',
  array['Monarquia, República e Império', 'Império, República e Monarquia', 'República, Monarquia e Império', 'Apenas República durante toda sua existência'], 0,
  'A tradição histórica romana reconhece a sucessão de Monarquia (753-509 a.C.), República (509-27 a.C.) e Império (27 a.C. em diante).', 7),
('143ae168-abcf-4512-a0c7-3c67e34e9fcb', 'As Guerras Púnicas, travadas entre Roma e Cartago, tiveram como resultado final:',
  array['A destruição de Cartago e a hegemonia romana no Mediterrâneo ocidental', 'A vitória cartaginesa e a conquista de Roma', 'Uma aliança permanente entre as duas potências', 'A fundação conjunta do Império Romano'], 0,
  'Após três guerras (264-146 a.C.), Roma destruiu Cartago na Terceira Guerra Púnica, consolidando seu domínio no Mediterrâneo ocidental.', 8),

-- Idade Média (c14f34bc-fdf8-4797-88a6-14fafbad4194)
('c14f34bc-fdf8-4797-88a6-14fafbad4194', 'O feudalismo, sistema socioeconômico predominante na Europa medieval, baseava-se principalmente:',
  array['Nas relações de suserania e vassalagem, e no trabalho servil na terra', 'No comércio marítimo em larga escala', 'Na indústria manufatureira urbana', 'No trabalho assalariado livre'], 0,
  'O feudalismo organizava-se em torno da posse da terra (feudo), das relações de vassalagem e do trabalho servil dos camponeses.', 1),
('c14f34bc-fdf8-4797-88a6-14fafbad4194', 'Na sociedade feudal, os servos se diferenciavam dos escravos antigos principalmente porque:',
  array['Não podiam ser vendidos separadamente da terra a que estavam vinculados', 'Recebiam salário integral por seu trabalho', 'Tinham total liberdade de locomoção', 'Ocupavam o topo da hierarquia social'], 0,
  'Os servos estavam presos à terra, mas deviam obrigações e trabalho ao senhor feudal em troca de proteção.', 2),
('c14f34bc-fdf8-4797-88a6-14fafbad4194', 'A Igreja Católica, durante a Idade Média, exerceu grande influência na sociedade europeia principalmente por meio:',
  array['Do controle sobre a educação, a cultura e a legitimação do poder político', 'Do controle exclusivo das rotas comerciais marítimas', 'Da ausência total de propriedades de terra', 'Do apoio incondicional a todas as heresias'], 0,
  'A Igreja dominava a produção cultural e educacional e legitimava religiosamente o poder dos monarcas e senhores feudais.', 3),
('c14f34bc-fdf8-4797-88a6-14fafbad4194', 'As Cruzadas, expedições militares religiosas promovidas pela cristandade europeia a partir do século XI, tinham como principal objetivo declarado:',
  array['Retomar a Terra Santa (Jerusalém) do domínio muçulmano', 'Conquistar a China', 'Evangelizar exclusivamente a América', 'Combater o Império Bizantino'], 0,
  'As Cruzadas buscavam, oficialmente, retomar Jerusalém e outros locais sagrados do controle muçulmano.', 4),
('c14f34bc-fdf8-4797-88a6-14fafbad4194', 'A Peste Negra, epidemia que assolou a Europa no século XIV, teve como uma de suas principais consequências:',
  array['Uma drástica redução populacional, com impactos profundos na economia e na estrutura social feudal', 'O fortalecimento imediato do sistema feudal', 'A imediata unificação política da Europa', 'O fim total do comércio europeu'], 0,
  'A peste dizimou entre um quarto e um terço da população europeia, provocando escassez de mão de obra e crise do feudalismo.', 5),
('c14f34bc-fdf8-4797-88a6-14fafbad4194', 'O Império Bizantino, herdeiro do Império Romano do Oriente, teve como sua capital:',
  array['Constantinopla', 'Roma', 'Atenas', 'Alexandria'], 0,
  'Constantinopla (atual Istambul), fundada por Constantino, foi a capital do Império Bizantino até sua queda em 1453.', 6),
('c14f34bc-fdf8-4797-88a6-14fafbad4194', 'A expansão do Islã, a partir do século VII, teve grande impacto na região do Mediterrâneo e do Oriente Médio, unificando vastos territórios sob:',
  array['Uma nova religião monoteísta e uma estrutura política e cultural comum', 'O domínio direto do Império Bizantino', 'O controle da Igreja Católica romana', 'Uma federação de reinos cristãos'], 0,
  'A expansão islâmica criou um vasto califado que unificava territórios sob uma mesma fé e cultura.', 7),
('c14f34bc-fdf8-4797-88a6-14fafbad4194', 'A queda de Constantinopla, em 1453, para os turcos otomanos, é tradicionalmente utilizada pela historiografia como um marco:',
  array['Do fim da Idade Média e início da Idade Moderna', 'Do início da Idade Média', 'Do fim do Império Romano do Ocidente', 'Do início das Cruzadas'], 0,
  'A tomada de Constantinopla pelos otomanos em 1453 é um dos marcos convencionais usados para delimitar o fim da Idade Média.', 8),

-- Idade Moderna (e93f87be-ca79-4813-9a67-616320aa9a8a)
('e93f87be-ca79-4813-9a67-616320aa9a8a', 'O Renascimento, movimento cultural e artístico que floresceu a partir do século XIV, teve como um de seus principais centros iniciais:',
  array['As cidades-estado italianas, como Florença', 'A Espanha unificada', 'A Rússia czarista', 'O Império Otomano'], 0,
  'O Renascimento surgiu inicialmente nas prósperas cidades-estado italianas, como Florença, sob o mecenato de famílias como os Médici.', 1),
('e93f87be-ca79-4813-9a67-616320aa9a8a', 'O Renascimento valorizava, entre outros aspectos, o(a):',
  array['Antropocentrismo, com maior valorização do ser humano e da razão em relação ao teocentrismo medieval', 'Teocentrismo absoluto, ainda mais acentuado que na Idade Média', 'Rejeição total da cultura clássica greco-romana', 'Total desprezo pelas artes e pela ciência'], 0,
  'O pensamento renascentista deslocou o foco do divino para o ser humano e a razão, retomando referências clássicas.', 2),
('e93f87be-ca79-4813-9a67-616320aa9a8a', 'A Reforma Protestante, iniciada por Martinho Lutero em 1517, teve como um de seus estopins imediatos:',
  array['A crítica à venda de indulgências pela Igreja Católica', 'A descoberta da América', 'A invenção da imprensa', 'A morte do Papa Leão X'], 0,
  'Lutero publicou as 95 teses criticando, entre outras práticas, a venda de indulgências, dando início ao movimento de Reforma.', 3),
('e93f87be-ca79-4813-9a67-616320aa9a8a', 'O Calvinismo, vertente protestante fundada por João Calvino, teve grande influência em regiões como:',
  array['Suíça, Holanda e parte da França', 'Espanha e Portugal', 'Estados italianos', 'Império Otomano'], 0,
  'O calvinismo se difundiu especialmente na Suíça (Genebra), na Holanda e entre os huguenotes franceses.', 4),
('e93f87be-ca79-4813-9a67-616320aa9a8a', 'O absolutismo monárquico, sistema político predominante em boa parte da Europa moderna, caracterizava-se por:',
  array['A concentração de poder político nas mãos do rei, frequentemente justificada pela teoria do direito divino', 'A divisão equilibrada de poderes entre Executivo, Legislativo e Judiciário', 'A soberania popular direta', 'A ausência total de exércitos permanentes'], 0,
  'No absolutismo, o monarca concentrava amplos poderes, muitas vezes legitimados pela ideia de que seu poder vinha diretamente de Deus.', 5),
('e93f87be-ca79-4813-9a67-616320aa9a8a', 'As Grandes Navegações, iniciadas por Portugal e Espanha a partir do século XV, foram impulsionadas, entre outros fatores, por:',
  array['A busca por novas rotas comerciais para o Oriente e por metais preciosos', 'O desejo exclusivo de expandir o cristianismo sem interesses econômicos', 'A necessidade de fugir de epidemias na Europa', 'Um acordo com o Império Otomano para dividir rotas comerciais'], 0,
  'Motivações econômicas, religiosas e políticas impulsionaram a expansão marítima ibérica.', 6),
('e93f87be-ca79-4813-9a67-616320aa9a8a', 'O Iluminismo, movimento filosófico do século XVIII, defendia principalmente:',
  array['O uso da razão como principal instrumento para compreender e transformar a sociedade, criticando o absolutismo', 'O fortalecimento incondicional do poder absoluto dos reis', 'A manutenção da sociedade estamental sem mudanças', 'A rejeição total da ciência'], 0,
  'Pensadores iluministas como Voltaire, Montesquieu e Rousseau defendiam a razão e a liberdade individual, criticando os privilégios do Antigo Regime.', 7),
('e93f87be-ca79-4813-9a67-616320aa9a8a', 'O mercantilismo, política econômica predominante nas monarquias absolutistas europeias, caracterizava-se por:',
  array['Forte intervenção estatal na economia, balança comercial favorável e acúmulo de metais preciosos', 'Livre mercado sem qualquer intervenção do Estado', 'Rejeição do comércio colonial', 'Incentivo à livre concorrência entre colônias e metrópoles'], 0,
  'O mercantilismo pregava intervenção estatal, protecionismo e acúmulo de metais preciosos como medida de riqueza nacional.', 8),

-- Idade Contemporânea (9d1627ca-eade-4dcf-83dc-a1acfcd096c8)
('9d1627ca-eade-4dcf-83dc-a1acfcd096c8', 'A Revolução Francesa, iniciada em 1789, teve como um de seus marcos iniciais:',
  array['A Queda da Bastilha', 'A execução de Napoleão Bonaparte', 'A unificação da Alemanha', 'A assinatura da Declaração de Independência dos Estados Unidos'], 0,
  'A Queda da Bastilha, em 14 de julho de 1789, é considerada o marco simbólico do início da Revolução Francesa.', 1),
('9d1627ca-eade-4dcf-83dc-a1acfcd096c8', 'A Declaração dos Direitos do Homem e do Cidadão, de 1789, consagrou princípios como:',
  array['Liberdade, igualdade e propriedade como direitos naturais', 'A manutenção dos privilégios da nobreza e do clero', 'A restauração da monarquia absoluta', 'A escravidão como instituição legítima e universal'], 0,
  'O documento consagrou princípios iluministas de liberdade e igualdade perante a lei, rompendo com os privilégios do Antigo Regime.', 2),
('9d1627ca-eade-4dcf-83dc-a1acfcd096c8', 'Napoleão Bonaparte, que ascendeu ao poder após a Revolução Francesa, foi finalmente derrotado definitivamente na batalha de:',
  array['Waterloo, em 1815', 'Trafalgar, em 1805', 'Austerlitz, em 1805', 'Leipzig, em 1813'], 0,
  'Após retornar do exílio na Ilha de Elba, Napoleão foi derrotado definitivamente em Waterloo, em junho de 1815.', 3),
('9d1627ca-eade-4dcf-83dc-a1acfcd096c8', 'A Revolução Industrial, iniciada na Inglaterra no século XVIII, foi marcada, entre outros aspectos, por:',
  array['A introdução de máquinas a vapor e a transição do trabalho artesanal para a produção fabril', 'O fim total do trabalho assalariado', 'A predominância exclusiva da produção agrícola', 'O desaparecimento das cidades'], 0,
  'A Revolução Industrial trouxe a mecanização da produção, com destaque para a máquina a vapor, transformando a economia e a sociedade.', 4),
('9d1627ca-eade-4dcf-83dc-a1acfcd096c8', 'A Primeira Guerra Mundial (1914-1918) teve como estopim imediato:',
  array['O assassinato do arquiduque Francisco Ferdinando, da Áustria-Hungria, em Sarajevo', 'A Revolução Russa', 'A ascensão de Hitler ao poder', 'A crise de 1929'], 0,
  'O assassinato do herdeiro do trono austro-húngaro em Sarajevo, em junho de 1914, desencadeou a cadeia de alianças que resultou na guerra.', 5),
('9d1627ca-eade-4dcf-83dc-a1acfcd096c8', 'A Revolução Russa de 1917 resultou na:',
  array['Derrubada do czarismo e na instauração do primeiro Estado socialista do mundo', 'Manutenção da monarquia czarista', 'Vitória da Alemanha na Primeira Guerra Mundial', 'Unificação da Rússia com os Estados Unidos'], 0,
  'A Revolução de 1917, liderada pelos bolcheviques sob Lenin, derrubou o governo provisório e instaurou o regime que originaria a União Soviética.', 6),
('9d1627ca-eade-4dcf-83dc-a1acfcd096c8', 'A Segunda Guerra Mundial (1939-1945) teve início formal com:',
  array['A invasão da Polônia pela Alemanha nazista', 'O ataque japonês a Pearl Harbor', 'O lançamento das bombas atômicas sobre o Japão', 'A ascensão de Mussolini na Itália'], 0,
  'A invasão alemã à Polônia, em setembro de 1939, levou Inglaterra e França a declararem guerra à Alemanha, marcando o início formal do conflito.', 7),
('9d1627ca-eade-4dcf-83dc-a1acfcd096c8', 'A Guerra Fria, que dividiu o mundo em dois blocos após a Segunda Guerra Mundial, opôs principalmente:',
  array['Estados Unidos (capitalismo) e União Soviética (socialismo)', 'Alemanha e França', 'China e Japão', 'Inglaterra e Portugal'], 0,
  'A Guerra Fria caracterizou-se pela disputa ideológica, política e militar entre EUA e URSS e seus respectivos blocos de influência.', 8),

-- História da América (3a6764c6-67a5-4941-b3c0-aa0b5e17a190)
('3a6764c6-67a5-4941-b3c0-aa0b5e17a190', 'Antes da chegada dos europeus, uma das civilizações mais desenvolvidas da América Central foi a dos:',
  array['Astecas, com capital na cidade de Tenochtitlán', 'Fenícios', 'Persas', 'Vikings'], 0,
  'Os astecas construíram um vasto império mesoamericano com capital em Tenochtitlán, no local da atual Cidade do México.', 1),
('3a6764c6-67a5-4941-b3c0-aa0b5e17a190', 'O Império Inca, uma das grandes civilizações pré-colombianas da América do Sul, desenvolveu-se principalmente na região:',
  array['Dos Andes, com centro no atual Peru', 'Da Amazônia', 'Do Caribe', 'Da Patagônia'], 0,
  'O Império Inca se estendeu ao longo da Cordilheira dos Andes, com Cusco, no atual Peru, como sua capital.', 2),
('3a6764c6-67a5-4941-b3c0-aa0b5e17a190', 'A conquista espanhola do Império Asteca, liderada por Hernán Cortés, foi concluída em:',
  array['1521', '1500', '1650', '1789'], 0,
  'Hernán Cortés conquistou Tenochtitlán, capital asteca, em 1521, com apoio de povos indígenas rivais dos astecas.', 3),
('3a6764c6-67a5-4941-b3c0-aa0b5e17a190', 'A colonização espanhola na América caracterizou-se, entre outros aspectos, pela exploração intensiva de:',
  array['Metais preciosos, como prata e ouro, sobretudo em Potosí', 'Especiarias asiáticas', 'Petróleo', 'Manufaturados industriais'], 0,
  'A exploração de metais preciosos, com destaque para as minas de prata de Potosí (atual Bolívia), foi central na economia colonial espanhola.', 4),
('3a6764c6-67a5-4941-b3c0-aa0b5e17a190', 'A independência dos Estados Unidos, proclamada em 1776, teve entre suas causas centrais:',
  array['A insatisfação das treze colônias com a tributação imposta pela Inglaterra sem representação política', 'Uma invasão francesa ao território americano', 'A abolição da escravidão pela coroa britânica', 'A descoberta de ouro na Califórnia'], 0,
  'O princípio de "no taxation without representation" resumia a insatisfação colonial com impostos britânicos sem representação política correspondente.', 5),
('3a6764c6-67a5-4941-b3c0-aa0b5e17a190', 'Simón Bolívar é uma figura histórica central nos processos de independência de países como:',
  array['Venezuela, Colômbia, Equador e Bolívia', 'Estados Unidos e Canadá', 'México e Cuba, exclusivamente', 'Brasil e Portugal'], 0,
  'Bolívar liderou movimentos de independência em diversas regiões da América espanhola, sendo homenageado inclusive no nome da Bolívia.', 6),
('3a6764c6-67a5-4941-b3c0-aa0b5e17a190', 'A Revolução Mexicana, iniciada em 1910, teve entre suas principais bandeiras:',
  array['A reforma agrária e o fim de governos autoritários, como o de Porfírio Díaz', 'A restauração da monarquia', 'A anexação do México aos Estados Unidos', 'A manutenção do status quo social vigente'], 0,
  'Lideranças como Emiliano Zapata e Pancho Villa lutaram por reforma agrária e mudanças políticas, encerrando o longo governo de Porfírio Díaz.', 7),
('3a6764c6-67a5-4941-b3c0-aa0b5e17a190', 'A Revolução Cubana, liderada por Fidel Castro e vitoriosa em 1959, resultou:',
  array['Na derrubada do ditador Fulgencio Batista e na posterior implantação de um regime socialista em Cuba', 'Na manutenção do governo de Batista', 'Na anexação de Cuba aos Estados Unidos', 'Na restauração da monarquia espanhola em Cuba'], 0,
  'A revolução depôs Batista e, nos anos seguintes, Cuba se alinhou ao bloco socialista, tornando-se um Estado de partido único sob Fidel Castro.', 8),

-- História da África (43bff7ca-8f49-46a3-b757-e20105c00ad2)
('43bff7ca-8f49-46a3-b757-e20105c00ad2', 'O Reino de Gana, um dos primeiros grandes impérios da África Ocidental, teve sua riqueza baseada principalmente:',
  array['No controle do comércio transaariano de ouro e sal', 'Na exploração de petróleo', 'No comércio marítimo com a Ásia', 'Na produção industrial têxtil'], 0,
  'Gana controlava rotas comerciais transaarianas, lucrando com a troca de ouro (do sul) por sal (do norte do deserto).', 1),
('43bff7ca-8f49-46a3-b757-e20105c00ad2', 'O Império do Mali, que sucedeu Gana como potência da África Ocidental, teve como um de seus governantes mais célebres:',
  array['Mansa Musa, conhecido por sua imensa riqueza e peregrinação a Meca', 'Túpac Amaru', 'Hamurábi', 'Ramessés II'], 0,
  'Mansa Musa, imperador do Mali no século XIV, ficou famoso por sua riqueza em ouro e por uma célebre peregrinação a Meca.', 2),
('43bff7ca-8f49-46a3-b757-e20105c00ad2', 'O comércio transaariano, que conectava a África subsaariana ao Mediterrâneo através do deserto do Saara, baseava-se no uso de:',
  array['Caravanas de camelos como principal meio de transporte', 'Grandes embarcações fluviais exclusivamente', 'Ferrovias construídas por europeus', 'Rotas marítimas ao redor do continente'], 0,
  'As caravanas de camelos eram fundamentais para atravessar o deserto do Saara, viabilizando o comércio entre a África subsaariana e o norte da África.', 3),
('43bff7ca-8f49-46a3-b757-e20105c00ad2', 'A Conferência de Berlim (1884-1885) teve como principal desdobramento:',
  array['A partilha do continente africano entre as potências europeias, sem considerar fronteiras étnicas e culturais locais', 'A independência de todos os países africanos', 'O fim do tráfico de escravizados', 'A unificação política da África sob um único governo'], 0,
  'A Conferência de Berlim organizou a partilha da África entre potências europeias, traçando fronteiras artificiais que ainda hoje geram tensões étnicas.', 4),
('43bff7ca-8f49-46a3-b757-e20105c00ad2', 'O período do "Novo Imperialismo", no final do século XIX, foi marcado pela dominação europeia sobre a África, justificada, entre outros discursos, por:',
  array['Ideias de suposta superioridade racial e a chamada "missão civilizadora"', 'Pedidos formais dos próprios povos africanos por colonização', 'Acordos comerciais plenamente equilibrados', 'A ausência completa de interesse econômico europeu'], 0,
  'Discursos racistas e a ideia de "missão civilizadora" foram usados para justificar ideologicamente a dominação colonial europeia sobre a África.', 5),
('43bff7ca-8f49-46a3-b757-e20105c00ad2', 'O apartheid, sistema de segregação racial institucionalizada, vigorou na África do Sul entre:',
  array['1948 e 1994, aproximadamente', '1800 e 1850', '1960 e 1965, apenas', '1994 até os dias atuais'], 0,
  'O apartheid foi instituído oficialmente em 1948 e vigorou até sua abolição, culminando na eleição de Nelson Mandela como presidente em 1994.', 6),
('43bff7ca-8f49-46a3-b757-e20105c00ad2', 'Nelson Mandela, um dos principais líderes na luta contra o apartheid, foi preso por décadas antes de:',
  array['Tornar-se o primeiro presidente negro da África do Sul, eleito democraticamente em 1994', 'Ser exilado permanentemente da África do Sul', 'Tornar-se rei zulu', 'Fundar o Estado de Israel'], 0,
  'Após 27 anos preso, Mandela foi libertado em 1990 e eleito presidente em 1994, na primeira eleição sul-africana com sufrágio universal.', 7),
('43bff7ca-8f49-46a3-b757-e20105c00ad2', 'O processo de descolonização africana, intensificado sobretudo a partir das décadas de 1950 e 1960, resultou:',
  array['Na independência política da maioria dos países africanos frente às antigas metrópoles europeias', 'Na manutenção do domínio colonial europeu até os dias atuais', 'Na anexação da África aos Estados Unidos', 'No fim imediato de todas as tensões étnicas herdadas do colonialismo'], 0,
  'A partir de meados do século XX, a maioria dos países africanos conquistou sua independência política, embora tenham herdado desafios estruturais do período colonial.', 8),

-- Grandes temas históricos (b5a0f0a7-33bf-4676-86aa-073a0d0f5426)
('b5a0f0a7-33bf-4676-86aa-073a0d0f5426', 'O tráfico transatlântico de escravizados, que trouxe milhões de africanos à força para as Américas entre os séculos XVI e XIX, teve o Brasil como:',
  array['O maior receptor de africanos escravizados em todo o continente americano', 'Um país que nunca recebeu africanos escravizados', 'O único país americano a praticar a escravidão', 'Um país que aboliu a escravidão antes de qualquer outro na América'], 0,
  'Estima-se que o Brasil tenha recebido a maior quantidade de africanos escravizados entre todos os países americanos, sendo o último a abolir formalmente a escravidão, em 1888.', 1),
('b5a0f0a7-33bf-4676-86aa-073a0d0f5426', 'A democracia ateniense, considerada uma origem histórica da democracia moderna, diferenciava-se desta principalmente por:',
  array['Ser uma democracia direta, restrita a uma minoria de cidadãos (homens livres)', 'Garantir direito de voto universal a toda a população', 'Não permitir qualquer participação popular', 'Ser idêntica em todos os aspectos às democracias representativas atuais'], 0,
  'A democracia ateniense era direta, mas excludente, restrita a uma parcela pequena da população total da cidade.', 2),
('b5a0f0a7-33bf-4676-86aa-073a0d0f5426', 'O conceito de cidadania passou por importantes transformações históricas, ampliando-se ao longo do tempo para incluir, entre outras conquistas:',
  array['O voto feminino, obtido em diferentes países ao longo dos séculos XIX e XX', 'A exclusão total das mulheres da vida política em todas as épocas', 'A manutenção de restrições censitárias em todos os países até hoje', 'A eliminação de qualquer forma de direito político'], 0,
  'A ampliação da cidadania incluiu conquistas como o fim do voto censitário e a extensão do direito ao voto às mulheres.', 3),
('b5a0f0a7-33bf-4676-86aa-073a0d0f5426', 'O colonialismo europeu, praticado entre os séculos XV e XX em diferentes continentes, teve como uma de suas principais características:',
  array['A exploração econômica e a subordinação política de territórios e povos por potências estrangeiras', 'O respeito irrestrito à soberania e cultura dos povos colonizados', 'A ausência de qualquer exploração de recursos naturais', 'O desenvolvimento simultâneo e equilibrado entre metrópoles e colônias'], 0,
  'O colonialismo baseava-se na exploração econômica e no controle político de territórios, geralmente subordinando os interesses locais aos das metrópoles.', 4),
('b5a0f0a7-33bf-4676-86aa-073a0d0f5426', 'O imperialismo do final do século XIX, praticado por potências como Inglaterra e França, diferenciava-se do colonialismo dos séculos anteriores principalmente por:',
  array['Estar associado à fase madura do capitalismo industrial e financeiro, em busca de mercados e matérias-primas', 'Ser praticado exclusivamente por países americanos', 'Não envolver qualquer disputa territorial', 'Ocorrer apenas na Europa'], 0,
  'O imperialismo do século XIX ligava-se à expansão do capitalismo industrial e financeiro, com potências buscando mercados e matérias-primas.', 5),
('b5a0f0a7-33bf-4676-86aa-073a0d0f5426', 'Movimentos revolucionários ao longo da história, como as revoluções Francesa, Russa e Cubana, compartilham, apesar de contextos distintos, o objetivo comum de:',
  array['Romper com uma ordem política e social vigente, buscando transformações profundas', 'Manter inalterada a estrutura de poder existente', 'Restaurar sempre regimes monárquicos', 'Excluir qualquer participação popular do processo'], 0,
  'Apesar de ideologias e contextos muito diferentes, revoluções históricas geralmente buscam romper com a ordem estabelecida e promover mudanças estruturais.', 6),
('b5a0f0a7-33bf-4676-86aa-073a0d0f5426', 'A liberdade religiosa, um dos temas centrais na história dos direitos humanos, foi frequentemente restringida ao longo da história por:',
  array['Perseguições e imposições de uma religião oficial pelo Estado, como ocorreu em diferentes períodos e regiões', 'Uma suposta ausência total de conflitos religiosos ao longo da história', 'Uma garantia universal e irrestrita desde a Antiguidade', 'Tratados internacionais assinados já na Antiguidade'], 0,
  'Historicamente, muitos Estados impuseram religiões oficiais e perseguiram minorias religiosas, tornando a liberdade de culto uma conquista gradual.', 7),
('b5a0f0a7-33bf-4676-86aa-073a0d0f5426', 'A Declaração Universal dos Direitos Humanos, adotada pela Organização das Nações Unidas em 1948, foi elaborada, entre outros fatores, em resposta:',
  array['Às atrocidades cometidas durante a Segunda Guerra Mundial, como o Holocausto', 'À Revolução Industrial do século XVIII', 'À Guerra do Peloponeso', 'Às Cruzadas medievais'], 0,
  'A Declaração de 1948 buscou estabelecer princípios universais de dignidade humana após as violações massivas de direitos ocorridas durante a Segunda Guerra Mundial.', 8);
