-- Português — Crase (4 leaves, 5 questões cada)
insert into questions (catalog_node_id, prompt, options, correct_index, explanation, order_index) values
-- Casos obrigatórios (dcb45577-a87e-4388-8653-846ef83e2e15)
('dcb45577-a87e-4388-8653-846ef83e2e15', 'Assinale a alternativa em que a crase foi empregada corretamente, ao indicar hora determinada:',
  array['O show começará às 21 horas.', 'O show começará a 21 horas.', 'O show começará à 21 horas.', 'O show começará as 21 horas.'], 0,
  'Diante de indicação de horas determinadas, no plural, usa-se a crase: "às 21 horas".', 1),
('dcb45577-a87e-4388-8653-846ef83e2e15', 'Assinale a alternativa em que o uso da crase é obrigatório, por se tratar de locução adverbial feminina:',
  array['O bordado foi feito à mão.', 'O bordado foi feito a mão.', 'O bordado foi feito a à mão.', 'O bordado foi feito na à mão.'], 0,
  'Em locuções adverbiais femininas formadas por "a" + substantivo feminino (à mão, à noite, à tarde), o uso da crase é obrigatório.', 2),
('dcb45577-a87e-4388-8653-846ef83e2e15', 'Assinale a alternativa em que a crase foi empregada corretamente antes do pronome relativo "a qual":',
  array['Esta é a empresa à qual me refiro.', 'Esta é a empresa a qual me refiro.', 'Esta é a empresa à a qual me refiro.', 'Esta é a empresa a a qual me refiro.'], 0,
  'Diante do pronome relativo "a qual" (feminino), quando o verbo da oração exige a preposição "a", o uso da crase é obrigatório.', 3),
('dcb45577-a87e-4388-8653-846ef83e2e15', 'Assinale a alternativa em que o uso da crase é obrigatório, diante de nome de lugar que admite o artigo "a":',
  array['Viajarei à Bahia nas próximas férias.', 'Viajarei a Bahia nas próximas férias.', 'Viajarei em à Bahia nas próximas férias.', 'Viajarei para à Bahia nas próximas férias.'], 0,
  'Como o topônimo "Bahia" admite o artigo feminino "a" ("gosto da Bahia"), o uso da crase é obrigatório diante da preposição "a" exigida pelo verbo "viajar".', 4),
('dcb45577-a87e-4388-8653-846ef83e2e15', 'Assinale a alternativa em que a crase é obrigatória, na indicação de "à moda de":',
  array['Ela se vestia à francesa.', 'Ela se vestia a francesa.', 'Ela se vestia à a francesa.', 'Ela se vestia na à francesa.'], 0,
  'Em expressões que indicam "à moda de" (à francesa, à moda antiga), o uso da crase é obrigatório, mesmo com a palavra "moda" implícita.', 5),

-- Casos proibidos (9ce83537-830c-4917-81f7-34ecdd190e04)
('9ce83537-830c-4917-81f7-34ecdd190e04', 'Assinale a alternativa em que a crase NÃO deve ser utilizada, por anteceder verbo:',
  array['Começou a chorar sem motivo aparente.', 'Começou à chorar sem motivo aparente.', 'Começou à a chorar sem motivo aparente.', 'Começou a à chorar sem motivo aparente.'], 0,
  'Não se usa crase diante de verbos, pois estes não admitem artigo definido antes de si: "começou a chorar".', 1),
('9ce83537-830c-4917-81f7-34ecdd190e04', 'Assinale a alternativa em que a crase NÃO deve ser empregada, por anteceder substantivo masculino:',
  array['Fiz o trabalho a lápis.', 'Fiz o trabalho à lápis.', 'Fiz o trabalho à um lápis.', 'Fiz o trabalho à o lápis.'], 0,
  'Não há crase diante de substantivos masculinos, pois estes não são antecedidos pelo artigo feminino "a": "a lápis".', 2),
('9ce83537-830c-4917-81f7-34ecdd190e04', 'Assinale a alternativa em que a crase NÃO deve ser utilizada, diante de pronome pessoal:',
  array['Entreguei o presente a ela.', 'Entreguei o presente à ela.', 'Entreguei o presente à-ela.', 'Entreguei o presente à a ela.'], 0,
  'Não se usa crase diante de pronomes pessoais do caso reto, como "ela", que não admitem artigo definido.', 3),
('9ce83537-830c-4917-81f7-34ecdd190e04', 'Assinale a alternativa em que a crase NÃO deve ser empregada, diante de palavra no plural sem determinação:',
  array['Referia-se a pessoas desconhecidas.', 'Referia-se à pessoas desconhecidas.', 'Referia-se às pessoa desconhecidas.', 'Referia-se à as pessoas desconhecidas.'], 0,
  'Sem artigo definido determinando o substantivo plural "pessoas" (sentido indeterminado), não há crase: "a pessoas desconhecidas".', 4),
('9ce83537-830c-4917-81f7-34ecdd190e04', 'Assinale a alternativa em que a crase NÃO deve ser utilizada, diante de nome próprio de pessoa sem artigo:',
  array['Entreguei a carta a Maria.', 'Entreguei a carta à Maria.', 'Entreguei a carta à-Maria.', 'Entreguei a carta à a Maria.'], 0,
  'Nomes próprios de pessoas, em geral, não são antecedidos por artigo definido, o que impede o uso da crase: "a Maria".', 5),

-- Casos facultativos (4eea3b08-cfd1-4658-98b0-98af83d3df62)
('4eea3b08-cfd1-4658-98b0-98af83d3df62', 'Assinale a alternativa em que o uso da crase é facultativo, diante de pronome possessivo feminino:',
  array['Entreguei o documento à minha secretária.', 'Entreguei o documento à a minha secretária.', 'Entreguei o documento à minhas secretária.', 'Entreguei o documento à minha às secretária.'], 0,
  'Diante de pronomes possessivos femininos, a crase é facultativa: tanto "à minha secretária" quanto "a minha secretária" são aceitos pela norma-padrão.', 1),
('4eea3b08-cfd1-4658-98b0-98af83d3df62', 'Assinale a alternativa em que o uso da crase é facultativo, diante de nome próprio feminino:',
  array['Contei o segredo à Ana.', 'Contei o segredo à à Ana.', 'Contei o segredo às Ana.', 'Contei o segredo à a Ana.'], 0,
  'Diante de nomes próprios femininos, o uso da crase é facultativo: tanto "a Ana" quanto "à Ana" são aceitos.', 2),
('4eea3b08-cfd1-4658-98b0-98af83d3df62', 'Assinale a alternativa em que o uso da crase é facultativo, na expressão com "até":',
  array['Foi até à padaria comprar pão.', 'Foi até à à padaria comprar pão.', 'Foi até às padaria comprar pão.', 'Foi até à a padaria comprar pão.'], 0,
  'Com a preposição "até" antes de palavra feminina, a crase é facultativa: "até a padaria" ou "até à padaria".', 3),
('4eea3b08-cfd1-4658-98b0-98af83d3df62', 'Assinale a alternativa em que o uso da crase é facultativo, diante de pronome possessivo:',
  array['Dedico esta vitória à minha mãe.', 'Dedico esta vitória à à minha mãe.', 'Dedico esta vitória às minha mãe.', 'Dedico esta vitória à a minha mãe.'], 0,
  'Assim como diante de outros possessivos femininos, o uso da crase antes de "minha mãe" é facultativo.', 4),
('4eea3b08-cfd1-4658-98b0-98af83d3df62', 'Assinale a alternativa em que o uso da crase é facultativo:',
  array['Caminhamos até à praça central.', 'Caminhamos até à à praça central.', 'Caminhamos até às praça central.', 'Caminhamos até à a praça central.'], 0,
  'Diante de "até" seguido de palavra feminina, o uso da crase é facultativo: "até a praça" ou "até à praça".', 5),

-- Locuções (1badbb7e-4488-4334-bbf5-6403153e2872)
('1badbb7e-4488-4334-bbf5-6403153e2872', 'Assinale a alternativa em que a locução está corretamente grafada com crase:',
  array['Às vezes, chego atrasado ao trabalho.', 'As vezes, chego atrasado ao trabalho.', 'Á vezes, chego atrasado ao trabalho.', 'À vezes, chego atrasado ao trabalho.'], 0,
  'A locução adverbial "às vezes" é sempre grafada com crase, indicando plural feminino.', 1),
('1badbb7e-4488-4334-bbf5-6403153e2872', 'Assinale a alternativa em que a locução conjuntiva com crase está correta:',
  array['À medida que o tempo passava, ele ficava mais calmo.', 'A medida que o tempo passava, ele ficava mais calmo.', 'Á medida que o tempo passava, ele ficava mais calmo.', 'Há medida que o tempo passava, ele ficava mais calmo.'], 0,
  'A locução conjuntiva "à medida que", que indica proporção, é sempre grafada com crase.', 2),
('1badbb7e-4488-4334-bbf5-6403153e2872', 'Assinale a alternativa em que a locução adverbial com crase está correta:',
  array['Ele dirigia à noite com bastante cuidado.', 'Ele dirigia a noite com bastante cuidado.', 'Ele dirigia á noite com bastante cuidado.', 'Ele dirigia há noite com bastante cuidado.'], 0,
  'A locução adverbial "à noite" é grafada com crase, assim como "à tarde" e "à mão".', 3),
('1badbb7e-4488-4334-bbf5-6403153e2872', 'Assinale a alternativa em que a locução prepositiva com crase está correta:',
  array['O carro seguia à frente do caminhão.', 'O carro seguia a frente do caminhão.', 'O carro seguia á frente do caminhão.', 'O carro seguia há frente do caminhão.'], 0,
  'A locução prepositiva "à frente de" é grafada com crase.', 4),
('1badbb7e-4488-4334-bbf5-6403153e2872', 'Assinale a alternativa em que a locução com crase está correta:',
  array['Tudo aconteceu à revelia dos moradores do bairro.', 'Tudo aconteceu a revelia dos moradores do bairro.', 'Tudo aconteceu á revelia dos moradores do bairro.', 'Tudo aconteceu há revelia dos moradores do bairro.'], 0,
  'A locução "à revelia de" (sem o conhecimento ou consentimento de alguém) é grafada com crase.', 5);
