-- Biologia — Genética e Biotecnologia (13 leaves, 5 questões cada)
insert into questions (catalog_node_id, prompt, options, correct_index, explanation, order_index) values
-- Gene (39a35cba-9950-4962-a03a-3996395bd685)
('39a35cba-9950-4962-a03a-3996395bd685', 'Um gene pode ser definido como:',
  array['Um segmento de DNA que contém a informação para a produção de uma proteína ou característica específica', 'Uma célula reprodutiva completa', 'Um tipo de organela celular', 'Uma proteína estrutural da membrana celular'], 0,
  'O gene é a unidade básica da hereditariedade, um trecho de DNA que codifica uma proteína ou característica.', 1),
('39a35cba-9950-4962-a03a-3996395bd685', 'Os genes estão localizados, dentro da célula, principalmente:',
  array['Ao longo dos cromossomos, no núcleo celular', 'Exclusivamente no citoplasma, fora do núcleo', 'Apenas nas mitocôndrias', 'Fora da célula, no meio extracelular'], 0,
  'Os genes ocupam posições específicas (loci) ao longo dos cromossomos, no núcleo das células eucarióticas.', 2),
('39a35cba-9950-4962-a03a-3996395bd685', 'A totalidade dos genes de um organismo é chamada de:',
  array['Genoma', 'Genótipo apenas', 'Fenótipo', 'Cariótipo'], 0,
  'O genoma corresponde ao conjunto completo de material genético (todos os genes) de um organismo.', 3),
('39a35cba-9950-4962-a03a-3996395bd685', 'Mutações genéticas correspondem a:',
  array['Alterações na sequência de DNA de um gene, que podem originar novas variações', 'A ausência total de genes em uma célula', 'A duplicação obrigatória e idêntica de todos os cromossomos', 'Um processo que nunca ocorre naturalmente'], 0,
  'Mutações são alterações no material genético que podem gerar variabilidade genética.', 4),
('39a35cba-9950-4962-a03a-3996395bd685', 'Os genes são transmitidos de pais para filhos, ao longo das gerações, por meio:',
  array['Dos gametas (células reprodutivas), durante a reprodução sexuada', 'Exclusivamente do ambiente em que o indivíduo vive', 'De processos completamente aleatórios, sem qualquer relação com os pais', 'Apenas da mãe, nunca do pai'], 0,
  'Na reprodução sexuada, óvulos e espermatozoides carregam metade da informação genética de cada progenitor.', 5),

-- Alelo (b6c1f281-a862-4508-a4b3-806650514fdc)
('b6c1f281-a862-4508-a4b3-806650514fdc', 'Alelos são definidos como:',
  array['Diferentes formas (versões) de um mesmo gene, que ocupam a mesma posição em cromossomos homólogos', 'Genes completamente distintos, sem qualquer relação entre si', 'Organelas citoplasmáticas', 'Proteínas produzidas por um único gene'], 0,
  'Alelos são variações de um mesmo gene, podendo gerar diferentes características para a mesma característica.', 1),
('b6c1f281-a862-4508-a4b3-806650514fdc', 'Em um organismo diploide, como o ser humano, cada característica é geralmente controlada por:',
  array['Dois alelos, um herdado de cada progenitor', 'Apenas um único alelo', 'Três ou mais alelos simultaneamente, sempre', 'Nenhum alelo, apenas pelo ambiente'], 0,
  'Organismos diploides possuem pares de cromossomos homólogos, portando dois alelos para cada característica.', 2),
('b6c1f281-a862-4508-a4b3-806650514fdc', 'Quando os dois alelos de um par são idênticos, o indivíduo é classificado, para aquela característica, como:',
  array['Homozigoto', 'Heterozigoto', 'Hemizigoto', 'Poliploide'], 0,
  'A homozigose ocorre quando os dois alelos herdados são iguais entre si.', 3),
('b6c1f281-a862-4508-a4b3-806650514fdc', 'O termo "alelo dominante" refere-se àquele que:',
  array['Se manifesta no fenótipo mesmo em heterozigose, mascarando o efeito do alelo recessivo', 'Nunca se manifesta no fenótipo do indivíduo', 'Só se manifesta quando presente em dose dupla', 'É sempre menos frequente na população'], 0,
  'O alelo dominante determina o fenótipo mesmo em apenas uma cópia, sobrepondo-se ao alelo recessivo.', 4),
('b6c1f281-a862-4508-a4b3-806650514fdc', 'A cor dos olhos em humanos, exemplo comumente estudado em genética, é influenciada por diferentes alelos que, combinados, determinam:',
  array['O fenótipo observável da característica', 'Apenas o sexo do indivíduo', 'Nenhuma variação fenotípica visível', 'Exclusivamente características adquiridas ao longo da vida'], 0,
  'A combinação específica dos alelos herdados determina o fenótipo, como a cor dos olhos.', 5),

-- Genótipo (9fbb43c6-7af2-4b6b-b454-9502d5150108)
('9fbb43c6-7af2-4b6b-b454-9502d5150108', 'O genótipo de um indivíduo corresponde a:',
  array['A constituição genética (combinação de alelos) que ele possui para determinada característica', 'As características físicas e observáveis do indivíduo', 'Apenas as características adquiridas ao longo da vida', 'A aparência externa do indivíduo, exclusivamente'], 0,
  'O genótipo é o conjunto de genes (alelos) que um organismo possui, independentemente da manifestação externa.', 1),
('9fbb43c6-7af2-4b6b-b454-9502d5150108', 'Um indivíduo com genótipo "Aa" para determinada característica é classificado como:',
  array['Heterozigoto', 'Homozigoto dominante', 'Homozigoto recessivo', 'Sem qualquer classificação genética possível'], 0,
  'A combinação de alelos diferentes ("A" e "a") caracteriza um heterozigoto.', 2),
('9fbb43c6-7af2-4b6b-b454-9502d5150108', 'Dois indivíduos podem ter fenótipos idênticos, mas genótipos diferentes, quando um deles é:',
  array['Homozigoto dominante (AA) e o outro heterozigoto (Aa) para uma característica de dominância completa', 'Ambos homozigotos recessivos', 'Impossível, pois genótipo e fenótipo são sempre idênticos', 'Portadores de espécies diferentes'], 0,
  'Em dominância completa, AA e Aa apresentam o mesmo fenótipo dominante, apesar de genótipos diferentes.', 3),
('9fbb43c6-7af2-4b6b-b454-9502d5150108', 'O genótipo de um indivíduo é determinado no momento:',
  array['Da fecundação, com a união dos gametas parentais', 'Apenas após o nascimento', 'Continuamente ao longo de toda a vida, mudando a cada dia', 'Exclusivamente pela influência do ambiente'], 0,
  'O genótipo é estabelecido na fecundação, permanecendo geralmente estável ao longo da vida.', 4),
('9fbb43c6-7af2-4b6b-b454-9502d5150108', 'O estudo do genótipo é fundamental, entre outras aplicações, para:',
  array['Prever a probabilidade de transmissão de determinadas características ou doenças hereditárias', 'Determinar exclusivamente a aparência física de um indivíduo', 'Substituir totalmente a necessidade de estudar o fenótipo', 'Prever características adquiridas ao longo da vida, sem qualquer relação genética'], 0,
  'Conhecer o genótipo permite calcular probabilidades de herança de características e doenças genéticas.', 5),

-- Fenótipo (1b185c81-5bc2-4217-b29b-fb2608b85c41)
('1b185c81-5bc2-4217-b29b-fb2608b85c41', 'O fenótipo de um organismo corresponde a:',
  array['As características observáveis, resultantes da interação entre o genótipo e o ambiente', 'Apenas a combinação de alelos que ele possui', 'Exclusivamente características internas, não visíveis', 'Um conceito idêntico ao de genótipo, sem qualquer diferença'], 0,
  'O fenótipo é a manifestação visível das características, influenciada pelos genes e pelo ambiente.', 1),
('1b185c81-5bc2-4217-b29b-fb2608b85c41', 'Duas plantas geneticamente idênticas podem apresentar fenótipos diferentes se forem cultivadas em condições ambientais distintas, o que demonstra:',
  array['A influência do ambiente na expressão do fenótipo', 'Que o genótipo não tem qualquer influência sobre o fenótipo', 'Que fenótipo e genótipo são sempre idênticos', 'Que mutações ocorrem instantaneamente em resposta ao ambiente'], 0,
  'O fenótipo resulta da interação entre genótipo e ambiente, mesmo com genótipo idêntico.', 2),
('1b185c81-5bc2-4217-b29b-fb2608b85c41', 'A altura de uma planta, influenciada tanto pela genética quanto pela disponibilidade de nutrientes e luz, é um exemplo de característica:',
  array['Fenotípica poligênica e multifatorial', 'Controlada exclusivamente por um único gene, sem influência ambiental', 'Que não tem qualquer base genética', 'Idêntica ao genótipo da planta'], 0,
  'Muitas características fenotípicas são influenciadas por múltiplos genes e fatores ambientais.', 3),
('1b185c81-5bc2-4217-b29b-fb2608b85c41', 'A cor da pele em seres humanos é um exemplo de característica fenotípica que:',
  array['Resulta da ação combinada de vários genes (herança poligênica)', 'É determinada por um único gene, com apenas dois alelos possíveis', 'Não possui qualquer componente genético', 'É determinada exclusivamente pelo ambiente, sem influência genética'], 0,
  'A cor da pele humana é um exemplo clássico de herança poligênica.', 4),
('1b185c81-5bc2-4217-b29b-fb2608b85c41', 'O estudo da relação entre genótipo, ambiente e fenótipo é fundamental para compreender:',
  array['Como características hereditárias se expressam de formas variadas em diferentes contextos', 'Apenas processos totalmente independentes da genética', 'Que o ambiente nunca influencia as características de um organismo', 'Que o fenótipo é sempre idêntico ao genótipo, sem exceções'], 0,
  'Compreender a interação genótipo-ambiente-fenótipo é essencial para diversas áreas da biologia e medicina.', 5),

-- Homozigoto (81a8d9f8-2691-41c2-be3a-5d93901ad947)
('81a8d9f8-2691-41c2-be3a-5d93901ad947', 'Um indivíduo é classificado como homozigoto para determinada característica quando:',
  array['Possui dois alelos idênticos para aquele gene', 'Possui dois alelos diferentes para aquele gene', 'Não possui nenhum alelo para aquele gene', 'Possui três ou mais alelos simultaneamente'], 0,
  'A homozigose ocorre quando os dois alelos herdados dos progenitores são idênticos entre si.', 1),
('81a8d9f8-2691-41c2-be3a-5d93901ad947', 'Um indivíduo com genótipo "AA" é classificado como:',
  array['Homozigoto dominante', 'Homozigoto recessivo', 'Heterozigoto', 'Sem qualquer classificação possível'], 0,
  'A presença de dois alelos dominantes idênticos ("AA") caracteriza um homozigoto dominante.', 2),
('81a8d9f8-2691-41c2-be3a-5d93901ad947', 'Um indivíduo com genótipo "aa" é classificado como:',
  array['Homozigoto recessivo', 'Homozigoto dominante', 'Heterozigoto', 'Sem qualquer classificação possível'], 0,
  'A presença de dois alelos recessivos idênticos ("aa") caracteriza um homozigoto recessivo.', 3),
('81a8d9f8-2691-41c2-be3a-5d93901ad947', 'Ao se autofecundar (ou cruzar com outro indivíduo idêntico), um indivíduo homozigoto tende a gerar descendentes:',
  array['Geneticamente uniformes para aquela característica, iguais ao progenitor', 'Sempre geneticamente diferentes entre si', 'Com genótipos completamente aleatórios', 'Sem qualquer relação genética com os progenitores'], 0,
  'Como só transmite um único tipo de alelo, um homozigoto gera descendentes uniformes para o gene em questão.', 4),
('81a8d9f8-2691-41c2-be3a-5d93901ad947', 'Apenas indivíduos homozigotos recessivos são capazes de expressar o fenótipo recessivo porque:',
  array['O alelo dominante, quando presente, mascara a expressão do alelo recessivo', 'O alelo recessivo é sempre mais forte que o dominante', 'Homozigotos recessivos não possuem qualquer alelo', 'Não existe qualquer relação entre genótipo e fenótipo nesse caso'], 0,
  'Como o alelo dominante se sobrepõe ao recessivo em heterozigose, só na ausência total do dominante o fenótipo recessivo se manifesta.', 5),

-- Heterozigoto (d3c597c4-5a2b-4cf4-958c-eb921554f24f)
('d3c597c4-5a2b-4cf4-958c-eb921554f24f', 'Um indivíduo é classificado como heterozigoto para determinada característica quando:',
  array['Possui dois alelos diferentes para aquele gene', 'Possui dois alelos idênticos para aquele gene', 'Não possui nenhum alelo para aquele gene', 'Possui três ou mais alelos simultaneamente'], 0,
  'A heterozigose ocorre quando os dois alelos herdados dos progenitores são diferentes entre si (por exemplo, "Aa").', 1),
('d3c597c4-5a2b-4cf4-958c-eb921554f24f', 'Em uma característica de dominância completa, um indivíduo heterozigoto (Aa) apresenta fenótipo:',
  array['Idêntico ao do homozigoto dominante (AA)', 'Idêntico ao do homozigoto recessivo (aa)', 'Intermediário entre os dois homozigotos', 'Completamente imprevisível'], 0,
  'Na dominância completa, o alelo dominante se expressa totalmente mesmo em heterozigose.', 2),
('d3c597c4-5a2b-4cf4-958c-eb921554f24f', 'Indivíduos heterozigotos são frequentemente chamados, na genética, de:',
  array['Híbridos, para aquela característica', 'Puros, para aquela característica', 'Clones geneticamente idênticos', 'Estéreis, sem capacidade reprodutiva'], 0,
  'O termo "híbrido" designa indivíduos heterozigotos, que carregam alelos diferentes para determinada característica.', 3),
('d3c597c4-5a2b-4cf4-958c-eb921554f24f', 'Ao se cruzar dois indivíduos heterozigotos (Aa x Aa) para uma característica de dominância completa, a proporção genotípica esperada na descendência é de:',
  array['1 AA : 2 Aa : 1 aa', '3 AA : 1 aa, sem qualquer Aa', 'Todos os descendentes serão necessariamente Aa', '1 AA : 1 aa, sem qualquer Aa'], 0,
  'O cruzamento entre dois heterozigotos gera, em média, a proporção genotípica clássica de 1:2:1.', 4),
('d3c597c4-5a2b-4cf4-958c-eb921554f24f', 'Em características com dominância incompleta ou codominância, os heterozigotos tendem a apresentar fenótipos:',
  array['Intermediários ou combinados entre os dois alelos, diferentemente da dominância completa', 'Sempre idênticos aos do homozigoto dominante', 'Sempre idênticos aos do homozigoto recessivo', 'Impossíveis de serem observados'], 0,
  'Ao contrário da dominância completa, nesses casos os heterozigotos exibem fenótipos distintos, intermediários ou combinados.', 5),

-- Primeira Lei de Mendel (f60e7769-0be0-4a8e-b2e5-bb84e9163a6f)
('f60e7769-0be0-4a8e-b2e5-bb84e9163a6f', 'A Primeira Lei de Mendel, também chamada de Lei da Segregação, afirma que:',
  array['Cada característica é determinada por um par de alelos, que se separam durante a formação dos gametas', 'Duas características diferentes são sempre herdadas juntas, sem separação', 'Todos os descendentes são sempre idênticos aos pais', 'Não existe qualquer relação entre genes e características hereditárias'], 0,
  'Segundo a Primeira Lei, os dois alelos de um gene se separam durante a formação dos gametas.', 1),
('f60e7769-0be0-4a8e-b2e5-bb84e9163a6f', 'No cruzamento entre um indivíduo homozigoto dominante (AA) e um homozigoto recessivo (aa), toda a geração F1 apresenta genótipo:',
  array['Heterozigoto (Aa)', 'Homozigoto dominante (AA)', 'Homozigoto recessivo (aa)', 'Uma mistura aleatória de diferentes genótipos'], 0,
  'Como cada progenitor contribui com um único tipo de alelo, toda a geração F1 será heterozigota (Aa).', 2),
('f60e7769-0be0-4a8e-b2e5-bb84e9163a6f', 'No experimento clássico de Mendel com ervilhas, ao cruzar plantas de sementes lisas (dominante) com plantas de sementes rugosas (recessivo), a geração F1 apresentou:',
  array['100% de plantas com sementes lisas', '100% de plantas com sementes rugosas', '50% lisas e 50% rugosas', 'Uma mistura de sementes de formato intermediário'], 0,
  'Como o alelo para semente lisa é dominante, toda a geração F1, heterozigota, apresentou o fenótipo dominante.', 3),
('f60e7769-0be0-4a8e-b2e5-bb84e9163a6f', 'Ao autofecundar os indivíduos da geração F1 (heterozigotos, Aa x Aa), a Primeira Lei de Mendel prevê, na geração F2, uma proporção fenotípica clássica de:',
  array['3 dominantes : 1 recessivo', '1 dominante : 1 recessivo', '100% dominantes, sem qualquer recessivo', '100% recessivos, sem qualquer dominante'], 0,
  'A proporção fenotípica 3:1 é a assinatura clássica da segregação mendeliana em heterozigotos.', 4),
('f60e7769-0be0-4a8e-b2e5-bb84e9163a6f', 'A Primeira Lei de Mendel é também conhecida como "Lei da Pureza dos Gametas" porque:',
  array['Cada gameta carrega apenas um alelo de cada par, sem misturar os dois', 'Os gametas nunca contêm qualquer material genético', 'Todos os gametas de um indivíduo são sempre idênticos entre si', 'Os gametas são formados sem qualquer relação com os alelos parentais'], 0,
  'A "pureza dos gametas" reflete que, na meiose, os alelos se separam, e cada gameta recebe apenas um deles.', 5),

-- Segunda Lei de Mendel (c141235f-fa2d-4f57-92f6-9155f4e51b24)
('c141235f-fa2d-4f57-92f6-9155f4e51b24', 'A Segunda Lei de Mendel, também chamada de Lei da Segregação Independente, estabelece que:',
  array['Genes localizados em cromossomos diferentes são herdados de forma independente entre si', 'Todas as características são sempre herdadas juntas, sem qualquer independência', 'Apenas uma característica pode ser estudada por vez, sem exceção', 'Não existe qualquer relação entre a herança de diferentes características'], 0,
  'A Segunda Lei mostra que genes em cromossomos diferentes se distribuem de forma independente na formação dos gametas.', 1),
('c141235f-fa2d-4f57-92f6-9155f4e51b24', 'No clássico cruzamento di-híbrido de Mendel (por exemplo, cor e textura da semente), a proporção fenotípica esperada na geração F2, ao cruzar dois duplos-heterozigotos, é de:',
  array['9:3:3:1', '3:1', '1:1:1:1', '9:9'], 0,
  'A proporção clássica 9:3:3:1 resulta da combinação independente de duas características, cada uma seguindo 3:1.', 2),
('c141235f-fa2d-4f57-92f6-9155f4e51b24', 'A Segunda Lei de Mendel se aplica corretamente apenas quando os genes estudados estão localizados:',
  array['Em cromossomos diferentes (ou distantes o suficiente no mesmo cromossomo)', 'Sempre no mesmo cromossomo, próximos entre si', 'Exclusivamente no cromossomo sexual', 'Fora do núcleo celular'], 0,
  'Genes muito próximos no mesmo cromossomo (ligados) tendem a ser herdados juntos, fugindo à segregação independente.', 3),
('c141235f-fa2d-4f57-92f6-9155f4e51b24', 'A base celular da Segunda Lei de Mendel está relacionada à:',
  array['Distribuição aleatória e independente dos cromossomos homólogos durante a meiose', 'Fusão obrigatória de todos os cromossomos em um único gameta', 'Ausência total de divisão celular na formação dos gametas', 'Duplicação simultânea de todos os genes do organismo'], 0,
  'Durante a meiose, os pares de cromossomos homólogos se separam de forma independente.', 4),
('c141235f-fa2d-4f57-92f6-9155f4e51b24', 'A Segunda Lei de Mendel amplia o entendimento da herança genética ao mostrar que:',
  array['A combinação de diferentes características pode gerar uma grande variabilidade genética nos descendentes', 'Apenas uma característica pode ser transmitida por vez, isoladamente', 'A variabilidade genética é impossível entre indivíduos da mesma espécie', 'Todas as características são sempre herdadas de forma idêntica entre irmãos'], 0,
  'Ao considerar múltiplas características simultaneamente, a Segunda Lei explica a diversidade de combinações genéticas.', 5),

-- Dominância completa (1c0394e3-ac5b-4b78-8e22-424c8d2eef2c)
('1c0394e3-ac5b-4b78-8e22-424c8d2eef2c', 'Na dominância completa, o fenótipo do heterozigoto (Aa) é:',
  array['Idêntico ao do homozigoto dominante (AA)', 'Intermediário entre os dois homozigotos', 'Idêntico ao do homozigoto recessivo (aa)', 'Sempre imprevisível'], 0,
  'Na dominância completa, o alelo dominante se expressa integralmente, mascarando o efeito do alelo recessivo.', 1),
('1c0394e3-ac5b-4b78-8e22-424c8d2eef2c', 'A cor das sementes de ervilha (amarela dominante sobre verde), estudada por Mendel, é um exemplo clássico de:',
  array['Dominância completa', 'Dominância incompleta', 'Codominância', 'Herança ligada ao sexo'], 0,
  'No modelo estudado por Mendel, o alelo para semente amarela é completamente dominante sobre o alelo para semente verde.', 2),
('1c0394e3-ac5b-4b78-8e22-424c8d2eef2c', 'Em uma característica de dominância completa, quantos fenótipos diferentes são possíveis para um gene com dois alelos (um dominante e um recessivo)?',
  array['2 (dominante e recessivo)', '3 (dominante, intermediário e recessivo)', '4', '1, pois todos apresentam o mesmo fenótipo'], 0,
  'Na dominância completa, apesar de existirem três genótipos possíveis, há apenas dois fenótipos.', 3),
('1c0394e3-ac5b-4b78-8e22-424c8d2eef2c', 'Ao analisar o fenótipo de um indivíduo dominante, sem conhecer seu genótipo, não é possível saber se ele é:',
  array['Homozigoto dominante (AA) ou heterozigoto (Aa)', 'Homozigoto dominante (AA) ou homozigoto recessivo (aa)', 'Heterozigoto (Aa) ou homozigoto recessivo (aa)', 'Macho ou fêmea'], 0,
  'Como AA e Aa produzem o mesmo fenótipo na dominância completa, o fenótipo sozinho não distingue esses dois genótipos.', 4),
('1c0394e3-ac5b-4b78-8e22-424c8d2eef2c', 'Um "teste cruzamento" (cruzamento-teste), utilizado para determinar o genótipo de um indivíduo de fenótipo dominante, consiste em cruzá-lo com um indivíduo:',
  array['Homozigoto recessivo (aa)', 'Homozigoto dominante (AA)', 'De outra espécie', 'Estéril, sem qualquer capacidade reprodutiva'], 0,
  'Cruzando com um homozigoto recessivo, é possível inferir o genótipo pela proporção de descendentes recessivos.', 5),

-- Dominância incompleta (58559535-fd80-4280-be81-84c7eedf4ebd)
('58559535-fd80-4280-be81-84c7eedf4ebd', 'Na dominância incompleta, o fenótipo do heterozigoto é:',
  array['Intermediário entre os fenótipos dos dois homozigotos', 'Idêntico ao do homozigoto dominante', 'Idêntico ao do homozigoto recessivo', 'Sempre igual ao fenótipo de um dos progenitores'], 0,
  'Na dominância incompleta, nenhum alelo se sobrepõe totalmente ao outro, gerando um fenótipo intermediário.', 1),
('58559535-fd80-4280-be81-84c7eedf4ebd', 'A cor das flores de "maravilha" (Mirabilis jalapa), exemplo clássico de dominância incompleta, ao cruzar uma planta de flor vermelha com uma de flor branca, resulta em descendentes com flores de cor:',
  array['Rosa (intermediária)', 'Vermelha, idêntica a um dos progenitores', 'Branca, idêntica ao outro progenitor', 'Impossível de prever'], 0,
  'A combinação dos alelos para vermelho e branco resulta em uma cor intermediária (rosa).', 2),
('58559535-fd80-4280-be81-84c7eedf4ebd', 'Na dominância incompleta, ao contrário da dominância completa, cada genótipo diferente (AA, Aa, aa) corresponde a:',
  array['Um fenótipo distinto e observável', 'Sempre o mesmo fenótipo, sem qualquer distinção', 'Apenas dois fenótipos possíveis, como na dominância completa', 'Nenhum fenótipo observável'], 0,
  'Na dominância incompleta, cada um dos três genótipos possíveis gera um fenótipo próprio e distinguível.', 3),
('58559535-fd80-4280-be81-84c7eedf4ebd', 'Ao cruzar duas plantas de flor rosa (heterozigotas) em um exemplo de dominância incompleta, a proporção fenotípica esperada na descendência é de:',
  array['1 vermelha : 2 rosa : 1 branca', '3 vermelhas : 1 branca', 'Todas as flores serão rosa', '1 vermelha : 1 branca, sem qualquer rosa'], 0,
  'Como o fenótipo reflete diretamente o genótipo, a proporção 1:2:1 corresponde à proporção fenotípica observada.', 4),
('58559535-fd80-4280-be81-84c7eedf4ebd', 'A dominância incompleta demonstra que a relação entre os alelos de um gene pode ser mais complexa do que a simples dominância completa, pois:',
  array['Nenhum alelo se sobrepõe totalmente ao outro, gerando uma expressão intermediária', 'Um dos alelos sempre desaparece completamente', 'Os alelos nunca interagem entre si', 'O fenótipo nunca reflete o genótipo, nesse caso'], 0,
  'A dominância incompleta ilustra que a interação entre alelos pode gerar fenótipos intermediários.', 5),

-- Codominância (c0706ac2-24d8-4fc6-a9b7-a73885687e25)
('c0706ac2-24d8-4fc6-a9b7-a73885687e25', 'Na codominância, os dois alelos de um heterozigoto se expressam:',
  array['Simultaneamente e de forma plena, sem se misturar, gerando um fenótipo combinado', 'De forma intermediária, misturando-se completamente', 'Apenas um dos alelos se expressa, mascarando totalmente o outro', 'Nenhum dos alelos se expressa'], 0,
  'Na codominância, ambos os alelos se manifestam totalmente e de forma independente no fenótipo do heterozigoto.', 1),
('c0706ac2-24d8-4fc6-a9b7-a73885687e25', 'O sistema sanguíneo ABO, em humanos, é um exemplo clássico de codominância, observado principalmente no genótipo:',
  array['IᴬIᴮ, que resulta no tipo sanguíneo AB', 'IᴬIᴼ, que resulta no tipo sanguíneo A', 'IᴼIᴼ, que resulta no tipo sanguíneo O', 'Apenas em indivíduos do tipo sanguíneo O'], 0,
  'No genótipo IᴬIᴮ, os alelos A e B se expressam simultaneamente, resultando no fenótipo sanguíneo AB.', 2),
('c0706ac2-24d8-4fc6-a9b7-a73885687e25', 'A diferença fundamental entre codominância e dominância incompleta é que, na codominância:',
  array['Os dois fenótipos parentais aparecem simultaneamente e distintamente no heterozigoto, sem mistura', 'Ocorre sempre uma mistura completa dos dois fenótipos', 'Um dos alelos é sempre completamente dominante sobre o outro', 'Não existe qualquer diferença entre os dois fenômenos'], 0,
  'Na codominância, os fenótipos aparecem lado a lado; na dominância incompleta, ocorre mistura em um fenótipo intermediário.', 3),
('c0706ac2-24d8-4fc6-a9b7-a73885687e25', 'Um exemplo frequentemente citado de codominância em animais é o padrão de pelagem de certas raças de gado, no qual um indivíduo heterozigoto apresenta:',
  array['Pelos brancos e vermelhos distintos, misturados no mesmo animal, sem formar uma cor intermediária', 'Pelagem completamente rosa, uniforme por todo o corpo', 'Pelagem idêntica a um dos progenitores, sem qualquer mistura', 'Ausência total de pelos'], 0,
  'No gado com codominância de cor, o heterozigoto exibe pelos das duas cores distintamente distribuídos.', 4),
('c0706ac2-24d8-4fc6-a9b7-a73885687e25', 'A codominância reforça a ideia de que a relação entre alelos, na genética, pode ser:',
  array['Muito mais variada do que apenas dominante ou recessivo', 'Sempre restrita a apenas dois padrões possíveis', 'Completamente aleatória, sem qualquer padrão', 'Idêntica em todos os casos de herança genética'], 0,
  'Fenômenos como codominância e dominância incompleta mostram que a interação entre alelos é complexa e variada.', 5),

-- Herança ligada ao sexo (6d0f873d-1dcd-4396-a193-fbe5b4476a7d)
('6d0f873d-1dcd-4396-a193-fbe5b4476a7d', 'A herança ligada ao sexo refere-se a características cujos genes estão localizados:',
  array['Nos cromossomos sexuais, geralmente no cromossomo X', 'Exclusivamente nos cromossomos autossômicos', 'Fora de qualquer cromossomo', 'Apenas no cromossomo Y, sem exceção'], 0,
  'A herança ligada ao sexo envolve genes presentes nos cromossomos sexuais, com padrões diferentes dos autossômicos.', 1),
('6d0f873d-1dcd-4396-a193-fbe5b4476a7d', 'O daltonismo e a hemofilia, condições humanas comumente estudadas em genética, são exemplos de herança:',
  array['Recessiva ligada ao cromossomo X', 'Dominante ligada ao cromossomo Y', 'Exclusivamente ligada ao cromossomo Y', 'Sem qualquer relação com os cromossomos sexuais'], 0,
  'Tanto o daltonismo quanto a hemofilia são causados por alelos recessivos localizados no cromossomo X.', 2),
('6d0f873d-1dcd-4396-a193-fbe5b4476a7d', 'Homens são mais frequentemente afetados por doenças recessivas ligadas ao X, como o daltonismo, principalmente porque:',
  array['Possuem apenas um cromossomo X, sendo hemizigotos para os genes desse cromossomo', 'Possuem dois cromossomos X, como as mulheres', 'Não possuem qualquer cromossomo sexual', 'Herdam sempre dois alelos recessivos automaticamente'], 0,
  'Com apenas um X (e um Y), homens expressam diretamente qualquer alelo presente nesse único cromossomo X.', 3),
('6d0f873d-1dcd-4396-a193-fbe5b4476a7d', 'Uma mulher heterozigota para uma doença recessiva ligada ao X, mas sem manifestar a doença, é chamada de:',
  array['Portadora', 'Homozigota afetada', 'Hemizigota', 'Estéril'], 0,
  'Mulheres heterozigotas não manifestam a doença, mas podem transmiti-la aos filhos, sendo chamadas de portadoras.', 4),
('6d0f873d-1dcd-4396-a193-fbe5b4476a7d', 'Para que uma mulher manifeste uma característica recessiva ligada ao X, ela precisa:',
  array['Herdar o alelo recessivo em ambos os cromossomos X (de pai e mãe)', 'Herdar o alelo recessivo apenas de um dos progenitores', 'Possuir apenas um cromossomo X', 'Nunca pode manifestar essa característica, independentemente da herança'], 0,
  'Como possuem dois cromossomos X, mulheres precisam herdar o alelo recessivo de ambos os progenitores.', 5),

-- Heredogramas (706f8471-6cd6-403b-8928-773860a47556)
('706f8471-6cd6-403b-8928-773860a47556', 'Um heredograma é uma representação gráfica utilizada para:',
  array['Ilustrar a transmissão de características hereditárias ao longo de gerações de uma família', 'Representar exclusivamente a estrutura de uma célula', 'Mostrar a composição química do DNA', 'Indicar apenas a localização geográfica de uma população'], 0,
  'Heredogramas organizam visualmente informações sobre a herança de características entre membros de uma família.', 1),
('706f8471-6cd6-403b-8928-773860a47556', 'Em um heredograma, quadrados e círculos são geralmente utilizados para representar, respectivamente:',
  array['Indivíduos do sexo masculino e do sexo feminino', 'Indivíduos afetados e não afetados, sem relação com o sexo', 'Gerações diferentes, sem relação com o sexo', 'Genes dominantes e recessivos'], 0,
  'Por convenção, quadrados representam homens e círculos representam mulheres nos heredogramas.', 2),
('706f8471-6cd6-403b-8928-773860a47556', 'Símbolos preenchidos (coloridos) em um heredograma geralmente indicam indivíduos:',
  array['Afetados pela característica ou condição estudada', 'Do sexo masculino, exclusivamente', 'Falecidos, independentemente da condição', 'Que nunca tiveram filhos'], 0,
  'A convenção de preenchimento indica os indivíduos que manifestam o fenótipo em estudo (afetados).', 3),
('706f8471-6cd6-403b-8928-773860a47556', 'A análise de um heredograma pode ajudar a determinar se uma característica é herdada de forma:',
  array['Dominante ou recessiva, autossômica ou ligada ao sexo', 'Exclusivamente ambiental, sem qualquer componente genético', 'Impossível de ser determinada, mesmo com dados suficientes', 'Idêntica em todas as características, sem qualquer variação'], 0,
  'Ao observar os padrões de transmissão em várias gerações, é possível inferir o tipo provável de herança.', 4),
('706f8471-6cd6-403b-8928-773860a47556', 'Em um heredograma, uma característica recessiva ligada ao X tende a aparecer com maior frequência:',
  array['Em indivíduos do sexo masculino', 'Em indivíduos do sexo feminino', 'Igualmente entre homens e mulheres, sem qualquer diferença', 'Apenas em indivíduos do sexo feminino'], 0,
  'Homens (hemizigotos para o X) expressam mais facilmente características recessivas ligadas a esse cromossomo.', 5);
