-- Português — Áreas gerais sem subdivisão (6 leaves, 8 questões cada)
insert into questions (catalog_node_id, prompt, options, correct_index, explanation, order_index) values
-- Gramática (282f04a3-1ac5-45ca-93d0-79ebb055890c)
('282f04a3-1ac5-45ca-93d0-79ebb055890c', 'Qual classe gramatical exerce a função de modificar o sentido de um substantivo, atribuindo-lhe uma característica?',
  array['Adjetivo', 'Advérbio', 'Conjunção', 'Interjeição'], 0,
  'O adjetivo caracteriza o substantivo, indicando qualidade, estado ou característica.', 1),
('282f04a3-1ac5-45ca-93d0-79ebb055890c', 'Qual classe gramatical é responsável por modificar o sentido de um verbo, adjetivo ou outro advérbio?',
  array['Advérbio', 'Substantivo', 'Artigo', 'Preposição'], 0,
  'O advérbio expressa circunstâncias (tempo, modo, lugar etc.) e modifica verbos, adjetivos ou outros advérbios.', 2),
('282f04a3-1ac5-45ca-93d0-79ebb055890c', 'As palavras "e", "mas", "ou" e "porque" pertencem a qual classe gramatical?',
  array['Conjunção', 'Preposição', 'Interjeição', 'Pronome'], 0,
  'Conjunções são palavras que ligam orações ou termos de mesma função sintática, estabelecendo relações de sentido entre eles.', 3),
('282f04a3-1ac5-45ca-93d0-79ebb055890c', 'Palavras como "eu", "ele", "meu" e "aquele" pertencem a qual classe gramatical, por substituírem ou acompanharem substantivos?',
  array['Pronome', 'Artigo', 'Numeral', 'Interjeição'], 0,
  'Pronomes substituem ou acompanham substantivos, indicando pessoa, posse ou outras funções.', 4),
('282f04a3-1ac5-45ca-93d0-79ebb055890c', 'O verbo "comer", conjugado como "eu como, tu comes, ele come", pertence a qual conjugação verbal?',
  array['Segunda conjugação (terminação -er)', 'Primeira conjugação (terminação -ar)', 'Terceira conjugação (terminação -ir)', 'Não pertence a nenhuma conjugação regular'], 0,
  'Verbos terminados em "-er" no infinitivo, como "comer", pertencem à segunda conjugação.', 5),
('282f04a3-1ac5-45ca-93d0-79ebb055890c', 'Na frase "Este é o melhor livro que já li", em que grau está o adjetivo "melhor"?',
  array['Superlativo relativo de superioridade', 'Comparativo de igualdade', 'Superlativo absoluto sintético', 'Grau normal (positivo)'], 0,
  '"O melhor" expressa que, entre um grupo de livros, este se destaca como superior: superlativo relativo de superioridade.', 6),
('282f04a3-1ac5-45ca-93d0-79ebb055890c', 'O processo de formação de palavras em que se juntam dois radicais já existentes, como em "passatempo", é chamado de:',
  array['Composição', 'Derivação prefixal', 'Derivação sufixal', 'Onomatopeia'], 0,
  'A composição forma novas palavras a partir da junção de dois radicais já existentes, como em "passatempo" (passa + tempo).', 7),
('282f04a3-1ac5-45ca-93d0-79ebb055890c', 'O verbo "pôr" é considerado, na gramática normativa, um verbo:',
  array['Irregular', 'Regular de primeira conjugação', 'Regular de segunda conjugação', 'Defectivo, sem qualquer forma conjugada'], 0,
  'O verbo "pôr" apresenta irregularidades em sua conjugação (eu ponho, ele põe), sendo classificado como irregular.', 8),

-- Sintaxe (6328fd95-8026-4dc2-8cdc-40bcaf543628)
('6328fd95-8026-4dc2-8cdc-40bcaf543628', 'Na frase "O menino correu pelo parque", qual é o sujeito da oração?',
  array['O menino', 'Correu', 'Pelo parque', 'Parque'], 0,
  '"O menino" é quem pratica a ação expressa pelo verbo "correu", exercendo a função de sujeito.', 1),
('6328fd95-8026-4dc2-8cdc-40bcaf543628', 'Na frase "A professora explicou a matéria aos alunos", qual termo exerce a função de objeto direto?',
  array['A matéria', 'A professora', 'Aos alunos', 'Explicou'], 0,
  '"A matéria" é o termo que recebe diretamente a ação do verbo "explicou", sem preposição obrigatória, sendo objeto direto.', 2),
('6328fd95-8026-4dc2-8cdc-40bcaf543628', 'Na frase "A professora explicou a matéria aos alunos", qual termo exerce a função de objeto indireto?',
  array['Aos alunos', 'A matéria', 'A professora', 'Explicou'], 0,
  '"Aos alunos" completa o sentido do verbo por meio de preposição, exercendo a função de objeto indireto.', 3),
('6328fd95-8026-4dc2-8cdc-40bcaf543628', 'Na frase "Maria é uma ótima médica", qual é a função sintática do termo "uma ótima médica"?',
  array['Predicativo do sujeito', 'Objeto direto', 'Objeto indireto', 'Adjunto adverbial'], 0,
  'Com o verbo de ligação "é", o termo "uma ótima médica" atribui uma característica ao sujeito, exercendo a função de predicativo do sujeito.', 4),
('6328fd95-8026-4dc2-8cdc-40bcaf543628', 'Na frase "Ele chegou cedo ao trabalho", qual é a função sintática do termo "cedo"?',
  array['Adjunto adverbial de tempo', 'Objeto direto', 'Sujeito', 'Predicativo do sujeito'], 0,
  '"Cedo" indica a circunstância de tempo em que a ação ocorreu, exercendo a função de adjunto adverbial.', 5),
('6328fd95-8026-4dc2-8cdc-40bcaf543628', 'Uma oração que não possui sujeito, como em "Choveu bastante ontem", é classificada como:',
  array['Oração sem sujeito (sujeito inexistente)', 'Oração de sujeito oculto', 'Oração de sujeito composto', 'Oração de sujeito indeterminado'], 0,
  'Verbos que indicam fenômenos da natureza, como "chover", são impessoais e formam orações sem sujeito.', 6),
('6328fd95-8026-4dc2-8cdc-40bcaf543628', 'Na frase "Comprei um livro e uma caneta", a relação entre as duas ideias coordenadas é de:',
  array['Adição (coordenação aditiva)', 'Oposição (coordenação adversativa)', 'Conclusão (coordenação conclusiva)', 'Explicação (coordenação explicativa)'], 0,
  'A conjunção "e" liga ideias que se somam, caracterizando uma oração coordenada aditiva.', 7),
('6328fd95-8026-4dc2-8cdc-40bcaf543628', 'Na frase "Estudei bastante, portanto passei na prova", a conjunção "portanto" estabelece uma relação de:',
  array['Conclusão', 'Adição', 'Oposição', 'Alternância'], 0,
  '"Portanto" é uma conjunção coordenativa conclusiva, indicando uma consequência lógica da oração anterior.', 8),

-- Ortografia e acentuação (7a5990be-75cb-47a5-a2c9-2ecafee8af28)
('7a5990be-75cb-47a5-a2c9-2ecafee8af28', 'Assinale a alternativa com a grafia correta da palavra:',
  array['Exceção', 'Excessão', 'Ecessão', 'Excepção'], 0,
  'A grafia correta, segundo o novo acordo ortográfico, é "exceção", sem o "p" mudo.', 1),
('7a5990be-75cb-47a5-a2c9-2ecafee8af28', 'Assinale a alternativa em que todas as palavras estão corretamente acentuadas:',
  array['Álbum, também, café', 'Album, tambem, café', 'Álbum, tambem, cafe', 'Album, também, cafe'], 0,
  '"Álbum" (paroxítona terminada em -um) e "também" (oxítona terminada em -em) recebem acento; "café" é oxítona terminada em "e" tônico, também acentuada.', 2),
('7a5990be-75cb-47a5-a2c9-2ecafee8af28', 'Qual regra justifica a acentuação da palavra "você"?',
  array['É uma palavra oxítona terminada em "e"', 'É uma palavra paroxítona terminada em "e"', 'É uma proparoxítona', 'Não segue nenhuma regra de acentuação'], 0,
  'Palavras oxítonas terminadas em "e" são acentuadas, como em "você", "café" e "jacaré".', 3),
('7a5990be-75cb-47a5-a2c9-2ecafee8af28', 'Todas as palavras proparoxítonas são, segundo a norma-padrão:',
  array['Sempre acentuadas graficamente', 'Nunca acentuadas', 'Acentuadas apenas quando terminam em vogal', 'Acentuadas apenas quando são substantivos'], 0,
  'Toda palavra proparoxítona recebe acento gráfico obrigatoriamente, como em "médico", "público" e "árvore".', 4),
('7a5990be-75cb-47a5-a2c9-2ecafee8af28', 'Assinale a alternativa que preenche corretamente a lacuna: "Assisti a uma ____ de cinema muito interessante."',
  array['Sessão', 'Seção', 'Cessão', 'Ceção'], 0,
  '"Sessão" refere-se a um período de duração de um espetáculo, reunião ou evento; "seção" é uma divisão/setor; "cessão" é o ato de ceder algo.', 5),
('7a5990be-75cb-47a5-a2c9-2ecafee8af28', 'Assinale a alternativa que preenche corretamente a lacuna: "A empresa fez a ____ de seus direitos autorais para a editora."',
  array['Cessão', 'Sessão', 'Seção', 'Cassão'], 0,
  '"Cessão" é o ato de ceder, transferir algo; no contexto de direitos autorais, é a forma correta.', 6),
('7a5990be-75cb-47a5-a2c9-2ecafee8af28', 'Assinale a alternativa que preenche corretamente a lacuna: "Procure na ____ de esportes do jornal."',
  array['Seção', 'Sessão', 'Cessão', 'Ceção'], 0,
  '"Seção" refere-se a uma divisão, parte ou departamento, como em "seção de esportes".', 7),
('7a5990be-75cb-47a5-a2c9-2ecafee8af28', 'Assinale a alternativa com a grafia correta da palavra, considerando o uso do hífen segundo o Novo Acordo Ortográfico:',
  array['Guarda-chuva', 'Guardachuva', 'Guarda chuva', 'Guarda-a-chuva'], 0,
  '"Guarda-chuva" é uma palavra composta que mantém o hífen segundo as regras vigentes do Novo Acordo Ortográfico.', 8),

-- Semântica (f25a58d3-8d53-4fda-abee-4ee3cb708b26)
('f25a58d3-8d53-4fda-abee-4ee3cb708b26', 'Qual é o sinônimo mais adequado para a palavra "efêmero"?',
  array['Passageiro, de curta duração', 'Eterno, permanente', 'Extremamente resistente', 'Complexo, difícil de entender'], 0,
  '"Efêmero" significa algo que dura pouco tempo, sendo sinônimo de "passageiro" ou "transitório".', 1),
('f25a58d3-8d53-4fda-abee-4ee3cb708b26', 'Qual é o antônimo da palavra "generoso"?',
  array['Mesquinho', 'Solidário', 'Caridoso', 'Altruísta'], 0,
  '"Mesquinho" expressa a ideia oposta de generosidade, sendo seu antônimo.', 2),
('f25a58d3-8d53-4fda-abee-4ee3cb708b26', 'Na frase "Ele tem um coração de ouro", qual figura de linguagem está presente?',
  array['Metáfora', 'Metonímia', 'Hipérbole', 'Eufemismo'], 0,
  'A metáfora consiste em uma comparação implícita, atribuindo a alguém uma qualidade (bondade) por meio de outra imagem (coração de ouro).', 3),
('f25a58d3-8d53-4fda-abee-4ee3cb708b26', 'Na frase "Chorei rios de lágrimas", qual figura de linguagem está presente, pelo exagero intencional?',
  array['Hipérbole', 'Eufemismo', 'Ironia', 'Prosopopeia'], 0,
  'A hipérbole consiste no exagero intencional de uma ideia para dar ênfase, como em "rios de lágrimas".', 4),
('f25a58d3-8d53-4fda-abee-4ee3cb708b26', 'Na frase "Ele foi para um lugar melhor", ao se referir à morte de alguém, qual figura de linguagem está presente?',
  array['Eufemismo', 'Hipérbole', 'Ironia', 'Metonímia'], 0,
  'O eufemismo suaviza uma ideia desagradável, como a morte, substituindo-a por uma expressão mais branda.', 5),
('f25a58d3-8d53-4fda-abee-4ee3cb708b26', 'Na frase "Que belo serviço você fez!", dita de forma sarcástica sobre um trabalho malfeito, qual figura de linguagem está presente?',
  array['Ironia', 'Metáfora', 'Eufemismo', 'Hipérbole'], 0,
  'A ironia expressa o contrário do que se diz literalmente, com intenção crítica ou sarcástica.', 6),
('f25a58d3-8d53-4fda-abee-4ee3cb708b26', 'A palavra "manga" pode significar tanto a fruta quanto a parte de uma camisa. Esse fenômeno linguístico é chamado de:',
  array['Homonímia', 'Sinonímia', 'Antonímia', 'Paronímia'], 0,
  'Palavras com a mesma grafia e/ou pronúncia, mas significados diferentes, como "manga", caracterizam a homonímia.', 7),
('f25a58d3-8d53-4fda-abee-4ee3cb708b26', 'As palavras "comprimento" e "cumprimento", com grafias parecidas mas significados diferentes, exemplificam o fenômeno da:',
  array['Paronímia', 'Homonímia', 'Sinonímia', 'Polissemia'], 0,
  'Parônimos são palavras com grafia e pronúncia semelhantes, mas significados distintos, como "comprimento" (extensão) e "cumprimento" (saudação).', 8),

-- Redação (3489b617-c328-4af1-bd3d-7a84dd343f79)
('3489b617-c328-4af1-bd3d-7a84dd343f79', 'Qual é a estrutura básica esperada de uma redação dissertativo-argumentativa, modelo cobrado no Enem?',
  array['Introdução, desenvolvimento e conclusão, com proposta de intervenção', 'Apenas narração de fatos em ordem cronológica', 'Somente diálogos entre personagens', 'Introdução e desenvolvimento, sem conclusão'], 0,
  'O texto dissertativo-argumentativo do Enem exige introdução com tese, desenvolvimento com argumentação e conclusão com proposta de intervenção.', 1),
('3489b617-c328-4af1-bd3d-7a84dd343f79', 'O que caracteriza a "tese" em uma redação dissertativo-argumentativa?',
  array['O ponto de vista central que o autor defenderá ao longo do texto', 'Um resumo de todos os parágrafos do texto', 'Uma lista de referências bibliográficas', 'A conclusão final, sem relação com a introdução'], 0,
  'A tese é a ideia central defendida pelo autor, geralmente apresentada já na introdução do texto.', 2),
('3489b617-c328-4af1-bd3d-7a84dd343f79', 'Na redação do Enem, o que é exigido na proposta de intervenção, presente na conclusão do texto?',
  array['Uma solução viável para o problema discutido, indicando agente, ação, modo e outros detalhes', 'Uma opinião pessoal sem qualquer relação com o tema', 'Um resumo repetido da introdução, sem elementos novos', 'Apenas uma pergunta retórica ao leitor'], 0,
  'A proposta de intervenção deve apresentar uma solução concreta e detalhada para o problema abordado, respeitando os direitos humanos.', 3),
('3489b617-c328-4af1-bd3d-7a84dd343f79', 'O que caracteriza um parágrafo de desenvolvimento bem construído em uma redação dissertativo-argumentativa?',
  array['Apresentar um argumento com repertório sociocultural e conclusão parcial ligada à tese', 'Apenas repetir a introdução com outras palavras', 'Conter somente exemplos, sem qualquer argumentação', 'Ser composto exclusivamente por citações de autores'], 0,
  'Um bom parágrafo de desenvolvimento apresenta um argumento consistente, sustentado por repertório sociocultural, conectado à tese defendida.', 4),
('3489b617-c328-4af1-bd3d-7a84dd343f79', 'O que se entende por "repertório sociocultural" em uma redação argumentativa?',
  array['Referências a fatos, dados, obras ou conhecimentos que enriquecem a argumentação', 'Uma lista de erros gramaticais a serem evitados', 'O uso exclusivo de gírias e expressões informais', 'Apenas opiniões pessoais sem qualquer fundamentação'], 0,
  'O repertório sociocultural consiste em referências (históricas, científicas, filosóficas, culturais) que sustentam e enriquecem os argumentos do texto.', 5),
('3489b617-c328-4af1-bd3d-7a84dd343f79', 'Qual é a principal função dos conectivos (como "portanto", "além disso", "por outro lado") em uma redação dissertativa?',
  array['Garantir a coesão textual, articulando as ideias entre os parágrafos', 'Aumentar artificialmente o número de palavras do texto', 'Substituir a necessidade de argumentos', 'Encerrar o texto sem necessidade de conclusão'], 0,
  'Os conectivos articulam as ideias e garantem a coesão entre frases e parágrafos, tornando o texto mais fluido e organizado.', 6),
('3489b617-c328-4af1-bd3d-7a84dd343f79', 'Fugir do tema proposto em uma redação do Enem acarreta, segundo os critérios de avaliação, qual consequência?',
  array['A anulação da redação, recebendo nota zero', 'Apenas uma pequena perda de pontos na competência de coesão', 'Nenhuma consequência, desde que o texto esteja bem escrito', 'Uma advertência, sem impacto na nota final'], 0,
  'Fugir do tema é um dos critérios que zeram a redação no Enem, independentemente da qualidade textual do restante do texto.', 7),
('3489b617-c328-4af1-bd3d-7a84dd343f79', 'O que caracteriza um texto dissertativo-argumentativo, diferenciando-o de um texto narrativo?',
  array['A defesa de um ponto de vista por meio de argumentos, e não o relato de uma sequência de fatos', 'A presença obrigatória de personagens e diálogos', 'A ausência total de qualquer opinião', 'O uso exclusivo de linguagem poética'], 0,
  'O texto dissertativo-argumentativo defende uma tese por meio de argumentos, diferentemente da narração, que relata uma sucessão de fatos.', 8),

-- Literatura (a0caa678-52be-4ae4-9251-8f26e0ca476c)
('a0caa678-52be-4ae4-9251-8f26e0ca476c', 'O Barroco, movimento literário do século XVII no Brasil, é caracterizado, entre outros aspectos, por:',
  array['O uso de contrastes (cultismo e conceptismo) e temas religiosos', 'A valorização exclusiva da razão e do equilíbrio clássico', 'A rejeição total de qualquer referência religiosa', 'O uso exclusivo de linguagem coloquial e informal'], 0,
  'O Barroco caracteriza-se pelo conflito entre razão e fé, prazer e culpa, expresso por meio de jogos de linguagem (cultismo) e argumentação lógica (conceptismo).', 1),
('a0caa678-52be-4ae4-9251-8f26e0ca476c', 'O Arcadismo, movimento literário do século XVIII, valorizava, entre outros ideais, o(a):',
  array['Retorno à simplicidade da vida no campo (bucolismo) e o equilíbrio clássico', 'Exaltação da vida urbana industrializada', 'Valorização do sonho e do inconsciente', 'Experimentalismo radical da linguagem'], 0,
  'O Arcadismo buscava a simplicidade da vida campestre (bucolismo), o equilíbrio e a racionalidade, inspirado nos clássicos greco-romanos.', 2),
('a0caa678-52be-4ae4-9251-8f26e0ca476c', 'José de Alencar, autor de "Iracema" e "O Guarani", é uma figura central de qual movimento literário brasileiro?',
  array['Romantismo', 'Realismo', 'Modernismo', 'Barroco'], 0,
  'José de Alencar é um dos principais representantes do Romantismo brasileiro, com destaque para o indianismo em suas obras.', 3),
('a0caa678-52be-4ae4-9251-8f26e0ca476c', 'Machado de Assis, autor de "Dom Casmurro" e "Memórias Póstumas de Brás Cubas", é o principal nome de qual movimento literário no Brasil?',
  array['Realismo', 'Romantismo', 'Barroco', 'Arcadismo'], 0,
  'Machado de Assis é considerado o maior expoente do Realismo brasileiro, com obras marcadas pela crítica social e pela análise psicológica.', 4),
('a0caa678-52be-4ae4-9251-8f26e0ca476c', 'A Semana de Arte Moderna de 1922, em São Paulo, é considerada o marco inicial de qual movimento literário e artístico no Brasil?',
  array['Modernismo', 'Romantismo', 'Simbolismo', 'Naturalismo'], 0,
  'A Semana de Arte Moderna de 1922 rompeu com os padrões estéticos tradicionais, dando início ao Modernismo brasileiro.', 5),
('a0caa678-52be-4ae4-9251-8f26e0ca476c', 'Carlos Drummond de Andrade, um dos principais poetas modernistas brasileiros, é autor de qual poema amplamente estudado, sobre uma pedra no meio do caminho?',
  array['"No meio do caminho"', '"Canção do exílio"', '"Vou-me embora pra Pasárgada"', '"Soneto de fidelidade"'], 0,
  '"No meio do caminho" é um dos poemas mais conhecidos de Drummond, com o verso repetido "tinha uma pedra no meio do caminho".', 6),
('a0caa678-52be-4ae4-9251-8f26e0ca476c', 'Clarice Lispector, autora de obras como "A Hora da Estrela" e "Laços de Família", é reconhecida principalmente por:',
  array['Sua prosa introspectiva, marcada pelo fluxo de consciência e reflexões existenciais', 'Poemas árcades sobre a vida no campo', 'Romances históricos sobre o período colonial', 'Peças de teatro em versos clássicos'], 0,
  'Clarice Lispector é conhecida por sua prosa introspectiva e psicológica, explorando o fluxo de consciência de seus personagens.', 7),
('a0caa678-52be-4ae4-9251-8f26e0ca476c', 'O movimento literário conhecido como Simbolismo, no final do século XIX, caracterizava-se por:',
  array['Uma linguagem musical, subjetiva e voltada para o mundo espiritual e sensorial', 'Descrição objetiva e científica da realidade, como no Naturalismo', 'O equilíbrio clássico greco-romano, como no Arcadismo', 'A experimentação radical da linguagem verbal, como na poesia concreta'], 0,
  'O Simbolismo valorizava a musicalidade, a subjetividade e temas espirituais/sensoriais, em oposição à objetividade do Realismo/Naturalismo.', 8);
