-- Biologia — Áreas gerais sem subdivisão (4 leaves, 8 questões cada)
insert into questions (catalog_node_id, prompt, options, correct_index, explanation, order_index) values
-- Botânica (ac32071e-53bb-4644-bc7e-a0dfe219e216)
('ac32071e-53bb-4644-bc7e-a0dfe219e216', 'A fotossíntese, processo fundamental realizado pelas plantas, ocorre principalmente:',
  array['Nos cloroplastos das células vegetais, utilizando luz solar, água e gás carbônico', 'Nas mitocôndrias, sem qualquer participação da luz solar', 'Exclusivamente nas raízes das plantas', 'Apenas durante a noite, na ausência de luz'], 0,
  'A fotossíntese converte energia luminosa em energia química (glicose), ocorrendo nos cloroplastos.', 1),
('ac32071e-53bb-4644-bc7e-a0dfe219e216', 'As raízes das plantas têm como principais funções:',
  array['Fixar a planta ao solo e absorver água e sais minerais', 'Realizar diretamente a fotossíntese', 'Produzir flores e frutos', 'Realizar a reprodução sexuada da planta'], 0,
  'As raízes ancoram a planta ao substrato e absorvem água e nutrientes minerais do solo.', 2),
('ac32071e-53bb-4644-bc7e-a0dfe219e216', 'O xilema, tecido condutor presente nas plantas vasculares, é responsável principalmente por transportar:',
  array['Água e sais minerais, das raízes até as demais partes da planta', 'Seiva elaborada (rica em açúcares), das folhas para o restante da planta', 'Exclusivamente gases, como oxigênio e gás carbônico', 'Pólen entre diferentes flores'], 0,
  'O xilema conduz a seiva bruta (água e minerais) das raízes até as folhas e demais órgãos da planta.', 3),
('ac32071e-53bb-4644-bc7e-a0dfe219e216', 'O floema, outro tecido condutor vegetal, é responsável por transportar:',
  array['A seiva elaborada, rica em açúcares produzidos na fotossíntese, para as diversas partes da planta', 'Exclusivamente água pura, sem qualquer nutriente dissolvido', 'Apenas oxigênio atmosférico', 'Pólen entre flores diferentes'], 0,
  'O floema distribui os produtos da fotossíntese das folhas para as demais partes da planta.', 4),
('ac32071e-53bb-4644-bc7e-a0dfe219e216', 'A polinização, processo essencial na reprodução da maioria das plantas com flores, corresponde à:',
  array['Transferência do pólen das partes masculinas para as partes femininas da flor', 'Absorção de água pelas raízes', 'Produção de clorofila nas folhas', 'Formação exclusiva de raízes novas'], 0,
  'A polinização é essencial para a fecundação e a formação de sementes e frutos.', 5),
('ac32071e-53bb-4644-bc7e-a0dfe219e216', 'As briófitas, como os musgos, são consideradas plantas relativamente simples por:',
  array['Não possuírem tecidos vasculares (xilema e floema) bem desenvolvidos', 'Serem as plantas mais complexas e evoluídas atualmente', 'Produzirem flores e frutos, como as angiospermas', 'Serem exclusivamente aquáticas, sem qualquer adaptação terrestre'], 0,
  'As briófitas são plantas avasculares, dependendo fortemente da umidade ambiental para sua sobrevivência.', 6),
('ac32071e-53bb-4644-bc7e-a0dfe219e216', 'As angiospermas, grupo vegetal mais diversificado atualmente, são caracterizadas principalmente por:',
  array['Produzirem flores e frutos, que envolvem e protegem suas sementes', 'Não produzirem sementes de forma alguma', 'Serem exclusivamente plantas aquáticas', 'Não realizarem fotossíntese'], 0,
  'A presença de flores e frutos, que protegem e auxiliam na dispersão das sementes, caracteriza as angiospermas.', 7),
('ac32071e-53bb-4644-bc7e-a0dfe219e216', 'O processo de germinação de uma semente depende geralmente de condições adequadas de:',
  array['Água, temperatura e oxigênio', 'Apenas luz solar direta, exclusivamente', 'Ausência total de água', 'Temperaturas extremamente baixas, exclusivamente'], 0,
  'A germinação depende de fatores ambientais favoráveis, como água, temperatura adequada e oxigênio.', 8),

-- Zoologia (b380072b-51b4-462b-99fa-266d0dcffa59)
('b380072b-51b4-462b-99fa-266d0dcffa59', 'Os animais são classificados, quanto à presença ou ausência de coluna vertebral, em:',
  array['Vertebrados e invertebrados', 'Apenas mamíferos e répteis', 'Terrestres e aquáticos, exclusivamente', 'Carnívoros e herbívoros, exclusivamente'], 0,
  'Essa é uma das classificações mais fundamentais da zoologia, dividindo os animais entre com e sem coluna vertebral.', 1),
('b380072b-51b4-462b-99fa-266d0dcffa59', 'Os invertebrados representam, em termos de diversidade de espécies conhecidas:',
  array['A grande maioria dos animais existentes no planeta', 'Uma pequena minoria, em comparação com os vertebrados', 'Exatamente a metade das espécies animais conhecidas', 'Um grupo inexistente atualmente'], 0,
  'Grupos como insetos, moluscos e crustáceos representam a esmagadora maioria das espécies animais catalogadas.', 2),
('b380072b-51b4-462b-99fa-266d0dcffa59', 'Os mamíferos, grupo de vertebrados que inclui os seres humanos, caracterizam-se, entre outros aspectos, por:',
  array['Possuírem glândulas mamárias, capazes de produzir leite para alimentar os filhotes', 'Serem todos exclusivamente aquáticos', 'Não possuírem qualquer tipo de pelo', 'Realizarem exclusivamente reprodução assexuada'], 0,
  'A presença de glândulas mamárias produtoras de leite é uma característica exclusiva dos mamíferos.', 3),
('b380072b-51b4-462b-99fa-266d0dcffa59', 'Os anfíbios, como sapos e rãs, são caracterizados por, geralmente, apresentarem:',
  array['Um ciclo de vida com fase aquática (larval) e fase terrestre (adulta)', 'Um ciclo de vida exclusivamente aquático, sem qualquer fase terrestre', 'Pele completamente impermeável, semelhante à dos répteis', 'Ausência total de qualquer relação com a água'], 0,
  'A maioria dos anfíbios passa por metamorfose, iniciando a vida na água e se desenvolvendo para a fase terrestre.', 4),
('b380072b-51b4-462b-99fa-266d0dcffa59', 'Os répteis, diferentemente dos anfíbios, apresentam como importante adaptação evolutiva:',
  array['Ovos com casca resistente, adaptados para o desenvolvimento fora da água (ovo amniótico)', 'Dependência obrigatória de ambientes aquáticos para reprodução', 'Ausência total de pele', 'Incapacidade de viver em ambientes terrestres'], 0,
  'O ovo amniótico permitiu que os répteis se reproduzissem de forma independente da água.', 5),
('b380072b-51b4-462b-99fa-266d0dcffa59', 'As aves, grupo de vertebrados caracterizado pela presença de penas, apresentam como uma de suas principais adaptações para o voo:',
  array['Ossos leves e pneumáticos, além de músculos peitorais desenvolvidos', 'Ossos extremamente densos e pesados', 'Ausência total de qualquer adaptação relacionada ao voo', 'Presença obrigatória de guelras'], 0,
  'A estrutura óssea leve e a musculatura peitoral desenvolvida são adaptações essenciais para o voo.', 6),
('b380072b-51b4-462b-99fa-266d0dcffa59', 'Os insetos, grupo mais numeroso entre os invertebrados, caracterizam-se, entre outros aspectos, por possuírem o corpo dividido em:',
  array['Cabeça, tórax e abdômen', 'Apenas duas regiões corporais', 'Uma única região corporal contínua', 'Cinco regiões corporais distintas'], 0,
  'A divisão do corpo em cabeça, tórax e abdômen é uma característica típica e diagnóstica dos insetos.', 7),
('b380072b-51b4-462b-99fa-266d0dcffa59', 'Os cnidários, grupo que inclui águas-vivas e corais, são caracterizados por possuírem:',
  array['Células urticantes (cnidócitos), utilizadas para captura de presas e defesa', 'Coluna vertebral desenvolvida', 'Pulmões bem desenvolvidos', 'Glândulas mamárias funcionais'], 0,
  'Os cnidócitos são células especializadas, exclusivas dos cnidários, usadas para injetar toxinas.', 8),

-- Microbiologia e Saúde (bee5e4cb-fe57-4ac9-936a-626442f07b75)
('bee5e4cb-fe57-4ac9-936a-626442f07b75', 'Os microrganismos estudados pela microbiologia incluem, entre outros grupos:',
  array['Bactérias, vírus, fungos e protozoários', 'Apenas animais de grande porte', 'Exclusivamente plantas', 'Somente seres humanos'], 0,
  'A microbiologia estuda organismos microscópicos, incluindo bactérias, vírus, fungos e protozoários.', 1),
('bee5e4cb-fe57-4ac9-936a-626442f07b75', 'As bactérias são organismos classificados como:',
  array['Procariontes, sem núcleo organizado por membrana', 'Eucariontes, com núcleo bem definido', 'Organismos exclusivamente multicelulares', 'Seres não vivos, sem qualquer atividade metabólica'], 0,
  'As bactérias são organismos procariontes, sem núcleo delimitado por membrana.', 2),
('bee5e4cb-fe57-4ac9-936a-626442f07b75', 'Os vírus são frequentemente considerados estruturas biológicas particulares porque:',
  array['Não possuem estrutura celular própria e dependem obrigatoriamente de uma célula hospedeira para se reproduzir', 'São sempre maiores do que as bactérias', 'Possuem estrutura celular completa, semelhante às bactérias', 'Não apresentam qualquer material genético'], 0,
  'Por não possuírem estrutura celular própria, os vírus dependem de uma célula hospedeira para se replicar.', 3),
('bee5e4cb-fe57-4ac9-936a-626442f07b75', 'Antibióticos, medicamentos amplamente utilizados no combate a infecções, são eficazes especificamente contra:',
  array['Bactérias', 'Vírus, exclusivamente', 'Todos os tipos de microrganismos, sem qualquer distinção', 'Nenhum tipo de microrganismo'], 0,
  'Antibióticos atuam sobre estruturas ou processos bacterianos, sendo ineficazes contra infecções virais.', 4),
('bee5e4cb-fe57-4ac9-936a-626442f07b75', 'O uso excessivo e inadequado de antibióticos pode contribuir para:',
  array['O desenvolvimento de resistência bacteriana aos medicamentos', 'A eliminação definitiva de todas as bactérias resistentes', 'Nenhuma consequência relevante para a saúde pública', 'Uma maior eficácia dos antibióticos a longo prazo'], 0,
  'O uso inadequado de antibióticos favorece a seleção de bactérias resistentes.', 5),
('bee5e4cb-fe57-4ac9-936a-626442f07b75', 'Os fungos, diferentemente das plantas, são organismos:',
  array['Heterotróficos, obtendo nutrientes por absorção de matéria orgânica externa', 'Autotróficos, capazes de realizar fotossíntese', 'Exclusivamente unicelulares', 'Desprovidos de parede celular'], 0,
  'Ao contrário das plantas, os fungos obtêm nutrientes absorvendo matéria orgânica do ambiente.', 6),
('bee5e4cb-fe57-4ac9-936a-626442f07b75', 'Doenças causadas por protozoários, como a malária (causada pelo Plasmodium), são frequentemente transmitidas por:',
  array['Vetores, como mosquitos, que transportam o agente causador entre hospedeiros', 'Contato direto com o ar, sem qualquer vetor', 'Ingestão exclusiva de água pura', 'Herança genética direta, de pais para filhos'], 0,
  'A malária é transmitida principalmente pela picada de mosquitos do gênero Anopheles, atuando como vetores.', 7),
('bee5e4cb-fe57-4ac9-936a-626442f07b75', 'Medidas básicas de higiene, como lavar as mãos regularmente, são eficazes na prevenção de diversas doenças infecciosas porque:',
  array['Reduzem significativamente a transmissão de microrganismos patogênicos', 'Não têm qualquer efeito sobre a propagação de doenças', 'Aumentam a proliferação de bactérias nocivas', 'Substituem totalmente a necessidade de vacinação'], 0,
  'A higienização adequada das mãos reduz significativamente o risco de transmissão de doenças.', 8),

-- Evolução (18976237-e643-437e-8216-7ff0c5a09df5)
('18976237-e643-437e-8216-7ff0c5a09df5', 'A Teoria da Evolução por Seleção Natural, proposta por Charles Darwin, baseia-se principalmente na ideia de que:',
  array['Indivíduos mais bem adaptados ao ambiente têm maior chance de sobreviver e se reproduzir, transmitindo suas características', 'Todos os indivíduos de uma população têm exatamente as mesmas chances de sobrevivência, independentemente de suas características', 'As características adquiridas ao longo da vida são sempre transmitidas geneticamente aos descendentes', 'A evolução ocorre de forma instantânea, em uma única geração'], 0,
  'A seleção natural favorece a sobrevivência e reprodução diferencial dos indivíduos mais adaptados, ao longo de gerações.', 1),
('18976237-e643-437e-8216-7ff0c5a09df5', 'A variabilidade genética dentro de uma população é fundamental para o processo evolutivo porque:',
  array['Fornece a matéria-prima sobre a qual a seleção natural pode atuar', 'Impede completamente qualquer mudança evolutiva', 'Garante que todos os indivíduos sejam sempre idênticos entre si', 'Não tem qualquer relação com a evolução das espécies'], 0,
  'Sem variabilidade genética, não haveria diferenças entre os indivíduos sobre as quais a seleção natural pudesse atuar.', 2),
('18976237-e643-437e-8216-7ff0c5a09df5', 'O conceito de "adaptação", central na teoria evolutiva, refere-se a:',
  array['Características que aumentam a capacidade de sobrevivência e reprodução de um organismo em seu ambiente', 'Mudanças aleatórias sem qualquer relação com o ambiente', 'Características que sempre prejudicam a sobrevivência do organismo', 'Um processo que ocorre apenas em plantas, nunca em animais'], 0,
  'Adaptações são características que conferem vantagens para a sobrevivência e reprodução em determinado ambiente.', 3),
('18976237-e643-437e-8216-7ff0c5a09df5', 'O processo de especiação, que resulta na formação de novas espécies, geralmente ocorre quando:',
  array['Populações de uma mesma espécie ficam isoladas reprodutivamente, acumulando diferenças genéticas ao longo do tempo', 'Todos os indivíduos de uma espécie permanecem sempre em contato direto, sem qualquer isolamento', 'Não existe qualquer variação genética entre indivíduos', 'A seleção natural nunca influencia a formação de novas espécies'], 0,
  'O isolamento reprodutivo entre populações permite o acúmulo independente de mudanças genéticas, podendo gerar novas espécies.', 4),
('18976237-e643-437e-8216-7ff0c5a09df5', 'Registros fósseis constituem uma das principais evidências utilizadas para sustentar a teoria da evolução porque:',
  array['Documentam mudanças graduais em características de organismos ao longo de longos períodos geológicos', 'Provam que nenhuma espécie jamais se extinguiu', 'Mostram que todas as espécies sempre permaneceram idênticas ao longo do tempo', 'Não têm qualquer relação com o estudo da evolução'], 0,
  'A análise de fósseis de diferentes períodos permite observar mudanças graduais, evidenciando processos evolutivos.', 5),
('18976237-e643-437e-8216-7ff0c5a09df5', 'A homologia entre estruturas anatômicas de diferentes espécies, como os membros de mamíferos com funções distintas (nadar, voar, correr), mas com estrutura óssea semelhante, é considerada uma evidência de:',
  array['Ancestralidade comum entre essas espécies', 'Ausência total de qualquer relação evolutiva entre as espécies', 'Que essas espécies surgiram de forma completamente independente', 'Que a evolução nunca ocorreu entre esses grupos'], 0,
  'Estruturas homólogas, apesar de funções diferentes, compartilham uma origem evolutiva comum.', 6),
('18976237-e643-437e-8216-7ff0c5a09df5', 'A resistência de certas bactérias a antibióticos, observada ao longo do tempo, é um exemplo atual e observável de:',
  array['Seleção natural em ação', 'Um fenômeno que nunca ocorre na natureza', 'Um processo completamente aleatório, sem qualquer relação com a sobrevivência', 'Ausência total de variabilidade genética nas populações bacterianas'], 0,
  'Bactérias com mutações que conferem resistência sobrevivem e se reproduzem preferencialmente, um exemplo direto de seleção natural.', 7),
('18976237-e643-437e-8216-7ff0c5a09df5', 'A evolução convergente ocorre quando espécies não diretamente aparentadas desenvolvem, de forma independente, características semelhantes devido a:',
  array['Pressões seletivas semelhantes em ambientes parecidos', 'Compartilharem obrigatoriamente um ancestral comum recente', 'Nenhuma relação com o ambiente em que vivem', 'Uma mutação idêntica ocorrida simultaneamente nas duas espécies'], 0,
  'A evolução convergente explica, por exemplo, a semelhança na forma do corpo de golfinhos e tubarões, adaptados a ambientes aquáticos semelhantes.', 8);
