-- Física — Mecânica > Dinâmica, Trabalho e energia, Gravitação (9 leaves, 5 questões cada)
insert into questions (catalog_node_id, prompt, options, correct_index, explanation, order_index) values
-- Primeira Lei de Newton (a5777654-961e-4813-9fed-c5d835825966)
('a5777654-961e-4813-9fed-c5d835825966', 'A Primeira Lei de Newton, também chamada de Lei da Inércia, afirma que um corpo:',
  array['Tende a manter seu estado de repouso ou movimento retilíneo uniforme, a menos que uma força resultante atue sobre ele', 'Sempre acelera na ausência de forças', 'Perde velocidade gradualmente mesmo sem forças atuando', 'Muda de direção espontaneamente sem qualquer força'], 0,
  'A inércia é a tendência de um corpo a resistir a mudanças em seu estado de movimento.', 1),
('a5777654-961e-4813-9fed-c5d835825966', 'Quando um ônibus freia bruscamente, os passageiros são lançados para frente. Esse fenômeno é explicado por:',
  array['A inércia dos passageiros, que tendem a manter seu movimento original', 'Uma força que empurra os passageiros para frente', 'A Terceira Lei de Newton exclusivamente', 'A ausência total de forças no sistema'], 0,
  'Pela Lei da Inércia, o corpo dos passageiros tende a continuar em movimento mesmo quando o ônibus freia.', 2),
('a5777654-961e-4813-9fed-c5d835825966', 'Um corpo em repouso permanecerá em repouso, segundo a Primeira Lei de Newton, se:',
  array['A força resultante sobre ele for nula', 'Qualquer força for aplicada sobre ele', 'Sua massa for suficientemente grande', 'Ele estiver sobre uma superfície com atrito'], 0,
  'A Lei da Inércia estabelece que, sem força resultante, um corpo em repouso permanece em repouso.', 3),
('a5777654-961e-4813-9fed-c5d835825966', 'A inércia de um corpo está diretamente relacionada a qual grandeza física?',
  array['Massa', 'Velocidade', 'Aceleração', 'Tempo'], 0,
  'Quanto maior a massa de um corpo, maior sua inércia, ou seja, maior sua resistência a mudanças no movimento.', 4),
('a5777654-961e-4813-9fed-c5d835825966', 'Em um referencial inercial, um corpo se movendo em linha reta com velocidade constante está sujeito a:',
  array['Força resultante nula', 'Uma força constante na direção do movimento', 'Uma força de atrito crescente', 'Uma aceleração constante diferente de zero'], 0,
  'Movimento retilíneo uniforme, segundo a Primeira Lei, ocorre justamente quando a força resultante é nula.', 5),

-- Segunda Lei de Newton (9df1808d-9ac5-4809-8bdb-63e12480aa97)
('9df1808d-9ac5-4809-8bdb-63e12480aa97', 'A Segunda Lei de Newton é expressa pela fórmula:',
  array['F = m · a', 'F = m / a', 'F = m + a', 'F = a / m'], 0,
  'A força resultante é igual ao produto da massa pela aceleração.', 1),
('9df1808d-9ac5-4809-8bdb-63e12480aa97', 'Uma força resultante de 20 N é aplicada sobre um corpo de massa 5 kg. Qual será a aceleração desse corpo?',
  array['4 m/s²', '25 m/s²', '15 m/s²', '100 m/s²'], 0,
  'a = F/m = 20/5 = 4 m/s².', 2),
('9df1808d-9ac5-4809-8bdb-63e12480aa97', 'Qual é a unidade de medida de força no Sistema Internacional (SI)?',
  array['Newton (N)', 'Joule (J)', 'Watt (W)', 'Pascal (Pa)'], 0,
  'A unidade de força no SI é o newton, definida como kg·m/s².', 3),
('9df1808d-9ac5-4809-8bdb-63e12480aa97', 'Um corpo de massa 10 kg recebe uma aceleração de 3 m/s². Qual é a intensidade da força resultante aplicada sobre ele?',
  array['30 N', '13 N', '7 N', '3,33 N'], 0,
  'F = m × a = 10 × 3 = 30 N.', 4),
('9df1808d-9ac5-4809-8bdb-63e12480aa97', 'De acordo com a Segunda Lei de Newton, para uma mesma força aplicada, quanto maior a massa de um corpo:',
  array['Menor será sua aceleração', 'Maior será sua aceleração', 'A aceleração permanecerá inalterada', 'A força se tornará nula'], 0,
  'Como a = F/m, para uma força constante, a aceleração é inversamente proporcional à massa.', 5),

-- Terceira Lei de Newton (a1fea6a5-c59f-43d7-8ba9-0e6865d95221)
('a1fea6a5-c59f-43d7-8ba9-0e6865d95221', 'A Terceira Lei de Newton, conhecida como Lei da Ação e Reação, afirma que:',
  array['Para toda ação, existe uma reação de mesma intensidade, mesma direção e sentido oposto', 'A força de ação é sempre maior que a de reação', 'As forças de ação e reação atuam sobre o mesmo corpo', 'A reação ocorre apenas em sistemas sem atrito'], 0,
  'As forças de ação e reação têm mesma intensidade e direção, mas sentidos opostos, e atuam em corpos diferentes.', 1),
('a1fea6a5-c59f-43d7-8ba9-0e6865d95221', 'Ao empurrar uma parede, você sente a parede empurrando sua mão de volta. Esse fenômeno é um exemplo de:',
  array['Ação e reação, segundo a Terceira Lei de Newton', 'Inércia, segundo a Primeira Lei de Newton', 'Aceleração, segundo a Segunda Lei de Newton', 'Gravitação Universal'], 0,
  'A força que você aplica na parede (ação) gera uma força de reação de mesma intensidade sobre sua mão.', 2),
('a1fea6a5-c59f-43d7-8ba9-0e6865d95221', 'As forças de ação e reação, segundo a Terceira Lei de Newton, atuam:',
  array['Em corpos diferentes, nunca se anulando entre si', 'No mesmo corpo, anulando-se mutuamente', 'Apenas quando há atrito envolvido', 'Somente em corpos em repouso'], 0,
  'Por atuarem em corpos diferentes, as forças de ação e reação nunca se cancelam, mesmo tendo a mesma intensidade.', 3),
('a1fea6a5-c59f-43d7-8ba9-0e6865d95221', 'Um foguete se propele expelindo gases para trás. Isso ocorre devido a:',
  array['A força de reação dos gases expelidos, que impulsiona o foguete para frente', 'A ausência total de forças no espaço', 'A Primeira Lei de Newton exclusivamente', 'Uma força externa aplicada por um agente externo ao sistema'], 0,
  'O foguete exerce força sobre os gases (ação), e os gases exercem força de reação sobre o foguete, impulsionando-o.', 4),
('a1fea6a5-c59f-43d7-8ba9-0e6865d95221', 'Quando um nadador empurra a água para trás com os braços, ele se desloca para frente devido a:',
  array['A reação da água, que empurra o nadador para frente', 'A ausência de qualquer força na água', 'Uma diminuição da massa do nadador', 'A gravidade atuando exclusivamente na horizontal'], 0,
  'A força que o nadador aplica na água (ação) gera uma força de reação que o impulsiona para frente.', 5),

-- Força peso (88d296cd-2bea-41f5-ad96-3bf158827298)
('88d296cd-2bea-41f5-ad96-3bf158827298', 'O peso de um corpo é definido como:',
  array['A força gravitacional que age sobre o corpo, calculada por P = m · g', 'A quantidade de matéria que compõe o corpo', 'Uma grandeza idêntica à massa, com a mesma unidade', 'Uma força que só existe na Terra'], 0,
  'O peso é a força com que a gravidade atrai um corpo, calculada pelo produto da massa pela aceleração da gravidade.', 1),
('88d296cd-2bea-41f5-ad96-3bf158827298', 'Um corpo de massa 8 kg está sujeito à gravidade terrestre (g = 10 m/s²). Qual é o seu peso?',
  array['80 N', '8 N', '18 N', '0,8 N'], 0,
  'P = m × g = 8 × 10 = 80 N.', 2),
('88d296cd-2bea-41f5-ad96-3bf158827298', 'Diferentemente da massa, o peso de um corpo:',
  array['Varia de acordo com a aceleração da gravidade do local', 'É sempre constante, independentemente do planeta', 'Não depende da massa do corpo', 'É medido em quilogramas (kg)'], 0,
  'Como P = m·g, o peso muda conforme a gravidade local varia, enquanto a massa permanece constante.', 3),
('88d296cd-2bea-41f5-ad96-3bf158827298', 'Um astronauta com massa de 70 kg está na Lua, onde a gravidade é aproximadamente 1,6 m/s². Qual é aproximadamente o peso do astronauta na Lua?',
  array['112 N', '700 N', '70 N', '43,75 N'], 0,
  'P = m × g = 70 × 1,6 = 112 N.', 4),
('88d296cd-2bea-41f5-ad96-3bf158827298', 'A unidade de medida do peso, por ser uma força, é:',
  array['Newton (N)', 'Quilograma (kg)', 'Metro por segundo (m/s)', 'Joule (J)'], 0,
  'Como o peso é uma força, sua unidade no SI é o newton, assim como qualquer outra força.', 5),

-- Força normal (ea8116d3-4182-4be6-a7b6-73f969adb43d)
('ea8116d3-4182-4be6-a7b6-73f969adb43d', 'A força normal é definida como a força que:',
  array['Uma superfície exerce sobre um corpo apoiado nela, perpendicular à superfície', 'Atua sempre na horizontal, independentemente da superfície', 'É idêntica ao peso do corpo em qualquer situação', 'Só existe quando há atrito envolvido'], 0,
  'A força normal é a reação da superfície ao peso (ou a outras forças) do corpo, sempre perpendicular ao plano de contato.', 1),
('ea8116d3-4182-4be6-a7b6-73f969adb43d', 'Um corpo de 10 kg está em repouso sobre uma superfície horizontal plana, sem outras forças verticais atuando. Qual é o valor da força normal, considerando g = 10 m/s²?',
  array['100 N', '10 N', '0 N', '1000 N'], 0,
  'Em uma superfície horizontal, sem outras forças verticais, a normal se iguala ao peso: N = P = m×g = 100 N.', 2),
('ea8116d3-4182-4be6-a7b6-73f969adb43d', 'Sobre um plano inclinado sem atrito, a força normal em relação ao peso do corpo é:',
  array['Menor que o peso total, pois equilibra apenas a componente perpendicular ao plano', 'Sempre igual ao peso total do corpo', 'Sempre maior que o peso total do corpo', 'Sempre nula, independentemente da inclinação'], 0,
  'No plano inclinado, a normal equilibra apenas a componente do peso perpendicular à superfície, sendo menor que o peso total.', 3),
('ea8116d3-4182-4be6-a7b6-73f969adb43d', 'Se um corpo está sobre uma superfície horizontal e uma força adicional é aplicada verticalmente para baixo sobre ele, a força normal:',
  array['Aumenta, pois passa a equilibrar o peso mais a força adicional', 'Diminui proporcionalmente', 'Permanece inalterada', 'Torna-se nula'], 0,
  'A força normal se ajusta para equilibrar todas as forças perpendiculares à superfície, incluindo forças adicionais aplicadas.', 4),
('ea8116d3-4182-4be6-a7b6-73f969adb43d', 'A força normal é uma força de contato que surge, segundo a Terceira Lei de Newton, como reação:',
  array['À força que o corpo exerce sobre a superfície', 'À força de atrito', 'Exclusivamente à força peso, mesmo sem contato', 'Ao movimento do corpo, apenas quando ele está em queda'], 0,
  'A normal é a reação da superfície à força que o corpo exerce sobre ela, conforme a Terceira Lei de Newton.', 5),

-- Atrito (fea10bb2-7f2f-40f8-baaf-e398343701aa)
('fea10bb2-7f2f-40f8-baaf-e398343701aa', 'A força de atrito surge devido a:',
  array['Irregularidades microscópicas entre as superfícies em contato, que se opõem ao movimento relativo', 'Uma propriedade exclusiva de superfícies lisas', 'A ausência total de força normal entre os corpos', 'A variação da temperatura ambiente'], 0,
  'O atrito resulta das interações microscópicas entre as superfícies em contato, opondo-se ao movimento ou à tendência de movimento.', 1),
('fea10bb2-7f2f-40f8-baaf-e398343701aa', 'O atrito estático, em comparação ao atrito cinético (dinâmico), geralmente tem coeficiente:',
  array['Maior ou igual ao do atrito cinético', 'Sempre menor que o do atrito cinético', 'Idêntico em qualquer situação', 'Nulo, por definição'], 0,
  'Em geral, o coeficiente de atrito estático é maior ou igual ao cinético.', 2),
('fea10bb2-7f2f-40f8-baaf-e398343701aa', 'A força de atrito de escorregamento (cinético) é calculada pela fórmula:',
  array['f = μ · N', 'f = m · a', 'f = m · g', 'f = μ + N'], 0,
  'A força de atrito cinético é o produto do coeficiente de atrito (μ) pela força normal (N).', 3),
('fea10bb2-7f2f-40f8-baaf-e398343701aa', 'Um bloco de 5 kg está sobre uma superfície horizontal com coeficiente de atrito cinético de 0,2. Considerando g = 10 m/s², qual é a força de atrito enquanto o bloco desliza?',
  array['10 N', '5 N', '1 N', '50 N'], 0,
  'N = m×g = 5×10 = 50 N; f = μ×N = 0,2×50 = 10 N.', 4),
('fea10bb2-7f2f-40f8-baaf-e398343701aa', 'O atrito, apesar de muitas vezes indesejado, é essencial para:',
  array['Permitir que caminhemos e que veículos freiem e acelerem', 'Anular completamente o peso dos corpos', 'Eliminar qualquer necessidade de força normal', 'Impedir toda forma de movimento'], 0,
  'Sem atrito, seria impossível caminhar, ou os veículos acelerarem e frearem adequadamente.', 5),

-- Plano inclinado (7e0cc321-55aa-4635-b067-8ab32d376084)
('7e0cc321-55aa-4635-b067-8ab32d376084', 'Em um plano inclinado sem atrito, a componente do peso responsável por acelerar o corpo ao longo do plano é:',
  array['P · sen(θ), onde θ é o ângulo de inclinação', 'P · cos(θ)', 'O peso total do corpo, sem decomposição', 'A força normal'], 0,
  'A componente do peso paralela ao plano, que causa o movimento, é dada por P·sen(θ).', 1),
('7e0cc321-55aa-4635-b067-8ab32d376084', 'Em um plano inclinado, a componente do peso perpendicular ao plano, equilibrada pela força normal, é dada por:',
  array['P · cos(θ)', 'P · sen(θ)', 'P · tan(θ)', 'P, sem decomposição'], 0,
  'A componente perpendicular ao plano, equilibrada pela normal, é P·cos(θ).', 2),
('7e0cc321-55aa-4635-b067-8ab32d376084', 'Quanto maior o ângulo de inclinação de um plano (sem atrito), mais próxima a aceleração do corpo ao longo do plano fica de:',
  array['g (aceleração da gravidade), quando o ângulo se aproxima de 90°', 'Zero, independentemente do ângulo', 'Uma constante fixa, igual em qualquer ângulo', 'A velocidade inicial do corpo'], 0,
  'Quando o ângulo se aproxima de 90° (plano quase vertical), o corpo se aproxima da condição de queda livre.', 3),
('7e0cc321-55aa-4635-b067-8ab32d376084', 'Em um plano inclinado com ângulo de 30°, sem atrito, qual é aproximadamente a aceleração de um corpo ao longo do plano, considerando g = 10 m/s² e sen(30°) = 0,5?',
  array['5 m/s²', '10 m/s²', '8,66 m/s²', '2,5 m/s²'], 0,
  'a = g·sen(θ) = 10 × 0,5 = 5 m/s².', 4),
('7e0cc321-55aa-4635-b067-8ab32d376084', 'Em um plano inclinado horizontal (ângulo de 0°), a componente do peso que impulsiona o corpo ao longo do plano é:',
  array['Nula, pois sen(0°) = 0', 'Igual ao peso total', 'Igual à força normal', 'Indefinida'], 0,
  'Como sen(0°) = 0, não há componente do peso ao longo de um plano perfeitamente horizontal.', 5),

-- Trabalho e energia (f394659b-6de0-4d60-a1bf-4935db2b35b5)
('f394659b-6de0-4d60-a1bf-4935db2b35b5', 'O trabalho realizado por uma força constante é calculado pela fórmula:',
  array['W = F · d · cos(θ)', 'W = F / d', 'W = F + d', 'W = m · a'], 0,
  'O trabalho é o produto da força pelo deslocamento e pelo cosseno do ângulo entre eles.', 1),
('f394659b-6de0-4d60-a1bf-4935db2b35b5', 'Uma força de 20 N é aplicada na mesma direção do deslocamento de 5 m de um corpo. Qual é o trabalho realizado por essa força?',
  array['100 J', '25 J', '4 J', '15 J'], 0,
  'W = F × d × cos(0°) = 20 × 5 × 1 = 100 J.', 2),
('f394659b-6de0-4d60-a1bf-4935db2b35b5', 'A energia cinética de um corpo é calculada pela fórmula:',
  array['Ec = (m · v²) / 2', 'Ec = m · v', 'Ec = m · g · h', 'Ec = m / v'], 0,
  'A energia cinética depende da massa e do quadrado da velocidade do corpo.', 3),
('f394659b-6de0-4d60-a1bf-4935db2b35b5', 'Um corpo de massa 4 kg se move a 5 m/s. Qual é sua energia cinética?',
  array['50 J', '20 J', '100 J', '10 J'], 0,
  'Ec = (m×v²)/2 = (4×25)/2 = 50 J.', 4),
('f394659b-6de0-4d60-a1bf-4935db2b35b5', 'O Teorema da Energia Cinética afirma que o trabalho da força resultante sobre um corpo é igual a:',
  array['A variação da energia cinética do corpo', 'A energia potencial do corpo', 'O peso do corpo', 'A força normal aplicada'], 0,
  'O trabalho realizado pela força resultante corresponde exatamente à variação da energia cinética do corpo.', 5),

-- Gravitação (e5d65d25-c4b5-40b9-8c2a-641f4c56e0bb)
('e5d65d25-c4b5-40b9-8c2a-641f4c56e0bb', 'A Lei da Gravitação Universal, formulada por Newton, afirma que a força gravitacional entre dois corpos é:',
  array['Diretamente proporcional ao produto das massas e inversamente proporcional ao quadrado da distância entre eles', 'Independente da massa dos corpos envolvidos', 'Diretamente proporcional à distância entre os corpos', 'Constante, independentemente da distância'], 0,
  'F = G·(m₁·m₂)/d², relação central da Lei da Gravitação Universal.', 1),
('e5d65d25-c4b5-40b9-8c2a-641f4c56e0bb', 'Se a distância entre dois corpos dobra, mantendo as massas constantes, a força gravitacional entre eles:',
  array['Fica reduzida a um quarto do valor original', 'Dobra de valor', 'Permanece inalterada', 'Fica reduzida à metade'], 0,
  'Como a força é inversamente proporcional ao quadrado da distância, dobrar a distância reduz a força a 1/4 do valor original.', 2),
('e5d65d25-c4b5-40b9-8c2a-641f4c56e0bb', 'A aceleração da gravidade na superfície de um planeta depende, entre outros fatores, de:',
  array['Sua massa e de seu raio', 'Apenas de sua distância ao Sol', 'Apenas de sua temperatura', 'Apenas de sua velocidade de rotação'], 0,
  'A gravidade superficial de um planeta é determinada por sua massa e pelo seu raio, segundo g = G·M/R².', 3),
('e5d65d25-c4b5-40b9-8c2a-641f4c56e0bb', 'Um satélite em órbita ao redor da Terra permanece em movimento circular devido a:',
  array['A força gravitacional, que atua como força centrípeta', 'A ausência total de força gravitacional no espaço', 'Uma força de atrito com a atmosfera', 'A força normal exercida pela Terra'], 0,
  'A gravidade terrestre atua como força centrípeta, mantendo o satélite em órbita.', 4),
('e5d65d25-c4b5-40b9-8c2a-641f4c56e0bb', 'As Leis de Kepler, que descrevem o movimento dos planetas, estabelecem, entre outros aspectos, que as órbitas planetárias são:',
  array['Elípticas, com o Sol em um dos focos', 'Perfeitamente circulares, com o Sol no centro', 'Retas, sem qualquer curvatura', 'Aleatórias, sem padrão geométrico definido'], 0,
  'A Primeira Lei de Kepler estabelece que os planetas descrevem órbitas elípticas, com o Sol ocupando um dos focos.', 5);
