-- Biologia — Ecologia (16 leaves, 5 questões cada)
insert into questions (catalog_node_id, prompt, options, correct_index, explanation, order_index) values
-- Cadeias alimentares (f7f37257-1f07-46d7-961d-36267d9ff9b0)
('f7f37257-1f07-46d7-961d-36267d9ff9b0', 'Uma cadeia alimentar representa:',
  array['A sequência linear de transferência de energia entre organismos, de um nível trófico a outro', 'Uma rede complexa de múltiplas interações alimentares', 'Apenas a relação entre predadores, sem produtores', 'A distribuição geográfica de uma espécie'], 0,
  'A cadeia alimentar mostra, de forma linear, quem come quem, representando o fluxo de energia entre organismos.', 1),
('f7f37257-1f07-46d7-961d-36267d9ff9b0', 'O primeiro elo de uma cadeia alimentar é geralmente ocupado por:',
  array['Produtores, como plantas e algas, capazes de realizar fotossíntese', 'Consumidores primários, como herbívoros', 'Decompositores', 'Predadores de topo'], 0,
  'Os produtores, autótrofos capazes de captar energia solar, formam a base de toda cadeia alimentar.', 2),
('f7f37257-1f07-46d7-961d-36267d9ff9b0', 'Os consumidores primários, em uma cadeia alimentar, são geralmente representados por:',
  array['Herbívoros, que se alimentam diretamente dos produtores', 'Carnívoros que se alimentam de outros carnívoros', 'Decompositores', 'Organismos fotossintetizantes'], 0,
  'Os consumidores primários ocupam o segundo elo da cadeia, alimentando-se diretamente dos produtores.', 3),
('f7f37257-1f07-46d7-961d-36267d9ff9b0', 'Em uma cadeia alimentar, a energia flui, de forma geral:',
  array['Dos produtores para os consumidores, com perda progressiva de energia em cada nível', 'Dos consumidores para os produtores', 'De forma cíclica e sem qualquer perda, entre todos os níveis', 'Apenas entre decompositores'], 0,
  'A energia flui unidirecionalmente ao longo da cadeia, com perda de energia (calor) em cada transferência.', 4),
('f7f37257-1f07-46d7-961d-36267d9ff9b0', 'Os decompositores, presentes ao final de uma cadeia alimentar, desempenham papel fundamental ao:',
  array['Decompor matéria orgânica morta, devolvendo nutrientes ao ambiente', 'Realizar fotossíntese, produzindo energia', 'Ocupar sempre o primeiro elo da cadeia', 'Impedir a reciclagem de nutrientes no ecossistema'], 0,
  'Fungos e bactérias decompositoras degradam restos orgânicos, liberando nutrientes reaproveitáveis pelos produtores.', 5),

-- Teias alimentares (c4b861cb-2247-46b7-9b38-fe2f1295d952)
('c4b861cb-2247-46b7-9b38-fe2f1295d952', 'Uma teia alimentar representa:',
  array['A interligação de múltiplas cadeias alimentares em um ecossistema, formando uma rede complexa de relações', 'Uma única sequência linear e isolada de organismos', 'Apenas a relação entre dois organismos', 'A distribuição de espécies em diferentes continentes'], 0,
  'A teia alimentar reflete a complexidade real dos ecossistemas, com relações alimentares múltiplas entre espécies.', 1),
('c4b861cb-2247-46b7-9b38-fe2f1295d952', 'Em comparação com uma cadeia alimentar isolada, a teia alimentar representa de forma mais realista:',
  array['A diversidade e a complexidade das relações alimentares em um ecossistema', 'Uma simplificação exagerada das relações ecológicas', 'Apenas relações entre plantas', 'A ausência total de interações entre espécies'], 0,
  'A teia alimentar capta melhor a realidade ecológica, com organismos participando de múltiplas relações.', 2),
('c4b861cb-2247-46b7-9b38-fe2f1295d952', 'A remoção de uma espécie-chave de uma teia alimentar pode causar:',
  array['Um desequilíbrio significativo em todo o ecossistema, afetando várias outras espécies', 'Nenhum impacto relevante para as demais espécies', 'Um fortalecimento imediato de todas as outras populações', 'A criação automática de novas espécies para substituí-la'], 0,
  'Espécies-chave desempenham papéis fundamentais na teia alimentar; sua remoção pode desestabilizar o ecossistema.', 3),
('c4b861cb-2247-46b7-9b38-fe2f1295d952', 'A maior complexidade de uma teia alimentar, com múltiplas conexões entre espécies, geralmente está associada a:',
  array['Uma maior estabilidade e resiliência do ecossistema', 'Uma maior fragilidade e instabilidade do ecossistema', 'Nenhuma relação com a estabilidade ecológica', 'Uma redução obrigatória da biodiversidade'], 0,
  'Ecossistemas com teias mais complexas tendem a ser mais resilientes, com rotas alternativas de fluxo de energia.', 4),
('c4b861cb-2247-46b7-9b38-fe2f1295d952', 'Um mesmo organismo, dentro de uma teia alimentar, pode ocupar:',
  array['Diferentes níveis tróficos, dependendo de sua dieta em diferentes momentos ou situações', 'Apenas um único nível trófico fixo, sem qualquer exceção', 'Nenhum nível trófico definido', 'Sempre o nível de produtor, independentemente de sua alimentação'], 0,
  'Organismos onívoros, por exemplo, podem atuar como consumidores primários e secundários, variando seu nível trófico.', 5),

-- Níveis tróficos (515a6c10-a2b5-4e46-b5a1-f1dc8340ee22)
('515a6c10-a2b5-4e46-b5a1-f1dc8340ee22', 'O nível trófico de um organismo indica:',
  array['Sua posição na cadeia alimentar, de acordo com sua fonte de energia', 'Sua localização geográfica', 'Seu tamanho corporal', 'Sua capacidade reprodutiva'], 0,
  'O nível trófico classifica os organismos conforme sua posição na cadeia alimentar.', 1),
('515a6c10-a2b5-4e46-b5a1-f1dc8340ee22', 'Os produtores ocupam o(a):',
  array['Primeiro nível trófico de uma cadeia alimentar', 'Último nível trófico', 'Nível intermediário, entre consumidores primários e secundários', 'Nenhum nível trófico específico'], 0,
  'Por captarem energia diretamente do Sol, os produtores formam a base da cadeia, no primeiro nível trófico.', 2),
('515a6c10-a2b5-4e46-b5a1-f1dc8340ee22', 'Os consumidores secundários, em uma cadeia alimentar, geralmente se alimentam de:',
  array['Consumidores primários (herbívoros)', 'Produtores diretamente', 'Apenas de outros consumidores secundários', 'Exclusivamente de decompositores'], 0,
  'Os consumidores secundários (geralmente carnívoros) ocupam o terceiro nível trófico, alimentando-se dos herbívoros.', 3),
('515a6c10-a2b5-4e46-b5a1-f1dc8340ee22', 'Em cada transição entre níveis tróficos, geralmente se perde, na forma de calor, aproximadamente:',
  array['90% da energia disponível no nível anterior', 'Toda a energia é transferida integralmente, sem qualquer perda', 'Apenas 1% da energia é perdida', '50% da energia, exatamente, em qualquer transição'], 0,
  'Pela regra dos 10%, apenas cerca de 10% da energia é transferida ao próximo nível, sendo o restante perdido como calor.', 4),
('515a6c10-a2b5-4e46-b5a1-f1dc8340ee22', 'Devido à grande perda de energia entre os níveis tróficos, cadeias alimentares muito longas, com muitos níveis, tendem a ser:',
  array['Relativamente raras, já que a energia disponível diminui drasticamente a cada nível', 'Extremamente comuns, sem qualquer limitação energética', 'Sempre mais estáveis do que cadeias curtas', 'Impossíveis de existir na natureza'], 0,
  'A perda progressiva de energia limita o número de níveis tróficos que uma cadeia pode sustentar.', 5),

-- Pirâmides ecológicas (2d65cb2b-f381-4767-b8a3-2ccb1d4f0f90)
('2d65cb2b-f381-4767-b8a3-2ccb1d4f0f90', 'As pirâmides ecológicas são representações gráficas utilizadas para ilustrar:',
  array['A distribuição de energia, biomassa ou número de indivíduos entre os níveis tróficos de um ecossistema', 'Apenas a localização geográfica das espécies', 'A estrutura genética de uma população', 'O ciclo de vida de um único organismo'], 0,
  'As pirâmides ecológicas representam visualmente como energia, biomassa ou número de organismos se distribuem entre níveis tróficos.', 1),
('2d65cb2b-f381-4767-b8a3-2ccb1d4f0f90', 'Em uma pirâmide de energia, a base (produtores) sempre apresenta:',
  array['A maior quantidade de energia disponível, em comparação com os níveis superiores', 'A menor quantidade de energia de todo o ecossistema', 'Quantidade de energia igual à dos demais níveis', 'Nenhuma relação com a quantidade de energia dos outros níveis'], 0,
  'Como há perda de energia a cada transferência, a base da pirâmide de energia sempre concentra a maior quantidade.', 2),
('2d65cb2b-f381-4767-b8a3-2ccb1d4f0f90', 'Diferentemente da pirâmide de energia, a pirâmide de números pode, em certos ecossistemas, apresentar formato invertido, como ocorre quando:',
  array['Um único produtor (como uma grande árvore) sustenta uma grande quantidade de consumidores primários pequenos', 'A quantidade de energia disponível é sempre igual em todos os níveis', 'Não existem produtores no ecossistema', 'Todos os organismos possuem exatamente o mesmo tamanho'], 0,
  'Em certos casos, o número de indivíduos pode ser maior nos consumidores do que nos produtores, invertendo a pirâmide.', 3),
('2d65cb2b-f381-4767-b8a3-2ccb1d4f0f90', 'A pirâmide de biomassa representa a quantidade total de:',
  array['Matéria orgânica viva presente em cada nível trófico', 'Energia luminosa recebida do Sol', 'Espécies diferentes presentes no ecossistema', 'Água disponível no ambiente'], 0,
  'A pirâmide de biomassa mede a massa total de organismos vivos em cada nível trófico de um ecossistema.', 4),
('2d65cb2b-f381-4767-b8a3-2ccb1d4f0f90', 'Entre os três tipos principais de pirâmides ecológicas (energia, biomassa e números), a pirâmide de energia é considerada a mais confiável para representar o funcionamento do ecossistema porque:',
  array['Ela nunca se apresenta invertida, refletindo fielmente a perda energética entre os níveis', 'É a única que pode se inverter, ao contrário das demais', 'Não depende da quantidade de organismos presentes', 'Mede exclusivamente o número de espécies, e não a energia'], 0,
  'Como reflete diretamente a perda inevitável de energia, a pirâmide de energia mantém sempre o formato piramidal padrão.', 5),

-- Mutualismo (3723cf19-5eb3-4231-8a8a-78b127777486)
('3723cf19-5eb3-4231-8a8a-78b127777486', 'O mutualismo é uma relação ecológica caracterizada por:',
  array['Benefício mútuo para as duas espécies envolvidas, sendo essencial para a sobrevivência de ambas', 'Benefício para apenas uma das espécies, sem prejuízo para a outra', 'Prejuízo para ambas as espécies envolvidas', 'Benefício para uma espécie e prejuízo para a outra'], 0,
  'No mutualismo, ambas as espécies obtêm benefícios significativos, sendo essa relação frequentemente essencial para sua sobrevivência.', 1),
('3723cf19-5eb3-4231-8a8a-78b127777486', 'A relação entre líquens, formada pela associação entre fungos e algas (ou cianobactérias), é um exemplo clássico de:',
  array['Mutualismo', 'Parasitismo', 'Predatismo', 'Amensalismo'], 0,
  'No líquen, o fungo fornece proteção e absorção de água/minerais, enquanto a alga fornece nutrientes da fotossíntese, beneficiando ambos.', 2),
('3723cf19-5eb3-4231-8a8a-78b127777486', 'A relação entre abelhas e flores, na qual as abelhas obtêm néctar e as flores são polinizadas, exemplifica:',
  array['Mutualismo', 'Comensalismo', 'Parasitismo', 'Competição'], 0,
  'Ambas as partes se beneficiam: as abelhas obtêm alimento, enquanto as flores garantem sua reprodução.', 3),
('3723cf19-5eb3-4231-8a8a-78b127777486', 'Bactérias presentes no intestino de muitos animais, incluindo humanos, que auxiliam na digestão de alimentos em troca de nutrientes e abrigo, exemplificam uma relação de:',
  array['Mutualismo', 'Predatismo', 'Amensalismo', 'Competição'], 0,
  'As bactérias intestinais benéficas auxiliam na digestão, enquanto recebem nutrientes e abrigo, caracterizando o mutualismo.', 4),
('3723cf19-5eb3-4231-8a8a-78b127777486', 'No mutualismo obrigatório, diferentemente do facultativo, as espécies envolvidas:',
  array['Dependem totalmente uma da outra para sobreviver', 'Podem sobreviver perfeitamente bem sem a interação', 'Nunca interagem diretamente', 'Sempre competem pelos mesmos recursos'], 0,
  'No mutualismo obrigatório, a relação é essencial à sobrevivência de pelo menos uma das espécies envolvidas.', 5),

-- Protocooperação (a78092ea-853a-4dea-9aff-0ad87ee76b60)
('a78092ea-853a-4dea-9aff-0ad87ee76b60', 'A protocooperação é uma relação ecológica caracterizada por:',
  array['Benefício mútuo entre duas espécies, sem que a relação seja obrigatória para a sobrevivência de nenhuma delas', 'Benefício obrigatório e essencial para a sobrevivência de ambas as espécies', 'Prejuízo para as duas espécies envolvidas', 'Benefício para uma espécie e prejuízo para a outra'], 0,
  'Diferentemente do mutualismo obrigatório, na protocooperação as espécies sobrevivem normalmente mesmo sem a interação.', 1),
('a78092ea-853a-4dea-9aff-0ad87ee76b60', 'A relação entre o crocodilo e o passarinho-palito (que remove restos de alimento entre os dentes do réptil) é um exemplo clássico de:',
  array['Protocooperação', 'Parasitismo', 'Predatismo', 'Amensalismo'], 0,
  'O pássaro se alimenta dos restos, enquanto o crocodilo tem os dentes limpos, mas ambos sobrevivem sem essa interação específica.', 2),
('a78092ea-853a-4dea-9aff-0ad87ee76b60', 'A principal diferença entre protocooperação e mutualismo obrigatório está em:',
  array['A protocooperação não é indispensável à sobrevivência das espécies envolvidas', 'A protocooperação sempre prejudica uma das espécies', 'O mutualismo nunca beneficia ambas as espécies', 'Não existe qualquer diferença entre os dois fenômenos'], 0,
  'Enquanto o mutualismo obrigatório é essencial à sobrevivência, a protocooperação é vantajosa, mas dispensável.', 3),
('a78092ea-853a-4dea-9aff-0ad87ee76b60', 'A relação entre aves que se alimentam de carrapatos sobre a pele de grandes mamíferos, como o boi, é comumente classificada como:',
  array['Protocooperação', 'Parasitismo', 'Amensalismo', 'Predatismo'], 0,
  'A ave se beneficia obtendo alimento, e o mamífero se beneficia da remoção dos parasitas, mas nenhum depende exclusivamente dessa relação.', 4),
('a78092ea-853a-4dea-9aff-0ad87ee76b60', 'Assim como o mutualismo, a protocooperação é classificada ecologicamente como uma relação:',
  array['Harmônica (positiva para ambas as espécies envolvidas)', 'Desarmônica (prejudicial para pelo menos uma espécie)', 'Neutra, sem qualquer efeito', 'Exclusivamente competitiva'], 0,
  'Por beneficiar ambas as espécies, tanto o mutualismo quanto a protocooperação são relações ecológicas harmônicas.', 5),

-- Comensalismo (ee473daf-bfff-422d-a764-d6234b14ffd1)
('ee473daf-bfff-422d-a764-d6234b14ffd1', 'O comensalismo é uma relação ecológica caracterizada por:',
  array['Benefício para uma espécie, sem prejuízo nem benefício significativo para a outra', 'Benefício mútuo para as duas espécies envolvidas', 'Prejuízo para ambas as espécies', 'Benefício para uma espécie e prejuízo evidente para a outra'], 0,
  'No comensalismo, uma espécie se beneficia, enquanto a outra não é significativamente afetada.', 1),
('ee473daf-bfff-422d-a764-d6234b14ffd1', 'A relação entre a rêmora (peixe) e o tubarão, na qual a rêmora se prende ao corpo do tubarão para se alimentar de restos de comida, é um exemplo clássico de:',
  array['Comensalismo', 'Mutualismo', 'Parasitismo', 'Predatismo'], 0,
  'A rêmora se beneficia obtendo alimento e proteção, enquanto o tubarão não é significativamente afetado.', 2),
('ee473daf-bfff-422d-a764-d6234b14ffd1', 'Plantas epífitas, como muitas orquídeas, que crescem sobre outras árvores utilizando-as apenas como suporte físico, exemplificam:',
  array['Comensalismo', 'Parasitismo', 'Mutualismo', 'Competição'], 0,
  'As epífitas se beneficiam do suporte físico, sem retirar nutrientes da árvore hospedeira nem causar prejuízo significativo.', 3),
('ee473daf-bfff-422d-a764-d6234b14ffd1', 'A principal diferença entre comensalismo e parasitismo está no fato de que, no comensalismo:',
  array['A espécie hospedeira não sofre prejuízo significativo com a interação', 'A espécie hospedeira é sempre prejudicada', 'Ambas as espécies se beneficiam igualmente', 'Nenhuma das espécies interage fisicamente'], 0,
  'Enquanto no parasitismo o hospedeiro é prejudicado, no comensalismo ele permanece praticamente indiferente.', 4),
('ee473daf-bfff-422d-a764-d6234b14ffd1', 'O comensalismo é classificado ecologicamente como uma relação:',
  array['Harmônica, já que não causa prejuízo evidente a nenhuma das espécies envolvidas', 'Desarmônica, por prejudicar uma das espécies', 'Sempre mutuamente benéfica, como o mutualismo', 'Exclusivamente competitiva'], 0,
  'Por não prejudicar nenhuma das espécies, apenas beneficiar uma delas, o comensalismo é uma relação harmônica.', 5),

-- Predatismo (c837e759-5dad-4a7e-ba58-6bbc7b99e205)
('c837e759-5dad-4a7e-ba58-6bbc7b99e205', 'O predatismo é uma relação ecológica na qual:',
  array['Um organismo (predador) caça e se alimenta de outro organismo (presa)', 'Duas espécies competem pelo mesmo recurso, sem qualquer predação', 'Ambas as espécies se beneficiam mutuamente', 'Uma espécie vive dentro ou sobre a outra sem causar sua morte'], 0,
  'No predatismo, o predador mata a presa para se alimentar dela.', 1),
('c837e759-5dad-4a7e-ba58-6bbc7b99e205', 'O predatismo desempenha um papel ecológico importante ao ajudar a:',
  array['Controlar o tamanho das populações de presas em um ecossistema', 'Eliminar completamente qualquer população de presas', 'Impedir qualquer forma de evolução das espécies', 'Reduzir sempre a biodiversidade de um ecossistema'], 0,
  'Predadores ajudam a manter o equilíbrio populacional das presas, evitando crescimento descontrolado.', 2),
('c837e759-5dad-4a7e-ba58-6bbc7b99e205', 'A relação entre leões e zebras, na savana africana, é um exemplo clássico de:',
  array['Predatismo', 'Mutualismo', 'Comensalismo', 'Amensalismo'], 0,
  'Os leões (predadores) caçam e se alimentam das zebras (presas), caracterizando uma clássica relação de predatismo.', 3),
('c837e759-5dad-4a7e-ba58-6bbc7b99e205', 'Ao longo da evolução, a relação de predatismo tem impulsionado o desenvolvimento de:',
  array['Adaptações defensivas nas presas e adaptações de caça mais eficientes nos predadores', 'Nenhuma mudança evolutiva significativa em qualquer das espécies', 'A extinção imediata de todas as espécies de presas', 'A eliminação completa da variabilidade genética'], 0,
  'A pressão do predatismo favorece adaptações de defesa e de captura, em um processo de coevolução.', 4),
('c837e759-5dad-4a7e-ba58-6bbc7b99e205', 'Diferentemente do parasitismo, no predatismo típico:',
  array['A presa geralmente morre imediatamente durante a interação', 'O hospedeiro sobrevive normalmente à interação', 'Não há qualquer consumo de tecido do organismo afetado', 'A relação é sempre benéfica para ambas as espécies'], 0,
  'No predatismo clássico, a presa é morta e consumida rapidamente, diferentemente do parasitismo prolongado.', 5),

-- Parasitismo (4a468f5a-608c-4dc3-becb-821d451dfc9c)
('4a468f5a-608c-4dc3-becb-821d451dfc9c', 'O parasitismo é uma relação ecológica na qual:',
  array['Um organismo (parasita) vive à custa de outro (hospedeiro), geralmente prejudicando-o sem matá-lo imediatamente', 'Ambas as espécies se beneficiam mutuamente', 'Uma espécie mata e consome a outra imediatamente', 'Duas espécies competem pelo mesmo recurso, sem qualquer relação direta'], 0,
  'No parasitismo, o parasita obtém nutrientes ou abrigo do hospedeiro, geralmente causando prejuízo sem morte imediata.', 1),
('4a468f5a-608c-4dc3-becb-821d451dfc9c', 'Vermes intestinais, como a lombriga (Ascaris lumbricoides), que vivem no interior do corpo do hospedeiro, são classificados como:',
  array['Endoparasitas', 'Ectoparasitas', 'Predadores', 'Organismos mutualistas'], 0,
  'Endoparasitas vivem no interior do organismo hospedeiro, diferentemente dos ectoparasitas.', 2),
('4a468f5a-608c-4dc3-becb-821d451dfc9c', 'Pulgas e carrapatos, que vivem sobre a pele de seus hospedeiros, alimentando-se de seu sangue, são classificados como:',
  array['Ectoparasitas', 'Endoparasitas', 'Predadores típicos', 'Organismos mutualistas'], 0,
  'Por viverem externamente ao corpo do hospedeiro, pulgas e carrapatos são classificados como ectoparasitas.', 3),
('4a468f5a-608c-4dc3-becb-821d451dfc9c', 'Diferentemente do predatismo, os parasitas geralmente:',
  array['Não causam a morte imediata do hospedeiro, podendo conviver com ele por longos períodos', 'Matam o hospedeiro instantaneamente', 'Beneficiam significativamente o hospedeiro', 'Nunca causam qualquer tipo de prejuízo ao hospedeiro'], 0,
  'Ao contrário dos predadores, muitos parasitas dependem da sobrevivência prolongada do hospedeiro.', 4),
('4a468f5a-608c-4dc3-becb-821d451dfc9c', 'O parasitismo é classificado ecologicamente como uma relação:',
  array['Desarmônica, pois prejudica uma das espécies envolvidas (o hospedeiro)', 'Harmônica, já que beneficia ambas as espécies', 'Neutra, sem qualquer prejuízo a nenhuma das partes', 'Idêntica ao mutualismo'], 0,
  'Como o hospedeiro é prejudicado, o parasitismo é classificado como uma relação ecológica desarmônica.', 5),

-- Competição (93ffea02-0672-48f6-9185-9b6b1a0fdedf)
('93ffea02-0672-48f6-9185-9b6b1a0fdedf', 'A competição, em ecologia, ocorre quando:',
  array['Duas ou mais espécies (ou indivíduos) disputam o mesmo recurso limitado do ambiente', 'Duas espécies se beneficiam mutuamente da interação', 'Uma espécie se alimenta diretamente de outra', 'Um organismo vive sobre o corpo de outro sem causar prejuízo'], 0,
  'A competição surge quando recursos como alimento, água, luz ou território são disputados por diferentes organismos.', 1),
('93ffea02-0672-48f6-9185-9b6b1a0fdedf', 'A competição interespecífica ocorre entre:',
  array['Indivíduos de espécies diferentes', 'Indivíduos exclusivamente da mesma espécie', 'Um predador e sua presa', 'Um parasita e seu hospedeiro'], 0,
  'A competição interespecífica envolve a disputa por recursos entre organismos de espécies distintas.', 2),
('93ffea02-0672-48f6-9185-9b6b1a0fdedf', 'A competição intraespecífica, por sua vez, ocorre entre:',
  array['Indivíduos da mesma espécie', 'Indivíduos de espécies diferentes', 'Um predador e uma presa', 'Um fungo e uma alga'], 0,
  'Indivíduos de uma mesma espécie frequentemente competem entre si por território, alimento ou parceiros.', 3),
('93ffea02-0672-48f6-9185-9b6b1a0fdedf', 'O "princípio da exclusão competitiva" propõe que:',
  array['Duas espécies com exigências ecológicas idênticas não podem coexistir indefinidamente no mesmo ambiente', 'Todas as espécies podem coexistir indefinidamente, independentemente da competição', 'A competição nunca influencia a distribuição das espécies', 'Apenas espécies idênticas geneticamente podem competir entre si'], 0,
  'Quando duas espécies competem exatamente pelos mesmos recursos, uma tende a ser eliminada ou a se adaptar.', 4),
('93ffea02-0672-48f6-9185-9b6b1a0fdedf', 'A competição por recursos limitados é um dos principais fatores que impulsionam, ao longo do tempo evolutivo:',
  array['A seleção natural e a adaptação das espécies ao ambiente', 'A ausência total de mudanças evolutivas', 'A eliminação de qualquer variabilidade genética', 'A extinção imediata de todas as espécies envolvidas'], 0,
  'A pressão gerada pela competição favorece indivíduos mais aptos, sendo um motor da seleção natural.', 5),

-- Amensalismo (599b3dba-748c-425a-b38b-411283947db3)
('599b3dba-748c-425a-b38b-411283947db3', 'O amensalismo é uma relação ecológica caracterizada por:',
  array['Prejuízo para uma espécie, sem que a outra seja beneficiada nem prejudicada significativamente', 'Benefício mútuo para as duas espécies envolvidas', 'Prejuízo mútuo para ambas as espécies', 'Benefício para uma espécie e prejuízo evidente para a outra, ambas afetadas'], 0,
  'No amensalismo, uma espécie é prejudicada, enquanto a outra permanece praticamente indiferente.', 1),
('599b3dba-748c-425a-b38b-411283947db3', 'A produção de substâncias químicas por certos fungos, como a penicilina, que inibem o crescimento de bactérias próximas sem que o fungo obtenha benefício direto dessa inibição, é um exemplo de:',
  array['Amensalismo', 'Mutualismo', 'Parasitismo', 'Predatismo'], 0,
  'O fungo prejudica as bactérias, mas não obtém benefício direto adicional com essa inibição, caracterizando o amensalismo.', 2),
('599b3dba-748c-425a-b38b-411283947db3', 'Algumas plantas liberam substâncias químicas no solo (alelopatia) que inibem o crescimento de outras plantas ao redor, sem que a planta produtora obtenha vantagem direta com esse efeito. Esse fenômeno exemplifica:',
  array['Amensalismo', 'Comensalismo', 'Mutualismo', 'Protocooperação'], 0,
  'A planta que libera a substância prejudica as vizinhas, sem obter benefício adicional direto, caracterizando o amensalismo.', 3),
('599b3dba-748c-425a-b38b-411283947db3', 'O amensalismo é classificado ecologicamente como uma relação:',
  array['Desarmônica, pois prejudica uma das espécies envolvidas', 'Harmônica, pois beneficia ambas as espécies', 'Idêntica ao mutualismo', 'Sempre benéfica para a espécie prejudicada'], 0,
  'Por causar prejuízo a uma das espécies, o amensalismo é classificado como uma relação ecológica desarmônica.', 4),
('599b3dba-748c-425a-b38b-411283947db3', 'A principal diferença entre amensalismo e competição está em:',
  array['No amensalismo, apenas uma espécie é prejudicada, enquanto na competição ambas as espécies envolvidas podem ser prejudicadas pela disputa', 'No amensalismo, ambas as espécies se beneficiam', 'Na competição, nenhuma espécie é prejudicada', 'Não existe qualquer diferença entre os dois fenômenos'], 0,
  'Na competição, a disputa pode prejudicar ambas as espécies; no amensalismo, tipicamente apenas uma sofre o prejuízo.', 5),

-- Aquecimento global (6ef61f6f-ff8b-4bc6-b064-6eeeb77d1ba7)
('6ef61f6f-ff8b-4bc6-b064-6eeeb77d1ba7', 'O aquecimento global é um fenômeno relacionado principalmente ao aumento da concentração atmosférica de:',
  array['Gases do efeito estufa, como o dióxido de carbono (CO₂) e o metano (CH₄)', 'Gases nobres, como hélio e neônio', 'Vapor de água exclusivamente, sem qualquer outro gás', 'Nitrogênio molecular (N₂) puro'], 0,
  'O acúmulo de gases do efeito estufa retém mais calor na atmosfera, contribuindo para o aquecimento global.', 1),
('6ef61f6f-ff8b-4bc6-b064-6eeeb77d1ba7', 'Entre as principais atividades humanas associadas ao agravamento do aquecimento global, destaca-se:',
  array['A queima de combustíveis fósseis, como petróleo e carvão', 'A produção exclusiva de energia solar', 'O plantio extensivo de florestas', 'A redução do uso de veículos automotores'], 0,
  'A queima de combustíveis fósseis libera grandes quantidades de CO₂, uma das principais causas antrópicas.', 2),
('6ef61f6f-ff8b-4bc6-b064-6eeeb77d1ba7', 'Entre as consequências associadas ao aquecimento global, encontram-se:',
  array['O derretimento de geleiras e a elevação do nível dos oceanos', 'A redução constante da temperatura média do planeta', 'O aumento da camada de gelo polar, sem qualquer alteração', 'A eliminação completa de eventos climáticos extremos'], 0,
  'O aumento da temperatura média contribui para o derretimento de geleiras, elevando o nível dos oceanos.', 3),
('6ef61f6f-ff8b-4bc6-b064-6eeeb77d1ba7', 'O desmatamento contribui para o agravamento do aquecimento global principalmente porque:',
  array['Reduz a quantidade de árvores capazes de absorver CO₂ da atmosfera pela fotossíntese', 'Aumenta diretamente a produção de oxigênio atmosférico', 'Não tem qualquer relação com a concentração de gases do efeito estufa', 'Reduz a temperatura média do planeta'], 0,
  'Árvores absorvem CO₂ durante a fotossíntese; sua remoção reduz essa capacidade de captura, agravando o efeito estufa.', 4),
('6ef61f6f-ff8b-4bc6-b064-6eeeb77d1ba7', 'Acordos internacionais, como o Acordo de Paris, têm como principal objetivo:',
  array['Reduzir as emissões globais de gases do efeito estufa, limitando o aumento da temperatura média do planeta', 'Aumentar livremente a emissão de poluentes atmosféricos', 'Eliminar totalmente o uso de qualquer fonte de energia', 'Incentivar exclusivamente o desmatamento controlado'], 0,
  'Acordos como o de Paris buscam estabelecer metas de redução de emissões, visando conter o aquecimento global.', 5),

-- Desmatamento (7b65a833-d7c3-44af-8168-07eb7c28bf4b)
('7b65a833-d7c3-44af-8168-07eb7c28bf4b', 'O desmatamento é definido como:',
  array['A remoção total ou parcial da cobertura florestal de uma determinada área', 'O plantio intensivo de novas árvores em uma região', 'A proteção legal de áreas florestais', 'O crescimento natural de florestas ao longo do tempo'], 0,
  'O desmatamento envolve a retirada da vegetação florestal, geralmente para uso agrícola, pecuário ou urbano.', 1),
('7b65a833-d7c3-44af-8168-07eb7c28bf4b', 'Entre as principais causas do desmatamento, especialmente em regiões tropicais como a Amazônia, destacam-se:',
  array['A expansão agropecuária e a extração ilegal de madeira', 'O crescimento espontâneo e natural das florestas', 'A ausência total de atividades humanas na região', 'A proteção rigorosa e efetiva de todas as áreas florestais'], 0,
  'A conversão de áreas florestais em pastagens e lavouras, além da extração madeireira, causam o desmatamento.', 2),
('7b65a833-d7c3-44af-8168-07eb7c28bf4b', 'O desmatamento pode contribuir diretamente para:',
  array['A perda de biodiversidade e a extinção de espécies que dependem daquele habitat', 'O aumento imediato da biodiversidade local', 'A melhoria da qualidade do solo, sem qualquer efeito negativo', 'A redução do risco de erosão do solo'], 0,
  'A destruição do habitat natural de diversas espécies é uma das principais ameaças à biodiversidade.', 3),
('7b65a833-d7c3-44af-8168-07eb7c28bf4b', 'Além da perda de biodiversidade, o desmatamento também está associado a:',
  array['Alterações no regime de chuvas e no ciclo hidrológico regional', 'Um aumento imediato e permanente da umidade do solo', 'Nenhuma alteração no clima local ou regional', 'A eliminação total do risco de queimadas'], 0,
  'A remoção da cobertura florestal pode alterar os padrões de evaporação e precipitação, afetando o ciclo hidrológico.', 4),
('7b65a833-d7c3-44af-8168-07eb7c28bf4b', 'O manejo florestal sustentável busca principalmente:',
  array['Conciliar o uso econômico dos recursos florestais com sua conservação a longo prazo', 'Maximizar o desmatamento em curto prazo, sem qualquer planejamento', 'Eliminar totalmente qualquer atividade econômica relacionada às florestas', 'Ignorar completamente os impactos ambientais da exploração florestal'], 0,
  'O manejo sustentável visa permitir o uso dos recursos florestais garantindo sua conservação ao longo do tempo.', 5),

-- Poluição (4b45af32-53e6-4f3a-a628-194ac2bc1035)
('4b45af32-53e6-4f3a-a628-194ac2bc1035', 'A poluição ambiental pode ser definida como:',
  array['A introdução de substâncias ou energia no ambiente, capazes de causar efeitos prejudiciais aos seres vivos', 'O processo natural de ciclagem de nutrientes em um ecossistema', 'A ausência total de qualquer atividade humana em uma região', 'O crescimento natural e equilibrado de uma população'], 0,
  'A poluição envolve a introdução de agentes que alteram negativamente as condições naturais do ambiente.', 1),
('4b45af32-53e6-4f3a-a628-194ac2bc1035', 'A poluição da água por esgoto doméstico não tratado pode causar, entre outros problemas:',
  array['A eutrofização, com proliferação excessiva de algas e redução do oxigênio dissolvido', 'Uma melhoria imediata na qualidade da água', 'O aumento da biodiversidade aquática, sem qualquer prejuízo', 'Nenhum impacto relevante sobre os organismos aquáticos'], 0,
  'O excesso de nutrientes presentes no esgoto favorece a proliferação de algas, reduzindo o oxigênio disponível.', 2),
('4b45af32-53e6-4f3a-a628-194ac2bc1035', 'A poluição atmosférica causada por veículos automotores e indústrias está diretamente relacionada a problemas como:',
  array['Doenças respiratórias e a formação de chuva ácida', 'A melhoria da qualidade do ar em áreas urbanas', 'A redução da temperatura média das cidades', 'O aumento da camada de ozônio estratosférica'], 0,
  'A emissão de poluentes atmosféricos está associada a problemas respiratórios e à formação de chuva ácida.', 3),
('4b45af32-53e6-4f3a-a628-194ac2bc1035', 'A poluição do solo, causada por descarte inadequado de resíduos e uso excessivo de agrotóxicos, pode resultar em:',
  array['Contaminação de lençóis freáticos e prejuízo à fertilidade do solo', 'Um aumento imediato e permanente da fertilidade do solo', 'Nenhuma alteração significativa nas propriedades do solo', 'A eliminação total de qualquer contaminante do ambiente'], 0,
  'Substâncias tóxicas descartadas inadequadamente podem infiltrar-se no solo, contaminando lençóis freáticos.', 4),
('4b45af32-53e6-4f3a-a628-194ac2bc1035', 'Medidas de controle da poluição incluem, entre outras ações:',
  array['Tratamento adequado de efluentes e resíduos antes de seu descarte no ambiente', 'O descarte livre e sem controle de qualquer tipo de resíduo', 'A eliminação total de qualquer legislação ambiental', 'O incentivo ao uso descontrolado de agrotóxicos'], 0,
  'O tratamento de efluentes e políticas de gestão de resíduos são medidas fundamentais para reduzir a poluição.', 5),

-- Chuva ácida (2dbe9c65-6d79-4abd-ace9-fa5f3545b7de)
('2dbe9c65-6d79-4abd-ace9-fa5f3545b7de', 'A chuva ácida é causada principalmente pela emissão atmosférica de:',
  array['Óxidos de enxofre e nitrogênio, provenientes da queima de combustíveis fósseis', 'Vapor de água puro', 'Gás oxigênio em excesso', 'Gases nobres emitidos por indústrias'], 0,
  'Óxidos de enxofre e nitrogênio reagem com a água atmosférica, formando ácidos que caem na forma de chuva ácida.', 1),
('2dbe9c65-6d79-4abd-ace9-fa5f3545b7de', 'A chuva ácida pode causar danos significativos, entre outros efeitos, a:',
  array['Florestas, corpos d''água e construções feitas de calcário ou mármore', 'Apenas a organismos marinhos de águas profundas', 'Nenhum tipo de estrutura ou ecossistema', 'Exclusivamente a regiões desérticas, sem qualquer vegetação'], 0,
  'A acidificação causada pela chuva ácida pode prejudicar florestas, acidificar rios e corroer certas construções.', 2),
('2dbe9c65-6d79-4abd-ace9-fa5f3545b7de', 'Em lagos e rios afetados pela chuva ácida, a acidificação da água pode causar:',
  array['A morte de peixes e outros organismos aquáticos sensíveis à variação do pH', 'Um aumento imediato da biodiversidade aquática', 'Nenhum impacto relevante sobre a vida aquática', 'A neutralização automática de qualquer poluente presente na água'], 0,
  'Muitos organismos aquáticos são sensíveis a variações no pH da água, sofrendo consequências graves.', 3),
('2dbe9c65-6d79-4abd-ace9-fa5f3545b7de', 'A instalação de filtros e tecnologias de controle de emissões em indústrias e veículos é uma medida importante para:',
  array['Reduzir a liberação de óxidos de enxofre e nitrogênio na atmosfera', 'Aumentar propositalmente a formação de chuva ácida', 'Eliminar totalmente a necessidade de energia', 'Impedir qualquer forma de poluição hídrica'], 0,
  'Tecnologias de controle de emissões reduzem a quantidade de óxidos poluentes liberados na atmosfera.', 4),
('2dbe9c65-6d79-4abd-ace9-fa5f3545b7de', 'A chuva ácida é um exemplo claro de como a poluição atmosférica pode ter efeitos que se estendem:',
  array['Além da fonte original de emissão, afetando regiões distantes através do transporte atmosférico', 'Exclusivamente ao local exato onde o poluente foi emitido', 'Apenas ao ambiente aquático, sem qualquer relação com o solo', 'Somente durante a noite, sem qualquer efeito diurno'], 0,
  'Poluentes emitidos em uma região podem ser transportados pelos ventos, causando chuva ácida em áreas distantes.', 5),

-- Espécies invasoras (a08bdf48-dce2-4e57-9418-96e2b1122ea5)
('a08bdf48-dce2-4e57-9418-96e2b1122ea5', 'Uma espécie invasora é caracterizada por:',
  array['Ser introduzida (geralmente pelo ser humano) em um ambiente diferente do seu habitat original, causando impactos negativos', 'Ser sempre nativa do ecossistema em que se encontra', 'Nunca causar qualquer impacto ao ecossistema local', 'Ser exclusivamente uma espécie extinta'], 0,
  'Espécies invasoras são introduzidas em novos ambientes, frequentemente por atividade humana, causando desequilíbrios.', 1),
('a08bdf48-dce2-4e57-9418-96e2b1122ea5', 'Espécies invasoras podem prejudicar ecossistemas nativos, principalmente por:',
  array['Competir por recursos com espécies nativas, podendo até levá-las à extinção local', 'Sempre coexistir harmoniosamente com as espécies nativas, sem qualquer competição', 'Nunca se reproduzir no novo ambiente', 'Reduzir automaticamente sua própria população, sem qualquer impacto'], 0,
  'Ao competir por recursos, espécies invasoras podem prejudicar populações nativas, alterando o equilíbrio ecológico.', 2),
('a08bdf48-dce2-4e57-9418-96e2b1122ea5', 'O javali, uma espécie invasora em diversas regiões do Brasil, causa impactos significativos, entre outros aspectos, à:',
  array['Agricultura e à biodiversidade local, devido à destruição de plantações e habitats nativos', 'Melhoria da qualidade do solo em todas as regiões onde é introduzido', 'Redução imediata da erosão do solo', 'Ausência total de qualquer impacto ambiental'], 0,
  'O javali causa prejuízos significativos à agricultura e aos ecossistemas nativos, competindo com a fauna local.', 3),
('a08bdf48-dce2-4e57-9418-96e2b1122ea5', 'A ausência de predadores naturais em um novo ambiente é um dos fatores que frequentemente favorece:',
  array['O sucesso reprodutivo e a expansão descontrolada de espécies invasoras', 'A rápida extinção de espécies invasoras', 'A redução imediata da população da espécie invasora', 'Nenhuma vantagem para a espécie introduzida'], 0,
  'Sem predadores naturais para controlar sua população, espécies invasoras frequentemente se espalham rapidamente.', 4),
('a08bdf48-dce2-4e57-9418-96e2b1122ea5', 'Entre as medidas utilizadas para controlar espécies invasoras, encontram-se:',
  array['Programas de monitoramento, controle populacional e, em alguns casos, erradicação', 'O incentivo à introdução de ainda mais espécies exóticas', 'A ausência total de qualquer ação de controle', 'A proteção legal irrestrita da espécie invasora'], 0,
  'O manejo de espécies invasoras geralmente envolve monitoramento contínuo e estratégias de controle populacional.', 5);
