-- Português — Interpretação de texto (10 leaves, 5 questões cada, cada uma com um pequeno texto original)
insert into questions (catalog_node_id, prompt, options, correct_index, explanation, order_index) values
-- Compreensão textual (8fe5bf1c-3e9f-4d21-9a31-f993693afaac)
('8fe5bf1c-3e9f-4d21-9a31-f993693afaac', 'Leia: "A cafeína é uma substância estimulante encontrada naturalmente no café, no chá e no chocolate. Em doses moderadas, ela aumenta o estado de alerta e reduz a sensação de cansaço." De acordo com o texto, o que a cafeína faz em doses moderadas?',
  array['Aumenta o estado de alerta e reduz o cansaço', 'Causa insônia imediata', 'Elimina totalmente a necessidade de sono', 'Provoca ansiedade em qualquer quantidade'], 0,
  'O texto afirma diretamente que, em doses moderadas, a cafeína aumenta o alerta e reduz o cansaço.', 1),
('8fe5bf1c-3e9f-4d21-9a31-f993693afaac', 'Leia: "Depois de meses de treino, Marina finalmente completou sua primeira maratona. Ao cruzar a linha de chegada, sentiu as pernas doerem, mas o sorriso no rosto mostrava que valera a pena." O que se pode compreender sobre o sentimento de Marina ao final do texto?',
  array['Satisfação, apesar do cansaço físico', 'Arrependimento por ter participado', 'Indiferença com o resultado', 'Raiva por não ter vencido a prova'], 0,
  'O texto indica dor física, mas o sorriso demonstra satisfação e realização.', 2),
('8fe5bf1c-3e9f-4d21-9a31-f993693afaac', 'Leia: "As abelhas desempenham papel fundamental na polinização de diversas plantas cultivadas pelo ser humano. Sem elas, a produção de muitos alimentos, como frutas e verduras, seria seriamente prejudicada." Segundo o texto, qual é a importância das abelhas mencionada?',
  array['Elas polinizam plantas essenciais para a produção de alimentos', 'Elas produzem exclusivamente mel para consumo humano', 'Elas são prejudiciais à agricultura', 'Elas não têm relação com a produção agrícola'], 0,
  'O texto destaca diretamente o papel das abelhas na polinização de plantas cultivadas.', 3),
('8fe5bf1c-3e9f-4d21-9a31-f993693afaac', 'Leia: "O novo aplicativo de transporte permite que usuários comparem preços entre diferentes motoristas antes de confirmar a corrida, o que tem ajudado muitos passageiros a economizar." Qual funcionalidade do aplicativo é destacada no texto?',
  array['A comparação de preços entre motoristas antes da corrida', 'A escolha automática do motorista mais caro', 'A eliminação total de qualquer custo de viagem', 'A proibição de comparação de preços'], 0,
  'O texto menciona explicitamente que o app permite comparar preços antes de confirmar a corrida.', 4),
('8fe5bf1c-3e9f-4d21-9a31-f993693afaac', 'Leia: "Depois de anos fechada, a antiga biblioteca do bairro foi reformada e reaberta ao público, agora com um espaço de leitura infantil e computadores para pesquisa." O que mudou na biblioteca do bairro, segundo o texto?',
  array['Ela foi reformada e ganhou novos espaços, como área infantil e computadores', 'Ela foi definitivamente fechada', 'Ela se tornou exclusiva para adultos', 'Ela perdeu seu acervo de livros'], 0,
  'O texto relata a reforma e reabertura da biblioteca com novos espaços.', 5),

-- Tema e assunto (44d0f715-a155-43e0-8b7b-96afdfaa2cdd)
('44d0f715-a155-43e0-8b7b-96afdfaa2cdd', 'Leia: "O artigo discute os efeitos do uso excessivo de redes sociais entre adolescentes, abordando desde a queda no rendimento escolar até problemas de autoestima." Qual é o assunto central do texto?',
  array['Os efeitos do uso excessivo de redes sociais entre adolescentes', 'A história da internet', 'Receitas culinárias para adolescentes', 'Regras de trânsito'], 0,
  'O assunto central, explicitado logo no início, são os efeitos do uso excessivo de redes sociais entre adolescentes.', 1),
('44d0f715-a155-43e0-8b7b-96afdfaa2cdd', 'Leia: "A reportagem apresenta diferentes técnicas de compostagem doméstica, comparando o tempo de decomposição e os materiais recomendados para cada método." Sobre o que trata principalmente o texto?',
  array['Técnicas de compostagem doméstica', 'A história da agricultura', 'Receitas vegetarianas', 'Poluição dos oceanos'], 0,
  'O texto trata especificamente de técnicas de compostagem doméstica, comparando métodos.', 2),
('44d0f715-a155-43e0-8b7b-96afdfaa2cdd', 'Leia: "Embora o texto mencione brevemente a fundação da cidade em 1822, seu foco está em detalhar o novo sistema de transporte público implantado em 2023, incluindo novas linhas de ônibus." Qual é o tema principal do texto, apesar da menção a outro fato histórico?',
  array['O novo sistema de transporte público implantado em 2023', 'A fundação da cidade em 1822', 'A história colonial do Brasil', 'A arquitetura da cidade'], 0,
  'Apesar de citar a fundação da cidade, o texto foca no novo sistema de transporte público.', 3),
('44d0f715-a155-43e0-8b7b-96afdfaa2cdd', 'Leia: "O documento analisa como diferentes culturas ao redor do mundo celebram o início de um novo ano, com rituais que vão de fogos de artifício a refeições simbólicas." Qual é o assunto do texto?',
  array['As diferentes formas de celebrar a passagem de ano em várias culturas', 'A receita de uma refeição típica', 'A história dos fogos de artifício', 'O calendário romano'], 0,
  'O texto trata das diferentes formas culturais de celebrar o início do ano.', 4),
('44d0f715-a155-43e0-8b7b-96afdfaa2cdd', 'Leia: "A palestra abordou, de forma ampla, a importância da leitura na infância, citando estudos sobre desenvolvimento cognitivo e o papel da família nesse processo." Qual é o tema central da palestra descrita?',
  array['A importância da leitura na infância', 'O desenvolvimento da escrita cursiva', 'A história da imprensa', 'Métodos de alfabetização de adultos'], 0,
  'O tema central, apresentado logo no início, é a importância da leitura na infância.', 5),

-- Ideia principal (2e4619ba-f64c-4e10-87cd-50e6b21b4c69)
('2e4619ba-f64c-4e10-87cd-50e6b21b4c69', 'Leia: "Estudos mostram que dormir bem melhora a memória, o humor e até o sistema imunológico. Por isso, especialistas recomendam entre 7 e 9 horas de sono por noite para adultos." Qual é a ideia principal do texto?',
  array['O sono adequado traz diversos benefícios à saúde', 'Dormir mais de 9 horas é sempre prejudicial', 'O sistema imunológico não tem relação com o sono', 'Apenas crianças precisam dormir bem'], 0,
  'A ideia principal, que organiza todo o texto, é que dormir bem traz benefícios à saúde física e mental.', 1),
('2e4619ba-f64c-4e10-87cd-50e6b21b4c69', 'Leia: "Embora a cidade tenha investido em novas ciclovias, poucos moradores mudaram seus hábitos de deslocamento, preferindo ainda o carro. A ideia central da reportagem é mostrar que apenas construir infraestrutura não é suficiente para mudar comportamentos." Qual é a ideia principal defendida no texto?',
  array['Somente construir infraestrutura não é suficiente para mudar hábitos de deslocamento', 'As ciclovias resolveram completamente o problema do trânsito', 'Ninguém utiliza as novas ciclovias', 'O carro deixou de ser usado na cidade'], 0,
  'O texto argumenta que a infraestrutura sozinha não muda comportamentos, sendo essa a ideia central.', 2),
('2e4619ba-f64c-4e10-87cd-50e6b21b4c69', 'Leia: "A pesquisa comparou o desempenho de estudantes que faziam pausas curtas durante os estudos com os que estudavam sem interrupção. O grupo que fez pausas apresentou melhor retenção de conteúdo." Qual é a ideia principal da pesquisa descrita?',
  array['Fazer pausas durante os estudos melhora a retenção de conteúdo', 'Estudar sem pausas é sempre mais eficiente', 'O tempo total de estudo não influencia o aprendizado', 'Pausas atrapalham a concentração dos estudantes'], 0,
  'A ideia principal é o benefício das pausas para a retenção de conteúdo, conforme mostrado pela pesquisa.', 3),
('2e4619ba-f64c-4e10-87cd-50e6b21b4c69', 'Leia: "Apesar de a empresa ter lançado vários produtos ao longo do ano, foi o investimento em atendimento ao cliente que mais contribuiu para o aumento da fidelização, segundo o relatório." Qual é a ideia principal apresentada no relatório?',
  array['O investimento em atendimento ao cliente foi o principal fator de fidelização', 'O lançamento de produtos foi irrelevante para a empresa', 'A fidelização dos clientes diminuiu ao longo do ano', 'A empresa não lançou nenhum produto novo'], 0,
  'O texto destaca o atendimento ao cliente como o principal fator de fidelização, sendo essa a ideia central.', 4),
('2e4619ba-f64c-4e10-87cd-50e6b21b4c69', 'Leia: "O documentário mostra diversos exemplos de cidades que reduziram o volume de lixo, mas sua mensagem central é que a mudança de hábitos individuais é o fator mais determinante para esse resultado." Qual é a ideia principal transmitida pelo documentário?',
  array['A mudança de hábitos individuais é o fator mais determinante para reduzir o lixo', 'Apenas o poder público pode reduzir o volume de lixo', 'É impossível reduzir a produção de lixo nas cidades', 'Os exemplos mostrados não têm relação entre si'], 0,
  'A mensagem central, destacada explicitamente no texto, é a importância da mudança de hábitos individuais.', 5),

-- Informações explícitas (5ba08373-5941-4b7f-8cd7-596108ce31d3)
('5ba08373-5941-4b7f-8cd7-596108ce31d3', 'Leia: "A loja informou que a promoção de aniversário será válida de 10 a 20 de outubro, com descontos de até 40% em produtos selecionados." Segundo o texto, até quando será válida a promoção?',
  array['Até 20 de outubro', 'Até 10 de outubro', 'Até 30 de outubro', 'O texto não menciona uma data final'], 0,
  'O texto informa explicitamente o período da promoção, de 10 a 20 de outubro.', 1),
('5ba08373-5941-4b7f-8cd7-596108ce31d3', 'Leia: "O prefeito anunciou que a nova ponte terá 300 metros de extensão e ligará os dois bairros separados pelo rio." Qual é a extensão da nova ponte, de acordo com o texto?',
  array['300 metros', '200 metros', '500 metros', 'O texto não informa a extensão'], 0,
  'O texto afirma explicitamente que a ponte terá 300 metros de extensão.', 2),
('5ba08373-5941-4b7f-8cd7-596108ce31d3', 'Leia: "De acordo com o comunicado da escola, as aulas serão suspensas na sexta-feira devido à manutenção elétrica no prédio." Por que as aulas serão suspensas na sexta-feira, segundo o texto?',
  array['Devido à manutenção elétrica no prédio', 'Por causa de um feriado nacional', 'Devido a uma reforma no pátio', 'Por falta de professores'], 0,
  'O motivo da suspensão das aulas é informado explicitamente: manutenção elétrica no prédio.', 3),
('5ba08373-5941-4b7f-8cd7-596108ce31d3', 'Leia: "O relatório aponta que a empresa contratou 150 novos funcionários no último trimestre, um aumento de 20% em relação ao trimestre anterior." Quantos novos funcionários a empresa contratou no último trimestre, segundo o texto?',
  array['150', '120', '200', '20'], 0,
  'O número de novos funcionários contratados, 150, está informado explicitamente no texto.', 4),
('5ba08373-5941-4b7f-8cd7-596108ce31d3', 'Leia: "A pesquisa foi realizada com 1.200 participantes de diferentes regiões do país, entre os meses de março e maio." Quantos participantes fizeram parte da pesquisa mencionada no texto?',
  array['1.200', '120', '12.000', '200'], 0,
  'O texto informa explicitamente que a pesquisa contou com 1.200 participantes.', 5),

-- Informações implícitas (c90c0ff6-432c-4ec2-bad7-6cad9bde3a70)
('c90c0ff6-432c-4ec2-bad7-6cad9bde3a70', 'Leia: "Joana chegou à reunião ofegante, com o cabelo molhado e o guarda-chuva ainda pingando ao lado da cadeira." O que o texto sugere, sem afirmar diretamente?',
  array['Estava chovendo e Joana teve que correr para chegar', 'Joana tomou banho antes da reunião', 'A reunião foi cancelada', 'Joana chegou muito antes do horário'], 0,
  'Os detalhes (cabelo molhado, guarda-chuva pingando, ofegante) sugerem chuva e pressa, sem o texto afirmar isso diretamente.', 1),
('c90c0ff6-432c-4ec2-bad7-6cad9bde3a70', 'Leia: "O restaurante estava com todas as mesas ocupadas, e uma fila se formava na porta desde as sete da noite." O que se pode subentender sobre o restaurante?',
  array['Ele é bastante popular e procurado pelos clientes', 'Ele estava fechado naquele dia', 'Ele acabara de ser inaugurado sem nenhum cliente', 'Ele não aceita reservas'], 0,
  'A lotação e a fila indicam, implicitamente, que o restaurante é popular, mesmo sem o texto afirmar isso diretamente.', 2),
('c90c0ff6-432c-4ec2-bad7-6cad9bde3a70', 'Leia: "Pedro verificou o relógio pela terceira vez em cinco minutos e olhou repetidamente para a porta do escritório." O que o comportamento de Pedro sugere?',
  array['Ele está ansioso esperando por algo ou alguém', 'Ele está completamente relaxado', 'Ele esqueceu o horário da reunião', 'Ele está satisfeito com a espera'], 0,
  'Verificar o relógio repetidamente e olhar para a porta sugerem ansiedade e expectativa, mesmo sem isso ser dito explicitamente.', 3),
('c90c0ff6-432c-4ec2-bad7-6cad9bde3a70', 'Leia: "Depois do anúncio do resultado, o time correu para o centro do campo, alguns jogadores caíram de joelhos, e o técnico foi erguido pelos reservas." O que se pode concluir implicitamente sobre o resultado do jogo?',
  array['O time comemorou porque venceu ou conquistou algo importante', 'O time perdeu a partida', 'O jogo foi cancelado', 'Os jogadores estavam magoados com o técnico'], 0,
  'As reações de comemoração indicam vitória ou conquista, ainda que o texto não diga isso de forma explícita.', 4),
('c90c0ff6-432c-4ec2-bad7-6cad9bde3a70', 'Leia: "Ana conferiu o extrato bancário três vezes e depois guardou os cartões de crédito na gaveta mais funda do armário." O que o comportamento de Ana sugere implicitamente?',
  array['Ela está tentando controlar ou reduzir seus gastos', 'Ela está planejando uma grande viagem de luxo', 'Ela perdeu todos os seus cartões', 'Ela não se importa com suas finanças'], 0,
  'Conferir o extrato e guardar os cartões sugerem uma tentativa de conter gastos, embora o texto não afirme isso diretamente.', 5),

-- Inferência (cb1d24d0-03e9-4017-ab28-d5fc087bcedb)
('cb1d24d0-03e9-4017-ab28-d5fc087bcedb', 'Leia: "Nas últimas três reuniões, o diretor chegou atrasado e saiu antes do fim. Seus e-mails, antes detalhados, agora vêm curtos e sem explicações." Com base nas pistas do texto, o que se pode inferir sobre o diretor?',
  array['Ele provavelmente está sobrecarregado ou desmotivado no momento', 'Ele foi promovido recentemente', 'Ele está de férias', 'Ele está mais empenhado do que nunca no trabalho'], 0,
  'A combinação de atrasos, saídas antecipadas e comunicação mais curta permite inferir sobrecarga ou desmotivação, mesmo sem afirmação direta.', 1),
('cb1d24d0-03e9-4017-ab28-d5fc087bcedb', 'Leia: "A loja de roupas da esquina reduziu o horário de funcionamento, colocou uma placa de liquidação total e, na semana seguinte, as prateleiras já estavam vazias." O que se pode inferir sobre a situação da loja?',
  array['A loja provavelmente está encerrando suas atividades', 'A loja está ampliando seus negócios', 'A loja acabou de abrir', 'A loja aumentou seu estoque'], 0,
  'Redução de horário, liquidação total e prateleiras vazias, juntos, sugerem o encerramento das atividades da loja.', 2),
('cb1d24d0-03e9-4017-ab28-d5fc087bcedb', 'Leia: "Depois de anos consecutivos de safras abundantes, a região enfrentou dois verões seguidos com chuvas muito abaixo da média, e os rios da área baixaram visivelmente de nível." O que se pode inferir sobre a produção agrícola futura da região?',
  array['Ela provavelmente será prejudicada por causa da escassez de água', 'Ela certamente aumentará nos próximos anos', 'Ela não tem qualquer relação com o clima', 'Ela permanecerá inalterada, independentemente da chuva'], 0,
  'A escassez de chuva e a queda no nível dos rios permitem inferir impactos negativos na produção agrícola futura.', 3),
('cb1d24d0-03e9-4017-ab28-d5fc087bcedb', 'Leia: "O aplicativo de música passou a sugerir cada vez mais artistas de rock clássico para o usuário, mesmo ele nunca tendo pesquisado esse gênero antes." O que se pode inferir sobre o comportamento recente do usuário no aplicativo?',
  array['Ele provavelmente tem ouvido bastante música desse gênero ultimamente', 'Ele nunca usou o aplicativo antes', 'O aplicativo escolhe sugestões de forma totalmente aleatória', 'Ele cancelou sua assinatura do serviço'], 0,
  'Algoritmos de recomendação geralmente se baseiam no histórico de escuta, permitindo inferir maior consumo recente daquele gênero.', 4),
('cb1d24d0-03e9-4017-ab28-d5fc087bcedb', 'Leia: "Antes muito ativo nas redes sociais, o influenciador não posta nada há semanas, e seu último vídeo, ainda incompleto, ficou marcado como rascunho." O que se pode inferir sobre a rotina recente do influenciador?',
  array['Algo provavelmente o afastou de sua atividade normal nas redes', 'Ele está mais ativo do que nunca nas redes sociais', 'Ele nunca utilizou vídeos em seu conteúdo', 'Ele encerrou definitivamente sua carreira sem deixar pistas'], 0,
  'A ausência repentina de postagens e um vídeo inacabado sugerem uma mudança na rotina, sem que o motivo seja dito explicitamente.', 5),

-- Intenção do autor (6a66a026-2fd0-4874-8216-4cdc03e6744e)
('6a66a026-2fd0-4874-8216-4cdc03e6744e', 'Leia: "Você já parou pra pensar em quantas horas do seu dia são desperdiçadas rolando a tela do celular sem propósito? Chegou a hora de repensar esse hábito." Qual é a principal intenção do autor no texto?',
  array['Alertar e convencer o leitor a refletir sobre o uso do celular', 'Apenas descrever de forma neutra o funcionamento dos celulares', 'Fazer propaganda de um novo aplicativo', 'Contar uma história de ficção'], 0,
  'O tom de questionamento direto e o apelo à reflexão indicam a intenção de alertar e convencer o leitor.', 1),
('6a66a026-2fd0-4874-8216-4cdc03e6744e', 'Leia: "O manual descreve, passo a passo, como instalar o software, sem opiniões pessoais, apenas instruções técnicas objetivas." Qual é a intenção do autor nesse tipo de texto?',
  array['Informar e instruir o leitor de forma objetiva', 'Convencer o leitor a comprar outro produto', 'Criticar o uso do software', 'Emocionar o leitor com uma narrativa pessoal'], 0,
  'A ausência de opiniões e o foco em instruções indicam intenção informativa e instrutiva.', 2),
('6a66a026-2fd0-4874-8216-4cdc03e6744e', 'Leia: "É um verdadeiro absurdo que, em pleno século XXI, ainda existam tantas pessoas sem acesso à água potável. Isso precisa mudar urgentemente." Qual é a intenção predominante do autor no trecho?',
  array['Denunciar um problema social e mobilizar o leitor para uma mudança', 'Apenas descrever dados estatísticos, sem opinião', 'Fazer uma piada sobre o tema', 'Elogiar a situação atual do saneamento básico'], 0,
  'O tom indignado ("verdadeiro absurdo") e o apelo à urgência revelam a intenção de denunciar e mobilizar o leitor.', 3),
('6a66a026-2fd0-4874-8216-4cdc03e6744e', 'Leia: "Era uma vez um pequeno vilarejo cercado por montanhas, onde ninguém jamais havia visto o mar." Qual é a intenção mais provável do autor ao iniciar o texto dessa forma?',
  array['Introduzir uma narrativa ficcional para entreter o leitor', 'Apresentar dados científicos sobre geografia', 'Convencer o leitor a comprar uma passagem de viagem', 'Descrever um manual de instruções'], 0,
  'A fórmula "Era uma vez" e o tom narrativo indicam a intenção de contar uma história, com finalidade de entretenimento.', 4),
('6a66a026-2fd0-4874-8216-4cdc03e6744e', 'Leia: "Compre já o nosso novo produto e sinta a diferença desde o primeiro uso! Oferta por tempo limitado." Qual é a intenção do autor nesse tipo de texto?',
  array['Persuadir o leitor a comprar um produto', 'Informar de maneira neutra sobre um produto', 'Narrar uma história de ficção', 'Criticar o consumo excessivo'], 0,
  'O uso de imperativos ("Compre já") e o apelo à urgência revelam clara intenção persuasiva/publicitária.', 5),

-- Argumentação (7715e4c7-fa79-47be-9cdf-ea20ca7b2db6)
('7715e4c7-fa79-47be-9cdf-ea20ca7b2db6', 'Leia: "A cidade deveria investir mais em transporte público, pois isso reduz o trânsito, diminui a poluição do ar e barateia o custo de locomoção para a população." Quais argumentos o autor utiliza para defender sua posição?',
  array['Redução do trânsito, diminuição da poluição e menor custo de locomoção', 'Apenas a opinião pessoal do autor, sem nenhum argumento', 'Um argumento de autoridade baseado em uma pesquisa científica', 'Nenhum argumento, apenas uma descrição neutra'], 0,
  'O texto apresenta três razões concretas (menos trânsito, menos poluição, menor custo) para sustentar sua defesa.', 1),
('7715e4c7-fa79-47be-9cdf-ea20ca7b2db6', 'Leia: "Estudos indicam que crianças que leem regularmente desenvolvem maior vocabulário e melhor desempenho escolar. Por isso, os pais devem incentivar a leitura desde cedo." Que tipo de argumento o autor utiliza para sustentar sua conclusão?',
  array['Um argumento baseado em evidências de estudos', 'Um argumento baseado apenas em uma opinião pessoal sem provas', 'Um argumento emocional, sem qualquer dado', 'Nenhum argumento é apresentado no texto'], 0,
  'O autor recorre a estudos (evidência) para justificar sua recomendação, caracterizando um argumento de autoridade/evidência.', 2),
('7715e4c7-fa79-47be-9cdf-ea20ca7b2db6', 'Leia: "Reduzir o desperdício de alimentos é importante porque, segundo a ONU, cerca de um terço de toda comida produzida no mundo é jogada fora, o que agrava a fome e o desperdício de recursos naturais." Qual argumento sustenta a defesa da redução do desperdício de alimentos?',
  array['O dado da ONU sobre o desperdício de um terço da comida produzida no mundo', 'Uma opinião pessoal sem embasamento', 'Um exemplo fictício sem relação com dados reais', 'Nenhum argumento é apresentado'], 0,
  'O autor usa um dado estatístico atribuído à ONU como argumento de autoridade para sustentar sua posição.', 3),
('7715e4c7-fa79-47be-9cdf-ea20ca7b2db6', 'Leia: "Ainda que pareça contraintuitivo, dormir mais cedo pode aumentar a produtividade, pois o corpo descansado realiza tarefas com mais foco e comete menos erros." Qual é o principal argumento utilizado para defender a ideia de dormir mais cedo?',
  array['O corpo descansado tem mais foco e comete menos erros', 'Dormir cedo é uma tradição cultural antiga', 'Não há nenhum argumento, apenas uma afirmação isolada', 'Um argumento baseado unicamente em opinião popular'], 0,
  'O texto relaciona o sono adequado ao foco e à redução de erros, argumento de causa e efeito que sustenta a ideia central.', 4),
('7715e4c7-fa79-47be-9cdf-ea20ca7b2db6', 'Leia: "Investir em educação básica de qualidade traz retorno econômico a longo prazo, pois adultos mais escolarizados tendem a ter empregos melhores e contribuir mais com impostos." Qual argumento o autor usa para defender o investimento em educação básica?',
  array['A relação entre maior escolaridade e melhores empregos, gerando retorno econômico', 'Um apelo emocional sem qualquer dado concreto', 'A citação de uma lei específica sobre educação', 'Nenhum argumento é apresentado no texto'], 0,
  'O autor estabelece uma relação de causa e consequência entre escolaridade, empregos melhores e retorno econômico, argumento central do texto.', 5),

-- Fato × opinião (6528814e-981a-48c0-959c-b4969beb0ebd)
('6528814e-981a-48c0-959c-b4969beb0ebd', 'Leia: "O filme dura duas horas e foi lançado em 2023. Na minha opinião, é o melhor filme do ano." Qual trecho do texto representa uma opinião, e não um fato?',
  array['"É o melhor filme do ano"', '"O filme dura duas horas"', '"Foi lançado em 2023"', 'Nenhum trecho representa uma opinião'], 0,
  'Afirmar que é "o melhor filme do ano" é um juízo de valor pessoal, enquanto a duração e o ano de lançamento são fatos verificáveis.', 1),
('6528814e-981a-48c0-959c-b4969beb0ebd', 'Leia: "A cidade tem 500 mil habitantes, segundo o último censo. Acredito que ela deveria ter mais parques públicos." Qual afirmação do texto é um fato verificável?',
  array['"A cidade tem 500 mil habitantes, segundo o último censo"', '"Ela deveria ter mais parques públicos"', 'Ambas as afirmações são opiniões', 'Nenhuma das afirmações pode ser considerada fato'], 0,
  'O número de habitantes, atribuído ao censo, é uma informação verificável, ao contrário da opinião sobre parques.', 2),
('6528814e-981a-48c0-959c-b4969beb0ebd', 'Leia: "A empresa registrou lucro de 10 milhões de reais no último trimestre. Para mim, esse resultado é decepcionante, considerando o potencial da empresa." Qual trecho expressa uma opinião do autor?',
  array['"Esse resultado é decepcionante, considerando o potencial da empresa"', '"A empresa registrou lucro de 10 milhões de reais"', 'Ambos os trechos são fatos', 'O texto não contém nenhuma opinião'], 0,
  'A avaliação do resultado como "decepcionante" é um juízo pessoal, diferente do dado numérico do lucro.', 3),
('6528814e-981a-48c0-959c-b4969beb0ebd', 'Leia: "O medicamento foi aprovado pela agência reguladora em 2022. Certamente, é o melhor tratamento disponível atualmente." Qual afirmação é um fato, e não uma opinião?',
  array['"O medicamento foi aprovado pela agência reguladora em 2022"', '"É o melhor tratamento disponível atualmente"', 'Ambas as afirmações são opiniões', 'Nenhuma das duas pode ser verificada'], 0,
  'A aprovação por uma agência reguladora em determinado ano é um dado verificável, diferente da afirmação de que é "o melhor tratamento".', 4),
('6528814e-981a-48c0-959c-b4969beb0ebd', 'Leia: "A ponte foi inaugurada em 1998. Particularmente, considero seu design pouco atraente." Qual trecho do texto representa uma opinião pessoal do autor?',
  array['"Considero seu design pouco atraente"', '"A ponte foi inaugurada em 1998"', 'Ambos os trechos são fatos verificáveis', 'O texto não expressa nenhuma opinião'], 0,
  'A avaliação estética ("pouco atraente") é subjetiva, enquanto a data de inauguração é um fato verificável.', 5),

-- Coesão e coerência textual (c158ce9d-b7ad-4cc6-ab9c-8ad373022d8a)
('c158ce9d-b7ad-4cc6-ab9c-8ad373022d8a', 'Leia: "Choveu bastante à noite. ____, a rua amanheceu completamente alagada." Qual conectivo preenche corretamente a lacuna, mantendo a coesão do texto?',
  array['Por isso', 'Embora', 'Caso', 'Apesar de'], 0,
  '"Por isso" estabelece uma relação de causa e consequência coerente entre chover e a rua alagar.', 1),
('c158ce9d-b7ad-4cc6-ab9c-8ad373022d8a', 'Leia: "Ele estudou bastante para a prova. ____, não conseguiu uma boa nota." Qual conectivo mantém a coerência do texto, expressando uma ideia de oposição?',
  array['Mesmo assim', 'Por isso', 'Portanto', 'Assim'], 0,
  '"Mesmo assim" expressa contraste entre o esforço nos estudos e o resultado não esperado, mantendo a coerência.', 2),
('c158ce9d-b7ad-4cc6-ab9c-8ad373022d8a', 'Leia: "O texto apresenta uma ideia no primeiro parágrafo e a contradiz no segundo, sem qualquer conectivo ou transição entre as partes, o que compromete sua leitura." Qual problema textual é apontado nesse trecho?',
  array['Falta de coesão entre as partes do texto', 'Excesso de conectivos', 'Uso incorreto da ortografia', 'Repetição excessiva de palavras'], 0,
  'A ausência de conectivos e transições entre ideias contraditórias caracteriza um problema de coesão textual.', 3),
('c158ce9d-b7ad-4cc6-ab9c-8ad373022d8a', 'Leia: "Maria comprou um carro novo. O carro novo de Maria é muito econômico. O carro novo de Maria também é confortável." Qual é o principal problema de coesão nesse trecho?',
  array['A repetição desnecessária da expressão "carro novo de Maria", que poderia ser substituída por pronomes', 'A falta total de qualquer verbo nas frases', 'O uso excessivo de conectivos', 'A ausência de pontuação'], 0,
  'A repetição da mesma expressão em vez do uso de pronomes ("ele", "que também é") prejudica a fluidez e a coesão do texto.', 4),
('c158ce9d-b7ad-4cc6-ab9c-8ad373022d8a', 'Leia: "Primeiro, misture os ingredientes secos. Em seguida, adicione os líquidos. Por fim, leve ao forno por 40 minutos." Que recurso garante a coerência e a organização sequencial desse texto instrucional?',
  array['O uso de conectivos de sequência temporal, como "primeiro", "em seguida" e "por fim"', 'A repetição do mesmo verbo em todas as frases', 'A ausência total de conectivos', 'O uso exclusivo de frases negativas'], 0,
  'Os conectivos de sequência ("primeiro", "em seguida", "por fim") organizam as etapas e garantem a coerência do texto instrucional.', 5);
