-- Química — Química Orgânica geral: Cadeias, Nomenclatura, Isomeria, Reações, Polímeros (5 leaves, 5 questões cada)
insert into questions (catalog_node_id, prompt, options, correct_index, explanation, order_index) values
-- Cadeias carbônicas (0f844d56-03ad-4c25-b48b-ce3ce4a5715e)
('0f844d56-03ad-4c25-b48b-ce3ce4a5715e', 'O átomo de carbono é capaz de formar cadeias longas e variadas principalmente porque:',
  array['Possui 4 elétrons de valência, formando até 4 ligações covalentes estáveis', 'Possui apenas 1 elétron de valência', 'É um metal altamente reativo', 'Não forma ligações com outros átomos de carbono'], 0,
  'A tetravalência do carbono permite a formação de cadeias longas, ramificadas e cíclicas, base da química orgânica.', 1),
('0f844d56-03ad-4c25-b48b-ce3ce4a5715e', 'Uma cadeia carbônica é classificada como aberta (acíclica) quando:',
  array['Não forma um ciclo fechado de átomos de carbono', 'Forma obrigatoriamente um anel fechado', 'Contém apenas átomos de hidrogênio', 'Não contém nenhum átomo de carbono'], 0,
  'Cadeias abertas têm extremidades livres, sem formar um anel fechado, diferentemente das cadeias cíclicas.', 2),
('0f844d56-03ad-4c25-b48b-ce3ce4a5715e', 'Uma cadeia carbônica é classificada como saturada quando:',
  array['Possui apenas ligações simples entre os átomos de carbono', 'Possui pelo menos uma ligação dupla ou tripla', 'Contém apenas átomos de oxigênio', 'É sempre uma cadeia cíclica'], 0,
  'Cadeias saturadas apresentam exclusivamente ligações simples entre os carbonos, sem duplas ou triplas.', 3),
('0f844d56-03ad-4c25-b48b-ce3ce4a5715e', 'Uma cadeia carbônica homogênea é aquela que contém:',
  array['Apenas átomos de carbono na cadeia principal, sem heteroátomos', 'Pelo menos um heteroátomo (como oxigênio ou nitrogênio) na cadeia principal', 'Exclusivamente ligações duplas', 'Um número ímpar de átomos de carbono'], 0,
  'Cadeias homogêneas não possuem heteroátomos interrompendo a sequência de átomos de carbono da cadeia principal.', 4),
('0f844d56-03ad-4c25-b48b-ce3ce4a5715e', 'Um carbono classificado como "terciário", em uma cadeia carbônica, está ligado diretamente a:',
  array['Três outros átomos de carbono', 'Um único átomo de carbono', 'Dois átomos de carbono', 'Quatro átomos de carbono'], 0,
  'A classificação do carbono depende do número de outros carbonos diretamente ligados a ele; o terciário está ligado a três.', 5),

-- Nomenclatura (5a184c6f-1a60-4351-afa3-dbd35050d165)
('5a184c6f-1a60-4351-afa3-dbd35050d165', 'Segundo as regras da IUPAC, o nome de um hidrocarboneto saturado (alcano) de cadeia normal com 4 átomos de carbono é:',
  array['Butano', 'Propano', 'Pentano', 'Metano'], 0,
  'A nomenclatura dos alcanos segue prefixos conforme o número de carbonos: but(4)+ano.', 1),
('5a184c6f-1a60-4351-afa3-dbd35050d165', 'O prefixo "met-", usado na nomenclatura orgânica, indica uma cadeia principal com quantos átomos de carbono?',
  array['1', '2', '3', '4'], 0,
  'O prefixo "met-" corresponde a apenas 1 átomo de carbono na cadeia principal, como em metano (CH₄).', 2),
('5a184c6f-1a60-4351-afa3-dbd35050d165', 'O sufixo "-ol", na nomenclatura orgânica, indica a presença da função:',
  array['Álcool', 'Ácido carboxílico', 'Cetona', 'Amina'], 0,
  'O sufixo "-ol" é característico dos álcoois, indicando a presença do grupo hidroxila (-OH) ligado a um carbono saturado.', 3),
('5a184c6f-1a60-4351-afa3-dbd35050d165', 'Na nomenclatura de um alceno (hidrocarboneto com uma ligação dupla), o sufixo utilizado é:',
  array['-eno', '-ano', '-ino', '-ol'], 0,
  'O sufixo "-eno" indica a presença de uma ligação dupla entre carbonos, como em eteno (CH₂=CH₂).', 4),
('5a184c6f-1a60-4351-afa3-dbd35050d165', 'Na nomenclatura orgânica, os prefixos numéricos (como di-, tri-, tetra-) são utilizados para indicar:',
  array['A quantidade de determinado grupo ou ramificação repetida na molécula', 'Sempre o número total de átomos de carbono da molécula', 'Apenas o número de átomos de hidrogênio', 'A massa molecular do composto'], 0,
  'Prefixos como di-, tri- e tetra- indicam quantas vezes um mesmo grupo ou ramificação aparece na estrutura.', 5),

-- Isomeria (6e3937ec-84c9-4de7-86ea-ffb98fb8f93f)
('6e3937ec-84c9-4de7-86ea-ffb98fb8f93f', 'Isômeros são compostos que possuem:',
  array['A mesma fórmula molecular, porém estruturas (fórmulas estruturais) diferentes', 'Fórmulas moleculares diferentes e mesma estrutura', 'A mesma fórmula molecular e a mesma estrutura, sem qualquer diferença', 'Nenhuma semelhança entre suas fórmulas'], 0,
  'Isômeros compartilham a mesma fórmula molecular, mas diferem na forma como os átomos estão organizados na estrutura.', 1),
('6e3937ec-84c9-4de7-86ea-ffb98fb8f93f', 'Na isomeria de cadeia, os isômeros diferem quanto:',
  array['Ao tipo de cadeia carbônica (aberta, fechada, ramificada, normal)', 'À posição de um heteroátomo apenas', 'À função orgânica presente na molécula', 'À disposição espacial dos átomos, sem alterar a cadeia'], 0,
  'Na isomeria de cadeia, os compostos têm a mesma função orgânica, mas cadeias carbônicas estruturalmente diferentes.', 2),
('6e3937ec-84c9-4de7-86ea-ffb98fb8f93f', 'Na isomeria de função, os isômeros pertencem a:',
  array['Funções orgânicas diferentes, apesar de terem a mesma fórmula molecular', 'Sempre a mesma função orgânica', 'Elementos químicos diferentes', 'Estados físicos diferentes, exclusivamente'], 0,
  'Um exemplo clássico é o álcool etílico e o éter dimetílico, ambos com fórmula C₂H₆O, mas de funções orgânicas distintas.', 3),
('6e3937ec-84c9-4de7-86ea-ffb98fb8f93f', 'A isomeria geométrica (cis-trans) ocorre em compostos que apresentam:',
  array['Restrição à livre rotação, geralmente devido a uma ligação dupla ou anel', 'Apenas ligações simples, sem qualquer restrição de rotação', 'Ausência total de carbono na estrutura', 'Sempre cadeias abertas e saturadas'], 0,
  'A isomeria cis-trans depende da restrição de rotação em torno de uma ligação dupla (ou estrutura cíclica).', 4),
('6e3937ec-84c9-4de7-86ea-ffb98fb8f93f', 'A isomeria óptica está relacionada à presença de:',
  array['Um carbono quiral (assimétrico), ligado a quatro grupos diferentes', 'Uma ligação dupla entre carbonos', 'Um anel aromático na molécula', 'Apenas átomos de hidrogênio na cadeia'], 0,
  'O carbono quiral, ligado a quatro substituintes diferentes, é a base da isomeria óptica.', 5),

-- Reações orgânicas (4d4f08dd-12b7-447c-8a16-17a5ec57eb26)
('4d4f08dd-12b7-447c-8a16-17a5ec57eb26', 'As reações de substituição, comuns em compostos saturados como os alcanos, consistem em:',
  array['Trocar um átomo ou grupo da molécula por outro', 'Adicionar átomos a uma ligação dupla ou tripla', 'Eliminar átomos, formando uma ligação dupla', 'Unir duas moléculas pequenas em uma maior, sem perda de átomos'], 0,
  'Na substituição, um átomo (geralmente hidrogênio) é trocado por outro átomo ou grupo.', 1),
('4d4f08dd-12b7-447c-8a16-17a5ec57eb26', 'As reações de adição, típicas de compostos insaturados como os alcenos, consistem em:',
  array['Adicionar átomos a uma ligação dupla ou tripla, transformando-a em ligação simples', 'Remover átomos da molécula, formando uma ligação dupla', 'Trocar um átomo de hidrogênio por outro átomo', 'Formar exclusivamente compostos aromáticos'], 0,
  'Na adição, átomos se ligam diretamente aos carbonos da dupla (ou tripla) ligação, que se transforma em ligação simples.', 2),
('4d4f08dd-12b7-447c-8a16-17a5ec57eb26', 'As reações de eliminação são caracterizadas por:',
  array['Remover átomos de uma molécula, geralmente formando uma ligação dupla ou tripla', 'Adicionar átomos a uma ligação simples', 'Substituir um átomo por outro sem alterar o tipo de ligação', 'Ocorrer exclusivamente em compostos aromáticos'], 0,
  'As reações de eliminação removem átomos da molécula, gerando uma insaturação.', 3),
('4d4f08dd-12b7-447c-8a16-17a5ec57eb26', 'A combustão completa de um hidrocarboneto, na presença de oxigênio suficiente, produz principalmente:',
  array['Dióxido de carbono (CO₂) e água (H₂O)', 'Apenas carbono sólido (fuligem)', 'Apenas gás hidrogênio', 'Nitrogênio e oxigênio puros'], 0,
  'A combustão completa de hidrocarbonetos, com oxigênio suficiente, gera CO₂ e H₂O como principais produtos.', 4),
('4d4f08dd-12b7-447c-8a16-17a5ec57eb26', 'A reação de esterificação, que produz ésteres, ocorre a partir da reação entre:',
  array['Um ácido carboxílico e um álcool', 'Um alcano e um alceno', 'Dois ácidos carboxílicos', 'Um éter e uma cetona'], 0,
  'A esterificação combina um ácido carboxílico e um álcool, liberando água e formando um éster.', 5),

-- Polímeros (b645c629-c218-475a-ad49-7524c0d4efe3)
('b645c629-c218-475a-ad49-7524c0d4efe3', 'Polímeros são macromoléculas formadas pela repetição de unidades estruturais menores chamadas:',
  array['Monômeros', 'Isômeros', 'Catalisadores', 'Radicais livres'], 0,
  'Os polímeros resultam da ligação repetida de unidades básicas (monômeros) por meio de reações de polimerização.', 1),
('b645c629-c218-475a-ad49-7524c0d4efe3', 'O polietileno, um dos plásticos mais comuns, é formado pela polimerização do monômero:',
  array['Eteno (etileno)', 'Metano', 'Ácido acético', 'Benzeno'], 0,
  'O polietileno é formado pela adição repetida de moléculas de eteno (CH₂=CH₂).', 2),
('b645c629-c218-475a-ad49-7524c0d4efe3', 'Os polímeros naturais, diferentemente dos sintéticos, são produzidos:',
  array['Por organismos vivos, como a celulose e as proteínas', 'Exclusivamente em laboratórios industriais', 'A partir do petróleo, sempre', 'Apenas por processos de fusão nuclear'], 0,
  'Polímeros naturais, como celulose, amido e proteínas, são produzidos por organismos vivos.', 3),
('b645c629-c218-475a-ad49-7524c0d4efe3', 'Um dos principais problemas ambientais associados aos polímeros sintéticos (plásticos convencionais) é:',
  array['Sua baixa taxa de degradação natural, permanecendo no ambiente por muito tempo', 'Sua rápida decomposição em poucos dias', 'A impossibilidade de serem reciclados', 'A ausência total de qualquer impacto ambiental'], 0,
  'Muitos plásticos convencionais demoram décadas ou séculos para se degradar naturalmente.', 4),
('b645c629-c218-475a-ad49-7524c0d4efe3', 'Os polímeros biodegradáveis se diferenciam dos convencionais por serem capazes de:',
  array['Se decompor mais rapidamente por ação de microrganismos', 'Nunca se degradarem, mesmo com ação microbiana', 'Serem produzidos exclusivamente a partir de metais', 'Substituir totalmente o uso de qualquer plástico atualmente'], 0,
  'Polímeros biodegradáveis são projetados para serem decompostos mais rapidamente por microrganismos.', 5);
