-- História — Brasil Colônia até República Velha (5 leaves, 5 questões cada)
insert into questions (catalog_node_id, prompt, options, correct_index, explanation, order_index) values
-- Povos indígenas (4387fdad-2724-4b69-be79-970eaf8f168a)
('4387fdad-2724-4b69-be79-970eaf8f168a', 'Qual foi a principal família linguística falada pelos povos indígenas do litoral brasileiro encontrados pelos portugueses em 1500?',
  array['Tupi-Guarani', 'Jê', 'Aruak', 'Karib'], 0,
  'Os povos tupi-guarani ocupavam boa parte do litoral brasileiro na chegada dos europeus.', 1),
('4387fdad-2724-4b69-be79-970eaf8f168a', 'Como era chamada a troca de produtos entre portugueses e indígenas nas primeiras décadas da colonização, baseada na extração do pau-brasil?',
  array['Escambo', 'Sesmaria', 'Quintos', 'Dízimo'], 0,
  'O escambo era a troca direta de mercadorias, sem uso de moeda, comum no início da exploração do pau-brasil.', 2),
('4387fdad-2724-4b69-be79-970eaf8f168a', 'Qual instituição religiosa teve papel central na catequese dos povos indígenas durante o período colonial, organizando aldeamentos?',
  array['A Companhia de Jesus (jesuítas)', 'A Ordem dos Beneditinos', 'O Santo Ofício', 'A Ordem Terceira'], 0,
  'Os jesuítas, sobretudo a partir de 1549, organizaram aldeamentos para catequizar os indígenas.', 3),
('4387fdad-2724-4b69-be79-970eaf8f168a', 'O conceito de "guerra justa", usado no período colonial, servia para justificar o quê?',
  array['A escravização de indígenas considerados hostis aos colonizadores', 'A doação de terras aos indígenas', 'A criação de reservas indígenas autônomas', 'A proibição do trabalho indígena'], 0,
  'A "guerra justa" era um argumento jurídico-religioso usado para legitimar a escravização de indígenas que resistissem à colonização ou à catequese.', 4),
('4387fdad-2724-4b69-be79-970eaf8f168a', 'Os bandeirantes, especialmente os paulistas, ficaram conhecidos historicamente por qual atividade relacionada aos povos indígenas?',
  array['Organizar expedições (bandeiras) que capturavam indígenas para escravização', 'Defender os aldeamentos jesuíticos das invasões estrangeiras', 'Negociar tratados de paz duradouros com os povos indígenas', 'Fundar universidades voltadas à cultura indígena'], 0,
  'As bandeiras paulistas dos séculos XVI e XVII tinham entre seus objetivos a captura de indígenas para escravização, além da busca por metais preciosos.', 5),

-- Brasil Colonial (ad10464d-0d11-4255-9fef-d341a0f856d6)
('ad10464d-0d11-4255-9fef-d341a0f856d6', 'O sistema de capitanias hereditárias, implantado a partir de 1534, tinha como objetivo principal:',
  array['Efetivar a ocupação e colonização do território a baixo custo para a Coroa', 'Criar um sistema republicano de governo nas colônias', 'Abolir o trabalho escravo na colônia', 'Unificar politicamente as capitanias desde o início'], 0,
  'Diante do alto custo de colonizar diretamente, a Coroa portuguesa dividiu o território em capitanias hereditárias, doadas a donatários.', 1),
('ad10464d-0d11-4255-9fef-d341a0f856d6', 'Qual foi a principal atividade econômica do Brasil colonial durante os séculos XVI e XVII, sustentada no trabalho escravo?',
  array['A produção açucareira', 'A mineração de ouro', 'A cafeicultura', 'A pecuária extensiva no Sul'], 0,
  'O açúcar foi o principal produto de exportação da colônia nos séculos XVI e XVII, cultivado sobretudo no Nordeste.', 2),
('ad10464d-0d11-4255-9fef-d341a0f856d6', 'O Governo-Geral, criado em 1548 com sede na Bahia, teve como principal função:',
  array['Centralizar a administração colonial e fiscalizar os donatários', 'Substituir definitivamente as capitanias hereditárias', 'Organizar eleições diretas para governador', 'Administrar exclusivamente o comércio de escravos'], 0,
  'O Governo-Geral foi criado para centralizar a administração e corrigir o fracasso de várias capitanias, mantendo porém o sistema de capitanias.', 3),
('ad10464d-0d11-4255-9fef-d341a0f856d6', 'A partir do final do século XVII, a descoberta de ouro em Minas Gerais provocou qual mudança relevante na colônia?',
  array['O deslocamento do eixo econômico e populacional para a região centro-sul', 'O fim definitivo da escravidão no Brasil', 'A independência imediata da colônia', 'A proibição da exploração de metais preciosos'], 0,
  'O ciclo do ouro atraiu grande contingente populacional para Minas Gerais, deslocando o eixo econômico do Nordeste açucareiro.', 4),
('ad10464d-0d11-4255-9fef-d341a0f856d6', 'A cobrança do "quinto", tributo característico do período da mineração colonial, correspondia a:',
  array['Um quinto (20%) de todo o ouro extraído, destinado à Coroa portuguesa', 'Um imposto sobre a venda de escravizados', 'Uma taxa cobrada apenas sobre a exportação de açúcar', 'Um tributo pago exclusivamente pelos senhores de engenho'], 0,
  'O quinto era a cobrança de 20% sobre o ouro extraído nas minas, destinada à Coroa portuguesa.', 5),

-- Independência do Brasil (8e6bf89f-70bf-4ecd-b680-e2ee171d41fc)
('8e6bf89f-70bf-4ecd-b680-e2ee171d41fc', 'A vinda da Família Real portuguesa para o Brasil, em 1808, ocorreu principalmente em razão de:',
  array['A fuga das tropas de Napoleão Bonaparte que invadiam Portugal', 'Um convite oficial do governo brasileiro', 'A descoberta de novas minas de ouro', 'Uma revolta popular em Lisboa'], 0,
  'Diante da invasão napoleônica a Portugal, a família real, sob proteção britânica, transferiu-se para o Brasil em 1808.', 1),
('8e6bf89f-70bf-4ecd-b680-e2ee171d41fc', 'A elevação do Brasil à condição de Reino Unido a Portugal e Algarves, em 1815, teve como consequência:',
  array['O fim da condição colonial do Brasil, equiparando-o juridicamente a Portugal', 'A imediata independência política do Brasil', 'A proibição do comércio direto com outras nações', 'O retorno definitivo da Corte a Lisboa'], 0,
  'Em 1815, o Brasil deixou de ser formalmente uma colônia, tornando-se Reino Unido a Portugal e Algarves.', 2),
('8e6bf89f-70bf-4ecd-b680-e2ee171d41fc', 'O episódio conhecido como "Dia do Fico" (janeiro de 1822) refere-se a:',
  array['A decisão de D. Pedro de permanecer no Brasil, desobedecendo às Cortes portuguesas', 'A assinatura da Constituição de 1824', 'A abdicação de D. Pedro I ao trono', 'A proclamação da Independência às margens do rio Ipiranga'], 0,
  'Pressionado pelas Cortes de Lisboa a retornar a Portugal, D. Pedro decidiu ficar no Brasil, episódio conhecido como "Dia do Fico".', 3),
('8e6bf89f-70bf-4ecd-b680-e2ee171d41fc', 'A Independência do Brasil, proclamada em 7 de setembro de 1822, resultou em:',
  array['A manutenção da monarquia no Brasil, agora sob D. Pedro I como imperador', 'A imediata implantação de uma república federativa', 'O fim total dos laços comerciais com Portugal', 'A abolição imediata da escravidão'], 0,
  'Diferentemente da maioria dos processos de independência na América, o Brasil manteve a forma monárquica de governo.', 4),
('8e6bf89f-70bf-4ecd-b680-e2ee171d41fc', 'O reconhecimento da independência do Brasil por Portugal, em 1825, esteve condicionado a:',
  array['O pagamento de uma indenização a Portugal, com empréstimo obtido junto à Inglaterra', 'A devolução integral do território brasileiro à Coroa portuguesa', 'A abdicação imediata de D. Pedro I', 'A anexação do Brasil aos Estados Unidos'], 0,
  'Portugal só reconheceu a independência mediante indenização, paga com recursos emprestados pela Inglaterra.', 5),

-- Brasil Império (f479bffd-9b8d-4b42-aa90-b17fb95862f4)
('f479bffd-9b8d-4b42-aa90-b17fb95862f4', 'O Primeiro Reinado (1822-1831) foi marcado por forte instabilidade política, que culminou em:',
  array['A abdicação de D. Pedro I em favor de seu filho, ainda criança', 'A proclamação imediata da República', 'A reeleição de D. Pedro I por voto direto', 'A dissolução completa do Império'], 0,
  'Pressionado por crises políticas e econômicas, D. Pedro I abdicou em 1831 em favor de seu filho, D. Pedro II, então com 5 anos.', 1),
('f479bffd-9b8d-4b42-aa90-b17fb95862f4', 'Durante o Período Regencial (1831-1840), o Brasil enfrentou diversas revoltas provinciais, entre elas:',
  array['A Cabanagem, a Balaiada, a Sabinada e a Revolução Farroupilha', 'A Inconfidência Mineira e a Conjuração Baiana', 'A Revolta da Vacina e a Revolta da Chibata', 'A Guerra dos Emboabas e a Guerra dos Mascates'], 0,
  'O Período Regencial, sem um monarca adulto, viu eclodir revoltas regionais como Cabanagem, Balaiada, Sabinada e Farroupilha.', 2),
('f479bffd-9b8d-4b42-aa90-b17fb95862f4', 'O golpe da Maioridade, em 1840, teve como principal objetivo:',
  array['Antecipar a coroação de D. Pedro II para conter a instabilidade do período regencial', 'Instaurar a República no Brasil', 'Abolir a escravidão antecipadamente', 'Transferir a capital do Império para Minas Gerais'], 0,
  'Setores políticos anteciparam a maioridade de D. Pedro II, então com 14 anos, esperando maior estabilidade ao país.', 3),
('f479bffd-9b8d-4b42-aa90-b17fb95862f4', 'A Guerra do Paraguai (1864-1870), maior conflito armado da história da América do Sul, envolveu o Brasil aliado a:',
  array['Argentina e Uruguai, formando a Tríplice Aliança contra o Paraguai', 'Bolívia e Chile, contra a Argentina', 'Estados Unidos, contra o Paraguai e o Uruguai', 'Inglaterra e França, contra o Paraguai'], 0,
  'A Tríplice Aliança (Brasil, Argentina e Uruguai) enfrentou o Paraguai, governado por Solano López.', 4),
('f479bffd-9b8d-4b42-aa90-b17fb95862f4', 'O movimento abolicionista ganhou força crescente no Segundo Reinado, culminando em:',
  array['A assinatura da Lei Áurea, em 1888, que extinguiu a escravidão no Brasil', 'A Lei do Ventre Livre, que já havia abolido totalmente a escravidão em 1871', 'A imediata proclamação da República junto com o fim da escravidão', 'A manutenção da escravidão até o início do século XX'], 0,
  'A Lei Áurea, assinada pela Princesa Isabel em 13 de maio de 1888, foi o ato final de um processo abolicionista gradual.', 5),

-- República Velha (602710f8-5c91-44c0-adf0-88b0cf87f333)
('602710f8-5c91-44c0-adf0-88b0cf87f333', 'A Proclamação da República, em 15 de novembro de 1889, foi liderada principalmente por:',
  array['Setores militares, com destaque para o Marechal Deodoro da Fonseca', 'Uma revolta popular espontânea nas ruas do Rio de Janeiro', 'A própria família imperial, que optou por abdicar do trono', 'Movimentos abolicionistas radicais'], 0,
  'A Proclamação da República foi um movimento essencialmente militar, liderado pelo Marechal Deodoro da Fonseca, com pouca participação popular direta.', 1),
('602710f8-5c91-44c0-adf0-88b0cf87f333', 'A "política do café com leite", característica da República Velha, refere-se a:',
  array['O revezamento no poder entre as oligarquias de São Paulo (café) e Minas Gerais (leite)', 'Um acordo comercial entre Brasil e Argentina', 'A política de incentivo à produção de laticínios no Sul do país', 'Um imposto cobrado sobre a exportação de café'], 0,
  'A alternância na presidência entre representantes das oligarquias paulista e mineira ficou conhecida como "política do café com leite".', 2),
('602710f8-5c91-44c0-adf0-88b0cf87f333', 'O "coronelismo", fenômeno típico da República Velha, caracterizava-se por:',
  array['O domínio político e social de grandes proprietários rurais, incluindo controle eleitoral', 'O governo direto dos militares sobre os estados', 'A eleição direta e livre de representantes em todos os municípios', 'O fim da influência dos grandes fazendeiros na política'], 0,
  'O coronelismo envolvia o controle político local por grandes proprietários rurais ("coronéis"), que exerciam forte influência sobre o voto ("voto de cabresto").', 3),
('602710f8-5c91-44c0-adf0-88b0cf87f333', 'O movimento tenentista, nas décadas de 1920, era formado principalmente por:',
  array['Jovens oficiais do Exército descontentes com as oligarquias e o sistema político vigente', 'Grandes proprietários de terra do Nordeste', 'Líderes sindicais urbanos ligados ao movimento operário', 'Membros do clero católico'], 0,
  'O tenentismo reunia jovens oficiais militares que criticavam o domínio oligárquico, como na Revolta do Forte de Copacabana e na Coluna Prestes.', 4),
('602710f8-5c91-44c0-adf0-88b0cf87f333', 'A Revolução de 1930, que encerrou a República Velha, teve como estopim imediato:',
  array['A derrota eleitoral de Getúlio Vargas e o assassinato de João Pessoa', 'A assinatura da Lei Áurea', 'A eclosão da Segunda Guerra Mundial', 'A crise do café de 1906'], 0,
  'A derrota de Vargas nas eleições de 1930 para Júlio Prestes, somada ao assassinato de João Pessoa, desencadeou o movimento armado que depôs Washington Luís.', 5);
