-- Química — Áreas gerais sem subdivisão (6 leaves, 8 questões cada)
insert into questions (catalog_node_id, prompt, options, correct_index, explanation, order_index) values
-- Ligações e Estrutura (806021ed-dee3-457f-94b5-a8e94e8b51aa)
('806021ed-dee3-457f-94b5-a8e94e8b51aa', 'A ligação iônica ocorre, tipicamente, entre:',
  array['Um metal e um ametal, com transferência de elétrons', 'Dois ametais, com compartilhamento de elétrons', 'Dois metais, com compartilhamento de elétrons', 'Dois gases nobres, sem qualquer interação'], 0,
  'Na ligação iônica, um metal cede elétrons a um ametal, formando um cátion e um ânion que se atraem eletrostaticamente.', 1),
('806021ed-dee3-457f-94b5-a8e94e8b51aa', 'A ligação covalente é caracterizada pelo(a):',
  array['Compartilhamento de pares de elétrons entre os átomos', 'Transferência total de elétrons de um átomo para outro', 'Ausência completa de elétrons envolvidos', 'União exclusiva entre metais'], 0,
  'Na ligação covalente, os átomos compartilham pares de elétrons, geralmente entre ametais.', 2),
('806021ed-dee3-457f-94b5-a8e94e8b51aa', 'A ligação metálica, responsável por propriedades como condutividade elétrica e maleabilidade dos metais, é frequentemente descrita como:',
  array['Um "mar de elétrons" livres, envolvendo os cátions metálicos', 'Uma transferência definitiva de elétrons entre átomos vizinhos', 'Um compartilhamento rígido de elétrons entre apenas dois átomos', 'A ausência total de elétrons livres na estrutura'], 0,
  'Na ligação metálica, os elétrons de valência formam um "mar" deslocalizado, compartilhado por todos os cátions metálicos.', 3),
('806021ed-dee3-457f-94b5-a8e94e8b51aa', 'A Teoria do Octeto estabelece que os átomos tendem a se estabilizar quando alcançam, na camada de valência:',
  array['Oito elétrons, semelhante à configuração dos gases nobres', 'Apenas um elétron, semelhante aos metais alcalinos', 'Exatamente quatro elétrons, sempre', 'Nenhum elétron na camada de valência'], 0,
  'A Teoria do Octeto propõe que os átomos buscam atingir 8 elétrons na camada de valência, alcançando estabilidade semelhante à dos gases nobres.', 4),
('806021ed-dee3-457f-94b5-a8e94e8b51aa', 'Uma ligação covalente é classificada como polar quando ocorre entre átomos:',
  array['De eletronegatividades diferentes, gerando uma distribuição desigual de carga', 'De eletronegatividades idênticas', 'Do mesmo elemento químico, sempre', 'Sem qualquer diferença de eletronegatividade possível'], 0,
  'A diferença de eletronegatividade entre os átomos ligados gera um dipolo elétrico, caracterizando a ligação covalente polar.', 5),
('806021ed-dee3-457f-94b5-a8e94e8b51aa', 'As geometrias moleculares, estudadas pela Teoria da Repulsão dos Pares de Elétrons da Camada de Valência (VSEPR), são determinadas principalmente por:',
  array['A repulsão entre os pares de elétrons ao redor do átomo central', 'A massa total da molécula', 'A cor da substância', 'O estado físico do composto'], 0,
  'A teoria VSEPR baseia-se na ideia de que os pares de elétrons se organizam de forma a minimizar a repulsão entre eles.', 6),
('806021ed-dee3-457f-94b5-a8e94e8b51aa', 'As forças intermoleculares, responsáveis por manter moléculas unidas em líquidos e sólidos moleculares, incluem, entre outras, as ligações de:',
  array['Hidrogênio, dipolo-dipolo e forças de London (dipolo induzido)', 'Apenas ligações iônicas', 'Apenas ligações metálicas', 'Nenhum tipo de força além das ligações covalentes internas'], 0,
  'As forças intermoleculares atuam entre moléculas distintas, diferentemente das ligações covalentes internas.', 7),
('806021ed-dee3-457f-94b5-a8e94e8b51aa', 'A água apresenta um ponto de ebulição relativamente elevado, para uma molécula tão pequena, principalmente devido à presença de:',
  array['Ligações de hidrogênio entre suas moléculas', 'Ligações iônicas fortes entre os átomos de hidrogênio e oxigênio', 'Ausência total de forças intermoleculares', 'Ligações metálicas entre suas moléculas'], 0,
  'As fortes ligações de hidrogênio entre as moléculas de água exigem mais energia para serem rompidas, elevando seu ponto de ebulição.', 8),

-- Estequiometria (1694b662-d892-4687-8727-9f74c2715b11)
('1694b662-d892-4687-8727-9f74c2715b11', 'A estequiometria é o ramo da química que estuda:',
  array['As relações quantitativas entre reagentes e produtos em uma reação química', 'Apenas as propriedades físicas dos elementos', 'Exclusivamente a estrutura eletrônica dos átomos', 'A classificação dos compostos orgânicos'], 0,
  'A estequiometria calcula as proporções de massa, mol ou volume entre substâncias envolvidas em uma reação química.', 1),
('1694b662-d892-4687-8727-9f74c2715b11', 'O mol é definido como a quantidade de matéria que contém um número de partículas igual a:',
  array['A constante de Avogadro, aproximadamente 6,02 × 10²³', 'Exatamente 1000 partículas', 'O número atômico do elemento', 'A massa molecular da substância, em gramas'], 0,
  'Um mol corresponde a 6,02 × 10²³ partículas, o chamado número de Avogadro.', 2),
('1694b662-d892-4687-8727-9f74c2715b11', 'Na equação balanceada 2H₂ + O₂ → 2H₂O, quantos mols de água são produzidos a partir de 4 mols de gás hidrogênio (H₂), supondo oxigênio suficiente?',
  array['4 mols', '2 mols', '8 mols', '1 mol'], 0,
  'Pela proporção da equação balanceada (2 mols de H₂ para 2 mols de H₂O), 4 mols de H₂ produzem 4 mols de H₂O.', 3),
('1694b662-d892-4687-8727-9f74c2715b11', 'A Lei da Conservação das Massas, formulada por Lavoisier, estabelece que, em uma reação química em sistema fechado:',
  array['A massa total dos reagentes é igual à massa total dos produtos', 'A massa dos produtos é sempre maior que a dos reagentes', 'A massa dos reagentes é sempre maior que a dos produtos', 'A massa não tem qualquer relação com a reação química'], 0,
  'Segundo Lavoisier, "na natureza nada se cria, nada se perde, tudo se transforma" — a massa total se conserva.', 4),
('1694b662-d892-4687-8727-9f74c2715b11', 'O reagente limitante de uma reação química é aquele que:',
  array['Se esgota primeiro, determinando a quantidade máxima de produto formado', 'Está sempre em maior quantidade na reação', 'Nunca participa efetivamente da reação', 'É formado ao final da reação, e não consumido'], 0,
  'O reagente limitante determina a quantidade máxima de produtos que pode ser formada, pois é consumido completamente primeiro.', 5),
('1694b662-d892-4687-8727-9f74c2715b11', 'A massa molar de uma substância é numericamente igual à sua massa molecular, porém expressa em:',
  array['Gramas por mol (g/mol)', 'Apenas unidades de massa atômica (u), sem outra unidade', 'Litros', 'Mols por litro'], 0,
  'A massa molar converte a massa molecular (em u) para uma grandeza prática, expressa em g/mol.', 6),
('1694b662-d892-4687-8727-9f74c2715b11', 'O rendimento de uma reação química, na prática industrial, costuma ser inferior a 100% principalmente devido a:',
  array['Reações secundárias, perdas no processo e reações reversíveis incompletas', 'Um erro inevitável na Lei da Conservação das Massas', 'A ausência total de reagentes limitantes', 'A impossibilidade de qualquer reação química ocorrer completamente'], 0,
  'Fatores como reações paralelas, perdas físicas e equilíbrios químicos incompletos reduzem o rendimento real em relação ao teórico.', 7),
('1694b662-d892-4687-8727-9f74c2715b11', 'Em condições normais de temperatura e pressão (CNTP), o volume molar de um gás ideal é aproximadamente:',
  array['22,4 litros por mol', '1 litro por mol', '6,02 litros por mol', '100 litros por mol'], 0,
  'Nas CNTP (0°C e 1 atm), qualquer gás ideal ocupa aproximadamente 22,4 litros por mol.', 8),

-- Soluções (f41ba2d7-4462-4a77-8362-272bb8313c47)
('f41ba2d7-4462-4a77-8362-272bb8313c47', 'Uma solução química é definida como uma mistura:',
  array['Homogênea entre duas ou mais substâncias', 'Heterogênea entre duas substâncias', 'Formada exclusivamente por um único componente', 'Sempre no estado sólido'], 0,
  'Soluções são misturas homogêneas, onde não é possível distinguir visualmente os componentes.', 1),
('f41ba2d7-4462-4a77-8362-272bb8313c47', 'Em uma solução, o componente presente em maior quantidade é geralmente chamado de:',
  array['Solvente', 'Soluto', 'Precipitado', 'Catalisador'], 0,
  'O solvente é o componente presente em maior proporção, no qual o soluto se dissolve.', 2),
('f41ba2d7-4462-4a77-8362-272bb8313c47', 'A concentração comum de uma solução é geralmente expressa pela razão entre:',
  array['A massa do soluto e o volume da solução', 'A massa do solvente e a massa do soluto', 'O volume do solvente apenas', 'O número de mols do solvente'], 0,
  'A concentração comum (C) é definida como a massa do soluto dividida pelo volume total da solução, geralmente em g/L.', 3),
('f41ba2d7-4462-4a77-8362-272bb8313c47', 'Uma solução é classificada como saturada quando:',
  array['Contém a quantidade máxima de soluto que pode ser dissolvida naquela temperatura', 'Contém menos soluto do que o solvente poderia dissolver', 'Não contém nenhum soluto dissolvido', 'É sempre uma solução heterogênea'], 0,
  'Na saturação, a solução atinge o limite de solubilidade do soluto naquela temperatura.', 4),
('f41ba2d7-4462-4a77-8362-272bb8313c47', 'Ao diluir uma solução, adicionando mais solvente sem alterar a quantidade de soluto, a concentração da solução:',
  array['Diminui', 'Aumenta', 'Permanece inalterada', 'Torna-se indefinida'], 0,
  'Como a mesma quantidade de soluto passa a ocupar um volume maior, a concentração diminui com a diluição.', 5),
('f41ba2d7-4462-4a77-8362-272bb8313c47', 'A solubilidade de um soluto em determinado solvente pode variar de acordo com:',
  array['A temperatura e, no caso de gases, a pressão', 'Apenas a cor do solvente', 'Nenhum fator externo, permanecendo sempre constante', 'Apenas o volume total da solução'], 0,
  'Fatores como temperatura e pressão influenciam diretamente a solubilidade de um soluto.', 6),
('f41ba2d7-4462-4a77-8362-272bb8313c47', 'Duas soluções são consideradas isotônicas quando apresentam:',
  array['A mesma concentração de partículas dissolvidas (mesma pressão osmótica)', 'Cores idênticas, independentemente da concentração', 'Volumes idênticos, independentemente da concentração', 'Solventes diferentes, obrigatoriamente'], 0,
  'Soluções isotônicas possuem a mesma pressão osmótica, ou seja, concentrações equivalentes de partículas dissolvidas.', 7),
('f41ba2d7-4462-4a77-8362-272bb8313c47', 'O soro fisiológico, amplamente utilizado na medicina, é uma solução aquosa de:',
  array['Cloreto de sódio (NaCl) em baixa concentração', 'Ácido sulfúrico concentrado', 'Álcool etílico puro', 'Gás oxigênio dissolvido em água'], 0,
  'O soro fisiológico é uma solução salina (NaCl a 0,9%), formulada para ser isotônica em relação ao plasma sanguíneo.', 8),

-- Físico-Química (2e117b4e-3e7c-492e-82dc-22b964209b9a)
('2e117b4e-3e7c-492e-82dc-22b964209b9a', 'A termoquímica, ramo da físico-química, estuda principalmente:',
  array['As trocas de energia (calor) que ocorrem durante as reações químicas', 'Exclusivamente a velocidade das reações químicas', 'A estrutura eletrônica dos átomos', 'A nomenclatura dos compostos orgânicos'], 0,
  'A termoquímica analisa a energia absorvida ou liberada durante reações químicas.', 1),
('2e117b4e-3e7c-492e-82dc-22b964209b9a', 'Uma reação química é classificada como exotérmica quando:',
  array['Libera energia (calor) para o ambiente', 'Absorve energia (calor) do ambiente', 'Não envolve qualquer troca de energia', 'Ocorre apenas em temperaturas muito baixas'], 0,
  'Reações exotérmicas liberam energia na forma de calor, geralmente aquecendo o ambiente ao redor.', 2),
('2e117b4e-3e7c-492e-82dc-22b964209b9a', 'A cinética química estuda principalmente:',
  array['A velocidade das reações químicas e os fatores que a influenciam', 'Apenas a energia liberada em reações exotérmicas', 'A estrutura cristalina dos sólidos', 'A solubilidade de gases em líquidos'], 0,
  'A cinética química analisa a rapidez com que as reações ocorrem e como diversos fatores a influenciam.', 3),
('2e117b4e-3e7c-492e-82dc-22b964209b9a', 'Um catalisador, em uma reação química, atua principalmente:',
  array['Aumentando a velocidade da reação, sem ser consumido no processo', 'Sendo totalmente consumido durante a reação', 'Diminuindo sempre a velocidade da reação', 'Alterando o produto final da reação'], 0,
  'Catalisadores aumentam a velocidade das reações ao diminuir a energia de ativação, sem serem consumidos no processo.', 4),
('2e117b4e-3e7c-492e-82dc-22b964209b9a', 'O equilíbrio químico é atingido quando:',
  array['As velocidades das reações direta e inversa se igualam, mantendo as concentrações constantes', 'A reação química é completamente interrompida', 'Todos os reagentes são totalmente convertidos em produtos', 'Não existe mais qualquer reagente ou produto no sistema'], 0,
  'No equilíbrio químico dinâmico, as reações direta e inversa continuam ocorrendo, mas em velocidades iguais.', 5),
('2e117b4e-3e7c-492e-82dc-22b964209b9a', 'O pH é uma escala utilizada para medir:',
  array['A acidez ou basicidade de uma solução aquosa', 'A temperatura de uma solução', 'A densidade de uma solução', 'A cor de uma solução'], 0,
  'O pH mede a concentração de íons H⁺ em uma solução, indicando seu grau de acidez ou basicidade.', 6),
('2e117b4e-3e7c-492e-82dc-22b964209b9a', 'Uma solução com pH igual a 7, a 25°C, é classificada como:',
  array['Neutra', 'Ácida', 'Básica (alcalina)', 'Impossível de existir'], 0,
  'O valor de pH 7, a 25°C, corresponde ao ponto neutro da escala, característico da água pura.', 7),
('2e117b4e-3e7c-492e-82dc-22b964209b9a', 'A eletroquímica é o ramo da físico-química que estuda a relação entre:',
  array['Reações químicas e a geração ou consumo de energia elétrica', 'Reações químicas e a cor dos compostos', 'A estrutura óssea dos seres vivos', 'Fenômenos exclusivamente mecânicos'], 0,
  'A eletroquímica estuda processos como pilhas e baterias e a eletrólise.', 8),

-- Química Inorgânica (047a3c19-6572-45e7-87fa-ba36b78190d0)
('047a3c19-6572-45e7-87fa-ba36b78190d0', 'Os ácidos, segundo a definição de Arrhenius, são substâncias que, em solução aquosa, liberam como único cátion:',
  array['Íons H⁺ (ou H₃O⁺)', 'Íons OH⁻', 'Íons metálicos', 'Elétrons livres'], 0,
  'Segundo Arrhenius, ácidos são substâncias que, ao se dissociarem em água, liberam íons H⁺.', 1),
('047a3c19-6572-45e7-87fa-ba36b78190d0', 'As bases, segundo a definição de Arrhenius, são substâncias que, em solução aquosa, liberam como único ânion:',
  array['Íons OH⁻ (hidroxila)', 'Íons H⁺', 'Íons metálicos', 'Elétrons livres'], 0,
  'Segundo Arrhenius, bases liberam íons hidroxila (OH⁻) ao se dissociarem em água.', 2),
('047a3c19-6572-45e7-87fa-ba36b78190d0', 'A reação entre um ácido e uma base, produzindo sal e água, é chamada de:',
  array['Reação de neutralização', 'Reação de combustão', 'Reação de oxirredução, exclusivamente', 'Reação de polimerização'], 0,
  'A neutralização é a reação característica entre ácidos e bases, formando um sal e água como produtos.', 3),
('047a3c19-6572-45e7-87fa-ba36b78190d0', 'O cloreto de sódio (NaCl), sal de cozinha, é classificado quimicamente como:',
  array['Um sal, resultante teoricamente da reação entre um ácido e uma base', 'Um ácido forte', 'Uma base forte', 'Um óxido'], 0,
  'O NaCl é um sal, formado pelo cátion de uma base (Na⁺) e o ânion de um ácido (Cl⁻).', 4),
('047a3c19-6572-45e7-87fa-ba36b78190d0', 'Os óxidos são compostos binários formados pela combinação de oxigênio com:',
  array['Outro elemento químico, exceto o flúor', 'Exclusivamente metais nobres', 'Apenas hidrogênio', 'Nenhum outro elemento além do próprio oxigênio'], 0,
  'Óxidos são compostos binários de oxigênio com outro elemento (exceto o flúor).', 5),
('047a3c19-6572-45e7-87fa-ba36b78190d0', 'O dióxido de carbono (CO₂), um óxido amplamente conhecido, é classificado como um óxido:',
  array['Ácido, pois reage com água formando um ácido', 'Básico, pois reage com água formando uma base forte', 'Neutro, sem qualquer reatividade', 'Anfótero, exclusivamente'], 0,
  'O CO₂ reage com água formando ácido carbônico (H₂CO₃), sendo classificado como um óxido ácido.', 6),
('047a3c19-6572-45e7-87fa-ba36b78190d0', 'O ácido sulfúrico (H₂SO₄), um dos ácidos inorgânicos mais produzidos industrialmente, é amplamente utilizado, entre outras aplicações, em:',
  array['Baterias automotivas e na indústria de fertilizantes', 'Bebidas alcoólicas', 'Cosméticos hidratantes, exclusivamente', 'Alimentos in natura'], 0,
  'O ácido sulfúrico é essencial na fabricação de baterias de chumbo-ácido e na produção de fertilizantes fosfatados.', 7),
('047a3c19-6572-45e7-87fa-ba36b78190d0', 'O hidróxido de sódio (NaOH), base forte amplamente utilizada industrialmente, é popularmente conhecido como:',
  array['Soda cáustica', 'Vinagre', 'Sal de cozinha', 'Bicarbonato de sódio'], 0,
  'O NaOH, comercialmente chamado de soda cáustica, é usado na fabricação de sabões, papel e em processos de limpeza industrial.', 8),

-- Química Ambiental e Cotidiano (73cac530-0e0d-4775-b9c0-ae6ce4912b8c)
('73cac530-0e0d-4775-b9c0-ae6ce4912b8c', 'A chuva ácida é um fenômeno ambiental causado principalmente pela emissão atmosférica de:',
  array['Óxidos de enxofre e nitrogênio, provenientes da queima de combustíveis fósseis', 'Vapor de água puro', 'Gás oxigênio em excesso', 'Gases nobres emitidos por indústrias'], 0,
  'Óxidos de enxofre e nitrogênio, liberados pela queima de combustíveis fósseis, reagem com a água atmosférica formando ácidos.', 1),
('73cac530-0e0d-4775-b9c0-ae6ce4912b8c', 'O efeito estufa, fenômeno natural intensificado por atividades humanas, está diretamente relacionado ao aumento da concentração atmosférica de gases como:',
  array['Dióxido de carbono (CO₂) e metano (CH₄)', 'Gases nobres, como o hélio e o neônio', 'Apenas vapor d''água, exclusivamente', 'Nitrogênio molecular (N₂) puro'], 0,
  'O aumento de gases como CO₂ e CH₄, provenientes de atividades humanas, intensifica o efeito estufa.', 2),
('73cac530-0e0d-4775-b9c0-ae6ce4912b8c', 'A camada de ozônio, localizada na estratosfera, tem papel fundamental ao:',
  array['Absorver parte da radiação ultravioleta prejudicial proveniente do Sol', 'Produzir oxigênio para a respiração de todos os seres vivos', 'Impedir totalmente a entrada de luz visível na Terra', 'Não ter qualquer relação com a radiação solar'], 0,
  'O ozônio estratosférico absorve grande parte da radiação ultravioleta nociva, protegendo os seres vivos.', 3),
('73cac530-0e0d-4775-b9c0-ae6ce4912b8c', 'Substâncias como os CFCs (clorofluorcarbonos), antigamente utilizadas em aerossóis e refrigeradores, foram associadas principalmente a:',
  array['A destruição da camada de ozônio', 'O aumento imediato da fertilidade do solo', 'A purificação da água potável', 'A redução do efeito estufa'], 0,
  'Os CFCs liberam átomos de cloro na estratosfera, que catalisam a decomposição do ozônio.', 4),
('73cac530-0e0d-4775-b9c0-ae6ce4912b8c', 'O tratamento de água para consumo humano geralmente inclui, entre outras etapas, a:',
  array['Cloração, para eliminar microrganismos patogênicos', 'Adição de metais pesados, para purificação', 'Remoção total de qualquer substância dissolvida na água', 'Exposição direta a radiação nuclear'], 0,
  'A cloração é uma etapa comum no tratamento de água, utilizada para desinfecção e eliminação de microrganismos.', 5),
('73cac530-0e0d-4775-b9c0-ae6ce4912b8c', 'A reciclagem de materiais como plástico, vidro, papel e metal contribui, entre outros benefícios, para:',
  array['Reduzir a extração de recursos naturais e o volume de resíduos em aterros', 'Aumentar exclusivamente os custos de produção, sem qualquer benefício ambiental', 'Eliminar totalmente a necessidade de tratamento de esgoto', 'Não ter qualquer impacto ambiental relevante'], 0,
  'A reciclagem reduz a demanda por matérias-primas virgens e diminui a quantidade de resíduos descartados.', 6),
('73cac530-0e0d-4775-b9c0-ae6ce4912b8c', 'Os agrotóxicos, amplamente utilizados na agricultura, podem trazer riscos ambientais e à saúde humana principalmente por meio de:',
  array['Contaminação do solo, da água e de alimentos, além de efeitos tóxicos diretos', 'Nenhum tipo de risco, sendo substâncias totalmente inofensivas', 'Purificação natural do ambiente onde são aplicados', 'Redução da poluição atmosférica'], 0,
  'O uso excessivo ou inadequado de agrotóxicos pode contaminar solo, água e alimentos, além de causar efeitos tóxicos.', 7),
('73cac530-0e0d-4775-b9c0-ae6ce4912b8c', 'Pilhas e baterias descartadas de forma inadequada representam um risco ambiental principalmente por conterem:',
  array['Metais pesados tóxicos, como chumbo, mercúrio e cádmio', 'Apenas água pura em sua composição', 'Substâncias totalmente biodegradáveis e inofensivas', 'Nenhum componente químico prejudicial'], 0,
  'Pilhas e baterias contêm metais pesados que, se descartados incorretamente, podem contaminar o solo e os lençóis freáticos.', 8);
