import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:aura/core/theme/app_colors.dart';
import 'package:aura/features/aurudo_reaction/presentation/aura_particles.dart';
import 'package:aura/shared/widgets/aura/aurudo_illustration.dart';

/// Where everything sits in the farm-Aura art, as fractions of its canvas.
///
/// The layers are the approved cut-out kit (aprovaura-brand/
/// aurudo-animation-kit/perfect-farm-aura, regenerated by its
/// `build_prod_layers.py`) cropped to exactly the frame of
/// `aurudo_farming_aura.webp`, so the animated Aurudo occupies the same
/// box as the still one at every size. Only these fractions are used --
/// never screen pixels -- so the motion scales with the mascot.
abstract final class FarmAuraGeometry {
  /// Width / height of the canvas (1201 × 1232 in the source).
  static const aspect = 1201 / 1232;

  /// Width the layers are exported at; nothing is ever decoded larger.
  static const sourceWidth = 780;

  /// The hidden shoulder the raised (left) arm turns about.
  static const armPivot = Offset(797 / 1201, 640 / 1232);

  /// The orb's centre: where it scales and counter-rotates.
  static const orbPivot = Offset(974 / 1201, 198 / 1232);

  /// Orb radius including its baked halo, as a fraction of the height.
  static const orbRadius = 192 / 1232;

  static const base = 'lib/assets/mascot/farm_aura/aurudo_farm_aura_base.webp';
  static const orb = 'lib/assets/mascot/farm_aura/aurudo_farm_aura_orb.webp';
  static const leftArm =
      'lib/assets/mascot/farm_aura/aurudo_farm_aura_left_arm.webp';

  /// The helmet rim and straps the arm passes behind, drawn above it. The
  /// arm sits between these and the base, so they cannot be baked in.
  static const helmetFront =
      'lib/assets/mascot/farm_aura/aurudo_farm_aura_helmet_front.webp';

  /// Paint order, back to front.
  static const all = [base, orb, leftArm, helmetFront];

  /// Where each pulled particle starts, as fractions of the art's box:
  /// the sides, the lower body, the orbits, a few from outside, hardly any
  /// from above.
  static const particleOrigins = [
    Offset(0.04, 0.42), // left side
    Offset(0.10, 0.68), // left, lower body
    Offset(0.26, 0.90), // bottom left
    Offset(0.52, 0.97), // under the feet
    Offset(0.34, 0.60), // front orbit
    Offset(0.70, 0.66), // back orbit
    Offset(0.97, 0.52), // right side
    Offset(0.94, 0.80), // right, lower
    Offset(1.08, 0.30), // from outside, right
    Offset(0.55, 0.02), // one from above
  ];
}

/// The farm-Aura timeline and amplitudes, fitted inside the reaction scene:
/// two clear pulls that finish around 1.8s after the mascot appears, so
/// the headline and the result arrive while Aurudo is still farming
/// instead of after. Plays once; never loops.
abstract final class FarmAuraTimeline {
  /// Same entrance as the still mascot: fade + [entranceScaleFrom] -> 1.
  static const entranceDuration = 350;
  static const entranceScaleFrom = 0.92;

  /// A beat of stillness before the first pull.
  static const preroll = 100;
  static const farmCycleDuration = 860;
  static const cycles = 2;
  static const total = preroll + farmCycleDuration * cycles; // 1820 ms

  /// Where in each pull the top sits.
  static const peakAt = 0.48;

  /// Inward/up only: the pose in the art is the lowest point.
  static const maxArmAngleDegrees = 4.0;
  static const orbMaxScale = 1.04;
  static const glowMaxOpacity = 0.20;

  /// The halo's reach, relative to the orb's own (baked) halo.
  static const glowRadiusFactor = 1.05;

  /// Lift at the top of a pull per logical pixel of mascot: ~1px at 120,
  /// ~1.5px at 180, ~2px at 240.
  static const liftPerSize = 1 / 120;
  static const particleCount = 10;

  /// (pull index, phase 0..1) while pulling; null before and after.
  static (int, double)? pullAt(double ms) {
    final t = ms - preroll;
    if (t < 0 || t >= farmCycleDuration * cycles) return null;
    return (
      t ~/ farmCycleDuration,
      (t % farmCycleDuration) / farmCycleDuration,
    );
  }

  /// 0 at rest, 1 at the top of a pull; smooth both ways, no bounce.
  static double energyAt(double ms) {
    final pull = pullAt(ms);
    if (pull == null) return 0;
    final p = pull.$2;
    return p <= peakAt
        ? Curves.easeInOutCubic.transform(p / peakAt)
        : Curves.easeInOutCubic.transform(1 - (p - peakAt) / (1 - peakAt));
  }

  /// Milliseconds from the start to the top of pull [index].
  static double peakMs(int index) =>
      preroll + farmCycleDuration * (index + peakAt);
}

/// The pose at one instant, before it is placed on screen. At rest (before,
/// between and after the pulls, and always under reduced motion) it is
/// exactly the art: 0°, scale 1, no lift, no glow.
@immutable
class FarmAuraPose {
  const FarmAuraPose._(this.energy);

  factory FarmAuraPose.at(double elapsedMs) =>
      FarmAuraPose._(FarmAuraTimeline.energyAt(elapsedMs));

  static const rest = FarmAuraPose._(0);

  final double energy;

  /// The arm group's turn about [FarmAuraGeometry.armPivot]; positive is
  /// inward/up (counter-clockwise on screen).
  double get armAngleDegrees => FarmAuraTimeline.maxArmAngleDegrees * energy;
  double get orbScale => 1 + (FarmAuraTimeline.orbMaxScale - 1) * energy;
  double get glowOpacity => FarmAuraTimeline.glowMaxOpacity * energy;
  double liftFor(double size) => size * FarmAuraTimeline.liftPerSize * energy;
}

/// Aurudo farming Aura: the signature `perfectFarmAura` reaction.
///
/// The body stays still. The raised arm turns inward/up about the hidden
/// shoulder (never outward -- the pose in the art is the lowest point), the
/// orb rides with the hand while counter-rotating so it reads as held
/// energy rather than a sticker, and Aura is drawn in from around the body
/// to the orb. Twice, then the exact base pose. One AnimationController
/// drives all of it.
///
/// [instant] (or the platform's reduced motion) shows that final pose
/// straight away: no entrance, no particles, no ticker. If any layer fails
/// to load, the still `farming_aura` illustration stands in.
class AurudoFarmAuraAnimation extends StatefulWidget {
  const AurudoFarmAuraAnimation({
    required this.size,
    this.instant = false,
    @visibleForTesting this.assets = FarmAuraGeometry.all,
    super.key,
  });

  final double size;
  final bool instant;

  /// Base, orb, arm and helmet-front layers, in that order.
  final List<String> assets;

  /// Keys on the two moving groups, so tests can read their transforms.
  @visibleForTesting
  static const armGroupKey = ValueKey('farm-aura-arm-group');
  @visibleForTesting
  static const orbKey = ValueKey('farm-aura-orb');

  @override
  State<AurudoFarmAuraAnimation> createState() =>
      _AurudoFarmAuraAnimationState();
}

class _AurudoFarmAuraAnimationState extends State<AurudoFarmAuraAnimation>
    with SingleTickerProviderStateMixin {
  late final AnimationController _clock = AnimationController(
    vsync: this,
    duration: const Duration(milliseconds: FarmAuraTimeline.total),
  );
  bool _failed = false;
  bool _precached = false;

  bool get _still => widget.instant || MediaQuery.disableAnimationsOf(context);

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    if (!_precached) {
      _precached = true;
      // The very providers the frame paints, so each layer is decoded once,
      // at display size.
      for (final image in _layersFor(context, widget.size, widget.assets)) {
        precacheImage(
          image,
          context,
          onError: (_, _) {
            if (mounted && !_failed) setState(() => _failed = true);
          },
        );
      }
    }
    if (_still) {
      _clock.value = 1;
    } else if (!_clock.isAnimating && _clock.value == 0) {
      _clock.forward();
    }
  }

  @override
  void dispose() {
    _clock.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (_failed) {
      return AurudoIllustration(
        pose: AurudoPose.farmingAura,
        size: widget.size,
        animate: !_still,
      );
    }
    final still = _still;
    return ExcludeSemantics(
      child: RepaintBoundary(
        child: AnimatedBuilder(
          animation: _clock,
          builder: (context, _) => _FarmAuraFrame(
            size: widget.size,
            elapsedMs: _clock.value * FarmAuraTimeline.total,
            assets: widget.assets,
            still: still,
          ),
        ),
      ),
    );
  }
}

/// The layers decoded at the width they are drawn, never at full size.
List<ImageProvider> _layersFor(
  BuildContext context,
  double size,
  List<String> assets,
) {
  final dpr = MediaQuery.maybeDevicePixelRatioOf(context) ?? 2;
  final decodeWidth = (size * FarmAuraGeometry.aspect * dpr).round().clamp(
    64,
    FarmAuraGeometry.sourceWidth,
  );
  return [
    for (final asset in assets)
      ResizeImage(AssetImage(asset), width: decodeWidth),
  ];
}

class _FarmAuraFrame extends StatelessWidget {
  const _FarmAuraFrame({
    required this.size,
    required this.elapsedMs,
    required this.assets,
    required this.still,
  });

  final double size;
  final double elapsedMs;
  final List<String> assets;
  final bool still;

  @override
  Widget build(BuildContext context) {
    final height = size;
    final width = size * FarmAuraGeometry.aspect;
    final left = (size - width) / 2;
    Offset at(Offset f) => Offset(left + f.dx * width, f.dy * height);

    final pose = still ? FarmAuraPose.rest : FarmAuraPose.at(elapsedMs);
    // Inward/up is counter-clockwise on screen: negative in Flutter.
    final armAngle = -pose.armAngleDegrees * math.pi / 180;
    final orbScale = pose.orbScale;
    final lift = pose.liftFor(size);
    final pivot = at(FarmAuraGeometry.armPivot);
    final orbC = at(FarmAuraGeometry.orbPivot);

    Matrix4 about(Offset o, Matrix4 m) =>
        Matrix4.translationValues(o.dx, o.dy, 0)
          ..multiply(m)
          ..multiply(Matrix4.translationValues(-o.dx, -o.dy, 0));

    final group = Matrix4.translationValues(0, -lift, 0)
      ..multiply(about(pivot, Matrix4.rotationZ(armAngle)));
    // Mode B: the orb rides with the hand but undoes the arm's turn, so it
    // reads as energy being held, not a sticker glued to the arm.
    final orbLocal = about(
      orbC,
      Matrix4.rotationZ(-armAngle)
        ..multiply(Matrix4.diagonal3Values(orbScale, orbScale, 1)),
    );
    final orbNow = MatrixUtils.transformPoint(group, orbC);
    final images = _layersFor(context, size, assets);

    Widget layer(int i) => Positioned(
      left: left,
      top: 0,
      width: width,
      height: height,
      child: Image(
        image: images[i],
        fit: BoxFit.fill,
        filterQuality: FilterQuality.medium,
        gaplessPlayback: true,
      ),
    );

    final entranceT = still
        ? 1.0
        : Curves.easeOutCubic.transform(
            (elapsedMs / FarmAuraTimeline.entranceDuration).clamp(0.0, 1.0),
          );
    const scaleFrom = FarmAuraTimeline.entranceScaleFrom;

    final colors = context.colors;
    return SizedBox.square(
      dimension: size,
      child: Opacity(
        opacity: entranceT,
        child: Transform.scale(
          scale: scaleFrom + (1 - scaleFrom) * entranceT,
          child: Stack(
            clipBehavior: Clip.none,
            children: [
              layer(0),
              Positioned.fill(
                child: Transform(
                  key: AurudoFarmAuraAnimation.armGroupKey,
                  transform: group,
                  child: Stack(
                    clipBehavior: Clip.none,
                    children: [
                      Positioned.fill(
                        child: Transform(
                          key: AurudoFarmAuraAnimation.orbKey,
                          transform: orbLocal,
                          child: Stack(
                            clipBehavior: Clip.none,
                            children: [
                              if (pose.glowOpacity > 0)
                                Positioned.fill(
                                  child: CustomPaint(
                                    painter: _HaloPainter(
                                      center: orbC,
                                      radius:
                                          FarmAuraGeometry.orbRadius *
                                          height *
                                          FarmAuraTimeline.glowRadiusFactor,
                                      color: colors.auraViolet,
                                      opacity: pose.glowOpacity,
                                    ),
                                  ),
                                ),
                              layer(1),
                            ],
                          ),
                        ),
                      ),
                      layer(2),
                    ],
                  ),
                ),
              ),
              // Helmet rim and straps stay in front of the turning arm.
              layer(3),
              // Only while pulling: nothing left mounted once it settles.
              if (!still && FarmAuraTimeline.pullAt(elapsedMs) != null)
                Positioned.fill(
                  child: IgnorePointer(
                    child: CustomPaint(
                      painter: _PullPainter(
                        elapsedMs: elapsedMs,
                        target: orbNow,
                        box: Rect.fromLTWH(left, 0, width, height),
                        palette: [
                          colors.primary,
                          colors.auraViolet,
                          colors.auraCyan,
                        ],
                      ),
                    ),
                  ),
                ),
            ],
          ),
        ),
      ),
    );
  }
}

class _HaloPainter extends CustomPainter {
  _HaloPainter({
    required this.center,
    required this.radius,
    required this.color,
    required this.opacity,
  });

  final Offset center;
  final double radius;
  final Color color;
  final double opacity;

  @override
  void paint(Canvas canvas, Size size) {
    canvas.drawCircle(
      center,
      radius,
      Paint()
        ..shader = RadialGradient(
          colors: [
            color.withValues(alpha: opacity),
            color.withValues(alpha: 0),
          ],
        ).createShader(Rect.fromCircle(center: center, radius: radius)),
    );
  }

  @override
  bool shouldRepaint(_HaloPainter old) =>
      old.opacity != opacity || old.center != center || old.radius != radius;
}

/// Aura from around the body ([FarmAuraGeometry.particleOrigins]) drawn
/// in to the orb on each pull, closest at the top, fading on the way back. The AuraParticles
/// shapes (four-point sparkle and dot) and palette.
class _PullPainter extends CustomPainter {
  _PullPainter({
    required this.elapsedMs,
    required this.target,
    required this.box,
    required this.palette,
  });

  final double elapsedMs;
  final Offset target;
  final Rect box;
  final List<Color> palette;

  @override
  void paint(Canvas canvas, Size size) {
    final pull = FarmAuraTimeline.pullAt(elapsedMs);
    if (pull == null) return;
    final (index, p) = pull;
    const origins = FarmAuraGeometry.particleOrigins;
    for (var i = 0; i < FarmAuraTimeline.particleCount; i++) {
      // Staggered so the closest, densest moment is the top of the pull.
      final start = 0.02 + 0.05 * ((i * 3 + index) % 5);
      final local = ((p - start) / (FarmAuraTimeline.peakAt + 0.06 - start))
          .clamp(0.0, 1.2);
      if (local <= 0) continue;
      final fade = local <= 1
          ? math.sin(local * math.pi / 2)
          : 1 - (local - 1) / 0.2;
      if (fade <= 0) continue;
      final from =
          box.topLeft +
          Offset(origins[i].dx * box.width, origins[i].dy * box.height);
      final travel = Curves.easeInCubic.transform(local.clamp(0.0, 1.0));
      // A slight curve, so they swirl in rather than fly in straight lines.
      final dir = target - from;
      final bend = Offset(-dir.dy, dir.dx) * 0.12 * math.sin(travel * math.pi);
      final at = Offset.lerp(from, target, travel * 0.9)! + bend;
      final color = palette[i % palette.length].withValues(
        alpha: (fade * 0.9).clamp(0.0, 1.0),
      );
      final s = box.height * (0.017 + 0.012 * (1 - travel * 0.5));
      if (i.isEven) {
        paintAuraSparkle(canvas, at, s, color);
      } else {
        canvas.drawCircle(at, s * 0.55, Paint()..color = color);
      }
    }
  }

  @override
  bool shouldRepaint(_PullPainter old) =>
      old.elapsedMs != elapsedMs || old.target != target || old.box != box;
}
